### ISSUE TITLE
Duplicate BioGrid interaction data

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1019]
If you load mutliple species from BioGrid (i.e., by loading each species' xml file), you end up with duplicated records for the between-species interactions. This is because each species file contains all interaction data for that species, include interactions with other species. If I load data files for both species A and species B, it get the A/B interactions twice. 

FlyMine loads BioGrid data for fly, worm, and yeast. This query nabs interactions where species1 != species2. The dupes are evident.

    <query model="genomic" view="Interaction.details.type Interaction.details.role1 Interaction.gene1.symbol Interaction.gene1.organism.name Interaction.details.role2 Interaction.gene2.primaryIdentifier Interaction.gene2.symbol Interaction.gene2.organism.name Interaction.details.experiment.name Interaction.details.experiment.publication.pubMedId" sortOrder="Interaction.gene1.symbol ASC" > 
    <constraint path="Interaction.gene2.organism" op="!=" value="Interaction.gene1.organism" code="A" />
    </query>

**Comment by julie-sullivan** [comment]
Looking at the code, the data structure that keeps the unique list is a global variable:

>    private Map<MultiKey, Item> interactions = new HashMap<MultiKey, Item>();

So it seems like this should work for both mouse and human. The multikey is gene1+gene2 and therefore is valid regardless of organism.

I'll run the unit test for biogrid with just pax6 and see what happens. I would think it should be a quick fix.

**Comment by JoelRichardson** [comment]
@julie-sullivan Just to be clear, I think it's the InteractionDetail and InteractionExperiment objects that are being duplicated, not the Interaction objects. So the key would have to include something like the BioGrid id and/or pubmed id.

**Comment by julie-sullivan** [comment]
Ah okay, that makes sense. I'll be sure to check those.

But the key wouldn't work as it's a single data source. I'll need to fix the Java instead.

**Comment by julie-sullivan** [comment]
This query produces duplicates:

```
select count(*) from interactiondetail group by role1,role2,name,interactionid,experimentid,relationshiptypeid;
```

For a single interaction and experiment where the roles are the same, we would expect only one detail record. An experiment can't show twice that gene1 as bait and gene2 is prey.
