### ISSUE TITLE
data sets should have more details - descriptions and pubs

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1030]
MGI is listed twice, as is NCBI

Also need descriptions and pubs

**Comment by rachellyne** [comment]
I'm going to change this to look more like the FlyMine page.

**Comment by julie-sullivan** [comment]
@rachellyne Yes that would be useful! Also, it would be good to have details on the data be queryable. e.g. this query:

```
<query model="genomic" view="DataSet.name DataSet.description DataSet.url DataSet.dataSource.name" sortOrder="DataSet.name ASC" >
</query>
```

That way people can query and see details about the data. Specifically someone asked me the other day how to do this via Python.

So maybe we could fill in the URLs and descriptions. I need to copy over some URLs for some data sets but might need your help with the descriptions.

**Comment by rachellyne** [comment]
Did I already do this?  I seem to remember spending a day filling out urls and descriptions.  If not, yes, we really need to do this.

**Comment by julie-sullivan** [comment]
@rachellyne The URLs and descriptions for human and flymine are mostly empty.

**Comment by julie-sullivan** [comment]
@rachellyne is this something we can update together?

**Comment by julie-sullivan** [comment]
Here is FlyMine's: https://github.com/intermine/intermine/blob/dev/flymine/integrate/datasets.xml

We can add a similar file for HumanMine.

**Comment by julie-sullivan** [comment]
@rachellyne I like this data sets page! http://medicmine.jcvi.org/medicmine/dataCategories.do
