### ISSUE TITLE
CORS issue - www.humanmine.org and humanmine.org

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1032]
If users go to humanmine.org the widgets don't work because the widgets are set to come from www.humanmine.org

This is confusing because browsers hide the http:// bit now and often hide the www part.

**Comment by joshkh** [comment]
Can we set up a redirect from humanmine.org to www.humanmine.org for the time being? I'm still surprised at this since the CORs spec doesn't support subdomains. Should be *, null, or exact domain.

**Comment by julie-sullivan** [comment]
@joshkh What was the hack we used to get this working for the conference?

**Comment by joshkh** [comment]
We had to specifically include **www** in www.humanmine.org.

It's not immediately clear to me why that works. CORS filters are usually either domain specific or a free-for-all wildcard. Out of the box, InterMine includes custom Tomcat filters:
https://github.com/intermine/intermine/blob/beta/intermine/webapp/main/resources/webapp/WEB-INF/web.xml#L3048

Maybe the answer is in the Java, possibly starting here:
https://github.com/intermine/intermine/blob/beta/intermine/web/main/src/org/intermine/web/filters/HeaderFilter.java
