### ISSUE TITLE
VCF data parser for InterMine

### ISSUE THREAD

**Issue by ThomasLet** [intermine/intermine#1035]
Hi,

I was wondering if the development of a VCF data parser was planned for InterMine future releases. We work a lot with InterMine in my unit and we try to handle polymorphic data, especially data from VCF files, this kind of parser could be very useful for us !

Best regards,

Thomas

**Comment by julie-sullivan** [comment]
@ThomasLet - Absolutely! This would be very useful for us. See #210. 

Did you have a specific VCF file in mind? I can write a test based on that file.

**Comment by julie-sullivan** [comment]
@ThomasLet - I've added a VCF file parser. See http://intermine.readthedocs.org/en/latest/database/data-sources/library/variation/vcf/. The parser is currently on a different branch so you could test now, but it will be in the next InterMine release.

I tested using the Ensembl file here - ftp://ftp.ensembl.org/pub/release-79/variation/vcf/homo_sapiens/ so let me know if that varies from what's in your file.

**Comment by ThomasLet** [comment]
Hi Julie,


We work on multi samples VCF files which contain CNV data.

Many thanks for your work, I will try the parser next week !

Best regards,

Thomas


I will test the parser next week and I will On 06/11/2015 03:27 PM, 
Julie Sullivan wrote:
