### ISSUE TITLE
PRIDE data parser

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1045]
ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2015/

**Comment by julie-sullivan** [comment]
@rachellyne Can you help me model the data?

**Comment by rachellyne** [comment]
Yes I can.  I am just prioritising HumanMine data sources - is this one a priority?

**Comment by julie-sullivan** [comment]
@rachellyne  @gmicklem mentioned it so I don't know. I suppose it will be relative to the other sources on the list? And how difficult the data is to model / parse.

**Comment by julie-sullivan** [comment]
I am going to close this if it's on your list @rachellyne. I'll reopen if we decide to add this source.
