### ISSUE TITLE
XenMine - list creation error

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1046]
When I create a list, it works fine but when I go to the list analysis page I get a pop up. The console says this:

> "Error: TypeError, _json is null"

I assume this is the case for already created lists but xenmine has no public lists.

Tell @kkarra

**Comment by kkarra** [comment]
It probably has to do with the right hand corner links - "Orthologues"  - will look into removing it and trying..


18/06/15,09:18:21 ERROR        org.intermine.dwr.AjaxServices     - failed to get custom converter counts
org.intermine.objectstore.ObjectStoreException: PathQuery is invalid: [Path Gene.homologues.type in constraint is not in the model]
	at org.intermine.api.query.MainHelper.makeQuery(MainHelper.java:135)
	at org.intermine.api.query.PathQueryExecutor.makeQuery(PathQueryExecutor.java:141)
	at org.intermine.api.query.PathQueryExecutor.execute(PathQueryExecutor.java:99)

**Comment by kkarra** [comment]
It does look like the problem. Commenting out below section in bag-queries.xml gets rids of the error. An empty box appears though. I

**Comment by julie-sullivan** [comment]
I guess because homologues aren't in the data model.

**Comment by kkarra** [comment]
you can close this item
