### ISSUE TITLE
BioGRID config doesn't work correctly for symbols

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1080]
This seems to work:

> 3702.xref.primaryIdentifier = tair

But this does not:

> 3702.symbol = shortLabel

Which is exactly the config that Homo sapiens have.

Is that right @sergiocontrino?

**Comment by julie-sullivan** [comment]
Also should fail loudly if config not found.

**Comment by sergiocontrino** [comment]
@julie-sullivan, yes. it seems that the second setting forces the use of  idResolver.

**Comment by justinccdev** [comment]
I have a fix for the shortLabel problem as part of a synbiomine branch.  I will clean this up for mainline InterMine at some point.  Please let me know if you need it sooner.

[1] https://github.com/synbiomine/intermine/tree/fix-biogrid-loading

**Comment by julie-sullivan** [comment]
@justinccdev sorry for short notice but i need this for the human build, didn't realise how bad of a bug this is.

**Comment by justinccdev** [comment]
No problem. You need thus reviewed urgently? Can do so Tues if necessary, otherwise I will look as first task when I am back on Wed.

**Comment by julie-sullivan** [comment]
@justinccdev 

1. You shouldn't be reading your email on holiday. >:(
2. I ran the build with my fix so I'll check now if it worked. So Wed is fine!
3. We should have a discussion, maybe after the holidays, on how we can refactor the ID resolver system. It's fairly fragile.

**Comment by justinccdev** [comment]
Comments on 4c18521

1.  If we are going to set primaryIdentifier to be the identifier name by default then it makes more sense to do this in readConfig().  I think that readConfig() is logically a better place and the logic is only run once for each taxon, whereas in setGene() it is executed for every gene.

2.  Just as a general point, I find it amusing that we bother with the rslv != null checks when this code up in process()

 ```
        if (rslv == null) {
            rslv = IdResolverService.getIdResolverByOrganism(taxonIds);
        }
 ```

means that there will always be a resolver present (since getIdResolverByOrganism() never returns null).  But as you say, this is an issue with the ID resolver stuff in general and needs to be cleaned up properly (not least to resolve the fragility of lots of ID resolver copy/pasted code).

**Comment by julie-sullivan** [comment]
1. Good point you are right. However, it could be the case that a taxon is NOT in the configuration file. In this case, we need a catch-all. Does that make sense? 
2. Yes, needs attention!

Thanks for your notes, very helpful!

**Comment by justinccdev** [comment]
1. As far as I can see, all taxons must be in the configuration file from this snippet of code before the single setGene() call.

 ```
                    Config config = configs.get(taxId);
                    if (config == null) {
                        if (taxonIds.contains(taxId)) {
                            throw new RuntimeException("Entry in configuration file for " + taxId
                                + " not found");
                        }
                    } else {
                        setGene(taxId, interactorHolder, config);
                    }
 ```

**Comment by julie-sullivan** [comment]
@justinccdev Yes! You are right. What about this: ba724aad4d623b221b81605acf1062ab85022508

I put as the default value in the Config object.

**Comment by justinccdev** [comment]
Yeah, I like that.  I also think that might be simpler than having more logic to work through in readConfig().

Just to note, that commit also contains an unrelated (?) change in bio/sources/biogrid/main/resources/biogrid_config.properties.

**Comment by justinccdev** [comment]
Ah, I see that was corrected in 19baed6

**Comment by julie-sullivan** [comment]
@justinccdev thank you for keeping me honest! : ) Yes, mixing up my branches.

**Comment by justinccdev** [comment]
Just typically developer pedantry.  Happy for you to do the same to my pull requests (when there are some).
