### ISSUE TITLE
Collections not obeying web.collections.expandonload property

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1089]
From @JoelRichardson 

I cannot seem to get this setting to work. I have set it to false in web.properties, and I've verified the value at runtime (with showProperties.do). Yet, when I go to a gene report page, collections are open by default. (Note that templates are OK. It's just collections.) Here's an example on mousemine beta:

http://beta.mousemine.org/mousemine/portal.do?class=Gene&externalids=MGI%3A97490

This gene has two collections, labeled "Involved in mutations" and "Targeted by".

**Comment by julie-sullivan** [comment]
Can't replicate this on beta flymine from master branch (1.5.6) or the 1.5.3 code. Works as expected.

**Comment by joshkh** [comment]
Working fine here on 1.5.3+.

It looks like MouseMine's collection tables aren't being constructed with the expansion logic. Here's an example from beta flymine (working):
```javascript
<script type="text/javascript">
           trimTable('#coll_im_summaryproteins_inner');
           (function($) {
             var EXPAND_ON_LOAD = false;
             $(function(){
               if(false && typeof(Storage)!=="undefined"){
```
And here's mouse mine:
```javascript
<script type="text/javascript">
            trimTable('#coll_im_aspect_InteractionstargetedBy_inner');
            (function($) {
              $(function(){
                if(false && typeof(Storage)!=="undefined"){
```

The logic is missing from MouseMine's base where the code is being generated (it should start on line 80):
https://github.com/mgijax/intermine/blob/master/intermine/webapp/main/resources/webapp/reportRefsCols.jsp#L80

**Comment by JoelRichardson** [comment]
Sorry for the confusion. We build our beta from the 'mmDev' branch of our intermine fork.
Looks like the code is there:
https://github.com/mgijax/intermine/blob/mmDev/intermine/webapp/main/resources/webapp/reportRefsCols.jsp#L78-L83

**Comment by joshkh** [comment]
Hi Joel,

That's really strange. If it's in the JSP then I can't think of a reason why it's being omitted from the built report page. Could you confirm that the reportRefsCols.jsp on your local file system has the code that you linked to? Maybe there was a merge conflict or a problem when it was pulled?

**Comment by JoelRichardson** [comment]
Yup, I verified that build has right file. Can't rule out a merge issue, though. I know Howie had some problems with that.

**Comment by JoelRichardson** [comment]
Argh! It was a merge issue - we had a stale version of reportRefsCols.jsp in mousemine that was overriding the one in intermine. It wasn't until we checked the installed webapp that we realized what was going on. Sorry for the wild goose chase. You can cancel this one. (Now I'm going to check for similar issues with #1090...)
