### ISSUE TITLE
Code generation not updating in result tables in Safari 8

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#1094]

**Comment by joshkh** [comment]
Fixed by intermine/im-tables@fe9a3e3f48d3c0c954bf5d67c8574db9dbc02bac

**Comment by joshkh** [comment]
The fix is to bust the browser's cache when a code generation request is made to Intermine and then store the results in a cache local to im-tables.

One thing to note: this problem is cascading from Safari 8 to IMJS and then to im-tables so any application using IMJS in Safari 8 could experience the same issue. So far I've only noticed it with code-generation. Either Intermine is caching the code-generation incorrectly (which I doubt because it works in all other browsers), or there's a bug in Safari (which is indicating that the requests are not being cached).

Maybe there's something we can do to cover all applications that implement IMJS? Maybe a shim for Safari 8?
https://github.com/intermine/imjs/blob/master/src/http.coffee#L153

**Comment by joshkh** [comment]
To test, change the following properties in global.web.properties on beta flymine:
```
head.js.results.RESULT_TABLES=http://intermine.github.io/test-cdn/js/intermine/im-tables/2.0.0-beta/imtables.js
head.css.results.RESULT_TABLES=http://intermine.github.io/test-cdn/js/intermine/im-tables/2.0.0-beta/main.sandboxed.css
```

Using Safari 8, go to a results table and generate code in each language.

**Comment by yochannah** [comment]
@joshkh When you are back would you be able to show me how to replicate this? I've tried testing on Humanmine and Flymine but been unable to reproduce it so I can't be sure if it's fixed or not in beta.

**Comment by yochannah** [comment]
I tried generating code for a couple of different genes in several different languages in the mines listed above and it all seemed to be updating correctly in Safari 8.0.6.

**Comment by julie-sullivan** [comment]
@yochannah says this is working and @joshkh says this is because the fix is already in the code.
