### ISSUE TITLE
Result table preview with many collections overflows off screen.

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#1102]
For items with a large number of collections, such as Genes, the item preview popover becomes too large and overflows off the screen. Since this is dependent on the data model, the functionality has been disabled by default and enabled through an Option:

See "ItemDetails.ShowReferenceCounts: false"
https://github.com/intermine/im-tables/blob/master/src/options.coffee#L36

**Comment by joshkh** [comment]
To test:

On beta flymine, change the following to properties in global.web.properties to use im-tables 2.0.0 beta42
```
head.js.results.RESULT_TABLES=http://intermine.github.io/test-cdn/js/intermine/im-tables/2.0.0-beta/imtables.js
head.css.results.RESULT_TABLES=http://intermine.github.io/test-cdn/js/intermine/im-tables/2.0.0-beta/main.sandboxed.css 
```

Hover over a table cell. References should no longer appear.

**Comment by julie-sullivan** [comment]
works as expected.
