### ISSUE TITLE
PFam data loader

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1104]
Load PFam data.

ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam28.0/

variations in their function

See https://github.com/synbiomine/intermine/issues/9

**Comment by julie-sullivan** [comment]
I need this for humanmine.

**Comment by julie-sullivan** [comment]
@rachellyne Is this a priority? Or is the data from interpro enough?

**Comment by rachellyne** [comment]
Has someone asked for something specific from PFam?.  If it's just for the domains and locations we get all this from interpro.

**Comment by julie-sullivan** [comment]
variation in their function? 

@Hendekagon needed this as well I think.

**Comment by rachellyne** [comment]
Between what?  Proteins, species?  I don't see immediately what this would be.

**Comment by julie-sullivan** [comment]
okay, maybe don't need. closing for now.
