### ISSUE TITLE
GAF: do we need the OBO file

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1112]
Because I don't think we do.

**Comment by justinccdev** [comment]
I agree, I can't see any trace of the ontologyfile property being used in the go annotation source.  I've removed it from the synbiomine project.xml and the also apparently unused ontologyPrefix property.

**Comment by julie-sullivan** [comment]
the ontologyPrefix is only used when processing the OBO files, not when processing the annotation. See #901

**Comment by julie-sullivan** [comment]
I will update the project XML files for flymine and humanmine and update the docs. Thanks @justinccdev!
