### ISSUE TITLE
YeastMine: serial number not being reset

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1114]
YeastMine build is getting negative numbers

```
13/08/15,10:54:02 WARN  org.intermine.web.struts.HtmlHeadController     - object ID not a number! -1122965846

I don’t see any error in pbuild.log but it takes 0 seconds!

  [ant] BUILD SUCCESSFUL
  [ant] Total time: 0 seconds
Mon Aug 10 15:30:05 PDT 2015
```

**Comment by julie-sullivan** [comment]
@kkarra 

1. Can you replicate this on your dev server? Can you run the same script locally? 
2. Have you restarted postgres?
3. Do the postgres logs (/var/log/postgres) give any indication of what happened?
4. Do the intermine logs (intermine.log in yeastmine/integrate) give any indication of what happened?

I believe last week you ran the build manually and did not have this problem. What is the difference between what you did and what the build normally does?

**Comment by julie-sullivan** [comment]
@sergiocontrino Did you say that you knew what happened?

**Comment by kkarra** [comment]
- No. I haven't found anything in the logs.
- I cannot deliberatley replicate. I haven't yet seen it happen in dev.
- No, did not restart postgres 
- Did not look in postgres logs 
But, I notice it happening quite often (before the recent build)..will keep an eye to see if there is a pattern (every other week or..?)
meanwhile, would appreciate the fix to make sure 'serial 'table is dropped and that clean-db does it job before proceeding.

**Comment by julie-sullivan** [comment]
the `build-db` task clearly deletes all the tables and resets the serial number:

https://github.com/intermine/intermine/blob/beta/intermine/objectstore/main/src/org/intermine/task/BuildDbTask.java#L116-L117

1. The command drops tables, not views. Is this a problem?
2. The overlap table will be quite large. Maybe it takes too long? But it's not the largest table, so that's a dumb idea.

**Comment by julie-sullivan** [comment]
@sergiocontrino Were you able to make any progress on this issue? Is this now fixed for AIP?

**Comment by sergiocontrino** [comment]
@julie-sullivan, yes i think it is solved and i'll cherry pick solution shortly

**Comment by sergiocontrino** [comment]
made pull request #1146

**Comment by kkarra** [comment]
pull request has 'checks failed' - should I wait or get the fix? 
btw, OverlapViewTask.java has code to drop overlappingfeaturessequencefeature table and view.
So, it is not 'serial' table that is used to start a new batch of IDs?

**Comment by julie-sullivan** [comment]
@kkarra No, wait. Sorry! Sergio is going to redo the pull request today to just drop all views, not just this one.

The OverlapViewTask.java is working correctly, we're trying to fix the build-db task. Since the database is not correctly dropped (because of the lingering view that OverlapViewTask creates), the serial number is not reset.

We'll get the fix to you shortly!!!
