### ISSUE TITLE
QueryBuilder - constraint values not updated without dropdown change

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine#1120]
To reproduce:

```
<query name="" model="genomic" view="Gene.primaryIdentifier">
  <constraint path="Gene.chromosome.primaryIdentifier" op="IS NOT NULL"/>
</query>
```

Edit constraint via the blue pen icon for "DB identifier".
In the dialog box click on: "Filter query results on this field having a specific value", and "Add to query".
No update occurs and an error message "No input given, please supply a valid expression" will be generated on the QueryBuilder page.
Click on the blue pen icon again. Select "Chr5" and Add to query. This time the query in "Query Overview" box is updated with "chr5".

**Comment by julie-sullivan** [comment]
this works for me in firefox.

**Comment by sergiocontrino** [comment]
if you tested on beta, it works because there is no drop-down for the chromosomes.
try with organism
```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.organism.shortName" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.organism.shortName" op="IS NULL"/>
</query>
```

**Comment by julie-sullivan** [comment]
@sergiocontrino This still works for me! Can you test again and reopen the ticket if this is a problem.

**Comment by sergiocontrino** [comment]
@julie-sullivan works for me as well now, will stay closed!
