### ISSUE TITLE
Query Builder: cannot query for disease names because of trailing whitespace

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1121]
From @kkarra

http://yeastmine.yeastgenome.org/yeastmine/template.do?name=Disease_Human_Yeast

```
Using the template above —> show results —-> summarize on 'Disease Name’ —> Click on ‘Toggle selection’ —> ‘Filter’  

Doing the above sequence of steps returns 'No Results', that should not be the case. This filtering stuff works fine on other columns but not this one, so, am not sure why. It is the main constraint with ‘CONTAINS’ in it.
```

@joshkh This is the query that is created:

```
<query name="" model="genomic" view="Disease.name Disease.identifier Disease.genes.symbol Disease.genes.name Disease.genes.primaryIdentifier Disease.genes.crossReferences.identifier Disease.genes.homologues.homologue.symbol Disease.genes.homologues.homologue.secondaryIdentifier Disease.genes.homologues.homologue.name Disease.genes.homologues.dataSets.dataSource.name" longDescription="" sortOrder="Disease.genes.primaryIdentifier asc" constraintLogic="B and C and D and A and E">
  <constraint path="Disease.genes.homologues.homologue.organism.shortName" code="B" op="=" value="S. cerevisiae"/>
  <constraint path="Disease.genes.organism.shortName" code="C" op="=" value="H. sapiens"/>
  <constraint path="Disease.genes.crossReferences.source.name" code="D" op="=" value="MIM"/>
  <constraint path="Disease.name" code="A" op="CONTAINS" value="diabetes"/>
  <constraint path="Disease.name" code="E" op="ONE OF">
    <value>DIABETES MELLITUS, PERMANENT NEONATAL; PNDM
    </value>
    <value>MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 2; MODY2
    </value>
    <value>DIABETES MELLITUS, TRANSIENT NEONATAL, 2
    </value>
    <value>DIABETES INSIPIDUS, NEPHROGENIC, AUTOSOMAL
    </value>
    <value>DIABETES MELLITUS, INSULIN-DEPENDENT; IDDM
    </value>
    <value>MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 7; MODY7
    </value>
    <value>EPIPHYSEAL DYSPLASIA, MULTIPLE, WITH EARLY-ONSET DIABETES MELLITUS
    </value>
    <value>MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 4; MODY4
    </value>
    <value>DIABETES MELLITUS, KETOSIS-PRONE; KPD
    </value>
    <value>MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 9; MODY9
    </value>
    <value>MICROCEPHALY, EPILEPSY, AND DIABETES SYNDROME; MEDS
    </value>
    <value>MICROVASCULAR COMPLICATIONS OF DIABETES, SUSCEPTIBILITY TO, 6; MVCD6
    </value>
  </constraint>
</query>
```

Notice that "disease name" has two constraints:

1. the original "CONTAINS diabetes" constraint
2. the new ONE OF constraint created by the filtering of the results tables.

The first constraint should have been dropped. Can you check on how the results tables handle these filters?

**Comment by julie-sullivan** [comment]
1. if you select only one value to filter on, it works fine
2. none of the other columns have problems
3. the disease names have commas and semi-colons. 

What delimiter are we using? Could punctuation be our problem?

**Comment by kkarra** [comment]
The table on summarization, has 'Filter' with a pull-down and 2 options (restrict and exclude). We were curious if this is a new feature in 1.5 ? Can't remember seeing it.

It looks like if you just select one item using the above 2 buttons things works fine. When you select more than one it does not.  Probably in line with what Josh said above - a combination of 'contains' and 'one of' ?  How does one look at the query being run on results tables?

Thanks,
-Kalpana

**Comment by julie-sullivan** [comment]
@kkarra This works on fields that do not contain commas and semi-colons, so I believe we are handling the delimiters incorrectly. I will fix!

**Comment by julie-sullivan** [comment]
This also works in live flymine. I imported the query and changed yeast to fly:

```
<template name="Disease_Human_Yeast" title="OMIM Disease Phenotype --&gt;  human gene(s) --&gt; yeast homolog(s)" comment="">
  <query name="Disease_Human_Yeast" model="genomic" view="Disease.name Disease.identifier Disease.genes.symbol Disease.genes.name Disease.genes.primaryIdentifier Disease.genes.crossReferences.identifier Disease.genes.homologues.homologue.symbol Disease.genes.homologues.homologue.secondaryIdentifier Disease.genes.homologues.homologue.name Disease.genes.homologues.dataSets.dataSource.name" longDescription="Specify &lt;a href= http://www.omim.org target=&quot;_blank&quot;&gt;OMIM &lt;/a&gt; phenotype(s) (by keyword or name) and retrieve all associated human gene(s) and the yeast homologs of these gene(s)." sortOrder="Disease.genes.primaryIdentifier asc" constraintLogic="B and C and D and A">
    <constraint path="Disease.genes.homologues.homologue.organism.shortName" code="B" editable="false" description="" op="=" value="S. cerevisiae"/>
    <constraint path="Disease.genes.organism.shortName" code="C" editable="false" description="" op="=" value="H. sapiens"/>
    <constraint path="Disease.genes.crossReferences.source.name" code="D" editable="false" description="" op="=" value="MIM"/>
    <constraint path="Disease.name" code="A" editable="true" op="CONTAINS" value="diabetes"/>
  </query>
</template>
```

I was able to filter by disease name (with punctuation) just fine.

**Comment by julie-sullivan** [comment]
@kkarra Okay, we've got it! Thanks to @sergiocontrino! We couldn't replicate this with any other data, so it seemed to be disease-specific. We looked in the database and found the disease name has a trailing whitespace. This whitespace is removed by the querybuilder, so that's why the query fails. 

You can test this in your own database. Querying postgres directly, this fails:

> SELECT a1_.id, a1_.name FROM disease AS a1_ WHERE a1_.name IN ('COACH SYNDROME', 'COCOON SYNDROME') ORDER BY a1_.name, a1_.id LIMIT 5000;

Add a space to the end, and it is successful:

> SELECT a1_.id, a1_.name FROM disease AS a1_ WHERE a1_.name IN ('COACH SYNDROME ', 'COCOON SYNDROME ') ORDER BY a1_.name, a1_.id LIMIT 5000;

I'm going to update the OMIM converter to trim() the disease name, and that should solve it!

**Comment by julie-sullivan** [comment]
@justinccdev Can you test this?

1. run the OMIM source as flymine
2. run a query like the one above specifically that uses the ONE OF constraint on disease.name.

Thanks!

**Comment by julie-sullivan** [comment]
@justinccdev This change is on the beta branch.
