### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1124]
We are having CORS issues. One problem might be that the code is looking for a parameter called [ws.response.origin](https://github.com/intermine/intermine/blob/beta/intermine/web/main/src/org/intermine/webservice/server/WebService.java#L404) but this [property](https://github.com/intermine/intermine/blob/beta/intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties#L280) is not set anywhere. 

I set the value of `ws.response.origin` (temporarily) to be * for beta flymine and @yochannah said that it seemed to work.

We will need more tests, and some security checks too.

**Comment by yochannah** [comment]
http://jsfiddle.net/1xLtkv0b/2/
http://jsbin.com/finobe/edit?html,console

Those links seem to show it working ok. 

To sum up the *reason* setting it to `*` can be problematic, see this [security.stackexchange post](http://security.stackexchange.com/questions/43639/why-is-the-access-control-allow-origin-header-necessary). 

The easiest way to fix this requires a simple-looking CSRF token implementation: 
https://en.wikipedia.org/wiki/Cross-site_request_forgery#Prevention

>Cookie-to-Header Token  
>Web applications that use JavaScript for the majority of their operations may use an anti-CSRF technique that relies on same-origin policy:

> * On login, the web application sets a cookie containing a random token that remains the same for the whole user session  
>     `Set-Cookie: Csrf-token=i8XNjC4b8KVok4uw5RftR38Wgp2BFwql; expires=Thu, 23-Jul-2015 10:25:33 GMT; Max-Age=31449600; Path=/`  

> * JavaScript operating on the client side reads its value and copies it into a custom HTTP header sent with each transactional request  
>    `X-Csrf-Token: i8XNjC4b8KVok4uw5RftR38Wgp2BFwql`   
 
> * The server validates presence and integrity of the token  
>Security of this technique is based on the assumption that only JavaScript running within the same origin will be able to read the cookie's value. JavaScript running from a rogue file or email will not be able to read it and copy into the custom header. Even though the csrf-token cookie will be automatically sent with the rogue request, the server will be still expecting a valid X-Csrf-Token header.  
>The CSRF token itself should be unique and unpredictable. It may be generated randomly, or it may be derived from the session token using HMAC:  

>    `csrf_token = HMAC(session_token, application_secret)`   
>The CSRF token cookie must not have httpOnly flag, as it is intended to be read by the JavaScript by design.
>
>This technique is implemented by many modern frameworks, such as Django[21] and AngularJS.[22] Because the token remains constant over the whole user session, it works well with AJAX applications, but does not enforce sequence of events in the web application.
>
> * Permissive Access-Control-Allow-Origin Cross-origin resource sharing header (with asterisk argument)

This has a more in-depth guide to CSRF tokens: https://docs.djangoproject.com/en/1.8/ref/csrf/

**Comment by julie-sullivan** [comment]
I've reverted this change: 38c14e78a3572089833df3cf2225c900c624735d

Did this fix the CORS issues?

**Comment by julie-sullivan** [comment]
This test needs to be fixed:

```
  1)  Uncaught error outside test suite:

     Uncaught TypeError: 'undefined' is not an object (evaluating 'resp.headers['content-type']') (file:///home/travis/build/intermine/intermine/client/test/browser/mocha-test.js:89)
```

**Comment by joshkh** [comment]
@julie-sullivan Yes, the reversion 38c14e7 fixed the CORS issue.
