### ISSUE TITLE
UniProt: add publications to genes too

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1125]
The UniProt source only adds publications to proteins, they should add them to the genes created too.

**Comment by julie-sullivan** [comment]
Do #1116 after.

**Comment by julie-sullivan** [comment]
FBgn0020474 gene has two proteins - Q28Z10 and Q8I1E3. A good test case

**Comment by julie-sullivan** [comment]
Does not work if the gene is related to multiple proteins. This is because we save the gene (and associated publications) to the database when we first encounter it. 

Later, for example, we might come across this gene again in the record of another protein. It's already been saved to the database, so we only need to store the relationship between gene and protein. However if that protein has publications, they will not be added to the gene. As it's already in the database.

We could hold all this information in memory and wait until then end to store everything, but I am not sure that is the best idea. We will increase the resources needed by this converter (one of our most important) without getting a lot in return.

Maybe there is a cleverer way to do this?

**Comment by julie-sullivan** [comment]
maybe we could do a post-process. That would capture all the publications for proteins that come from other data sources too.

**Comment by sergiocontrino** [comment]
doing some test on this at the moment

**Comment by julie-sullivan** [comment]
@sergiocontrino Can you make a pull request from what you did for AIP?

**Comment by julie-sullivan** [comment]
@sergiocontrino If not, we can put this on the next release.
