### ISSUE TITLE
CORS code for a GET request

### ISSUE THREAD

**Issue by claus022015** [intermine/intermine#1133]
Hello!

I'm new with CORS, and i'm trying to use it to GET information from a few websites.
First i've tried a demo script with the help of w3school and the code looks like this:

<html>
<head>
<style>
    table, th, td { border: 1px solid black; border-collapse:collapse; }
  th, td { padding: 5px; }
</style>
</head>
<body>

<script>
if (window.XMLHttpRequest)
  {// code for IE7+, Firefox, Chrome, Opera, Safari
  xmlhttp=new XMLHttpRequest();
  }
else
  {// code for IE6, IE5
  xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
  }
xmlhttp.open("GET","http://www.w3schools.com/xml/cd_catalog.xml",true);
xmlhttp.send();
xmlDoc=xmlhttp.responseXML;

document.write("<table><tr><th>Artist</th><th>Title</th></tr>");
var x=xmlDoc.getElementsByTagName("CD");
for (i=0;i<x.length;i++)
  {
  document.write("<tr><td>");
  document.write(x[i].getElementsByTagName("ARTIST")[0].childNodes[0].nodeValue);
  document.write("</td><td>");
  document.write(x[i].getElementsByTagName("TITLE")[0].childNodes[0].nodeValue);
  document.write("</td></tr>");
  }
document.write("</table>");
</script>
</body>
</html>

In w3school "Try it yourself" section i get the xml result i want = 2 columns table with values like this
Artist	Title
Bob Dylan	Empire Burlesque
Bonnie Tyler	Hide your heart
Dolly Parton	Greatest Hits
Gary Moore	Still got the blues
Eros Ramazzotti	Eros
Bee Gees	One night only

But when i access it in a browser, from my own server, i only get the first 2 fields of the table =
Artist	Title

I have configured Apache2 for CORS (i'm running Ubuntu) , in apache2.config i have set Header set Access-Control-Allow-Origin "*"

Does someone have an idea about whats happening, or what am i missing here?

Thanks in advance!

**Comment by julie-sullivan** [comment]
I think you have the wrong git repository?
