### ISSUE TITLE
Changes to list upgrade system

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#1134]
I suggest we automatically upgrade any lists which only have synonym changes, but provide a report explaining that this has been done.  We also need to review how the changes are presented.  I know we have re-designed this once, but I'm still finding it sometimes time-consuming to identify what has changed.  e.g most recent flymine upgrade, I have one list with one less gene but I can't find out why. If there is a direct hit, but to two genes, this is flagged up somewhere within the direct hits, which can be a lot to scroll through.  I'll also email Tim Karr to find out how his big upgrade went and if he had problems/suggestions.

**Comment by julie-sullivan** [comment]
> but provide a report explaining that this has been done

When / where?

**Comment by julie-sullivan** [comment]
A review of this tool can be done as part of stepZ

**Comment by julie-sullivan** [comment]
> I suggest we automatically upgrade any lists which only have synonym changes

This is already how it works. The non-automatic upgrading only happens when there are two options.

**Comment by rachellyne** [comment]
This definitely wasn't the case with the last FlyMine release, but looks like this is correct for the current HumanMine.

**Comment by julie-sullivan** [comment]
This should be working as expected now.
