### ISSUE TITLE
Problem with SNV list analysis page on upload

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#1136]
Uploading a set of SNVs - table displays "no results".

e.g upload:

rs190207943
 rs144023246
 rs185066721
 rs184732368
 rs113521347
 rs183827533
 rs7209929
 rs112039964
 rs367819487
 rs182692037
 rs374289282
 rs7215510
 rs147731827
 rs138910485
 rs151190301
 rs192019563
 rs376179813
 rs139016025
 rs34556017
 rs367886943
 rs78963114
 rs140659435
 rs375245594
 rs114323615
 rs372059515
 rs57094262
 rs185596020
 rs373011389
 rs191592762
 rs145699483
 rs142353813
 rs111303253

**Comment by julie-sullivan** [comment]
on humanmine.org?

**Comment by rachellyne** [comment]
yes.

**Comment by julie-sullivan** [comment]
humanmine must have been experiencing network issues, because this performs fine now. I am closing this ticket but I am putting a note to check humanmine's config and see what we can do about making it more stable.
