### ISSUE TITLE
FlyAtlas widget is showing rows rather than unique number of genes

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#1141]
When mouseover a bar, the unique number of genes is shown, but the pop up box is showing the number of rows in the resulting table - this should also show number of unique genes for consistency.

**Comment by julie-sullivan** [comment]
@yochannah this was the bug we were talking about today. Take a look when you have a chance?

**Comment by yochannah** [comment]
To test this fix, you'll need to point a local flymine's global.web.properties file to the right place.

point `head.js.bagDetails.Cz` to `http://cdn-dev.intermine.org/js/intermine/apps-c/list-widgets/2.1.4/app.min.js`, navigate to a list page, and go to the fly atlas widget. the popup and hover counts for each bar should match - screenshot below shows an example of the bug. Both should say "6".

![image](https://cloud.githubusercontent.com/assets/9271438/18318443/9cb17dfe-7519-11e6-864b-7b18bc6b4fbe.png)


If it works, we can add version 2.1.4 to the master cdn and then point intermine config to the master cdn.

**Comment by julie-sullivan** [comment]
@rachellyne this looks good to me. Take a look?

http://beta.flymine.org/beta/bagDetails.do?scope=all&bagName=testList

Nice job @yochannah!!

**Comment by rachellyne** [comment]
Yes, looks fine to me.
