### ISSUE TITLE
Results table summarize acting funny

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#1145]
You can check this using this template
- http://www.flymine.org/flymine/template.do?name=Gene_Interactions&scope=global
- Summarize on one of the columns
- The column on which it is summarized displays blank and then populates
- If you click on the check box to select one of the items, all values go blank
- If you mouse over elsewhere on the results table then magically the values in the summarize box appear.
- The dropdown on 'Filter' button does not appear easily..eventually saw it appear..
Something wierd is going on.

**Comment by julie-sullivan** [comment]
Which browser are you using? I can't replicate. @yochannah Can you try to replicate? Maybe using safari?

**Comment by kkarra** [comment]
Chrome Version 45.0.2454.85 (64-bit)

**Comment by yochannah** [comment]
I've just upgraded from Chrome 44 to 45.0.2454.93 (64-bit) on Ubuntu, but I also can't replicate. Screenshot below - did I try to reproduce it correctly?

It looks the summary requests make an asynchronous call to the server. If you right click anywhere on the page, click inspect element, then choose the console tab, do you see any errors in red when your error occurs? 

![issue-results-table](https://cloud.githubusercontent.com/assets/9271438/9929894/a51cc03a-5d27-11e5-9a7f-c63a4abe1567.png)

**Comment by julie-sullivan** [comment]
@yochannah can you try on an apple? I believe that's what @kkarra is using.

**Comment by yochannah** [comment]
@julie-sullivan Thanks for the tip. I tried briefly on Chrome 45.0.2454.85 for Mac, and this issue *did* occur. Good news, hopefully, though: When I upgraded to 45.0.2454.93 the problem seemed to disappear. @kkarra, can you try upgrading Chrome to .93 or greater and try again?

**Comment by kkarra** [comment]
Thanks! It now works fine on my mac and chrome Version 45.0.2454.93 (64-bit).
