### ISSUE TITLE
Web services: tags for templates

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1154]
I need the tags for each template. Do the web services provide these? @joshkh says no! I say yes!

Tell @yochannah too.

**Comment by julie-sullivan** [comment]
What did we need these for? I forget.

**Comment by julie-sullivan** [comment]
Here's where the action happens:

https://github.com/intermine/intermine/blob/dev/intermine/web/main/src/org/intermine/webservice/server/template/AvailableTemplatesService.java#L82-L84

It retrieves a list of templates. No tags. We could make another web service that gets tags for templates. Or we could try to append it to this webservice somehow. I know @joshkh said that he saw tags but they were always empty. Where was that?

**Comment by yochannah** [comment]
I think it was this? http://iodocs.labs.intermine.org/flymine/docs#/ws-available-lists/GET/lists

Sample json:

{"timestamp":1213096578494,"tags":[],"authorized":false,"title":"PL FlyAtlas_brain_top","status":"CURRENT","description":"List of the most enriched genes in the adult fly brain (Source: www.flyatlas.org) ","name":"PL FlyAtlas_brain_top","dateCreated":"2008-06-10T12:16:18+0100","type":"Gene","size":37}

**Comment by julie-sullivan** [comment]
The JSONListFormatter prepares the lists and adds more information. 

```
        BagManager bm = im.getBagManager();
        List<Tag> tags = bm.getTagsForBag(list, profile);
        List<String> tagNames = new ArrayList<String>();
        for (Tag t: tags) {
            tagNames.add(t.getTagName());
        }
        listMap.put("tags", tagNames);
```

We don't have anything like that for templates. But I could write something.

**Comment by yochannah** [comment]
We possibly don't want to copy it directly as I think the tags might be broken for lists? That query has exactly 0 tags in every response. I assume there *are* some tags somewhere, they just aren't being returned?

**Comment by julie-sullivan** [comment]
ha, yes! we would want a working version. but currently the code just outputs the templates and that's it. Without any extra information, like tags.

**Comment by julie-sullivan** [comment]
http://iodocs.labs.intermine.org/flymine/docs#/ws-list-tags/GET/list/tags

**Comment by julie-sullivan** [comment]
oh, doesn't seem to work right now:

```
{"tags":[
],"executionTime":"2015.10.22 12:38::31","wasSuccessful":false,"error":"Service failed. Please contact support.","statusCode":500}
```

**Comment by julie-sullivan** [comment]
The tags are empty (I think) because the profile is passed in. Instead we should use the superuser.
