### ISSUE TITLE
'Contact Us' link not working

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#1160]
It could be something wrong with my setup..
http://www.xenmine.org/

I see 'Failed to load resource: the server responded with a status of 404 (Not Found)' in the browser for an error..

and the following in catalina.out ..

SEVERE: Servlet.service() for servlet [jsp] in context with path [/xenmine] threw exception [An exception occurred processing JSP page /layout.jsp at line 18

15: 
16: <c:set var="iePre7" value='<%= new Boolean(request.getHeader("user-agent").matches(".*MSIE [123456].*")) %>' scope="request"/>
17: 
18:   <tiles:importAttribute name="pageName" scope="request"/>
19: 
20:   <head>
21: 

Stacktrace:] with root cause
javax.servlet.jsp.JspException: Error - tag importAttribute : no tiles context found.
	at org.apache.struts.tiles.taglib.ImportAttributeTag.doStartTag(ImportAttributeTag.java:153)
	at org.apache.jsp.layout_jsp._jspx_meth_tiles_005fimportAttribute_005f0(layout_jsp.java:374)
	at org.apache.jsp.layout_jsp._jspService(layout_jsp.java:168)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)

**Comment by julie-sullivan** [comment]
@kkarra I don't see the contact form at the bottom of the page. Why is that? 

I don't see the code here: https://github.com/kkarra/xenmine

**Comment by kkarra** [comment]
Isn't it the same contactform from either top or bottom? I have the link 'Contact Us' at the top. 
Did not push to github yet. Can do. I have headMenu.jsp, layout.jsp etc.  (its been a while and probably a matter of not configuring properly..)

**Comment by julie-sullivan** [comment]
@kkarra Do you have this in your footer: https://github.com/intermine/intermine/blob/dev/intermine/webapp/main/resources/webapp/footer.jsp#L12

Maybe try copying that footer.jsp over yours and redeploying? Just to see if that fixes it?

**Comment by julie-sullivan** [comment]
This is where the JavaScript is to do the toggling:

https://github.com/intermine/intermine/blob/dev/intermine/webapp/main/resources/webapp/js/imutils.js#L327-L332

**Comment by kkarra** [comment]
Copying over footer.jsp worked! but, I get emails if I create new account but not via 'Contact Us' even thought it says - thanks for contacting! . 

Where can I find the doc for SMTP set up?  Checked here..
http://intermine.readthedocs.org/en/latest/webapp/properties/intermine-properties/

Can I use gmail to do this?
this seems to work for create account confirmation.
mail.host=localhost
mail.smtp.starttls.enable=true
mail.from=xenmine@gmail.com

**Comment by julie-sullivan** [comment]
Did you set `feedback.destination` too?

**Comment by kkarra** [comment]
Yes. 
feedback.destination = xenmine@gmail.com

**Comment by julie-sullivan** [comment]
If your "welcome to xenmine" emails are working that doesn't make sense that these aren't then. Is that gmail account the sender in the working emails too?

**Comment by julie-sullivan** [comment]
never mind, yes it is.

**Comment by julie-sullivan** [comment]
* And there are no error messages in the logs? grep for ContactAction. If not, do you have debugging set up? Maybe you could walk through sending an email and see what fails.
* It doesn't make sense that the welcome message works and the contact us doesn't. 
* Here's the (code)[https://github.com/intermine/intermine/blob/dev/intermine/web/main/src/org/intermine/web/struts/ContactAction.java]. It looks like it just uses, which is all I have in FlyMine's properties file:
  * mail.host
  * feedback.destination
 * The live site still is missing the contact link. Where is your dev version? I would like to try. Does it look like it works?

**Comment by kkarra** [comment]
Stuart had to make some config change in sendmail so that mail can be sent to non-Stanford address (gmail here..)
