### ISSUE TITLE
Remove unused parameter "type" from BioSequenceFactory.make(BioEntity bioEnt, SequenceType type)

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1165]
The "generic" method BioSequenceFactory. make(BioEntity bioEnt, SequenceType type), which one might assume allows an override of bioEnt's SequenceType by explicitly supplying it, doesn't do such a thing. Instead, it just queries the given BioEntity as to whether it's a Protein or a SequenceFeature and processes accordingly. I recommend that the unused parameter "type" be removed from this method since its presence is very confusing! Thanks, Sam.

**Comment by sammyjava** [comment]
Yeah, since I actually need the method, I ended up rewriting it to work as advertised, rather than yanking it. :) Sorry about the confusion. I'm using this rewritten method successfully in my current InterMine to display polypeptide FASTAs.

**Comment by julie-sullivan** [comment]
Thanks @sammyjava, looks great. :) We're right in the middle of a release but will test ASAP. Really appreciate the fix!
