### ISSUE TITLE
Query results - filtering on summary doesn't work when values > 1000

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1169]
1. run a query
2. click on a column summary
3. enter in text to filter the results. Nothing happens

It does flicker like it refreshed but nothing is filtered.

Can we summarise the first 1,000 at least? There should be a better solution. Let the user know?
There is no error on the console.

**Comment by julie-sullivan** [comment]
Also I think the limit of 1,000 is arbitrary. Can we remove? And let people page through maybe?

**Comment by julie-sullivan** [comment]
The filter button is disabled when count > 1000. However, you can still type in the input field, and then nothing happens. The filter input field should be disabled if there are more than 1000 results.

**Comment by danielabutano** [comment]
It works now
