### ISSUE TITLE
Panther and Treefam merging issue

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1172]
FlyMine has PPARG twice. It looks like treefam and panther are setting pparg, the symbol as the primaryidentifier.

**Comment by julie-sullivan** [comment]
@rachellyne Running build now. see live flymine there are two ppargs.

**Comment by rachellyne** [comment]
Strange.  I thought we had fixed that one.

**Comment by julie-sullivan** [comment]
@rachellyne Okay beta flymine is up and there is only one pparg! woo hoo! Can you test a bit more? This only impacts homologues created by panther and treefam.
