### ISSUE TITLE
UniProt: protein publications seem to be wrong

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1175]
@rachellyne pointed out that ZEN1_DROME:

http://www.uniprot.org/uniprot/P09089

has five publications. But on flymine there are only three. Where did they go?

**Comment by julie-sullivan** [comment]
@rachellyne We only load the publications that have pubmed IDs. let me know if you think this is wrong. See the other two publications (that we don't load) don't have pubmed references.

**Comment by rachellyne** [comment]
In this case, the other two are actually database submissions, so fine not to have under publications.  I didn't look close enough!
