### ISSUE TITLE
CNVs

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1178]
We should load these data:

```
ftp://ftp.ensembl.org/pub/release-82/variation/vcf/homo_sapiens/

file:  Homo_sapiens_structural_variations.vcf.gz 
```

How to model?

**Comment by julie-sullivan** [comment]
Here's a sample of the data

```
1       68496   nssv2866214     A       <CNV:GAIN>      .       .       DGVa_201507;SVTYPE=CNV:GAIN;END=70627;ST_ACC=nstd46;Parent=nsv514929
1       68496   nssv2866234     A       <CNV:GAIN>      .       .       DGVa_201507;SVTYPE=CNV:GAIN;END=70627;ST_ACC=nstd46;Parent=nsv514929
1       68496   nssv2866245     A       <CNV:GAIN>      .       .       DGVa_201507;SVTYPE=CNV:GAIN;END=70627;ST_ACC=nstd46;Parent=nsv514929
1       68496   nssv2866252     A       <CNV:GAIN>      .       .       DGVa_201507;SVTYPE=CNV:GAIN;END=70627;ST_ACC=nstd46;Parent=nsv514929
1       68496   nssv2866257     A       <CNV:GAIN>      .       .       DGVa_201507;SVTYPE=CNV:GAIN;END=70627;ST_ACC=nstd46;Parent=nsv514929
```

**Comment by rachellyne** [comment]
The data file is a bit limited - it just gives us locations.  Ideally we would want study/publication, and consequence/phenotype as well.  The data that is there should just slot into our sequence alterations model - although there can be more then one "Type" (e.g. gain and loss) so we may need to re-think this.     For the rows that have a "parent=xxx", in ensembl these are "evidences" for the longer parent CNV.  So we could just load the parents or add an evidence class for rest.  Given the limited data, it might be worth just providing a link-out to ensembl from each parent.  It's possible we may get more info from other files in ensembl - e.g the phenotypes file - i'll have a look.  This is data that should be displayed on our genome browser when we get one.

**Comment by julie-sullivan** [comment]
I'll leave this to @rachellyne to decide what to add next.
