### ISSUE TITLE
UniProt: comments not capturing disease

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1202]
@rachellyne I noticed the protein had duplicated comments.

> "The disease is caused by mutations affecting the gene represented in this entry."

Search this file for those words:

http://www.uniprot.org/uniprot/Q9BSI4.xml

It's referring to two different diseases. How can we capture these data?

```
<comment type="disease" evidence="12">
<disease id="DI-03165"><name>Dyskeratosis congenita, autosomal dominant, 3</name>
<acronym>DKCA3</acronym>
<description>A rare multisystem disorder caused by defective telomere maintenance. It is characterized by progressive bone marrow failure, and the clinical triad of reticulated skin hyperpigmentation, nail dystrophy, and mucosal leukoplakia. Common but variable features include premature graying, aplastic anemia, low platelets, osteoporosis, pulmonary fibrosis, and liver fibrosis among others. Early mortality is often associated with bone marrow failure, infections, fatal pulmonary complications, or malignancy.</description>
<dbReference type="MIM" id="613990"/></disease>
<text>The disease is caused by mutations affecting the gene represented in this entry.</text></comment>
<comment type="disease" evidence="12"><disease id="DI-00998">
<name>Dyskeratosis congenita, autosomal dominant, 5</name>
<acronym>DKCA5</acronym><description>A disease characterized by bone marrow hypoplasia, nail dystrophy, fine sparse hair, fine reticulate skin pigmentation, oral leukoplakia, bilateral exudative retinopathy, cerebellar hypoplasia, and growth retardation.</description><dbReference type="MIM" id="268130"/></disease>
<text>The disease is caused by mutations affecting the gene represented in this entry.</text></comment>
```

**Comment by rachellyne** [comment]
It look like we already process this correctly - we can have multiple comments of the same type.

**Comment by julie-sullivan** [comment]
@rachellyne Take a look at PPARG: http://humanmine.org/humanmine/portal.do?class=Gene&externalids=ENSG00000132170

There is a comment:

```
Disease susceptibility may be associated with variations affecting the gene 
represented in this entry.
```

But we aren't capturing the name of the disease so that makes this comment less useful. How can we capture the name of the disease? Have a "disease" reference from the comment data type?

This is how it's shown in the XML:

```
<comment type="disease" evidence="47">
<disease id="DI-01221"
><name>Obesity</name>
<acronym>OBESITY</acronym>
<description>A condition characterized by an increase of body weight beyond the limitation of skeletal and physical requirements, as the result of excessive accumulation of body fat.</description>
<dbReference type="MIM" id="601665"/></disease>
<text>Disease susceptibility may be associated with variations affecting the gene represented in this entry.</text>
</comment>
```

* We only capture the `text` part
* There may be other data we are missing, they seem to have added a bit
* The end result of this (besides missing the data) is that we have duplicate comments that say "Disease susceptibility may be associated with variations affecting the gene 
represented in this entry."

So how to capture these data?

**Comment by rachellyne** [comment]
oh I see.  Ok i'll take a look at all the comments and see how they are structured.

**Comment by rachellyne** [comment]
We could just place all under the Disease comment and cat the id, name description and text with a : separator.  This is what they do if you view a uniprot page as text.  Long term we probably want to look at displaying the comments in a nicer way, as they do on the default uniprot view.

**Comment by julie-sullivan** [comment]
@rachellyne Okay, so just put all the text in the Comment.description. I'll try it!

**Comment by julie-sullivan** [comment]
@rachellyne from Anthony: 

```
You might even want to consider having it as its own section - most of the biologists I deal with consider it to be invaluable when looking at candidates.  
```
