### ISSUE TITLE
YeastMine prod (1.5) no model changes since complexes

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#1220]
This bug came to my attention just today (still looking into it..)

http://yeastmine.yeastgenome.org/yeastmine/template.do?name=Domain_Protein_Gene&scope=global

it works with the default value of 'WD40 repeats' but not 'Signal peptide region' (it should).  I see this error in logs with both values i.e when it works and when it does not..

bag tables: 0 ms, generate: 1 ms, optimise: 22 ms,  ms,  estimate: 0 ms, execute: 5 ms, convert results: 0 ms, extra queries: 13 ms, total: 41 ms, rows: 21
12/11/15,14:45:23 ERROR org.intermine.webservice.server.core.TableRowIterator     - Couldn't find any paths for org.intermine.model.bio.GOAnnotation from amongst [Gene.secondaryIdentifier, Gene.symbol, Gene.proteins.secondaryIdentifier, Gene.proteins.symbol, Gene.proteins.proteinDomains.name, Gene.proteins.proteinDomains.description, Gene.proteins.proteinDomains.interpro.name, Gene.proteins.proteinDomains.interpro.description, Gene.proteins.proteinDomains.goAnnotation.ontologyTerm.identifier, Gene.proteins.proteinDomains.goAnnotation.ontologyTerm.description, Gene.proteins.proteinDomains.start, Gene.proteins.proteinDomains.end, Gene.proteins.proteinDomains.evalue, Gene.proteins.proteinDomains.method]

**Comment by julie-sullivan** [comment]
`Signal peptide region` doesn't have an interpro domain (which probably isn't right?). If you make the join to interpo be an outer join, the query will work:

```
<query name="" model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.proteins.secondaryIdentifier Gene.proteins.symbol Gene.proteins.proteinDomains.name Gene.proteins.proteinDomains.description Gene.proteins.proteinDomains.interpro.name Gene.proteins.proteinDomains.interpro.description Gene.proteins.proteinDomains.goAnnotation.ontologyTerm.identifier Gene.proteins.proteinDomains.goAnnotation.ontologyTerm.description Gene.proteins.proteinDomains.start Gene.proteins.proteinDomains.end Gene.proteins.proteinDomains.evalue Gene.proteins.proteinDomains.method" longDescription="Retrieve Proteins/Genes that have a given domain." sortOrder="Gene.symbol asc">
  <join path="Gene.proteins.proteinDomains.goAnnotation" style="OUTER"/>
  <join path="Gene.proteins.proteinDomains.goAnnotation.ontologyTerm" style="OUTER"/>
  <join path="Gene.proteins.proteinDomains.interpro" style="OUTER"/>
  <constraint path="Gene.proteins.proteinDomains.description" op="=" value="Signal peptide region"/>
</query>
```

I don't know why you are getting that error in the logs though.

**Comment by kkarra** [comment]
I have to try again but making outerkoin, removing the whole interpro thing..nothing worked which puzzled mr

Sent from my iPhone


On Nov 13, 2015, at 3:11 AM, Julie Sullivan <notifications@github.com<mailto:notifications@github.com>> wrote:


Signal peptide region doesn't have an interpro domain (which probably isn't right?). If you make the join to interpo be an outer join, the query will work:

<query name="" model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.proteins.secondaryIdentifier Gene.proteins.symbol Gene.proteins.proteinDomains.name Gene.proteins.proteinDomains.description Gene.proteins.proteinDomains.interpro.name Gene.proteins.proteinDomains.interpro.description Gene.proteins.proteinDomains.goAnnotation.ontologyTerm.identifier Gene.proteins.proteinDomains.goAnnotation.ontologyTerm.description Gene.proteins.proteinDomains.start Gene.proteins.proteinDomains.end Gene.proteins.proteinDomains.evalue Gene.proteins.proteinDomains.method" longDescription="Retrieve Proteins/Genes that have a given domain." sortOrder="Gene.symbol asc">
  <join path="Gene.proteins.proteinDomains.goAnnotation" style="OUTER"/>
  <join path="Gene.proteins.proteinDomains.goAnnotation.ontologyTerm" style="OUTER"/>
  <join path="Gene.proteins.proteinDomains.interpro" style="OUTER"/>
  <constraint path="Gene.proteins.proteinDomains.description" op="=" value="Signal peptide region"/>
</query>


I don't know why you are getting that error in the logs though.

-

**Comment by julie-sullivan** [comment]
Does the query above work for you? It returns 553 rows for me when I run it, with signal peptide region as the value

**Comment by kkarra** [comment]
Yes your query works. It is exactly the query Edith and I tried and did not work (unfortunately you have to take my word for it ;-) )

**Comment by kkarra** [comment]
Oh, try it in the template above. Either I have the template wrong or something odd with 'ON' 'OFF' usage..

**Comment by julie-sullivan** [comment]
Even though you have turned the interpro constraint "OFF", the interpro description is still in the output. So the query still has a join on that table, hence the 0 results.

**Comment by kkarra** [comment]
<query model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.proteins.secondaryIdentifier Gene.proteins.symbol Gene.proteins.proteinDomains.name Gene.proteins.proteinDomains.description Gene.proteins.proteinDomains.interpro.name Gene.proteins.proteinDomains.interpro.description Gene.proteins.proteinDomains.goAnnotation.ontologyTerm.identifier Gene.proteins.proteinDomains.goAnnotation.ontologyTerm.description Gene.proteins.proteinDomains.start Gene.proteins.proteinDomains.end Gene.proteins.proteinDomains.evalue Gene.proteins.proteinDomains.method" sortOrder="Gene.symbol ASC" >
  <join path="Gene.proteins.proteinDomains.goAnnotation" style="OUTER"/>
  <join path="Gene.proteins.proteinDomains.goAnnotation.ontologyTerm" style="OUTER"/>
  <join path="Gene.proteins.proteinDomains.interpro" style="OUTER"/>
  <constraint path="Gene.proteins.proteinDomains.description" op="=" value="Signal peptide region " code="A" />
</query>

This query is what I think is identical to yours, but does not work for me.. 

I made it an outer join in the template and should be fine. But editing that template behaves wierdly..

**Comment by kkarra** [comment]
Never mind!! a trailing space in input was the culprit! odd that it is not trimmed (may be it is in 1.6)
