### ISSUE TITLE
UniProt: why does this gene have 79 proteins?

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1224]
http://www.flymine.org/flymine/portal.do?class=Gene&externalids=FBgn0033159

@rachellyne From their names, it looks like they should be isoforms. But they aren't. trembl's at fault?

This is a problem for next steps in that we want to show data for our protein.

**Comment by julie-sullivan** [comment]
Here's a list of genes with the protein counts:

[flies.txt](https://github.com/intermine/intermine/files/35699/flies.txt)

**Comment by rachellyne** [comment]
This is the Dscam protein - it's a very famous protein partic in Drosophila as it has so many isoforms.  I'll post details.

**Comment by rachellyne** [comment]
A homologue of the Dscam protein in Drosophila melanogaster has 38,016 isoforms [4] arising from four variable exon clusters (12, 48, 33 and 2 alternatives, respectively).[1] By comparison, the entire Drosophila melanogaster genome only has 15,016 genes. The diversity of isoforms from alternative splicing of the Dscam1 gene in D. melanogaster allows every neuron in the fly to display a unique set of Dscam proteins on its cell surface. Dscam interaction stimulates self-avoidance mechanisms that are essential for normal neural circuit development

**Comment by julie-sullivan** [comment]
@rachellyne But they aren't marked as isoforms, they are listed as full proteins. That's our problem.

**Comment by julie-sullivan** [comment]
In the name they say "isoform GK" (or whatever) but they are not listed as isoforms in the Uniprot file.

**Comment by julie-sullivan** [comment]
@rachellyne From their names, it looks like they should be isoforms. But they aren't. trembl's at fault?

**Comment by rachellyne** [comment]
Yes, I think it's because they are all still in tremble.

**Comment by julie-sullivan** [comment]
Is there anything we can do about this? @yochannah wants so show our nice protein displayer but it's going to show 79 times for this gene. Is there a way to tell the "good" proteins? Can we ask UniProt to update their data?

**Comment by rachellyne** [comment]
This is real though so isn't going to go away in swissprot - they may expand it to the full 38,000!.   How bad does it look with 79?  Can we collapse at all - only show 10 and expand for all?

**Comment by yochannah** [comment]
I think collapsing is the way forward, but if there are only three 'real' results we could be forcing the user to play 'spot the difference' to find meaningful data. Maybe I can filter out some of the results if they come through blank or identical - I'll have to experiment - but I'd rather not make a query that huge if most of the data are meaningless. I think the protein viewer will have to make 79 separate web service calls, which isn't the greatest idea. In fairness most results aren't this bad.

**Comment by julie-sullivan** [comment]
@yochannah Good point. This is going to be true for all protein-related tools. So something we might need to solve in general.

**Comment by julie-sullivan** [comment]
Also

> they may expand it to the full 38,000!

omg no

**Comment by rachellyne** [comment]
I think the 38,000 is just hypothetical (at the moment).

**Comment by JervenBolleman** [comment]
Just chiming in: it would be 12,000 or so which would break a whole lot of downstream users of uniprot. So we are unlikely to 'fix' it in the data soonish. The automated TrEMBL redundancy removal won't work as these being different splice forms and sequence is too different. This wouldn't really help you guys either :( Like any hyper variable gene product its a pain to fit in the UniProt flat file model.

**Comment by julie-sullivan** [comment]
@JervenBolleman Thanks, good to know!
