### ISSUE TITLE
List upload: losing duplicates 

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1233]
From @rachellyne 

```
FlyMine list upload example - has E2f.    It marks this up as a duplicate (E2f1; E2f2)
 if run as is, but if you select "match on case" it puts it as a non-gene-identifier. 
```

Only returns `E2f1` when you "match on case". Should say "Duplicate" instead and show `E2f2` too.

**Comment by rachellyne** [comment]
Should still be a duplicate shouldn't it?

**Comment by julie-sullivan** [comment]
Oh you are right! Yes, might be easier to change the identifier.

**Comment by julie-sullivan** [comment]
@rachellyne Okay, here's what's happening.

1. Search for `È2f`
1. Both genes have synonym `E2F` so both genes are matched

As expected. Then ...

1. Search for `È2f` with match on case = `true`
1. Neither gene has a synonym `E2f` so neither gene is matched
1. BUT `E2f1` has a protein with `E2f` in its name `E2F_DROME`. `E2F2` does not have this protein so is not matched.

Does that make sense? So according to our rules, these results are correct.

**Comment by rachellyne** [comment]
ok, so our rules don't quite work as this is a match on synonyms AND it find duplicates. If we find one match in synonyms it is marked as a synonym match.  The synonym bit needs to be indicated as well - maybe could show the field actually matched so the user knows it is hitting synonyms.  For someone who doesn't know, it maybe assumed that the search is adding a wild card.

**Comment by julie-sullivan** [comment]
@rachellyne how would you expect that to look?

**Comment by julie-sullivan** [comment]
I am going to close this for now, but maybe include this comment when discussing the list upload page with @yochannah
