### ISSUE TITLE
Hardcoded CDN values

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1245]
From @JoeCarlson

```
Just a bit of warning: this is not quite enough to deliver your own CDN. 
There are some hardcoded values of cdn.intermine.org
<http://cdn.intermine.org> in some of the js files. 
You can check the ’Net’ tab of firebug to identify these. You may want to
change this host in the source files.
```

Tell @sammyjava

**Comment by yochannah** [comment]
I've done some hunting and I'm having a hard time spotting any hardcoded values. Searching the intermine repo comes up with 55 results but the vast majority are test files and can safely be ignored. https://github.com/intermine/intermine/search?p=5&q=cdn.intermine.org&type=Code&utf8=%E2%9C%93 

I've also tried pointing my local flymine to a CDN locally hosted on my machine and I didn't spot any calls to cdn.intermine.org. My best guess here is that this might be an edge case scenario that doesn't come through in casual browsing and testing. @JoeCarlson, do you remember which files you had to change by any chance?

Thanks.

**Comment by sammyjava** [comment]
I think api/main/src/org/intermine/api/query/codegen/WebserviceJavaScriptCodeGenerator.java is the (main?) culprit:

shokin@chama:~/intermine$ grep -R cdn.intermine.org intermine/api/main
Binary file intermine/api/main/build/classes/org/intermine/api/query/codegen/WebserviceJavaScriptCodeGenerator.class matches
intermine/api/main/src/org/intermine/api/query/codegen/WebserviceJavaScriptCodeGenerator.java: 
"http://cdn.intermine.org");
Binary file intermine/api/main/dist/intermine-api.jar matches

**Comment by JoeCarlson** [comment]
There are URLs for javascript from cdn.intermine.org in:

https://github.com/intermine/CDN/blob/master/api

As I recall, if cdn.intermine.org is down, the javascript for the 
enhancement widgets does not load. (And there is no exception thrown. So 
it's not obvious what the issue is). This showed up for me when trying 
to display the GO enhancement widget for a list of genes.

**Comment by yochannah** [comment]
@sammyjava I think that the hardcode in [WebserviceJavaScriptCodeGenerator](https://github.com/intermine/intermine/blob/3834c5f9ce17cf6ad0a34371ec63347e89da0ebb/intermine/api/main/src/org/intermine/api/query/codegen/WebserviceJavaScriptCodeGenerator.java#L62
) is safe. As the second argument for `getProperty`, It's only there as a [default value/fallback](https://github.com/intermine/intermine/blob/3834c5f9ce17cf6ad0a34371ec63347e89da0ebb/intermine/api/main/src/org/intermine/api/query/codegen/WebserviceCodeGenInfo.java#L101) in case you haven't manually specified a cdn in your properties. Thanks for the look though! 

@JoeCarlson that does look like a possible culprit. I'll see what we can do and update the ticket when I know more.

**Comment by JoeCarlson** [comment]
I realized only today that this should be an issue in intermine/CDN and 
not intermine/intermine

joe
