### ISSUE TITLE
Web services: add an intermine version web service

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1260]
Should we add this to flymine.org/flymine/service/version or make a new web service?

**Comment by joshkh** [comment]
The current /service/version endpoint description is "Web-Service Version" and the property that it returns is "version". Having a "version" attribute along with an "intermineVersion" attribute could be a bit confusing so I vote for a new endpoint.

**Comment by julie-sullivan** [comment]
1. Add this to return current intermine version:

> /service/version/intermine

2. Leave current /service/version/ as is
3. Add new endpoint for webservice version

> /service/version/webservice

Will return the same value as

> /service/version/

**Comment by julie-sullivan** [comment]
Fixed by #1261
