### ISSUE TITLE
Complex - interacting region has two locations

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1277]
@rachellyne I am sure this is my fault but Interaction Regions has a locations collection and a location reference. 

I think we should remove the location reference to prevent confusion. Where is this added?

**Comment by rachellyne** [comment]
Oh yes - I wonder how that snuck in.  Yes, we should remove the reference.

**Comment by julie-sullivan** [comment]
@kkarra @rachellyne Can you comment? I removed the "gene" reference from interaction region. I think that was a mistake. 

![dupe-locations](https://cloud.githubusercontent.com/assets/1663057/12353910/1d020f0e-bb8a-11e5-9a33-6b8e1b66aa94.png)


However we also had two locations - one from PSI-IntAct and one from the PSI-Complex converter. I removed one. The complex source set `location` whilst the other source added to the `locations`collection. I don't care which one we use but `locations` seems safer. Thoughts? I don't know how I missed this. Kalpana, if you only used one source you wouldn't have duplicates, but still a concern because you'll have to change your model. By adding an "S".

**Comment by kkarra** [comment]
* where do you see both  'location' and 'locations'? I can't seem to find this view in YeastMine.  
* changing the model is fine with me
* did we assume the interacting regions are identical in say biogrid  and ebi complexes?

**Comment by julie-sullivan** [comment]
@kkarra 

* InteractionDetail.location has been changed to InteractionDetail.locations. See HumanMine for an example. We had regions with more than one location. You might have to change some templates.
* Yes, the model for InteractionDetail should be the same across interaction data sources.
