### ISSUE TITLE
stepZ - working with results sets

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1282]
We are introducing the idea of a "temporary list".

InterMine currently has this already. When a non-logged in user creates a list, the list is not stored to disk. Instead it's kept in memory and lost if the user closes the browser. However if the user logs in, the list IS stored to disk, saved in the user database forever.

These new temporary lists will treated a bit different. They will only be used by the stepZ user interface.

* temporary lists disappear 24 hours after last use
* temporary lists are never saved to disk, regardless of user auth status.
* temp lists are not shown to the user.

``POST cache/result-set/``

<table>
<tr>
<th>parameter</th><th>content</th>
</tr><tr>
<th>IDs</th><td>intermine IDs</td>
</tr>
</table>

* returns UUID for temporary list

``GET cache/result-set/:UUID``

* returns the same information as GET /lists/ when a list name is supplied

Tell @yochannah  and @joshkh

**Comment by julie-sullivan** [comment]
What if I do this:

1. run a template
2. select a subset of results (here's my temp list!)
3. enrich
4. look at results, filter
5. run another tool. use the GUI to filter. 
6. run complex viewer tool. while looking at complex viewer, I log in.
    * whole workflow re-runs. but I am taken from complex viewer to this other tool to reselect. I don't remember what I did.

Might be a problem?

**Comment by julie-sullivan** [comment]
Input to a tool might be a real list OR a temp list. e.g. list operations tool

**Comment by joshkh** [comment]
Just two quick thoughts:

1. /cache/result-set/add seems redundant when we could just use POST as we do with ID resolution.

To store something in the cache:
```
POST /cache/result-set
```
Payload:
```
ids: [11111, 22222, 33333, 44444]
token: ABCDEFGHIJK (sent in Authorization header)
```
Returns:
```
{"uid": "c780f648-8595-4798-96cc-f2b944caa274",
"executionTime":"2016.01.25 13:54::47",
"wasSuccessful":true,
"error":null,
"statusCode":200}
```

2. Calling GET on the cached result-set shouldn't return its contents. Instead it should return the same information as GET /lists/ when a list name is supplied.

```
GET /cache/result-set/:uuid
```

Returns
```
{"timestamp":1425906726786,
"authorized":true,
"uuid":"c780f648-8595-4798-96cc-f2b944caa274",
"status":"CURRENT",
"dateCreated":"2015-03-09T13:12:06+0000",
"type":"Gene",
"size":101},
```

**Comment by joshkh** [comment]
Logging in mid-stream is a problem. If a user has a temporary token, makes a history and then logs in, they'll lose access to their caches if the caches are protected by the temporary token. Sharing sessions is not an option because it couples the UI back to the server.

Solution: Don't require tokens for accessing a cache. The likelihood of someone guessing a UUID within a cache's time-to-live is nearly zero. Also, do not return token information when accessing a list via /cache/result-set/:uuid as this could be used as identifiable information.

Tokens should still be required to create a cache.

**Comment by julie-sullivan** [comment]
@joshkh @yochannah Update all the ``/list`` endpoints to also accept UUID. 

(I need to figure out how to make either field required.)

**Comment by julie-sullivan** [comment]
Creating lists even for anonyous users writes to disk. This is dumb. Update the code so that anonymous lists are not stored in the DB until the user logs in. This will allow us to create temporary lists as discussed above, and use the same code.

**Comment by justinccdev** [comment]
If anonymous user lists are only held in memory then this will fail in high availability scenarios where more than one Tomcat instance is handling requests.  However, I don't know if InterMine supports such a thing.

**Comment by julie-sullivan** [comment]
Closing this. We aren't going to do temporary lists, just going to pass around the identifiers.
