### ISSUE TITLE
App gene report page kills HumanMine

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#1284]
Viewing the report page for the App gene causes HumanMine to crash.  I am guessing this is because this gene has thousands of interactions - so maybe an Esyn issue.

**Comment by julie-sullivan** [comment]
When I go to the report page, I get a few errors from esyn and cytoscape.

@yochannah Can you have cytoscape stop analysing if there are more than N interactions. I don't know what N is. Maybe where N interactions breaks the site, but N+1 does not. ha! @rachellyne? Will be unusable spaghetti monster anyway. And fix esyn displayer too? Same issue.

@rachellyne Why does this gene have so many interactions?

**Comment by rachellyne** [comment]
I'm not sure why it's got quite so many.  It's cleaved into a number of peptides that all have different interactions.  It's a major protein in Alzheimers so well studied.

**Comment by yochannah** [comment]
It's both esyn and the interaction displayer causing this problem. I'll add a blocking conditional in the JSP so that neither script initialises if there are more than 500 interactions.
