### ISSUE TITLE
FlyMine: make mRNA expression terms list-able

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1286]
Right now you can't make a list of expression terms. Maybe because it's not a proper ontology?

Tell @rachellyne

**Comment by rachellyne** [comment]
I could.

**Comment by julie-sullivan** [comment]
@rachellyne I used the same list that the guy used in his query:

```
sensory
ventral midline
glia
neuroderm
ganglion
mushroom body
cerebrum
visual
ventral ectoderm
nerve
brain
neurectoderm
neuroblast
neuron
mesectoderm
nervous
```

I get "no matches". Which terms did you try to upload? Those aren't terms, they're just keywords -- part of term names. So maybe that's why.

**Comment by rachellyne** [comment]
I ran this template with a list: "Gene [D. melanogaster] -> BDGP in situ data" and made a list of the terms.  That worked fine.  I don't know how list upload works with keywords - maybe the quick search would be a better place to start and filter on mRNA expression term?

**Comment by julie-sullivan** [comment]
This works fine now. 

```
adult clypeolabrum anlage
adult eye primordium
adult foregut precursor
```

Uploads correctly in beta flymine.
