### ISSUE TITLE
Regions Tab - configure default regions

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#1287]
Is it possible to configure different and working examples for default regions for each of the Organism selected from the drop-down in the Regions Tab? If not, is it possible to add this feature?

**Comment by julie-sullivan** [comment]
Yes! Here are the docs:

http://intermine.readthedocs.io/en/latest/webapp/region-search/

On your `web.properties` file, set the `genomicRegionSearch.defaultSpans` parameter. 

Try that and let me know if you have problems!
