### ISSUE TITLE
Check for unique number before rejecting large lists.

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#1288]
List upload (particularly of very large lists) - include a step that checks for actual number of genes/proteins before rejecting if list size is over 100,000.

(I tried to upload a list containing > 200,000 entries but the actual unique number was only ~17,000.  It was rejected due to the 100,000 list limit).

**Comment by julie-sullivan** [comment]
@rachellyne Can you attach your list? For testing?

**Comment by julie-sullivan** [comment]
Implement with #1282

**Comment by rachellyne** [comment]
Its says:  Yowza, that's a big file!  So doesn't look like I can.  But, its:

/local-homes/rachel/humanmine/panther/panther_humanEntries

**Comment by julie-sullivan** [comment]
@rachellyne Can you put your list on the shared drives?

**Comment by julie-sullivan** [comment]
otherwise i can write a script and generate a huge file but would rather have yours.
