### ISSUE TITLE
List converter with subtype constraint fails

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1296]
If a list converter template contains a subtype constraint, you get an error when you try to convert a list.
The link appears on the list analysis page where it should, and has (apparently) the right count. 
But clicking on the link gets this error:
java.lang.IllegalArgumentException: Mismatch between end type of prefix: OntologyTerm and type parameter: GOTermat 
org.intermine.web.logic.pathqueryresult.PathQueryResultHelper.getDefaultViewForClass(PathQueryResultHelper.java:89)at …

In my case, there is a subtype constraint (GOTerm) on the path Gene.goAnnotation.ontologyTerm.

**Comment by sergiocontrino** [comment]
see pull #1568
