### ISSUE TITLE
Template generates bad web service URL

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1297]
On a template, if you plug in a list and then click the web
service link, you get a bad URL.

![image](https://cloud.githubusercontent.com/assets/1064767/13047459/366e023c-d3ad-11e5-967f-c424bdabf42c.png)

**Comment by JoelRichardson** [comment]
#1298

**Comment by sergiocontrino** [comment]
appears to have never worked (also modmine got the bug).
