### ISSUE TITLE
GOMine: add GO annotation to protein if no gene present in UniProt entry

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#131]
1. process GO separately from genes
2. refactor processGoAnnotation() to work with proteins or genes
3. add annotation to protein if entry doesn't have genes

**Comment by julie-sullivan** [comment]
@kkarra is this still needed?

**Comment by kkarra** [comment]
no, gomine doesn't exist anymore..

**Comment by julie-sullivan** [comment]
How sad!
