### ISSUE TITLE
Inconsistent session expiration

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1318]
Original error report: 

> I keep getting this -  when I try to view results from a widget it opens
> a new humanMine, but this one is not "logged in" as me and so throws an
> error.  I am logged into the original one.
>
>   Rachel.
>
>
>
>
>
> We encountered an error running a query from an
> embedded result table.
>
> page:
> http://www.humanmine.org/humanmine/results.do?trail=%7Cquery%7Cresults.0&queryBuilder=true
> service: http://www.humanmine.org/humanmine/service/
> error: Error: The query XML is well formatted but you do not have access
> to the following mentioned lists:
> LISTE.
>
> date-stamp: Thu Mar 03 2016 11:21:42 GMT+0000 (GMT)
>
> -------------------------------
> IMJS: 3.15.0
> -------------------------------
> IMTABLES: 2.0.0
> -------------------------------
> QUERY: <query model="genomic" view="Gene.secondaryIdentifier Gene.symbol
> Gene.primaryIdentifier Gene.organism.name
> Gene.goAnnotation.ontologyTerm.identifier
> Gene.goAnnotation.ontologyTerm.name
> Gene.goAnnotation.ontologyTerm.parents.identifier
> Gene.goAnnotation.ontologyTerm.parents.name" constraintLogic="A and B"
>  ><constraint path="Gene" op="IN" value="LISTE" code="A" /><constraint
> path="Gene.goAnnotation.ontologyTerm.parents.identifier" op="ONE OF"
> code="B" ><value>GO:0070997</value></constraint></query>
> -------------------------------
> STACK: Error: The query XML is well formatted but you do not have access
> to the following mentioned lists:
> LISTE.
>
> at null.<anonymous>
> (http://cdn.intermine.org/js/intermine/imjs/3.15.0/im.js:139:31)
> at EventEmitter.emit
> (http://cdn.intermine.org/js/intermine/imjs/3.15.0/im.js:8281:17)
> at Response.handle
> (http://cdn.intermine.org/js/intermine/imjs/3.15.0/im.js:13263:19)
> at XMLHttpRequest.xhr.onreadystatechange
> (http://cdn.intermine.org/js/intermine/imjs/3.15.0/im.js:13026:13)

**Comment by yochannah** [comment]
When this happens, it's from a list page that was open from yesterday. I could access the old session from the original window, but not any new windows. Closing the original window and starting a brand new session made it all work fine.

**Comment by yochannah** [comment]
Tell @julie-sullivan @rachellyne

**Comment by julie-sullivan** [comment]
This is likely a tomcat issue.

**Comment by julie-sullivan** [comment]
Tomcat has the site is www.humanmine.org but sees that you are coming from humanmine.org and thinks you are coming from a different site and Freaks Out.

Paul updated the proxy to forward humanmine.org to be www.humanmine.org. Now everything is working as expected.

Thanks to @yochannah for figuring that out!!
