### ISSUE TITLE
Cannot change LOOKUP filter in results table

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1328]
To reproduce, run some query that has a LOOKUP parameter.
I used http://www.flymine.org/flymine/template.do?name=Gene_Location&scope=global

From the results table, go to Manage Filters and try to change the LOOKUP to a different value.
Whatever you enter is ignored and the original query is rerun.

**Comment by julie-sullivan** [comment]
@JoelRichardson It worked for me. Did you click on the "update" button? Can you try again.

That is poor UI!

**Comment by JoelRichardson** [comment]
@julie-sullivan Hmm..flymine's cdn seems to be down at the moment. 
But I tried it on MouseMine and got the same behavior. 
Try this one:
http://www.mousemine.org/mousemine/template.do?name=Gene_Protein&scope=global
From the result, "Manage Filters" -> edit the LOOKUP, change from Pparg to Pax6.
Click "update", no change.

**Comment by julie-sullivan** [comment]
@JoelRichardson that worked for me. Is this browser specific? I tried on the latest chrome.

**Comment by JoelRichardson** [comment]
@julie-sullivan Yes this is weird. So I'm seeing tons of 503 Service Unavailable errors from cdn.intermine.org. But only in chrome. Safari is fine. 

I'm running the latest chrome (53.0.2785.89 64-bit).

Back to the original problem...even in safari, I'm seeing the same behavior. I change the LOOKUP value in the filter dialog box, click "Update", and nothing happens. The dialog goes away, but the results to not change. If I open "Manage filters" again, the LOOKUP has the original value.

**Comment by yochannah** [comment]
I can reproduce this. I have a feeling that the modify filter section doesn't support `LOOKUP` properly, as if you try to change from `LOOKUP` to something else, perhaps `=`, then `LOOKUP` disappears from the dropdown entirely....

**Comment by julie-sullivan** [comment]
This is now working correctly.
