### ISSUE TITLE
org.intermine.task.BuildDbTask throws PSQLException: ERROR: relation "objectstore_unique_integer" already exists

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1329]
It seems like all but the first integrate task throws this exception:
```
2016-03-17 15:52:45 INFO         org.intermine.task.BuildDbTask     - Failed to create SEQUENCE: org.postgresql.util.PSQLException: ERROR: relation "objectstore_unique_integer" already exists
```
I know it's a bit of a pain to test whether a sequence exists before trying to create it, but this is hugely annoying because I grep ERROR in my intermine.log as I debug my data sources, and I have to skip over this one all the time. Here's [an example solution on StackOverflow](http://stackoverflow.com/questions/13752885/how-to-create-sequence-if-not-exists), I don't know if it fits into how things are done here.

**Comment by justinccdev** [comment]
Was fixed in 1ec6ce1 on 2016-06-15.  Won't be in a release yet.
