### ISSUE TITLE
Graph widgets: use filters

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1333]
Tell @sammyjava 

The graph widget has a "filters" parameter. Is this used? Specifically, we'd like to be able to filter out scaffolds.

**Comment by julie-sullivan** [comment]
Hi, devs. I've got a lot of scaffolds in a mine, which I've loaded as Chromosomes so they take advantage of all the nice chromosome features in the webapp (report heading, JBrowse, etc.). However, one thing that's very annoying is that if I look at a list of genes that are located on chromosomes, the chromosome_distribution_for_gene graphdisplayer shows all the chromosomes plus scaffolds on the domain axis, meaning that the histogram is relegated to a tiny portion of the axis (see attached). There are far more scaffolds than real chromosomes.

I see there is a filters attribute on the graphdisplayer, and I'm wondering if I could restrict the graph to only include chromosomes that have names that contain the string "Chr" or something. I've done some searching and haven't found any such examples.
```
  <!-- widgets -->
  <widgets>
    <graphdisplayer id="chromosome_distribution_for_gene"
                    title="Chromosome Distribution"
                    description="Actual: number of items in this list found on each chromosome.  Expected: given the total number of items on the chromosome and the number of items in this list, the number of items expected to be found on each chromosome."
                    graphType="ColumnChart"
                    rangeLabel="Count"
                    domainLabel="Chromosome"
                    filterLabel="Organism"
                    filters="organism.name=[list]"
                    startClass="Gene"
                    typeClass="Gene"
                    categoryPath="chromosome.secondaryIdentifier"
                    seriesLabels="Actual,Expected"
                    seriesPath="ActualExpectedCriteria"
                    constraints="organism.name=[Organism]"
                    views="primaryIdentifier, symbol, secondaryIdentifier, organism.name, chromosome.primaryIdentifier,
                           chromosomeLocation.start, chromosomeLocation.end, chromosomeLocation.strand"/>

  </widgets> 
```

**Comment by julie-sullivan** [comment]
@rachellyne This is true of flymine too. Is there a safe way to do this? Is there a regular expression maybe that we can use?

**Comment by danielabutano** [comment]
Not sure @sammyjava if its' still relevant but have you tried to add  it in the constraint?

**Comment by sammyjava** [comment]
Wow. This is ancient; I've been loading "Supercontig" for years now, so only "true" chromosomes are loaded as such. I'll close this as no longer relevant. :)
