### ISSUE TITLE
PSI-XML -> SBGN

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1338]
Tell @tschaka1904 

```
The SBGN Process Description language 14 shows the temporal courses of biochemical
interactions in a network. visualising all the molecular interactions taking place in a network
of biochemical entities. For causal interactions to be displayed in the most appropriate
format, a PSI-MI  XML  →  SBGN  converter  will  need  to  be  written,  that will give the user
access to the many open-source visualisation tools which have been written.
```

**Comment by bmeldal** [comment]
Hi Julie,

I don't think I'm the best person to help you here :( but as you already emailed MIDAS wait for a reply there :)

Birgit

**Comment by julie-sullivan** [comment]
oops sorry! I will delete you and replace with Max! 

If you delete your comment you won't get emails from this ticket. (i think!)

**Comment by bmeldal** [comment]
I'll unsubscribe :)

**Comment by julie-sullivan** [comment]
Can use this library to convert:
http://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1000-2

**Comment by julie-sullivan** [comment]
This is going to be in the viewer code, not in InterMine.
