### ISSUE TITLE
InterMine - update wiki

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1344]
http://gmod.org/wiki/InterMine

https://en.wikipedia.org/wiki/InterMine

We could likely add some other intermine wiki pages. But to update what is there is enough. Should add pubmed papers too.

**Comment by yochannah** [comment]
Also, need to do: 

- http://www.openhelix.com/search.cgi
- Biosharing
- http://www.programmableweb.com/api/intermine

Wikipedia proper is done.

**Comment by chanakaDe** [comment]
what we need to do here ?

**Comment by yochannah** [comment]
Hey @chanakaDe,

This is a ticket to help increase InterMine's presence on the web. 

 I'd suggest starting with openhelix or biosharing, figuring out how to register and add entries for any InterMines that don't explicitly exist already. You can see a list of active intermines at intermine.org.

You could also find InterMine's papers and add them to the InterMine wikipedia article if you are inclined.

**Comment by chanakaDe** [comment]
Yeah I would love to. And also I can see a list of active intermines at intermine.org. So, if you guide me on the process, i love to contribute.....

**Comment by julie-sullivan** [comment]
What about lab worm?

**Comment by julie-sullivan** [comment]
bio.tools?

**Comment by julie-sullivan** [comment]
https://omictools.com/intermine-tool

**Comment by julie-sullivan** [comment]
https://www.re3data.org/

**Comment by julie-sullivan** [comment]
@yochannah Maybe we should keep a list of orgs to update in the outreach repo instead?

**Comment by yochannah** [comment]
Yes, that sounds like a good plan. When we get a minute, we should migrate them. 

I'd also rather have 10 or 15 tickets in the outreach repo that are achievable individual site items rather than a monolithic neverending task, I think. It might make it easier to approach.

**Comment by anmol27katyani** [comment]
Hello, @yochannah , Is this issue still in progress, I would like to help out?

**Comment by yochannah** [comment]
@anmol27katyani I've been on leave so slow to respond to GitHub issues 😭 if you're still interested, then yes, we could use help adding entries for InterMine to various online repositories. Many of the tasks in this issue are outdated, though. I'm going to close this issue - see this repo, instead: https://github.com/intermine/outreach/labels/online-presence

**Comment by anmol27katyani** [comment]
Checking it out, I'll focus on the new repo

Thanks for the heads up
