### ISSUE TITLE
Throw an exception when source tries to load duplicate data.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1347]
From @sammyjava 

I've finally resolved some extreme confusion about enforcement of unique keys defined in DATASOURCE_keys.properties. What I've found is that the production database can be loaded with two records that violate those key definitions without throwing an error; however, if you then run _another_ datasource that attempts to merge with those records, you get an error thrown as follows:

```
Problem while loading item identifier 2_1100 because
Duplicate objects from the same data source; o1 = "QTL:10012630" (in database), o2 = "QTL:10011241" (in database), source1 = "<Source: name="file-cmap", type="null", skeleton=false>", source2 = "<Source: name="file-cmap", type="null", skeleton=false>"
```

Fair enough, but file-cmap was run two sources ago! And, yes, there ARE two records that violate the key definitions IN the production database from file-cmap:

```
soymine=> select * from qtl where secondaryidentifier='Pod maturity 22-3';
-[ RECORD 1 ]--------------+-------------------------------------
id                         | 10011241
primaryidentifier          | GmComposite2003_H_Pod maturity 22-3
secondaryidentifier        | Pod maturity 22-3
sequenceontologytermid     | 10012811
organismid                 | 10000001
class                      | org.intermine.model.bio.QTL
-[ RECORD 2 ]--------------+-------------------------------------
id                         | 10012630
primaryidentifier          | GmComposite2003_C2_Pod maturity 22-3
secondaryidentifier        | Pod maturity 22-3
sequenceontologytermid     | 10012811
organismid                 | 10000001
class                      | org.intermine.model.bio.QTL
```

Here are the key definitions that resulted in the error being thrown well after the culprit datasource was run:

```
QTL.key_primaryidentifier=primaryIdentifier
QTL.key_secondaryidentifier=secondaryIdentifier,organism
```

The second of these is violated by these two records.

This seems fundamentally wrong (and very confusing) to me. I should not be able to load duplicate objects into the production database which violate the unique keys that I've defined.

Is there a reason why the uniqueness rules defined in DATASOURCE_keys.properties aren't applied when loading data from a datasource into the production database, but rather only throw an error during a merge later on? Is there something I can change so that my uniqueness rules are enforced during data loading, so I get an informative error when it happens, rather than down the line when I'm running a totally different data source?

**Comment by julie-sullivan** [comment]
@sammyjava yes, this is terrible and should be fixed. The build system does not handle this case properly and causes lots of confusing errors.

The keys you define are integration keys only. The build only checks for uniqueness on merge, not on load. 

This needs to be corrected! InterMine stores items in batches so I'm not really sure where the duplicate check should take place. What do you think? After all data is loaded, before the next source, check all the keys and check if each has duplicates?

Current system:

1. on store, checks if object is already in database, using integration keys
2. if not, load
3. if so, merge. error if duplicate records already in database

New system:

1. on store, checks if object is already in database, using integration keys
    * maybe add a check here to check if object is in current batch too.
2. if not, load
3. if so, merge. error if duplicate records already in database

**Comment by sammyjava** [comment]
I think the fundamental thing is that the production database allows two identical records from a data source. Every field but id is identical in my example. I don't see any situation where that would make sense. I think this would be improved greatly at the data source stage by simply creating a unique constraint on ALL non-id fields in every object table during the db build. That would have resulted in a Postgres SQL error during the source run in this case, which would have prevented me from going further down the line of sources.

BTW, Joe gave a talk on "InterMine Doppelgangers" last week on the topic of post-merge doppelgangers (where you haven't restricted the fields enough) which is a different but also ever-present annoyance. Tuning the keys and priorities is much more an art than a science, it seems, and requires the practice an art requires.

**Comment by julie-sullivan** [comment]
```I think the fundamental thing is that the production database allows two identical records from a data source. ...  I don't see any situation where that would make sense```

I don't either BUT InterMine cannot decide what is unique or not, it has to rely on keys set by the developer. We can't and don't make these sorts of decisions for the dev, sometimes data is garbage and they need to load it. We don't judge.

Currently the keys are only used for integration, this should be changed, I agree. The keys should be used on load, not just on merge.

However, we can't force users to unique-ify everything.

**Comment by sammyjava** [comment]
Well, I think you need to come up with a use case where a user would WANT to have two fully identical records in the post-source production database to convince me that's "helpful", since it breaks the merge down the line, anyway and you have to rebuild the mine from the start or quit your job. This isn't a judgment issue, it's a basic data integrity issue. We're supposed to be making mines easier to build, not harder. :)

That being said, I can run a post-dbmodel-build script to add a unique constraint to all non-id fields in the object tables, to make my life better during integration, so it need not be an IM policy in any case. I know I don't want two identical records in any object table, in fact I'm trying my hardest to prevent that from happening!

Otherwise it gets hard, I think, with the abstraction of objects into items and then back into DB tables during merge.

**Comment by julie-sullivan** [comment]
Yes, that's a good point. I agree!

I do know that we have duplicates in our mines out of necessity. Locations. It's cheaper to make a new location object than to check to see if we already have a location at these coordinates. Because we have millions and millions of locations, and objects are cheap. 

But I do agree. We could do a uniqueness check but then maybe let people opt out for some sources?

**Comment by sammyjava** [comment]
That would work. You could set a notUnique flag somewhere in the data source /resources probably since it's a data loading thing.

But I don't think location records are dupes, since you presumably have a different featureid value in two otherwise identical records.

**Comment by julie-sullivan** [comment]
This is a duplicate of #1148 so closing this ticket. 

Same solution though: uniqueify all input unless otherwise stated.
