### ISSUE TITLE
postprocess for datasource with multiple entries in the project file

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine#1351]
request from @sammyjava:

```
I think running a post-processor for every time you have a data source
integration entry in project.xml is bad design - it goes against the idea of being able to use a data source with multiple
integration processors (I have a total of eight so far), since one would never run a post-processor more than once. To me, it makes
sense to define the post-processor under the legfed datasource and for it to be run once from do-sources. 
```

Check the present setting.  Probably just have mechanism that impose it to be run only once.

**Comment by sammyjava** [comment]
I think the easiest way to implement this is to run a post-processor once per data source _type_ rather than once per data source. The post-processor is listed in the project.properties file for the _type_, so that's the relevant level.
