### ISSUE TITLE
Gene expression bar charts missing labels 

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1366]
![image](https://cloud.githubusercontent.com/assets/9271438/15321372/ebe1047a-1c2d-11e6-9248-4e429b34a16e.png)
Note in the attached image, the number of bars doesn't equal the number of images. This may be due to the fact that this is google charts - google may have changed the chart behaviour. Remove this dependency if possible.

**Comment by yochannah** [comment]
the labels are misaligned, too, although the chart is floating so far away from the labels it's hard to tell

**Comment by danielabutano** [comment]
Not relvant anymore with the new interface
