### ISSUE TITLE
HumanMine: report page data summary bar:  alleles

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#1367]
This should link to a summary table/template about the actual allele rather than the phenotypes of the allele as not all alleles have recorded phenotypes.  The phenotype viewer should appear below the allele table.

**Comment by julie-sullivan** [comment]
Update this line to point to alleles collection instead of displayer:

https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/displayer/MetabolicGeneSummaryDisplayer.java#L68

**Comment by julie-sullivan** [comment]
never mind, this looks fine! says @rachellyne
