### ISSUE TITLE
Deleting templates doesn't really delete them

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1369]
Thought I was going crazy.

If you delete a template via the MyMine UI, it's gone from the UI, but doesn't actually get deleted from the db. Next time you restart the webapp, the deleted templates reappear!

**Comment by julie-sullivan** [comment]
Test very carefully!

Added / edited / deleted correctly:

1. templates
2. queries

- Even after webapp restart
- Even after tomcat restart
