### ISSUE TITLE
Issues with https

### ISSUE THREAD

**Issue by terrymun** [intermine/intermine#1370]
Thanks for the amazing project. I have managed to deploy the malariamine web app with the help of the step-by-step guide, with one issue: the CDN still insists on being loaded via HTTP, which breaks the SSL encryption and causing all CDN resources to be blocked from loading:

![screen shot 2016-05-19 at 12 26 56](https://cloud.githubusercontent.com/assets/5593067/15390634/1a0a4556-1dbd-11e6-9a7a-6855cab82855.png)

If anyone wants to take a peek, it's currently deployed over at [https://lotus.au.dk/malariamine/](https://lotus.au.dk/malariamine/).

I see that this issue has been raised previously (#1360 and #1245). #1245 has been fixed in v1.6.6 which I am currently using, so I am not too sure if that is the case.

Perhaps someone can point me in the right direction?

p/s: Also, on the main page of the web app, the `<base href="...">` insists on dictating http:// instead of a protocol-agnostic URI, which causes local resources to be forced through HTTP instead of HTTPS. Commenting out `<html:base/>` from `/intermine/webapp/main/resources/webapp/layout.jsp` fixed it, without causing much issue.

**Comment by julie-sullivan** [comment]
@terrymun Hi Terry! Yes, HTTPS is still broken, but should be fixed in the next release. You should be able to pull in this fix however:

https://github.com/intermine/intermine/pull/1360

And have everything work for you. I believe the web service clients are still to be tested, I don't know if that's an issue for you.

@sergiocontrino Can you comment on @terrymun's comment on the home page?

**Comment by sergiocontrino** [comment]
hi @terrymun, when simply commentig out the <html:base/> bit we had an issue with the templates (on the front page) loosing part of the path. please have a look at #1370 for a fix.
i notice now that probably we should pass the protocol type via a property. let us know how your testing goes! thanks

**Comment by terrymun** [comment]
Thanks @julie-sullivan and @sergiocontrino, thanks for the quick reply. I have pulled the fix, and redeployed the webapp but it seems like the changes aren't being made. Do I have to rebuild Intermine and redeploy the web app again? Sorry if the questions are really pedestrian, it's not exactly what I'm good at.

**Comment by sergiocontrino** [comment]
hi @terrymun , please rebuild e deploy the webapp (ant default remove-webapp release-webapp in the mine/webapp directory). thanks.

**Comment by terrymun** [comment]
Hi @sergiocontrino, seems like modifying the original layout.jsp (`intermine/webapp/main/resources/webapp/layout.jsp`) didn't work for me, so I hand-edited the generated layout.jsp instead, and it worked :) thanks for the help!

I do not encounter any further warnings or error 👍 thanks guys!
