### ISSUE TITLE
OMIM script fails

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1378]
I am pretty sure it works, just does not exit gracefully.

```
MIM[601929] pubmedID does not exist: {u'source': u'Molec. Cell. Biol. 155: 173-182, 1996.', u'mimNumber': 601929, u'authors': u'Santiago-Garcia, J., Mas-Oliva, J., Saavedra, D., Zarain-Herzberg, A.', u'title': u'Analysis of mRNA expression and cloning of a novel plasma membrane Ca(2+)-ATPase splice variant in human heart.', u'referenceNumber': 9}
Traceback (most recent call last):
  File "./get_omim_pubmed.py", line 104, in <module>
    main()
  File "./get_omim_pubmed.py", line 94, in main
    pubmed_cited_list = get_omim_pubmed(mim_number, log)
  File "./get_omim_pubmed.py", line 45, in get_omim_pubmed
    data = resp.json() # In case the JSON decoding fails, r.json simply returns None.
  File "/usr/local/lib/python2.7/dist-packages/requests-2.8.1-py2.7.egg/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Also, took a brazillon hours to run, guessing could be quicker. Tell @rachellyne

**Comment by julie-sullivan** [comment]
No, the script failed after all. 

The older file is 2.9 mb and our file is now at 900 k. So something went wrong.

**Comment by julie-sullivan** [comment]
Failed on ID `616527`

**Comment by julie-sullivan** [comment]
I will use mimTitles.txt now instead.

How do I parse? 

`Mim Number` - Disease identifier
`Preferred Title` - Disease name

Do I do anything with the rest? Synonyms?

```
# Prefix        Mim Number      Preferred Title; symbol Alternative Title(s); symbol(s) Included Title(s); symbols
NULL    100050  AARSKOG SYNDROME, AUTOSOMAL DOMINANT            
Percent 100070  AORTIC ANEURYSM, FAMILIAL ABDOMINAL, 1; AAA1    ANEURYSM, ABDOMINAL AORTIC; AAA;; ABDOMINAL AORTIC ANEURYSM     
Number Sign     100100  PRUNE BELLY SYNDROME; PBS       ABDOMINAL MUSCLES, ABSENCE OF, WITH URINARY TRACT ABNORMALITY AND CRYPTORCHIDISM;; EAGLE-BARRETT SYNDROME; EGBRS        
NULL    100200  ABDUCENS PALSY   
```

**Comment by rachellyne** [comment]
We have disease synonyms too.

**Comment by julie-sullivan** [comment]
So I should make all the rest of the entries synonyms? "symbol Alternative Title(s); symbol(s) Included Title(s); symbols"

**Comment by rachellyne** [comment]
Just the alternative titles.

**Comment by julie-sullivan** [comment]
ok, just the first one, got it. thanks!

**Comment by julie-sullivan** [comment]
Rewriting the whole thing to use the API instead. 

[] write download script
[] update parser to use API

How do I save the API key?

**Comment by julie-sullivan** [comment]
Nope, the `mim2gene.txt` file does not have all the data for some reason. e.g. this is the entry for ```DIABETES MELLITUS, INSULIN-DEPENDENT; IDDM``` which has five associated genes in current humanmine. @rachellyne Is that right? In this file it has none:

```
 222100  phenotype 
```

Just glancing at the data file, it looks like there is only one gene per disease.

**Comment by rachellyne** [comment]
That doesn't make sense - I'm looking at it now.

**Comment by rachellyne** [comment]
I think it might be that OMIM has changed, but let me check some over examples as well.

**Comment by julie-sullivan** [comment]
1. use genemap.txt to get the gene to disease mapping information
2. use the API to get the disease names and pubs

**Comment by julie-sullivan** [comment]
I just ended up doing what we did before. Because it was easier. Using the API doesn't seem like an option as it doesn't have the data we need. Or rather it's buried in the paragraphs.

**Comment by julie-sullivan** [comment]
Without resolver

```
flymine=# select count(*) from disease;
 count 
-------
 24740
(1 row)


flymine=# select count(*) from gene;
 count 
-------
 43531
(1 row)


```

With resolver

```
flymine=# select count(*) from disease;
 count 
-------
 24740
(1 row)

flymine=# select count(*) from gene;
 count 
-------
 44526
(1 row)
```
