### ISSUE TITLE
Templates page - my mine - add summarise all link

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1382]
From @JoeCarlson

> How about an ‘summarize all’ link on the templates page?

**Comment by julie-sullivan** [comment]
The precomputing should be done on the command line as part of the release process. If you add templates after the webapp is released you can summarise them individually.

**Comment by JoeCarlson** [comment]
@julie-sullivan, that would be great.

**Comment by julie-sullivan** [comment]
@JoeCarlson Do you want to test what I've done? To make sure it's what you meant? #1559

**Comment by danielabutano** [comment]
@julie-sullivan The new functionality is only applied to the templates with tag im:public
