### ISSUE TITLE
Bootstrap fails

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1383]
```
 ~/git/intermine $ sh config/download_and_configure_tomcat.sh
config/download_and_configure_tomcat.sh: 6: config/download_and_configure_tomcat.sh: Bad substitution
```

**Comment by cmdcolin** [comment]
I think this should simply say ./config/download_and_configure_tomcat.sh (or "bash config/download_and_configure_tomcat.sh"). The "Bad substitution" is common if you just us "sh"
