### ISSUE TITLE
Disease - add data set

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1386]
Disease has a "source" field but it's empty. 

If we are going to load disease from multiple sources (OMIM and HPO) we should indicate the source.

@rachellyne Is that a good idea? Or is everything from OMIM anyway

**Comment by rachellyne** [comment]
For disease we have OMIM and orphanet.  HPO is phenotypes, but should also have a source.
At the moment the orphanet only comes in through the HPO, so we don't load the full data source.

**Comment by julie-sullivan** [comment]
Need data set on GWAS too. People need to be able to find the original data easily.

**Comment by rachellyne** [comment]
Yes, everything should have a dataset.  I don't know why these were not added originally.

**Comment by julie-sullivan** [comment]
diseases now have data sets.
