### ISSUE TITLE
Docker: tomcat uses a different port

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1388]
This line gets the port from the request:

[AbstractQueryService.java](https://github.com/intermine/intermine/blob/master/intermine/web/main/src/org/intermine/webservice/server/query/AbstractQueryService.java#L60)

This works fine obviously, except in docker where the tomcat in the docker is using a different port. So in docker the region and keyword searches work fine but queries do not. Also webservice requests not running queries, e.g. model, work fine.

Fixed by 

ba5ce7dbb96049296193598287f48ea69a63fe22
83320f173f87a0daf7e0f9a68e779f2d66d44701
88bfc8e60a4daad299fa4000912300d1d400f7eb
edf5f70efe963119bf4e945ad8601b8af973521a

Another way to do this is to always use the same port. @zorino Would that work do you think? Or is that bad practice?

@joshkh is fixing the tests which were broken by these changes. the URL looks like localhost/query/service. It's missing the port. 

@sergiocontrino Can you test? I am worried that like the tests, some requests would not work.

**Comment by zorino** [comment]
@julie-sullivan I believe it would be better to let the user configure the port for tomcat instead of hard-coding it. Otherwise it prevents the deployment of InterMine on a system that already uses that port.

**Comment by sergiocontrino** [comment]
tested on the lastest arabidopsis branch (cherry-picking the changes listed above).
deployed public webapp and all seems to work fine.
