### ISSUE TITLE
Column headers for download

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#141]
Include column headers:  exports the entire path which isn't nice.  I would truncate this to last class + field name.

Minor point: Checkbox is a bit far away from the 'Include column headers' text.

**Comment by julie-sullivan** [comment]
@rachellyne Can we close this ticket?

**Comment by rachellyne** [comment]
Has it been fixed?   I don't see any change on preview.

**Comment by julie-sullivan** [comment]
This is done.
