### ISSUE TITLE
Make display names for collections and references available as JSON model

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#1410]
Presumably this could happen in the results of the `/service/model/json` endpoint.

Currently we provide display names for classes (see `"displayName": "Synonym"`):

```
{
  "classes": {
    "Synonym": {
      "tags": [],
      "references": {
        "subject": {
          "reverseReference": "synonyms",
          "name": "subject",
          "referencedType": "BioEntity"
        }
      },
      "extends": [],
      "isInterface": true,
      "name": "Synonym",
      "displayName": "Synonym",
      "collections": {
        "dataSets": {
          "name": "dataSets",
          "referencedType": "DataSet"
        }
      }
```

Providing the plural display name for references and collections would allow us to remove asynchronous / complex behaviour in our web apps. (see last line, with reasoning below):

```
{
  "classes": {
    "Synonym": {
      "tags": [],
      "references": {
        "subject": {
          "reverseReference": "synonyms",
          "name": "subject",
          "referencedType": "BioEntity"
        }
      },
      "extends": [],
      "isInterface": true,
      "name": "Synonym",
      "displayName": "Synonym",
      "collections": {
        "dataSets": {
          "name": "dataSets",
          "referencedType": "DataSet",
          "displayName": "Data Sets"
        }
      }
```

It's already possible to get this information from intermine but it requires querying the same endpoint for any known path:
`http://www.flymine.org/query/service/model/Gene.proteins.dataSets.name`

> {"id":"Gene.proteins.dataSets.name","name":"Name","display":"Gene > Proteins > Data Sets > Name","type":"class","fields":[],"executionTime":"2016.08.30 16:15::08","wasSuccessful":true,"error":null,"statusCode":200}

**Comment by joshkh** [comment]
See https://github.com/intermine/intermine/blob/dev/intermine/web/main/src/org/intermine/webservice/server/model/ModelService.java#L141

This is where the web service gets display names for collections when a specific path is requested, such as http://www.flymine.org/query/service/model/Gene.proteins.dataSets.name

**Comment by joshkh** [comment]
We also want unique value counts for each attribute. Intermine already calculates this at build time and stores it in a summary table.

**Comment by joshkh** [comment]
And we also want row counts per collection. This will require changes to the java so maybe phase two.

**Comment by joshkh** [comment]
Scope of the request:

1. Add the display name of collections and references of a class (these are usually plural). For example, ```{Gene: {collections: {dataSets: {displayName: "Data Sets"...}}}```

I think some of these are overridden in web.properties as well. 

2. Add a count to collections and references, for example:

```{model: {classes: {Gene: {collections: {flankingRegions: {count: 0}}}}}}```

**Comment by julie-sullivan** [comment]
3 is done. check out beta flymine

```
      "Synonym":{
         "tags":[

         ],
         "references":{
            "subject":{
               "reverseReference":"synonyms",
               "name":"subject",
               "referencedType":"BioEntity"
            }
         },
         "count":3436866,
```

**Comment by julie-sullivan** [comment]
1 is more tricky. The objectstore summary doesn't have those numbers. It only has number of values in each field, which is available at the /path/values end point. It doesn't count references or collections.

I'll have to add.

These numbers will not be valid in the QB though. e.g. `Proteins.publications` count could be 100 but `Genes.proteins.publications` count be 50.

**Comment by julie-sullivan** [comment]
@joshkh I think this is key:

```
These numbers will not be valid in the QB though. e.g. Proteins.publications count could be 100 but Genes.proteins.publications count be 50.
```

let's discuss.

**Comment by julie-sullivan** [comment]
3 is done as part of  #1513, those counts already existed so easy to add to the data model.

2 is also done as part of #1513. This means that attributes refs and collections all have a "display name". Previously only the class had a display name. 

Please note that currently the webconfig-model.xml file does not allow devs to give labels to refs and collections. Only attributes can be configured. I don't know why this is the case, but it is our plan to allow this in the future (#1393).  When this happens and refs and colls can get "display names" via the webconfig, these labels will be automatically applied to the model.

**Comment by julie-sullivan** [comment]
Also given the title of this ticket, if we still do require counts for refs and colls, maybe make a new ticket.

**Comment by julie-sullivan** [comment]
Also fix tags. 

`tags` is an attribute for each class but it's always empty. This is because it's handing the tag fetching method "Gene" instead of the fully qualified name.
