### ISSUE TITLE
Query Builder: Not equals and null values problem

### ISSUE THREAD

**Issue by antcsmith** [intermine/intermine#1414]
Hello,

I've come across an odd issue when using != as a constraint in the query builder.

If you try a query such as all genes where the gene description doesn't equal something (e.g. predicted gene) it excludes all the null values from the results too.

<query name="" model="genomic" view="Gene.primaryIdentifier Gene.description" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.description" op="!=" value="predicted gene*"/>
</query>

I can replicate this with RatMine and FlyMine as well.

Thanks, Anthony

**Comment by danielabutano** [comment]
@julie-sullivan @sergiocontrino I don't think this is a bag. For instance, both postgres and neo4j have the same behaviour. If you use the operator !=, the result will not include items with null value. I would be consistent to avoid any ambiguity/confusion. Any thoughts?

**Comment by julie-sullivan** [comment]
If you ask for gene.name != "ABC", a null value is NOT equal to ABC and should be returned. 

```
<query name="query_4" model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.primaryIdentifier Gene.organism.name" longDescription="" sortOrder="Gene.secondaryIdentifier asc">
  <constraint path="Gene.description" op="!=" value="monkey"/>
</query>
```

Returns 22,000 genes instead of the 500,000 that are in the database.

**Comment by julie-sullivan** [comment]
So we have to add a constraint to add NULLs the query only when the operator is negative:

```
!= 
DOES NOT CONTAIN
NOT LIKE
```

**Comment by sergiocontrino** [comment]
i agree that this is not a bug, i would not make any change.

**Comment by julie-sullivan** [comment]
NULL means we don't have the information says @sergiocontrino .

**Comment by antcsmith** [comment]
I'm not wild about leaving this as is. Nulls are quite common - biological data rarely being complete. Any query with a negative constraint is likely to be missing entries and it was not intuitive (to us at least!) thats how it would behave. If it excludes nulls I'm not sure what queries it would be useful to use one of these negative constraints....

**Comment by danielabutano** [comment]
@antcsmith you can always create a query using 2 constraints on the same field and the OR operator. 
'''
<query name="" model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.primaryIdentifier Gene.organism.name Gene.description" longDescription="" sortOrder="Gene.secondaryIdentifier asc" constraintLogic="A or B">
  <constraint path="Gene.description" code="A" op="!=" value="predicted gene"/>
  <constraint path="Gene.description" code="B" op="IS NULL"/>
</query>
'''

**Comment by julie-sullivan** [comment]
@antcsmith Yes, you are right! NULLs are common. However NULL values (not existing) have a special meaning in computer science -- as compared to an empty value (exists but is empty). In the case above, you list this query as an example:

```
... gene description doesn't equal something
```

So something like 

```
<query name="query_4" model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.primaryIdentifier Gene.organism.name" longDescription="" sortOrder="Gene.secondaryIdentifier asc">
  <constraint path="Gene.description" op="!=" value="foobar"/>
</query>
```

If you do this in FlyMine, you will only return Rat genes because it's the only data source **in which we load these data**.

By not returning Fly genes, we are saying that we don't know what the gene description for those is so we can't answer your question. Because we don't have the data.

If Gene.description was empty, the query would behave in the way you are expecting. But the data is NULL, which means no data exists. So we don't know anything about the data. So we can't answer the query.

I hope that makes sense. Tell me how unhappy you are with that explanation @antcsmith!

**Comment by antcsmith** [comment]
I quite understand the reason and as you say you can add the extra constraint to get the nulls back again. Just not sure how obvious this will be to those making queries in the builder!

Add this to the documentation?

**Comment by danielabutano** [comment]
I think that updating the documentation is a good idea. Thanks @antcsmith for the suggestion!
@rachellyne please could you do it? Thanks!
