### ISSUE TITLE
Results: Manage columns problem

### ISSUE THREAD

**Issue by antcsmith** [intermine/intermine#1415]
Hello,

I have a problem when using the manage columns option when there is a large number of columns selected - the end of the columns selected and apply changes button disappears off the bottom (see attached screenshot). I think it needs to scroll!

Thanks, Anthony

![mitominer_4_0__list_analysis__mitocarta_2_0_human_mitochondrial_genes](https://cloud.githubusercontent.com/assets/2598621/18198857/be549892-70f5-11e6-99c3-dcd67bcaf968.png)

**Comment by julie-sullivan** [comment]
"It's a 30 second fix" = @yochannah
