### ISSUE TITLE
Add UniProt to xrefs

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1418]
@danielabutano We should add UniProt to the cross references when we create proteins.

**Comment by julie-sullivan** [comment]
This was because of modelling in neo4j, i believe. Oh no it was for RDF generation. 

@danielabutano - does this address the original URI issue

@rachellyne - is this a bad idea in general because we already have synonyms. Might want a conversation about xrefs in general.

**Comment by danielabutano** [comment]
@julie-sullivan Tested with malariamine and it works.

**Comment by danielabutano** [comment]
@julie-sullivan ...ut UniprotConverterTest doesn't work

**Comment by danielabutano** [comment]
@julie-sullivan Thanks. Now UniprotConverterTest works too.
