### ISSUE TITLE
ZebrafishMine: Perl client is not working

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1420]
The Python client seems to be fine. The Perl client is not working as expected:

```
#!/usr/bin/perl

######################################################################
# This is an automatically generated script to run your query.
# To use it you will require the InterMine Perl client libraries.
# These can be installed from CPAN, using your preferred client, eg:
#
#    sudo cpan Webservice::InterMine
#
# For help using these modules, please see these resources:
#
#  * https://metacpan.org/pod/Webservice::InterMine
#       - API reference
#  * https://metacpan.org/pod/Webservice::InterMine::Cookbook
#       - A How-To manual
#  * http://intermine.readthedocs.org/en/latest/web-services
#       - General Usage
#  * http://iodoc.labs.intermine.org
#       - Reference documentation for the underlying REST API
#
######################################################################

use strict;
use warnings;

# Set the output field separator as tab
$, = "\t";
# Print unicode to standard out
binmode(STDOUT, 'utf8');
# Silence warnings when printing null fields
no warnings ('uninitialized');

# This code makes use of the Webservice::InterMine library.
# The following import statement sets ZebrafishMine as your default
use Webservice::InterMine 0.9904 'http://zebrafishmine.org';

my $query = new_query(class => 'Gene');

# The view specifies the output columns
$query->add_view(qw/
    primaryIdentifier
    symbol
    name
/);

# edit the line below to change the sort order:
# $query->add_sort_order('primaryIdentifier', 'ASC');


# Use an iterator to avoid having all rows in memory at once.
my $it = $query->iterator();
while (my $row = <$it>) {
    print $row->{'primaryIdentifier'}, $row->{'symbol'}, $row->{'name'}, "\n";
}
```

This script works on every other mine but not ZebrafishMine.org. Is is because of the URL? Not having a path. I bet the Perl client assumes the URL is going to look a certain way. What else is different? ZFIN is on the latest InterMine code.

Tell @zebrafishmine

**Comment by zebrafishmine** [comment]
We tried recreating the context and fixing our redirect.  Neither seemed to fix the problem.  Confirmed that we can use the same perl code, replacing zebrafishmine.org/ with humanmine.org/humanmine and it works.  We also confirmed that the python client works. Should we try to debug further into the perl code?  Thanks a bunch!

**Comment by julie-sullivan** [comment]
@zebrafishmine So you changed it to be zebrafishmine.org/zebrafishmine and that still didn't work? Hrm. I assumed that was the issue (us making dumb assumptions about what the URL looks like). What is the error you get in the tomcat logs?

**Comment by julie-sullivan** [comment]
@sierra-moxon Looking at the Perl client, I don't see where the problem is:

https://github.com/intermine/intermine-ws-perl/blob/master/lib/Webservice/InterMine/Service.pm#L171

It looks like it's just using the full URI, so why the problem? 

Does tomcat give you why the request failed? That might help!

Did you try `zebrafishmine.org/zebrafishmine` and test the Perl client? I don't see how that couldn't work! Okay, tough question. Are you using your mine for anything? e.g. Do you have strong opinions on the URL? Or is there a reason for the URL changing. Because you changing your thing would be easier (for me) than me fixing this bug. lol. 

I'd really like your Perl client to work!

**Comment by julie-sullivan** [comment]
Another clue I got this error message:

```
Error parsing template sequence_alterations_pubs: (<template name="sequence_alterations_pubs" title="Author + PubMed ID --&gt; Sequence alterations in publication" comment=""><query name="sequence_alterations_pubs" model="genomic" view="SequenceAlteration.primaryIdentifier SequenceAlteration.symbol SequenceAlteration.name SequenceAlteration.publications.doi SequenceAlteration.publications.pubMedId SequenceAlteration.publications.primaryIdentifier SequenceAlteration.publications.title SequenceAlteration.publications.authorNames" longDescription="Find all sequence alterations for a publication using an author name and/or a PubMed ID." sortOrder="SequenceAlteration.primaryIdentifier asc" constraintLogic="A and B"><constraint path="SequenceAlteration.publications.pubMedId" code="A" editable="true" op="=" value="17531218"/><constraint path="SequenceAlteration.publications.authorNames" code="B" editable="true" op="CONTAINS" value="Stainier"/></query></template>) You cannot overwrite a locally defined method (addPromoter) with a delegation at /usr/local/lib/perl/5.18.2/Class/MOP/Class.pm line 899
	Class::MOP::Class::try {...}  at /usr/local/share/perl/5.18.2/Try/Tiny.pm line 81
	eval {...} at /usr/local/share/perl/5.18.2/Try/Tiny.pm line 72
```

**Comment by julie-sullivan** [comment]
![promoter](https://cloud.githubusercontent.com/assets/1663057/26346538/711d4b14-3f9e-11e7-8657-5c9b878d8df9.png)

**Comment by julie-sullivan** [comment]
Promoter is there twice:

https://github.com/sierra-moxon/intermine/blob/dev/bio/sources/zebrafish/zfinGenotypes/zfinGenotypes_additions.xml#L150

Is that what's causing the error?

**Comment by julie-sullivan** [comment]
I am closing this ticket but please reopen if this doesn't solve your problem!!
