### ISSUE TITLE
Linking proteins (fasta) and gene features (gff)

### ISSUE THREAD

**Issue by terrymun** [intermine/intermine#1432]
Sorry again, to bother you folks with a rather mundane question. I have been trying awhile now to map/integrate protein identifiers against gene features, the former coming from a typical fasta file and the latter a gff3-compatible file.

_Lotus_ proteins are still not available on Uniprot yet, so I have decided to load protein sequences and their unique identifiers from a fasta file. **The issue is that I can't seem to link the protein sequences from the `*.fa` file with the gene features provided in the `*.gff` file**. While both the protein, mRNA, exon, and CDS are populated in their respective tables PostgreSQL database, they do not appear to be integrated on the gene page itself.

I suspect my issue might be two-fold: (1) that I am not using a valid protein source (Uniprot/Interpro) as stated in the documentation, and/or (2) that my custom gff parser is not doing the thing I expected it to.

I have attached some files in my issue, with has a very minimal example (one gene, two mRNAs and proteins, with one GO annotation). I have managed to build the mine and deploy it as a web app without any issue.

If my issue is too implementation specific, do advice me on where can I seek help. Thank you so much 👍 
## Source: Protein fasta file

It is formatted as seen below:

``` fasta
> Lj4g3v0281080.1
[sequence]
```

The file is parsed using the standard `fasta` class, and the `protein` table is propagated properly:

| secondaryidentifier | molecularweight | md5checksum | symbol | primaryidentifier | length | id | name | primaryaccession | organismid | sequenceid | class |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  |  | fead0a3ecea01863cc5d2c9e52ca2ebf |  | Lj4g3v0281080.1 | 638 | 1000005 |  |  | 1000000 | 1000003 | org.intermine.model.bio.Protein |
## Source: GFF3 file

The protein `Lj4g3v0281080.1` is encoded by the gene `Lj4g3v0281040`, which is described as follows in the GFF3 file:

``` gff
chr4    LotusBase   gene    3304707 3309364 .   .   .   ID=Lj4g3v0281080;Name=CUFF.46779;sequencetype=Protein coding
chr4    LotusBase   mRNA    3304707 3309364 .   +   .   ID=Lj4g3v0281080.mrna.1;Parent=Lj4g3v0281080;Name=Lj4g3v0281080.mrna.1;sequencetype=Protein coding;annotation=PREDICTED: pentatricopeptide repeat-containing protein At3g14730-like [Glycine max] gi|356546044|ref|XP_003541442.1|
chr4    LotusBase   exon    3304707 3304956 .   +   .   ID=Lj4g3v0281080.1.exon.1;Parent=Lj4g3v0281080.mrna.1;sequencetype=Protein coding
chr4    LotusBase   exon    3305538 3305652 .   +   .   ID=Lj4g3v0281080.1.exon.2;Parent=Lj4g3v0281080.mrna.1;sequencetype=Protein coding
chr4    LotusBase   exon    3305745 3308308 .   +   .   ID=Lj4g3v0281080.1.exon.3;Parent=Lj4g3v0281080.mrna.1;sequencetype=Protein coding
chr4    LotusBase   exon    3308875 3309003 .   +   .   ID=Lj4g3v0281080.1.exon.4;Parent=Lj4g3v0281080.mrna.1;sequencetype=Protein coding
chr4    LotusBase   exon    3309118 3309364 .   +   .   ID=Lj4g3v0281080.1.exon.5;Parent=Lj4g3v0281080.mrna.1;sequencetype=Protein coding
chr4    LotusBase   CDS 3305767 3307682 .   +   0   ID=Lj4g3v0281080.1.CDS.1;Parent=Lj4g3v0281080.mrna.1;sequencetype=Protein coding
```

As I wanted the features to be identified by their ID and not name, I have created a new gff parser in `intermine/bio/sources/` as instructed in the documentation, called `lotus-gff`. It has the same key mapping as the example `malaria-gff` file, since I also intend the `ID`, not the `name`, to be used as a primary identifier:

```
# In intermine/bio/sources/lotus-gff/resources/lotus-gff_keys.properties
Gene.key_primaryidentifier=primaryIdentifier
Chromosome.key_primaryidentifier=primaryIdentifier
Transcript.key_primaryidentifier=primaryIdentifier
Exon.key_primaryidentifier=primaryIdentifier
SOTerm.key_name=name
DataSource.key_name=name
DataSet.key_title=name
Organism.key_taxonid=taxonId
Synonym.key_synonym=subject, value
OntologyTerm.key_name_ontology=name,ontology
Ontology.key_title=name
```

After importing, I checked the `exon` and `gene` table to verify the entires are being properly populated:
### Gene table

| secondaryidentifier | symbol | briefdescription | primaryidentifier | length | id | name | scoretype | score | description | chromosomeid | chromosomelocationid | organismid | downstreamintergenicregionid | upstreamintergenicregionid | sequenceid | sequenceontologytermid | class |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | CUFF.46779 |  | Lj4g3v0281080 | 4658 | 2000005 |  |  |  |  | 2000003 | 2000004 | 1000000 |  |  |  | 2000006 | org.intermine.model.bio.Gene |
### mRNA table

| secondaryidentifier | symbol | primaryidentifier | length | id | name | scoretype | score | chromosomeid | chromosomelocationid | organismid | proteinid | sequenceid | sequenceontologytermid | geneid | class |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | Lj4g3v0281080.mrna.1 | Lj4g3v0281080.mrna.1 | 4658 | 2000009 |  |  |  | 2000003 | 2000008 | 1000000 |  |  | 2000010 |  | org.intermine.model.bio.MRNA |
### CDS table

| secondaryidentifier | symbol | primaryidentifier | length | id | name | scoretype | score | geneid | chromosomeid | chromosomelocationid | transcriptid | organismid | sequenceid | proteinid | sequenceontologytermid | class |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  |  | Lj4g3v0281080.1.CDS.1 | 1916 | 2000023 |  |  |  |  | 2000003 | 2000022 |  | 1000000 |  |  | 2000024 | org.intermine.model.bio.CDS |
### Exon table

| secondaryidentifier | symbol | primaryidentifier | length | id | name | scoretype | score | chromosomeid | geneid | chromosomelocationid | organismid | sequenceid | sequenceontologytermid | class |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  |  | Lj4g3v0281080.1.exon.1 | 250 | 2000012 |  |  |  | 2000003 |  | 2000011 | 1000000 |  | 2000013 | org.intermine.model.bio.Exon |
|  |  | Lj4g3v0281080.1.exon.2 | 115 | 2000015 |  |  |  | 2000003 |  | 2000014 | 1000000 |  | 2000013 | org.intermine.model.bio.Exon |
|  |  | Lj4g3v0281080.1.exon.3 | 2564 | 2000017 |  |  |  | 2000003 |  | 2000016 | 1000000 |  | 2000013 | org.intermine.model.bio.Exon |
|  |  | Lj4g3v0281080.1.exon.4 | 129 | 2000019 |  |  |  | 2000003 |  | 2000018 | 1000000 |  | 2000013 | org.intermine.model.bio.Exon |
|  |  | Lj4g3v0281080.1.exon.5 | 247 | 2000021 |  |  |  | 2000003 |  | 2000020 | 1000000 |  | 2000013 | org.intermine.model.bio.Exon |
## Source: Gene ontology

The gene ontology for the gene `Lj4g3v0281080` is specified as follow:

```
LotusBase_Ljaponicus_v3.0   Lj4g3v0281080   Lj4g3v0281080       GO:0005515  GO_REF:nd   ND      F   PREDICTED: pentatricopeptide repeat-containing protein At3g14730-like [Glycine max] gi|356546044|ref|XP_003541442.1|    Lj4g3v0281080   gene_product    taxon:34305 20160919    LotusBase_Ljaponicus_v3.0
```

I can confirm that both the `goannotation` and `genegoannotation` tables are also populated:

| qualifier | annotationextension | id | ontologytermid | subjectid | class |
| --- | --- | --- | --- | --- | --- |
|  |  | 4000003 | 3000001 | 2000005 | org.intermine.model.bio.GOAnnotation |

| gene | goannotation |
| --- | --- |
| 2000005 | 4000003 |
## Outcome:

While both the protein and the gene are searchable in the newly deployed mine, they appear not to be linked to each other. An example screenshot for the gene page for `Lj4g3v0281080`:

![Example gene page for Lj4g3v0281080](https://cloud.githubusercontent.com/assets/5593067/18748894/b2c06f12-80d4-11e6-976e-f575bb7baf5f.png)

---

Thanks again for your help :)

**Comment by julie-sullivan** [comment]
@terrymun So sorry we missed this. Is this still an issue? Also, you might try the dev list for a speedier reply!

### Protein to Gene ###

Just glancing over your data files, I don't see where the protein and gene relationship is being reported (other than they have the same name -- which isn't enough). You are right in that most InterMines use UniProt to populate the gene-protein relationship, so you'll have to do this yourself. 

You can add these data (protein accession) to your GFF file and write a GFF parser -- I can help with this. Or you could write a post-process that creates this relationship after the build is done based on identifier I guess?

Let me know and I can help!

### Features to Gene ###

Your GFF file looks legal so it's likely the relationship is being created and this is not showing up on your report page correctly. Due to something wrong with InterMine. Can you query and confirm this? (using the UI or psql)

Looking at the working displayer here in [FlyMine](http://www.flymine.org/flymine/portal.do?class=Gene&externalids=FBgn0004053), I see that it's expecting sequence. Maybe that's the problem? Let me check the code, and fix if that's the problem.

**Comment by julie-sullivan** [comment]
I am closing this but please reopen if you have more questions!
