### ISSUE TITLE
Determining the size of the network in the cytoscape viewer

### ISSUE THREAD

**Issue by chenyian-nibio** [intermine/intermine#1445]
I would like to report a bug in the cytoscape network displayer. For my understanding, so far this displayer could be use for both Gene and the Protein report pages and the contents will always show the interactions associated with the Gene class. In order not to crash the browser, there is filter in the displayer said no more than 500 interactions. However, when the displayer is set to the Protein class, the check become the number of the interactions associated to the protein which is likely a mistake. 
As an example, in HumanMine, TP53 contains more than 1000 interactions and will not be displayed using cytoscape.js, but the corresponding protein, P53_HUMAN will still try to display the interactions in the displayer.

By the way, I have made some modifications to the CytoscapeNetworkDisplayer.java class and the cytoscapeNetworkDisplayer.jsp file to resolve this issue in TargetMine.

**Comment by julie-sullivan** [comment]
Thanks @chenyian-nibio! Would it be possible for you to do a pull request so we can share your fix with everyone?

**Comment by julie-sullivan** [comment]
Fixed by 5805ece542236f3585f1c297264999d11ac9b0e3 (I think?)
