### ISSUE TITLE
List widgets with too-long titles disappear offscreen

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1446]
When a list widget's column headers are too wide, they push the content out of the viewable area, like in the rightmost column of the screenshot below - the column should say "interactions" and the numbers in the column should be fully visible. 

![links on the right of the  widget are almost entirely offscreen](https://cloud.githubusercontent.com/assets/9271438/19649017/1eda1636-99fc-11e6-9746-dcc1c751187b.png)

Probably the easiest way to fix this is probably by breaking header values if they're over `n` characters long. 

Start fixing the bug by looking here: https://github.com/intermine/intermine-apps-c/tree/master/list-widgets/src

**Comment by danielabutano** [comment]
In the new interface we have an orizontal bar, when it happens
