### ISSUE TITLE
Upgrade jQuery from 1.11 to 3

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#1448]
Intermine loads jQuery 1.110 which is now three years old (98 in JS years). Devs seeking to use modern jQuery functionality have to load a newer version and then reapply old plugins, or even worse juggle multiple versions at the same time. Let's investigate the impact of upgrading to jQuery 3* by default.

**Comment by julie-sullivan** [comment]
This is a lot of work to update, we are going to retire this UI soon.
