### ISSUE TITLE
Don't add ORDER BY clause to count(*) queries

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1455]
Don't add ORDER BY clause to count(*) queries, it's pointless and it slows down the query quite a bit.

tell @sneuhaus and @JoelRichardson

**Comment by julie-sullivan** [comment]
```
<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.name Gene.sequenceOntologyTerm.name Gene.organism.name Gene.crossReferences.identifier Gene.crossReferences.source.name Gene.crossReferences.source.url Gene.synonyms.value" sortOrder="Gene.primaryIdentifier ASC" >
</query>

SELECT COUNT(*) FROM (SELECT a5_.id AS a5_id, a6_.id AS a6_id, a1_.id AS a1_id, a2_.id AS a2_id, a3_.id AS a3_id, a4_.id AS a4_id, a5_.identifier AS orderbyfield0, a6_.name AS orderbyfield1, a6_.url AS orderbyfield2, a1_.primaryIdentifier AS orderbyfield3, a1_.symbol AS orderbyfield4, a1_.name AS orderbyfield5, a2_.name
 AS orderbyfield6, a3_.name AS orderbyfield7, a4_.intermine_value AS orderbyfield8 FROM Gene AS a1_, SOTerm AS a2_, Organism AS a3_, Synonym AS a4_,
 CrossReference AS a5_, DataSource AS a6_ WHERE a1_.sequenceOntologyTermId = a2_.id AND a1_.organismId = a3_.id AND a1_.id = a4_.subjectId 
 AND a1_.id = a5_.subjectId AND a5_.sourceId = a6_.id ORDER BY a5_.identifier, a6_.name, a6_.url, a1_.primaryIdentifier, a1_.symbol, a1_.name, a2_.name, a3_.name, a4_.intermine_value, a5_.id, a6_.id, a1_.id, a2_.id, a3_.id, a4_.id) as fake_table
 

 
                                                                                         QUERY PLAN

------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------
 Aggregate  (cost=2537469.52..2537469.53 rows=1 width=0)
   ->  Sort  (cost=2390831.17..2415270.90 rows=9775890 width=254)
         Sort Key: a5_.identifier, a6_.name, a6_.url, a1_.primaryidentifier, a1_.symbol, a1_.name, a2_.name, a3_.name, a4_.intermine_value, a5_.id, a6
_.id, a1_.id, a2_.id, a3_.id, a4_.id
         ->  Hash Join  (cost=134228.95..420468.90 rows=9775890 width=254)
               Hash Cond: (a5_.subjectid = a1_.id)
               ->  Hash Join  (cost=8.64..106128.10 rows=2994967 width=104)
                     Hash Cond: (a5_.sourceid = a6_.id)
                     ->  Seq Scan on crossreference a5_  (cost=0.00..64938.67 rows=2994967 width=23)
                     ->  Hash  (cost=6.06..6.06 rows=206 width=85)
                           ->  Seq Scan on datasource a6_  (cost=0.00..6.06 rows=206 width=85)
               ->  Hash  (cost=117903.09..117903.09 rows=1305378 width=158)
                     ->  Hash Join  (cost=27874.57..117903.09 rows=1305378 width=158)
                           Hash Cond: (a4_.subjectid = a1_.id)
                           ->  Seq Scan on synonym a4_  (cost=0.00..53135.87 rows=2383887 width=36)
                           ->  Hash  (cost=22875.58..22875.58 rows=399919 width=122)
                                 ->  Hash Join  (cost=96.72..22875.58 rows=399919 width=122)
                                       Hash Cond: (a1_.organismid = a3_.id)
                                       ->  Hash Join  (cost=95.56..17375.54 rows=399919 width=90)
                                             Hash Cond: (a1_.sequenceontologytermid = a2_.id)
                                             ->  Seq Scan on gene a1_  (cost=0.00..11281.19 rows=399919 width=69)
                                             ->  Hash  (cost=71.36..71.36 rows=1936 width=25)
                                                   ->  Seq Scan on soterm a2_  (cost=0.00..71.36 rows=1936 width=25)
                                       ->  Hash  (cost=1.07..1.07 rows=7 width=36)
                                             ->  Seq Scan on organism a3_  (cost=0.00..1.07 rows=7 width=36)
```
From @sneuhaus

**Comment by julie-sullivan** [comment]
@sneuhaus That's terrible! It's not using any of the indexes. But in reality, it should only use the indexes and not use the table at all. Every field in there should have an index.

@danielabutano Can you verify if that is happening for our queries too? Is it skipping the indexes because it's a subquery?

**Comment by sergiocontrino** [comment]
the XML query works fine on humanmine (retrieving 1.4 M rec) and on thelemine (retrieving 10k).
i get different generated queries though. they are explained as not using indexes on thalemine, and on using index scan on humanmine (except for tables datasource and organism).

postgres states that
"Sequential-scan-and-sort frequently beats an index scan for sorting many rows, because of the nonsequential disk access required by the index scan"
https://www.postgresql.org/docs/current/static/using-explain.html

the SQL query on humanmine gives a slightly different query plan (see below), where the order is different (datasource, organism, gene, crossreference, synonym) and index on soterm.
the query execute in 11s.

                                                                                        QUERY PLAN                                                                                         
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=375676.72..375676.73 rows=1 width=0)
   ->  Sort  (cost=342263.37..347832.26 rows=2227557 width=189)
         Sort Key: a5_.identifier, a6_.name, a6_.url, a1_.primaryidentifier, a1_.symbol, a1_.name, a2_.name, a3_.name, a4_.intermine_value, a5_.id, a6_.id, a1_.id, a2_.id, a3_.id, a4_.id
         ->  Hash Join  (cost=49313.90..107400.55 rows=2227557 width=189)
               Hash Cond: (a4_.subjectid = a1_.id)
               ->  Seq Scan on synonym a4_  (cost=0.00..18009.02 rows=890102 width=20)
               ->  Hash  (cost=43548.19..43548.19 rows=461257 width=177)
                     ->  Hash Join  (cost=12403.38..43548.19 rows=461257 width=177)
                           Hash Cond: (a5_.sourceid = a6_.id)
                           ->  Hash Join  (cost=12401.64..37204.16 rows=461257 width=137)
                                 Hash Cond: (a5_.subjectid = a1_.id)
                                 ->  Seq Scan on crossreference a5_  (cost=0.00..15000.83 rows=691883 width=23)
                                 ->  Hash  (cost=10865.70..10865.70 rows=122875 width=114)
                                       ->  Hash Join  (cost=110.54..10865.70 rows=122875 width=114)
                                             Hash Cond: (a1_.sequenceontologytermid = a2_.id)
                                             ->  Hash Join  (cost=1.04..8913.09 rows=122875 width=93)
                                                   Hash Cond: (a1_.organismid = a3_.id)
                                                   ->  Seq Scan on gene a1_  (cost=0.00..6992.12 rows=184312 width=61)
                                                   ->  Hash  (cost=1.02..1.02 rows=2 width=36)
                                                         ->  Seq Scan on organism a3_  (cost=0.00..1.02 rows=2 width=36)
                                             ->  Hash  (cost=85.30..85.30 rows=1935 width=25)
                                                   ->  Index Only Scan using soterm__ontologyterm__key_name_ontology on soterm a2_  (cost=0.28..85.30 rows=1935 width=25)
                           ->  Hash  (cost=1.33..1.33 rows=33 width=44)
                                 ->  Seq Scan on datasource a6_  (cost=0.00..1.33 rows=33 width=44)
(24 rows)

**Comment by sergiocontrino** [comment]
removing the order by clause (original query) on humanmine reduce by a factor 10 the duration of the query, the query planner doing seq scan for all tables.
so it would be convenient to do counts without ordering. we can assume for now that probably the query planner is working fine.

**Comment by julie-sullivan** [comment]
@sergiocontrino @danielabutano but we cannot remove the order by clause without unexpected behaviour. Is that right?

Should I close this ticket?

**Comment by sneuhaus** [comment]
I think because the query is 'select count(*) from ...'  the order by should have no impact on the results,

**Comment by julie-sullivan** [comment]
The code expects an order by always because that's how it does paging with postgres.

I think @danielabutano researched and found out that we couldn't remove the order by on one query and not the other because of how queries are processed. I hope I am wrong though! Let's confirm with @danielabutano first.

**Comment by JoelRichardson** [comment]
Doesn't that suggest that the code should change? After all, this is a significant performance hit that is entirely unnecessary, given what the query is doing.

**Comment by danielabutano** [comment]
From SqlGenerator clas line 490
`if ((kind == QUERY_NORMAL) || (kind == QUERY_FOR_PRECOMP) || (kind == QUERY_FOR_GOFASTER)) {
            boolean haveOrderBy = true;
            if (q.getGroupBy().isEmpty()) {
                for (QuerySelectable selectable : q.getSelect()) {
                    if (selectable instanceof QueryFunction) {
                        haveOrderBy = false;
                    }
                }
            }
            if (haveOrderBy) {
                orderBy = buildOrderBy(state, q, schema, kind);
            }
        }`

**Comment by danielabutano** [comment]
@sneuhaus or @JoelRichardson or @julie-sullivan could you please help me to reproduce the execution of the query above-mentioned?
```
SELECT COUNT(*) FROM (SELECT a5_.id AS a5_id, a6_.id AS a6_id, a1_.id AS a1_id, a2_.id AS a2_id, a3_.id AS a3_id, a4_.id AS a4_id, a5_.identifier AS orderbyfield0, a6_.name AS orderbyfield1, a6_.url AS orderbyfield2, a1_.primaryIdentifier AS orderbyfield3, a1_.symbol AS orderbyfield4, a1_.name AS orderbyfield5, a2_.name
 AS orderbyfield6, a3_.name AS orderbyfield7, a4_.intermine_value AS orderbyfield8 FROM Gene AS a1_, SOTerm AS a2_, Organism AS a3_, Synonym AS a4_,
 CrossReference AS a5_, DataSource AS a6_ WHERE a1_.sequenceOntologyTermId = a2_.id AND a1_.organismId = a3_.id AND a1_.id = a4_.subjectId 
 AND a1_.id = a5_.subjectId AND a5_.sourceId = a6_.id ORDER BY a5_.identifier, a6_.name, a6_.url, a1_.primaryIdentifier, a1_.symbol, a1_.name, a2_.name, a3_.name, a4_.intermine_value, a5_.id, a6_.id, a1_.id, a2_.id, a3_.id, a4_.id) as fake_table
```
In beta-flymine,  I have run the query:
```
<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.name Gene.sequenceOntologyTerm.name Gene.organism.name Gene.crossReferences.identifier Gene.crossReferences.source.name Gene.crossReferences.source.url Gene.synonyms.value" sortOrder="Gene.primaryIdentifier ASC" >
</query>
```
then I've saved the list with 53536 gene and then displayed the List Analysis page.
In the log files, there are no queries similar to:  
`
SELECT COUNT(*) AS ... FROM (SELECT .....ORDER BY..... )
`
I have also slightly updated the code to log  the orderby variable but with subqueries is always empty.
Being able to reproduce the query mentioned, it would help in me in debugging!!
Thanks!

**Comment by julie-sullivan** [comment]
@danielabutano I get the above SQL but it always has another field in the SELECT:

```
generated sql: SELECT DISTINCT a1_.a3_ AS a2_, COUNT(*) AS a3_ FROM (SELECT a1_.briefDescription AS a1_briefDescription... 
GROUP BY a1_.a3_ 
ORDER BY a3_ DESC, a1_.a3_ LIMIT 5000
```

**Comment by sneuhaus** [comment]
@danielabutano I just tried this query
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.name Gene.sequenceOntologyTerm.name Gene.organism.name Gene.crossReferences.identifier Gene.crossReferences.source.name Gene.crossReferences.source.url Gene.synonyms.value" longDescription="" sortOrder="Gene.primaryIdentifier asc">
</query>

And can see this in postgres pg_stat_activity
 
SELECT COUNT(*) FROM (SELECT a1_.id AS a1_id, a2_.id AS a2_id, a3_.id AS a3_id, a4_.id AS a4_id, a5_.id AS a5_id, a6_.id AS a
6_id, a1_.primaryIdentifier AS orderbyfield0, a1_.symbol AS orderbyfield1, a1_.name AS orderbyfield2, a2_.name AS orderbyfield3, a3_.name AS orderbyfield4, a4_.identifier AS orderbyfield5, a5_.name AS
orderbyfield6, a5_.url AS orderbyfield7, a6_.intermine_value AS orderbyfield8 FROM Gene AS a1_, SOTerm AS a2_, Organism AS a3_, CrossReference AS a4_, DataSource AS a5_, Synonym AS a6_ WHERE a1_.sequen
ceOntologyTermId = a2_.id AND a1_.organismId = a3_.id AND a1_.id = a4_.subjectId AND a4_.sourceId = a5_.id AND a1_.id = a6_.subjectId ORDER BY a1_.primaryIdentifier, a1_.symbol, a1_.name, a2_.name, a3_
.name, a4_.identifier, a5_.name, a5_.url, a6_.intermine_value, a1_.id, a2_.id, a3_.id, a4_.id, a5_.id, a6_.id) as fake_table

**Comment by danielabutano** [comment]
thanks @sneuhaus!

**Comment by danielabutano** [comment]
Thanks @sneuhaus for you help. I think I have fixed the problem. Please feel free to test it (if you have time)!
The changes are on my local repo https://github.com/danielabutano/intermine/tree/orderby-pathquery

**Comment by sneuhaus** [comment]
@danielabutano Tested with the query above. On our current system it times out. On your branch it returned over 10 million results in under 20 seconds. Fantastic.

**Comment by danielabutano** [comment]
Thanks @sneuhaus for testing!
