### ISSUE TITLE
disable text field in query builder constraint dialogue

### ISSUE THREAD

**Issue by motenko** [intermine/intermine#1467]
I've included two screenshots: 
(1) the problem [note: I click on the text box to show the long text string]
![screenshot1-theproblem](https://cloud.githubusercontent.com/assets/1467164/20537032/842042c6-b0b9-11e6-9bb3-b94a0c260e34.png)

(2) the solution for a different field (but I don't know what the solution is - just that we have implemented it in the past).
![screenshot2-hopefulsolution](https://cloud.githubusercontent.com/assets/1467164/20537049/97b87808-b0b9-11e6-88da-266534558c17.png)

email thread:

[Julie writes]
We disabled text in the constraint dialogue? No, I don't know how that is done either!
Can you open a ticket and maybe include a screenshot? Maybe if I see it, it will come to me! :) Thanks!

[Howie writes]
I’ve added a note field (specificity) to mousemine and when I attempt to add a constraint in the query builder the length of the notes is wider than the query builder window, causing the information to be hidden.  I know we have disabled displaying the actual text in the constraint
dialog, but I don’t know how that is achieved.  Can you advise?

**Comment by julie-sullivan** [comment]
Thanks @motenko!

In the first example you show, is that a dropdown field? I can't tell. The dropdowns are generated in the objectstore summary part of the build. You can set your mine to ignore these fields:

http://intermine.readthedocs.io/en/latest/webapp/template-queries/

Then it won't have that dropdown on the next build. Try that and let me know?

**Comment by motenko** [comment]
Hi Julie,

That worked, thanks.  BTW - yes, that was a dropdown field.

Please feel free to this ticket.

Gratefully,
Howie
