### ISSUE TITLE
API exposing assumptions in lists

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1469]
```
1. GET `/service/session` for an anonymous API token
2. GET `/service/lists` to view all lists
3. Click a list and view it in im-tables (so we build a query, Select summary fields from root where root IN listname)
4. POST `/service/lists` to save the results, and this request includes the API token in the header
```

Saving lists via the API is not updating them correctly. Why?

**Comment by julie-sullivan** [comment]
I assume the API is changing the lists in memory incorrectly. e.g. pointing to the wrong part of the list map. There is a repository of "web searchables" -- likely not being updated correctly. 

Redeploying the webapp fixes the problem. Whatever error is happening is not being written to disk.

**Comment by julie-sullivan** [comment]
@joshkh can you send me the exact request you sent as part of above? We can't replicate this issue.

**Comment by julie-sullivan** [comment]
We can't replicate using the iodocs, using the UI or by calling the web services directly. 

This is something that only blue genes is doing. What is that?

**Comment by danielabutano** [comment]
**Final comment about how to reproduce the error**
Run a query, for instance Company's summary and create a list from the result given the name _test_ Set it as public.
Using the browser, call the web service http://localhost:8080/intermine-test/service/query/results?query=<query> where the query is URL encoded and contains in the view all the fields in the summary and as constraint the bag constraint to the list _test_ just created.
<query model="testmodel" view="Company.name Company.vatNumber Company.address.address"><constraint path="Company" op="IN" value="d11"/>
</query>
