### ISSUE TITLE
ClinVar changed the data layout

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1470]
@rachellyne It looks like ClinVar moved the columns around. Can you check my work? There may be new columns we can add, and I can't find the xrefs columns anymore. I'm running a new build now.

<table>
<th>
<td>previous column</td>
<td>current column</td>
</th>
<tr>
<td>clinicalSignificance</td>
<td>5</td>
<td>6</td>
</tr>
<tr>
<td>dbSNPXref</td>
<td>6</td>
<td>?</td>
</tr>
<tr>
<td>ncbiXref</td>
<td>7</td>
<td>?</td>
</tr>
<tr>
<td>clinVarXref</td>
<td>8</td>
<td>?</td>
</tr>
<tr>
<td>referenceAllele</td>
<td>25</td>
<td>21</td>
</tr>
<tr>
<td>alternateAllele</td>
<td>26</td>
<td>22</td>
</tr>
</table>

**Comment by julie-sullivan** [comment]
Here are the new column headings:

```
0   #AlleleID
1   Type
2   Name
3   GeneID
4   GeneSymbol
5   HGNC_ID
6   ClinicalSignificance
7   ClinSigSimple
8   LastEvaluated
9   RS# (dbSNP)
10  nsv/esv (dbVar)
11  RCVaccession
12  PhenotypeIDS
13  PhenotypeList
14  Origin
15  OriginSimple
16  Assembly
17  ChromosomeAccession
18  Chromosome
19  Start
20  Stop
21  ReferenceAllele
22  AlternateAllele
23  Cytogenetic
24  ReviewStatus
25  NumberSubmitters
26  Guidelines
27  TestedInGTR
28  OtherIDs
29  SubmitterCategories
```

**Comment by julie-sullivan** [comment]
I missed one:

<table>
<th>
<td>previous column</td>
<td>current column</td>
</th>
<tr>
<td>disease</td>
<td>10</td>
<td>12</td>
</tr>
</table>

Is that right @rachellyne?

**Comment by rachellyne** [comment]
I don't see a disease column.

**Comment by julie-sullivan** [comment]
@rachellyne Take a look at the data file? 

* genes have alleles
* alleles have diseases
* PPARG has alleles
* PPARG alleles have no diseases.

I looked in the data file and this looks correct. Either the disease column has no OMIM identifier, or there is something called the `OMIM Allelic Variant:601487.0001`

Take a look and let me know what to do?

**Comment by julie-sullivan** [comment]
@rachellyne This was the problem (again). The file has these values (look at OMIM):

```
19112   single nucleotide variant       NM_015474.3(SAMHD1):c.760A>G (p.Met254Val)      25939   SAMHD1  HGNC:15925      Pathogenic      1       Mar 13, 2014    121434521       -       RCV000004288    MedGen:C2749659,OMIM:^@ Aicardi Goutieres syndrome 5    germline        germline        GRCh37  NC_000020.10    20      35547859        35547859        T       C       20q11.2 no assertion criteria provided  3       -       N       OMIM Allelic Variant:606754.0007,UniProtKB (protein):Q9Y3Z3#VAR_058487  1
19112   single nucleotide variant       NM_015474.3(SAMHD1):c.760A>G (p.Met254Val)      25939   SAMHD1  HGNC:15925      Pathogenic      1       Mar 13, 2014    121434521       -       RCV000004288    MedGen:C2749659,OMIM:^@ Aicardi Goutieres syndrome 5    germline        germline        GRCh38  NC_000020.11    20      36919456        36919456        T       C       20q11.23        no assertion criteria provided  3       -       N       OMIM Allelic Variant:606754.0007,UniProtKB (protein):Q9Y3Z3#VAR_058487  1
```

```^@``` has a special meaning for programming languages:

https://en.wikipedia.org/wiki/Control_character
```
0 (null, NUL, \0, ^@), originally intended to be an ignored character, but now used by many programming languages to mark the end of a string.
```
This is why it silently failed. The code interpreted as a end of string, then kept going. I've emailed the NIH but in the meantime we should add this to the download script:

```
sed -i 's/OMIM:\x00/DELETED/g' variant_summary.txt
```

**Comment by julie-sullivan** [comment]
Working correctly now in new build.
