### ISSUE TITLE
BUG: QueryExecutor.summariseQuery(PathQuery pathQuery, java.lang.String summaryPath) adds first two rows together

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1485]
I'm finding that QueryExecutor.summariseQuery(pathQuery, summaryPath) is returning the wrong results. Namely, I've got 11 distinct values, but summariseQuery returns 10 rows, and the counts are added together in the first row. Here's the example:
```
cowpeamine=> select number,count(*) from linkagegroupposition,linkagegroup where linkagegroupposition.linkagegroupid=linkagegroup.id group by number order by number;
 number | count 
--------+-------
      1 |  3317
      2 |  3877
      3 |  6183
      4 |  3050
      5 |  2790
      6 |  3125
      7 |  2597
      8 |  3350
      9 |  2993
     10 |  3063
     11 |  3027
(11 rows)
```
So, 11 rows, and the first two have counts 3317 and 3877. Now summariseQuery:
```
PathQuery countQuery = new PathQuery(im.getModel());
countQuery.addViews(
    "LinkageGroupPosition.id",
    "LinkageGroupPosition.linkageGroup.number"
);
try {
    Results results = executor.summariseQuery(countQuery, "LinkageGroupPosition.linkageGroup.number");
    for (Object o : results) {
        ResultsRow row = (ResultsRow) o;
        System.out.println(row.toString());
    }
} catch (Exception ex) {
    System.err.println(ex.toString());
}
```
which puts out the following output:
```
[1, 11, 5.6288932890934389, 3.1806462693633066, 10, 1, 7194]
[1, 11, 5.6288932890934389, 3.1806462693633066, 10, 2, 6183]
[1, 11, 5.6288932890934389, 3.1806462693633066, 10, 3, 3050]
[1, 11, 5.6288932890934389, 3.1806462693633066, 10, 4, 2790]
[1, 11, 5.6288932890934389, 3.1806462693633066, 10, 5, 3125]
[1, 11, 5.6288932890934389, 3.1806462693633066, 10, 6, 2597]
[1, 11, 5.6288932890934389, 3.1806462693633066, 10, 7, 3350]
[1, 11, 5.6288932890934389, 3.1806462693633066, 10, 8, 2993]
[1, 11, 5.6288932890934389, 3.1806462693633066, 10, 9, 3063]
[1, 11, 5.6288932890934389, 3.1806462693633066, 10, 10, 3027]
```
As you can see, there are only 10 results, and the total in the first result is 7194=3317+3877. The first two actual results are being added together by summariseQuery!

**Comment by julie-sullivan** [comment]
@justinccdev can you have a look at this this week? Higher priority

**Comment by julie-sullivan** [comment]
@sammyjava Is this still a problem? Can you give me another example I can test locally, e.g. replicate the problem in FlyMine?

**Comment by sammyjava** [comment]
Well, I'd like to, but I'm stumped on how to create a PathQueryExecutor in a standalone Java routine. In the webapp I'm given an InterMineAPI object to call getPathQueryExecutor(), but I can't find a way to do it in in a standalone testing app from, presumably, a ServiceFactory. Got a sample that does it? I don't want you to have to build a webapp to see this happen.

**Comment by julie-sullivan** [comment]
What problem are we trying to solve? 

As far as I can tell, the summaries are working correctly in the webapp. I can't replicate this issue there. So it's only happening (AFAIK) in your code. Maybe something to do with integers being treated as strings? e.g. some concatenation (a + b) going horribly wrong? That doesn't make sense because it only happens in the first row.

Looking at the code I don't see anything obvious. But the code is rather dense! There is a GROUP BY:

https://github.com/intermine/intermine/blob/dev/intermine/api/main/src/org/intermine/api/query/MainHelper.java#L1370

But that shouldn't happen because it should pass the first test:

```
        if (!occurancesOnly && isNumeric(summaryType)
                && (!SummaryConfig.summariseAsOccurrences(className + "." + fieldName))) {
```

`occurancesOnly` I assume is to differentiate when we want to see the distributation of integers, for example, as opposed to the frequency counts -- which is what we do for strings. What is that variable set to? What is the exact query that is running?

Unfortunately since I can't replicate locally, I might need your help to debug!

**Comment by sammyjava** [comment]
I think you can see from the code I posted in the original issue that I'm not doing anything weird - I'm just using the ResultsRow.toString() method and it's clearly adding the counts for the first two rows together.

But I'd like to test the issue in a standalone Java app using PathQueryExecutor (which AFAIKT is the only class that provides summariseQuery()). I was using it in a displayer or list analysis so it was given a ready-to-bake InterMineAPI via  ```SessionMethods.getInterMineAPI(session)``` or passed in a la ```GeneHeatmapDisplayer(ReportDisplayerConfig config, InterMineAPI im)``` - but I can't grok how to instantiate an InterMineAPI and therefore a PathQueryExecutor in a standalone Java app from a ServiceFactory, created with ```new ServiceFactory(intermineServiceUrl)```. It'd be nice to test the issue without having to build a webapp. I haven't been able to find a path from ServiceFactory to PathQueryExecutor in the API docs.

**Comment by julie-sullivan** [comment]
Testing in the webapp would be my preference because it would lessen the probability whatever errors we see are an artifact of how we implemented it.

**Comment by julie-sullivan** [comment]
So you are trying to use this method to populate your heat map displayer?

**Comment by julie-sullivan** [comment]
When you call the web service for the summaries of those fields, are the data correct there?

http://iodocs.apps.intermine.org/flymine/docs#/ws-possible-values/GET/path/values

**Comment by julie-sullivan** [comment]
Whoops, sorry, you are running a query so you want the query/results end point with the `summaryPath` parameter set like so:

```
http://www.flymine.org/query/service/query/results?summaryPath=Gene.symbol&query=%3Cquery%20model%3D%22genomic%22%20view%3D%22Gene.secondaryIdentifier%20Gene.symbol%20Gene.primaryIdentifier%20Gene.organism.name%22%20%3E%0A%20%20%3Cconstraint%20path%3D%22Gene%22%20op%3D%22IN%22%20value%3D%22esyN%20demo%20list%22%20code%3D%22A%22%20%2F%3E%0A%3C%2Fquery%3E&size=10&format=json
```

http://iodocs.apps.intermine.org/flymine/docs#/ws-query-results/POST/query/results

**Comment by sammyjava** [comment]
Well, things have changed - I don't have the number field in LinkageGroup any more, so I can't even reproduce the query that initiated the issue - that was across all linkage groups, collecting data by number (chromosome, usually), so totaling across all linkage groups for a given chromosome. If I run a query/results?summaryPath on it grouping by the name of the linkage groups, it works fine. So let's close this, it's pretty obscure if it still exists.
