### ISSUE TITLE
FASTA export other IDs option 

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#1490]
From List Analysis or Results table, exporting FASTA always exports PrimaryID which may not be very useful for the users. 

Wondering if this is configurable so we can change to use secondaryID or better yet if such an option can be provided on the dialog box where FASTA output options are displayed (currently choice to extend on both sides is available)
Thanks,
-Kalpana

**Comment by julie-sullivan** [comment]
Here's where the magic happens:

https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java#L306

We have the class keys. We'd have to update this to accept the selection from the UI.

@kkarra What's the priority on this?

**Comment by kkarra** [comment]
oops, I didn't get email alert on this like I normally do.. I just happened to see it by chance..
priority is up to you. If I could change it in code thats fine too for now.

**Comment by julie-sullivan** [comment]
You can change this in the "columns" section of the export. 

![fasta-export](https://cloud.githubusercontent.com/assets/1663057/24805474/d285f05e-1ba9-11e7-9af1-895dc6b3d6bd.png)

I think that's what you mean? If not, reopen ticket!

Also, see #1515
