### ISSUE TITLE
LOOKUP and List upload use BagQueryRunner. Need different "match" behaviour

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1494]
@kkarra brought up the point that they have `matchOnFirst` set to be FALSE.

See the bottom of this page for details:

http://intermine.readthedocs.io/en/latest/webapp/lists/list-upload/

This means that, for list upload and LOOKUPs, all queries are run (genes, sequence features, synonyms and xrefs). This is useful for list upload, we need to find all the relevant entries and let the user decide which to add to their list.

However, for LOOKUPs it's a bit different. The "less good" matches are still added to the query and appear in the results. It's not obvious what they are matched to as the LOOKUP queries don't have a screen like the list upload does.

Solutions?

One option is to have the LOOKUP queries ignore `matchOnFirst` and only return the first match. Then it will be clear where the record comes from. Rather then multiple synonym matches etc.

**Comment by julie-sullivan** [comment]
Here is an example problem:

Upload YJL018W and YCL003W. You get matches and duplicates.

The "match all" behaviour should only happen in the LOOKUP queries, NOT the list upload.

**Comment by julie-sullivan** [comment]
@kkarra I guess I want to know if this is the expected behaviour. Is this a feature or a bug? lol

**Comment by kkarra** [comment]
I would say 'bug' since unexpected results appear in results table without a disambiguation or warning page like in List upload. If somehow LOOKUP to be configured to behave differently in Templates vs List upload, that would be ideal...I think.

**Comment by julie-sullivan** [comment]
(from pull request #1575)

@kkarra going to close this temporarily whilst I release 1.8. If you get a chance to test, I will push to the master branch!
