### ISSUE TITLE
Docs: links in search results drop .html extension, only on index pages.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1497]
From Joe:

```
Wanted to pass on that I'm getting a lot of 'page not found' 
errors from  intermine.readthedocs.io. For example: I just 
searched for 'portal' and first search result  of 'Linking to 
your mine' is dead.
```

I can reproduce this error. Search for "portal". 

![rtfd](https://cloud.githubusercontent.com/assets/1663057/22066544/47a47f12-dd85-11e6-9e03-854a40243f5d.png)

The first search result goes to:

http://intermine.readthedocs.io/en/latest/webapp/linking-in/index?highlight=portal

instead of (which is the working link):

http://intermine.readthedocs.io/en/latest/webapp/linking-in/index.html?highlight=portal

It's missing the `html` extension for some reason.

However, if I build the docs locally, the links are correct.

**Comment by julie-sullivan** [comment]
https://github.com/rtfd/readthedocs.org/issues/2596

**Comment by julie-sullivan** [comment]
@yochannah The readthedocs people say this is our JS or theme clashing with elasticsearch. Do we want to remove the theme and have generic green docs? Or maybe just leave it because only a couple links are bad.

We could try to fix but I looked at the [theme](https://github.com/intermine/im-docs/tree/master/docs/_theme/intermine) and have no idea where to start. What could cause `.html` to be chopped off?

**Comment by julie-sullivan** [comment]
Decision: remove the theme. We need the links working.

**Comment by yochannah** [comment]
Well, I'd like to get the docs theme matching the intermine.org theme anyway (and it's probably not all that much work to do). Maybe let's just start from scratch from whatever their base theme is and re-theme that interminely, at some point when back from BOSC.

**Comment by julie-sullivan** [comment]
this is working now.
