### ISSUE TITLE
/version method returns things for random child urls

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1499]
I was sounding out various intermine URLS, and I discovered that children of the `/service/version` endpoint seem to always return the `/service/version` response even when they perhaps shouldn't. If you try to access `/service/version/intermine` on a pre 1.6.6 mine you get back the results for `/service/version`. 

The bug still exists in mines after 1.6.6, insofar as you'll still get a response to `/service/version/somerandomthinghere`, etc. that looks like this
![image](https://cloud.githubusercontent.com/assets/9271438/22116101/5727fe0e-de67-11e6-8e56-2ffc42d38a73.png)

Click'n'see:
http://www.humanmine.org/humanmine/service/version/julie

**Comment by julie-sullivan** [comment]
this is a bug not a feature.

`/service/version/intermine` doesn't exist on older mines, so it defaults to the root action `/service/version`

This might be misleading! We'll examine this behaviour more when we refactor the web services.
