### ISSUE TITLE
InterPro: new DB error

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1501]
```


        starting command: ant -v -Dsource=protein2ipr

        BUILD FAILED
        /var/lib/jenkins/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
        /var/lib/jenkins/intermine/imbuild/source.xml:145: java.lang.RuntimeException: Unknown DB found. ID: SFLDF00063
        at org.intermine.bio.dataconversion.Protein2iprConverter.getSource(Protein2iprConverter.java:204)
        at org.intermine.bio.dataconversion.Protein2iprConverter.process(Protein2iprConverter.java:137)
               Etc…
```
From @JoelRichardson 
Looks like there’s an unexpected value in the lastest download.
This function has a hardcoded switch that maybe should be configurized:
https://github.com/intermine/intermine/blob/dev/bio/sources/protein2ipr/main/src/org/intermine/bio/dataconversion/Protein2iprConverter.java#L177-L207

**Comment by julie-sullivan** [comment]
Yes! I will put in a config file. 

@rachellyne Which database does `SFLDF00063` come from? Do you know?

**Comment by rachellyne** [comment]
Superfamily.

**Comment by julie-sullivan** [comment]
See #1508
