### ISSUE TITLE
head.cdn.location = http://cdn.intermine.org breaks HTTPS mines in Chrome

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1506]
So the beany mines are on https now, and I find that Chrome complains when it sees the cdn URLs that are set by default in
```intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties```
as
```head.cdn.location = http://cdn.intermine.org```
This should be changed to https so security-minded beany types have a smooth user experience! It's actually a serious problem since it breaks HTTPS mines in Chrome.

**Comment by sammyjava** [comment]
OH. It's even worse. You're not running HTTPS on cdn.intermine.org. You must! Google says so!

**Comment by joshkh** [comment]
We switched to HTTPS and had some problems with mines that were still configured to use HTTP. I'll set up our test CDN to serve both and if all goes well I'll deploy into production.

**Comment by joshkh** [comment]
@sammyjava It might take a few days for us to test this due to our internal network setup, however in the mean time you can point your mine to https://cdn-dev.intermine.org which is secure and update-to-date with the production CDN. In the mean time I'll keep this ticket updated with our progress.

**Comment by sammyjava** [comment]
Thanks! No biggy, I use Firefox and I'm the only user, heh heh. :+1:

**Comment by sammyjava** [comment]
Slight variation on this now: the cert on cdn.intermine.org expired today:

cdn.intermine.org uses an invalid security certificate.The certificate expired on May 4, 2017 at 7:08 AM. The current time is May 4, 2017 at 6:01 PM.Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by julie-sullivan** [comment]
Closing this ticket.

@sammyjava is hosting his own HTTPS CDN. When we get our certs sorted out we'll put our CDN on HTTPS too.
