### ISSUE TITLE
InterPro - new database (SFLD - Structure-Function Linkage Database)

### ISSUE THREAD

**Issue by reset11** [intermine/intermine#1508]
Protein2iprConverter.java needs an additional DB entry
       } else if (dbId.startsWith("SFLD")) {
            dbName = "Structure-Function Linkage Database (SFLD)";

SFLD:
http://sfld.rbvi.ucsf.edu/django/

**Comment by 12dave123** [comment]
Hello, I think the issue has been resolved and will make a pull request shortly.

David
