### ISSUE TITLE
New displayer: Human Expression Heatmap

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1511]
It's open source: https://github.com/gxa/atlas-heatmap

Screenshot in action on the ebi test complex portal: 

![image](https://cloud.githubusercontent.com/assets/9271438/23264185/6932ba8a-f9d8-11e6-868a-a0451869ed9f.png)

We should add this to humanmine

**Comment by julie-sullivan** [comment]
Moving this to the tool planner.
