### ISSUE TITLE
Requesting a new anonymous token shouldn't fail if an old/invalid token is supplied

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1519]
We can work around this in the various client libraries, but it doesn't seem logical that inadvertently passing the old token (which is easy to do by default) should prevent you from getting a new good token

Demo: http://www.flymine.org/query/service/session?token=someexpiredtoken

**Comment by julie-sullivan** [comment]
How would you envision that working? Unfortunately, we don't keep records of API keys. `someexpiredtoken` may have been valid yesterday but it's not valid today. We don't know who you are. Who are you? 

We could respond to invalid tokens with a valid new token but is that expected behaviour?

**Comment by julie-sullivan** [comment]
We need a way to get API token for blue genes, need to add web service. This issue will be addressed then.
