### ISSUE TITLE
Userprofile backup script - more improvements

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1523]
Our servers are backed up daily but in the event something Goes Wrong, we would like to have local and more frequent copies as well.

The userprofile script currently:

* dumps userprofile database
* diffs the dump with the last dump
* if there is a difference, saves current dump
* CRON jobs for human and fly are set for every 5 minutes

This works fine because we have lots of backups of the userprofile database. It doesn't work that well because we have lots of backups of the userprofile database. The disk fills up.

What do we want to do? Take too few and then we can't roll back on error. Take too many and the disk fills up.

Options:

1. on saving of a new backup, delete the oldest. only keep 20 (or whatever) at a time.
2. take a snapshot once a day.
3. take a snapshot once a month
4. archive an entire day in gzip file. 

Maybe a combination of above?

Ask @sergiocontrino 

NB: The userprofile is permanently archived on a new release. 

Refs #1226

**Comment by julie-sullivan** [comment]
copy over weekly, monthly backups to owncloud?

**Comment by sergiocontrino** [comment]
i think we could just keep a gizipped file per day. i have modified the script to do that, and to alert via mail if the dump fails to create a file or the file is empty. making a pull request.
