### ISSUE TITLE
Add SyntenicRegion and SyntenyBlock to core data model

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1525]
As a bit of a push toward the "RFC" process to add to/standardize the data model, here's a good ol' issue submission to add MY (not someone ELSE'S) synteny classes!!! As per SO, syntenic_region is simply a single sequence feature. So I used a class SyntenyBlock to tie two syntenic regions together. We had the desire to specify the subject and target sequences (has to do with how they were divined in the first place with DAGChainer) as well as the similarity score medianKs. So, here it is:

```
  <class name="SyntenicRegion" extends="SequenceFeature" is-interface="true">
    <reference name="syntenyBlock" referenced-type="SyntenyBlock"/>
  </class>
  
  <class name="SyntenyBlock" is-interface="true">
    <attribute name="primaryIdentifier" type="java.lang.String"/>
    <attribute name="medianKs" type="java.lang.Double"/>
    <reference name="sourceRegion" referenced-type="SyntenicRegion"/>
    <reference name="targetRegion" referenced-type="SyntenicRegion"/>
  </class>
```

Let the games begin!

**Comment by JoelRichardson** [comment]
Next up: **our** way of representing this, which is similar, except that the SyntenicRegions simply reference each other, and we added an orientation (+/-) attribute
```
  <class name="SyntenicRegion" extends="SequenceFeature" is-interface="true">
    <reference name="partner" referenced-type="SyntenicRegion" reverse-reference="partner" />
    <attribute name="orientation" type="java.lang.String"/>
  </class>
```
The nice thing about the symmetric partner reference is it makes querying easier. We had no 'target' vs 'source' distinction to worry about.

**Comment by sammyjava** [comment]
Works for me, and certainly what I'll be doing for the Neo4j model anyway. The "source" vs. "target" thing for us is just documenting how DAGchainer was run. It's not of any biological significance AFAIK (although Andrew will straighten me out shortly on that if it is).  I like the simplicity/symmetry of just relating a partner to a partner.

We'll add an additional attribute medianKS, which will be duplicated on both partners, rather than currently in a single place in the SyntenyBlock. But that's a small price to pay, it's just a number. SyntenyBlock is another example of one of these relationships that I stored as an object, like Homologue and many others, that become Neo4j edges, or simply relations in your version.

**Comment by adf-ncgr** [comment]
Hi - only seeing this discussion now, but since my name was mentioned I'll briefly weigh in. I don't have intense convictions about which of the two proposed models to prefer, but I would note that in addition to the median Ks there may be other attributes of the synteny relation that could be of interest to record (some methods produce other scores and e-values) and similar to homology we may wish to be able to subclassify the nature of the synteny relationship (homoeologous, segmental duplication) or be able to characterize large-scale differences between the related partners (e.g. to record phenomena like subgenomic dominance). Not sure we necessarily need to make room for all this, but can imagine it being of interest to some groups. Looking forward to the discussion...

**Comment by rachellyne** [comment]
Could you point us to some of your synteny data so we can take a look?

**Comment by sammyjava** [comment]
Take a look at LegumeMine: https://intermine.legumefederation.org/legumemine

Our current model has a SyntenyBlock which contains two SyntenyRegions: a sourceRegion and a targetRegion (as defined by the 
synteny-finding tool, DAGChainer). The SyntenyRegions are just run-of the mill SequenceFeatures with the added reverse reference to 
the syntenyBlock.

Others do it differently. Joel Richardson's version simply stores the synteny region, and each has a reference to the syntenic pair, 
thus avoiding the SyntenyBlock middle man.

If you want the original DAGChainer data, I can send you some files.

**Comment by sammyjava** [comment]
![legumemine-synteny](https://user-images.githubusercontent.com/5657219/27293571-115ee4c6-54d4-11e7-8996-04e2b7bc4225.png)

**Comment by julie-sullivan** [comment]
@JoelRichardson I like your model better (easier queries!), but how would we record the extra data seen in @sammyjava's model?

**Comment by JoelRichardson** [comment]
@julie-sullivan I'm not sure. @sammyjava 's model is asymmetric wrt the the two regions - one is the source and the other is that target. I don't know if that's an important distinction or not. It seems like one could add a synteny block to my model that both participants could refer to. This would be optional (our process would not populate them), but block level data could be stored there if needed. Existing queries would not be affected, but queries that needed the data could get it. (Equally, one could add the 'partner' reference to the SyntenicRegions in Sam's model.)

**Comment by julie-sullivan** [comment]
@sammyjava what does the "source" and "target" mean?

**Comment by sammyjava** [comment]
That's from DAGChainer. It looks for synteny with _other_ genomes w.r.t. a source. Joel is correct, it's asymmetric, for purely 
notational reasons. Referencing the SyntenyBlock from the SyntenicRegions would be fine, but you'd not have the reverse 
relationship, unless you wanted to create a collection of SyntenicRegions, which would not be limited to two, which is inherent in 
the concept of synteny. But that would work fine otherwise.

A SyntenicRegion -> SyntenyBlock <- Another SyntenicRegion

would be fine, and you'd store the medianKs in the SyntenyBlock as before.

**Comment by julie-sullivan** [comment]
**PROPOSED SOLUTION**

```
  <class name="SyntenicRegion" extends="SequenceFeature" is-interface="true">
    <reference name="partner" referenced-type="SyntenicRegion" reverse-reference="partner" />    
    <reference name="syntenyBlock" referenced-type="SyntenyBlock"/>
  </class>
  
  <class name="SyntenyBlock" is-interface="true">
    <attribute name="primaryIdentifier" type="java.lang.String"/>
    <attribute name="medianKs" type="java.lang.Double"/>    
  </class>
```

**Comment by sammyjava** [comment]
Hrm. That makes a weird graph, having the regions directly related but also related through the SyntenyBlock:
```
SyntenicRegion1-PARTNER_OF->SyntenicRegion2
  \-MEMBER_OF->SyntenyBlock<-MEMBER_OF-/
```
I think we're better off with a single relating path:
```
  <class name="SyntenicRegion" extends="SequenceFeature" is-interface="true">
    <reference name="syntenyBlock" referenced-type="SyntenyBlock" reverse-relationship="syntenyBlock"/>
  </class>  
  <class name="SyntenyBlock" is-interface="true">
    <attribute name="primaryIdentifier" type="java.lang.String"/>
    <attribute name="medianKs" type="java.lang.Double"/>
    <collection name="syntenicRegions" type="SyntenicRegion"/>
  </class>

**Comment by julie-sullivan** [comment]
@sammyjava @JoelRichardson doesn't have syntenic blocks, so we need the blocks to be optional.

Yes, there are duplicate relationships but I don't see that's a downside. It let's queries be built both ways.

**Comment by sammyjava** [comment]
@JoelRichardson it's a downside for migrating the database for Neo4j, for one thing, which is something we're seriously considering. We'll have to code special cases for things like this that have duplicate relationships. But for Postgres, perhaps. Still strikes me as being clunky design, but that's aesthetics, not functionality.

**Comment by sammyjava** [comment]
@julie-sullivan Joel can create SyntenicBlock entries. Just tie two SyntenicRegions together, leaving medianKs null. We can't define a new data model that will accommodate the existing data in every mine that  is already out there. If so, we shouldn't define a core data model and leave it to the individual mines.

**Comment by julie-sullivan** [comment]
We have come to an agreement:

```
  <class name="SyntenicRegion" extends="SequenceFeature" is-interface="true">
    <reference name="syntenyBlock" referenced-type="SyntenyBlock"/>
  </class>
  
  <class name="SyntenyBlock" is-interface="true">    
   <collection name="syntenicRegions" referenced-type="SyntenicRegion"/>
  </class>
```

**Comment by JoelRichardson** [comment]
Can we add the inverse relationships? 
`  
<class name="SyntenicRegion" extends="SequenceFeature" is-interface="true">
    <reference name="syntenyBlock" referenced-type="SyntenyBlock" reverse-reference="syntenicRegions"/>
  </class>
  
  <class name="SyntenyBlock" is-interface="true">    
   <collection name="syntenicRegions" referenced-type="SyntenicRegion" reverse-reference="syntenyBlock" />
  </class>`

**Comment by julie-sullivan** [comment]
yes good idea @JoelRichardson !

**Comment by JoelRichardson** [comment]
One more question... In the current mousemine model, we use the DataSet containing the SyntenicRegions to distinguish one set of syntenic blocks from another. Is that the assumption for the new core model? Or would it be better to be more explicit? Maybe add a DataSet reference to the SyntenyBlock class. Possibly also add a Publication reference.

**Comment by sammyjava** [comment]
Yeah, those seem standard enough to warrant core inclusion. I think we figured specialty attributes, like medianKs in my case, would be added per mine, but DataSet and Publication are certainly widespread references. I'm agnostic regarding any additional core SyntenyBlock attributes, references, collections.

**Comment by JoelRichardson** [comment]
Maybe SyntenyBlock doesn't need a publication, because DataSet already has one.

**Comment by sammyjava** [comment]
Yeah, except sometimes you reference a Pub without having an associated DataSet. I haven't been using DataSets much, but I do use Pub refs. So I'd say no harm done in keeping a direct Pub reference.

**Comment by JoelRichardson** [comment]
Yup, ok.

**Comment by JoelRichardson** [comment]
So...this?

```<class name="SyntenicRegion" extends="SequenceFeature" is-interface="true">
    <reference name="syntenyBlock" referenced-type="SyntenyBlock" reverse-reference="syntenicRegions"/>
  </class>
  
  <class name="SyntenyBlock" is-interface="true">    
   <collection name="syntenicRegions" referenced-type="SyntenicRegion" reverse-reference="syntenyBlock" />
   <reference name="dataSet" referenced-type="DataSet" />
   <reference name="publication" referenced-type="Publication" />
  </class>```

**Comment by sammyjava** [comment]
Fine with me.

**Comment by julie-sullivan** [comment]
Would it be useful to have data set and publication be collections instead of references? Or would it never happen that a block would have multiple?

**Comment by sammyjava** [comment]
Pretty rare, since a synteny block results from a particular analysis. I think refs would cover all cases.

**Comment by JoelRichardson** [comment]
Agreed.
