### ISSUE TITLE
update-publications job fails if using UTF8 encoding

### ISSUE THREAD

**Issue by jdepons** [intermine/intermine#1535]
I am updating our mine to version 1.7.1 and am having trouble getting the update-publications job to complete.  It appears the job no longer supports a database with UTF8 encoding.  This job has worked for us with past versions of Intermine

> *Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte 
> sequence for encoding "UTF8": 0xed 0xa0 0xb5*

**Comment by julie-sullivan** [comment]
@jdepons We've figured out the problem - an invalid kappa from PubMed ID 27041523. 

I am not sure how to fix. In my case, the publication is coming from the `pubmed-gene` source so for now I am going to remove it from that data file. 

As for in the future, I don't know that I want to add a UTF check to the publications source, it will slow things down a bit. I'll have to think.

See #1532
