### ISSUE TITLE
Signor data source - signalling data 

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1538]
Add data from Signor. Data comes from here:

http://signor.uniroma2.it/downloads.php

The "all data" data file.

There will be a signalling object with participants. Along with a "details" object with the publication information. Similar to interactions.

Tell @joshkh

**Comment by joshkh** [comment]
Looks good! Can you please add Signor to the data sources page?

**Comment by julie-sullivan** [comment]
@joshkh done. check it over?

http://beta.humanmine.org/beta/dataCategories.do

**Comment by julie-sullivan** [comment]
From @rachellyne 


1. If the relationship is protein-protein then all looks fine but for other entities we need a way to bring in more info - eg. SIGNOR-PH28 is actually a 'Phenotype" (Mitotic checkpoint) and SIGNOR-C17 is a complex (Cyclin B/CDK1).  This info is in the file but I don't know how we would add it to BioEnity.

2. Some of the notes have just "1" or "2" - I don't think this is a loading/parsing problem though, I think it's like that in the file.

3. One entry has three genes: "CALM1 ; CALM2; CALM3" but they have used the same separator as the rest of the file so it's parsed incorrectly - we now have a CALM3".
