### ISSUE TITLE
OBO Source loader crossReferences bug

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1545]
Sources based off the standard obo file converter can be configured so that xrefs in the obo file are automagically converted to crossReferences between terms: the id in the xref is used to create another OntologyTerm, and the two terms are made to point to each other. The relevant code is here: https://github.com/mgijax/intermine/blob/master/bio/core/main/src/org/intermine/bio/dataconversion/OboConverter.java#L225-L236

The bug: if the same xref identifier appears for multiple terms, the xref term will only point back to the first term to be processed where it occurs. That is because this line is inside the if-statement:
https://github.com/mgijax/intermine/blob/master/bio/core/main/src/org/intermine/bio/dataconversion/OboConverter.java#L233

**Comment by JoelRichardson** [comment]
Here's an abridged example from the DiseaseOntology:

```
[Term]
id: DOID:10041
name: dysplastic nevus syndrome
xref: OMIM:155600

[Term]
id: DOID:1909
name: melanoma
xref: OMIM:155600
```
In MouseMine, both DO terms have xrefs to the OMIM term, but the OMIM term only has an xref to  DOID:1909.

**Comment by julie-sullivan** [comment]
From @JoelRichardson 

```
Looks like it worked. Thanks Julie!
```
