### ISSUE TITLE
We've lost the trail

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1572]
The breadcrumbs are missing. 

To fix we can replace the encoded pipe with regular pipe:

```
        if (!StringUtils.isEmpty(trail)) {
            trail = trail.replace("%7C", "|");
        }
```

Because the next line is looking for a regular pipe: https://github.com/intermine/intermine/blob/dev/intermine/web/main/src/org/intermine/web/struts/ObjectTrailController.java#L70

Is that the best thing to do?

**Comment by justinccdev** [comment]
I think it would be better to use URLDecoder.decode() if we can here rather than special-case the |

**Comment by justinccdev** [comment]
Please describe the reproduction steps. I am not familiar with all aspects of the trail.

**Comment by julie-sullivan** [comment]
Run a query. on the results page at the top left there should be a `Trail: Query` where the query link goes back to the query build or template form.

**Comment by justinccdev** [comment]
Okay, in the PR the trails are showing after queries and template execution, unlike before.
