### ISSUE TITLE
Update InterMIne code generation to be Python 3 compatible

### ISSUE THREAD

**Issue by justinccdev** [intermine/intermine#1583]
Python code generation needs to be updated to be Python 3 compatible.  This will probably be done by generating code that can be used in both Python 3 and 2 (via future statements).

**Comment by yochannah** [comment]
We are getting asked about this by community members: https://twitter.com/Fomightez/status/964544743437893632

**Comment by julie-sullivan** [comment]
Let's do this for 2.0!

**Comment by julie-sullivan** [comment]
`Missing parentheses in call to 'print'`

**Comment by julie-sullivan** [comment]
See https://github.com/fomightez/intermine-binder

**Comment by julie-sullivan** [comment]
@justinccdev This isn't going to make the 2.0 release, but let's get it done ASAP and we can put in its own point release!
