### ISSUE TITLE
Create ECO data parser and add descriptions to GO evidence codes

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#160]
We should add the full name for each GO evidence code so that when someone clicks on it or on mouse-over they can see what it means.

We can get the GO evidence codes from ECO:

www.obofoundry.org/cgi-bin/detail.cgi?id=evidence_code

**Comment by julie-sullivan** [comment]
@rachellyne This would require a model change to GO and others. Maybe worth it to review some data sources (interactions? expression) and use this ECO term where possible.

Or would the effort not be worth the work?

**Comment by rachellyne** [comment]
I'll take a look - I don't think any others use it.  Are GO going to re-do all evidence codes?   I thought the current system was good - simple!

**Comment by julie-sullivan** [comment]
@rachellyne We could ask GO people.

**Comment by julie-sullivan** [comment]
We need to change the model to have go evidence code be an ontology term instead of just a string. 

With sources that still use the regular GO evidence, we'd have to map them to the ECO term. Do they all map?

**Comment by julie-sullivan** [comment]
https://github.com/evidenceontology/evidenceontology/blob/master/eco.obo
Make a data loader for that ontology.

There is also a GO-ECO data set. use that instead?

**Comment by julie-sullivan** [comment]
https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/eco.obo

**Comment by julie-sullivan** [comment]
Here is an example entry:

```
[Term]
id: ECO:0000501
name: evidence used in automatic assertion
def: "A type of evidence that is used in an automatic assertion." [ECO:cjm]
subset: valid_with_gene
subset: valid_with_protein
subset: valid_with_protein_complex
synonym: "IEA" EXACT [GOECO:IEA]
synonym: "inferred from electronic annotation" EXACT [GOECO:IEA]
xref: GO_REF:0000003 "Gene Ontology annotation based on Enzyme Commission mapping."
xref: GO_REF:0000004 "Gene Ontology annotation based on Swiss-Prot keyword mapping."
xref: GO_REF:0000023 "Gene Ontology annotation based on Swiss-Prot Subcellular Location vocabulary mapping."
xref: GOECO:IEA "inferred from electronic annotation"
is_a: ECO:0000000 {is_inferred="true"} ! evidence
intersection_of: ECO:0000000 ! evidence
intersection_of: used_in ECO:0000203 ! automatic assertion
relationship: used_in ECO:0000203 {is_inferred="true"} ! automatic assertion
property_value: seeAlso http://geneontology.org/page/automatically-assigned-evidence-codes xsd:string
created_by: cjm
```

**Comment by julie-sullivan** [comment]
Just add a description for the evidence codes.

**Comment by julie-sullivan** [comment]
Model change so waiting until InterMine 2.0

**Comment by julie-sullivan** [comment]
ECO parser is done.

We are going to add description to GO evidence code, and a URL to the ontology term (if available).

**Comment by julie-sullivan** [comment]
* should I put this in the postprocess? or the main source?
* where do i get the description?
* which URL to use:

http://geneontology.org/page/automatically-assigned-evidence-codes
http://purl.obolibrary.org/obo/ECO_0000322

**Comment by julie-sullivan** [comment]
Looks good in beta flymine!
