### ISSUE TITLE
Portal - go to disambiguation page if there are issues

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1606]
From @kkarra 

Add a flag, e.g. `goToListUpload` to the portal parameters. If TRUE, the portal forwards to the disambiguation page -- but only if there are duplicates, etc.

Normally the portal adds all identifiers to the list and forwards directly to list analysis page.

**Comment by julie-sullivan** [comment]
An example:

http://www.flymine.org/query/portal.do?externalids=CG9151, FBgn0000099, tinman, runt, E2f&class=Gene

e2f1 and e2f2 are both added to the list. Instead, this should forward to disambiguation page in list upload.

**Comment by julie-sullivan** [comment]
@kkarra check 65380a0163e4ebbaa6b547d4ac0e5e90c06cf8fd. Maybe that's what you need? It goes to the list upload page if a flag is set.

**Comment by julie-sullivan** [comment]
Be sure to update Portal docs too when this is pushed into master

http://intermine.readthedocs.io/en/latest/webapp/linking-in/

**Comment by kkarra** [comment]
Thanks, Julie!!  I will test it and comment soon.

**Comment by kkarra** [comment]
do I need to set some property in yeastmine? I don't see it behaving as desired.
