### ISSUE TITLE
FlyBase chromosomes

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1610]
From @rachellyne 

```We are still getting some additional chromosomes - e.g. we have a D. mel chromosome 2 (with no located features). For D. mel we should have 2L, 2R, 3L, 3R, 4, X and Y. For release6 most of the heterochromatin was incorporated into the main chromosome arms, but we still have 2H, 3H etc. We also have XL and XR etc - I think X and Y have always been just X and Y, not divided into arms. There are also three scaffolds still appearing : 211000022278760, 211000022279188 and 211000022280328 and an unmapped scaffold: Unmapped_Scaffold_8_D1580_D1567```

**Comment by julie-sullivan** [comment]
Refs #1052

**Comment by julie-sullivan** [comment]
@rachellyne The scaffolds are coming from the FASTA file:

```
211000022278760, 211000022279188 and 211000022280328
```

```
dmel-all-CDS-r6.16.fasta:>CG40635-PB type=CDS; loc=211000022278760:complement(join(562..814,869..879)); name=CG40635-RB; dbxref=FlyBase:FBpp0291548,FlyBase_Annotation_IDs:CG40635-PB,REFSEQ:NP_001104166,GB_protein:EDP27858,UniProt/TrEMBL:A8QIA9,FlyMine:FBpp0291548,modMine:FBpp0291548; MD5=00717bbcf3b4fc3c1f9cb72c3c2ffeb3; length=264; parent=FBgn0085506,FBtr0302344; release=r6.16; species=Dmel; 
dmel-all-gene-r6.16.fasta:>FBgn0085506 type=gene; loc=211000022278760:complement(562..879); ID=FBgn0085506; name=CG40635; dbxref=FlyBase:FBgn0085506,GB:AJ784867,FlyBase:FBan0040635,FlyBase_Annotation_IDs:CG40635,UniProt/TrEMBL:A8QIA9,INTERPRO:IPR016149,INTERPRO:IPR000704,EntrezGene:5740827,GB_protein:EDP27858,GB_protein:EDP27858; MD5=43fce258bcee2b2f36e8b5e0607baa3b; length=318; release=r6.16; species=Dmel; 
```

What exactly can I do about that?

**Comment by rachellyne** [comment]
The unmapped scaffolds are still part of the reference sequence so actually I think we need to load these and associated genes, we just want to exclude them from the chromosome widget - is that possible.

**Comment by julie-sullivan** [comment]
Refs #1052 and #1634
