### ISSUE TITLE
Add defaults web service for each mine

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1631]
certain defaults are available to the jsp web app that aren't exposed via web services. These include:

- **default 'popular' object types** that appear at the top of class lists. Usually Gene, Protein.
- **default examples for the ID resolver**. There may be more than one set of IDs, e.g. 

```
     {:Gene    "CG9151, FBgn0000099, CG3629, TfIIB, Mad, CG1775, CG2262, TWIST_DROME, tinman, runt, E2f, CG8817, FBgn0010433, CG9786, CG1034, ftz, FBgn0024250, FBgn0001251, tll, CG1374, CG33473, ato, so, CG16738, tramtrack,  CG2328, gt"
      :Protein "Q8T3M3,FBpp0081318,FTZ_DROME"}
```
- **default separators** (Yeast can't use a comma, for example) 
- **default regionsearch example**, e.g. 
```
                                ["2L:14615455..14619002"
                                 "2R:5866646..5868384"
                                 "3R:2578486..2580016"]
```
- **default organism** (yes, intermines may be multi-organism, but there's almost always one we'd _rather_ appeared at the top of a list). This would need to be consistent across mines, e.g. perhaps in the format of `D. melanogaster`. Mixing and matching with longer format names would make queries fail and that would be silly.
- **default query builder query**. This isn't one that exists right now but should be added while we are exposing defaults. Query XML would be fine. 

@joshkh Did I miss anything?

**Comment by yochannah** [comment]
Why this is important: Right now this has to be hardcoded into BlueGenes! no good! We can't test it on the testmodel or any new mine without trawling through the JSP UI or making up defaults on our own - but they *are* in properties files somewhere. just top secret.

**Comment by julie-sullivan** [comment]
This will be a single web service that will return all parameters that @yochannah specified above in JSON format.

**Comment by julie-sullivan** [comment]
- [ ] default 'popular' object types that appear at the top of class lists. Usually Gene, Protein.
- [ ] default examples for the ID resolver 
- [ ] default separators 
- [ ] default regionsearch 
- [ ] default organism
- [ ] default query builder query.

**Comment by julie-sullivan** [comment]
okay the others are done. TODO

1. default types are set as tags, not in web properties. Should I try to get the tags? Or should I move to set all values by properties. e.g. later on we won't have the same tagging technology. Or will we?
2. default organism 4ab244e5667a34a01b745103a2857bc61cc8f026 Can we use those? are those used anymore? 
3. @sergiocontrino just added a property called `services.defaults.query` 
```
<query model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.primaryIdentifier Gene.organism.name" sortOrder="Gene.secondaryIdentifier ASC" ><constraint path="Gene.organism.name" op="=" value="Drosophila melanogaster" code="A" /></query>
```
Could we use that? Or is that bad practice?

**Comment by julie-sullivan** [comment]
@joshkh Do we want to store these properties with blue genes? 

YES

* These are to do with displaying the data. Nothing to do with the database layer. 
* These might be set by the biologist not by the InterMine dev. 
* They can change based on the whims of the admin. Not tied to the database build or intermine release. They should be in blue genes, not the codebase.

NO

* They are per-database. Default organism is database specific
* They are already there. Quit making trouble. This is easier

MAYBE

Use these for now, they are there, this is easy. Later -- make a UI to update config in blue genes.

**Comment by julie-sullivan** [comment]
Regarding the default 'popular' object types -- you can get these in the data model right now. It's the `im:preferredBagType` tag.

**Comment by julie-sullivan** [comment]
I am open to renaming this end point as well.

**Comment by julie-sullivan** [comment]
Made two more properties available to you:

```
# is this used by imtables?
constraint.default.value=eve
constraint.default.extra-value=D. melanogaster
```

and 

```
# used for iodocs. Just added by Sergio last month.
services.defaults.query = <query model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.primaryIdentifier Gene.organism.name" sortOrder="Gene.secondaryIdentifier ASC" ><constraint path="Gene.organism.name" op="=" value="Drosophila melanogaster" code="A" /></query>
```

Since these properties are meant for other apps, maybe safer to make a new one for blue genes? 

I added them here so you can test.

**Comment by julie-sullivan** [comment]
We need to document where we get these variables and how they are used in bluegenes.

http://intermine.readthedocs.io/en/latest/webapp/properties/web-properties/

**Comment by julie-sullivan** [comment]
I removed the constants parameter after discussing with Josh. These were added in 2012, there's no docs, they aren't used anymore. (if ever?)

If we want to add organism / default value as a property, we'll need to add it to the property file.

**Comment by yochannah** [comment]
```
        "bag": {
            "results": {
                "table": {
                    "size": "5"
                }
            },
            "example": {
                "identifiers": "PPARG, FTO, 3949, LEP, 946, MC3R, 9607, LPL, LDLR, P55916, 335, GLUT4, Notch1, SLC27A1"
            }
        },
```

This one could be improved a little - there may be more than one preferred default bolded type in list upload. Those ids cover Gene, but humanmine also has defaults for protein, for example: `P37231, PPARG_HUMAN`

still reviewing other bits

**Comment by yochannah** [comment]
Other than this I think it's all reasonable. Any reason why default QB query wasn't added? We can cope without it (and use something universal like select all genes and their homologues), but it'd be nice.

**Comment by julie-sullivan** [comment]
@yochannah that it is missing the config for the bag example for proteins, that's a bug. I must have parsed that wrong?

**Comment by julie-sullivan** [comment]
@yochannah @joshkh As for adding default query, we can use the one used for iodocs. It's really basic (give me all genes).  So I think safe to add?

**Comment by yochannah** [comment]
I think that all sounds good! let me know when you want me to re-review

**Comment by yochannah** [comment]
now that the default query and proteins come back this looks a-ok to me

**Comment by julie-sullivan** [comment]
Docs: http://intermine.readthedocs.io/en/latest/webapp/blue-genes/
