### ISSUE TITLE
Author names with characters that have accents and diacritical mark end up as ? in imtables

### ISSUE THREAD

**Issue by deepakunni3** [intermine/intermine#1644]
We first noticed this on BovineMine when a table displays publication with author names.

![screen shot 2017-07-27 at 10 46 55 am](https://user-images.githubusercontent.com/4530272/28679525-122754b2-72b9-11e7-8e42-ccfd15209fcb.png)

But in the Publication report page we don't see this behavior.

It seems to be a bug specifically in imtables.

**Comment by julie-sullivan** [comment]
`González-Agüero Mauricio` displays correctly. Please reopen the ticket if you find this error hasn't been fixed.
