### ISSUE TITLE
Need way to upgrade anonymous sessions via web service

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#1650]
In the current web app, an anonymous user's lists are persisted to the database when the user logs in or registers for an account. This happens in LoginAction.java

A web service driven webapp might first request a 24 hour anonymous session token via /service/session and then create lists using that token. We need a way to attach their anonymously created lists to their new or existing account if the user registers or authenticates.

We don't have a "Log In" web service so maybe we can re-use the /user/token endpoint with an optional parameter? The end point will need to accept either basic authentication (username and password) or a token (it already does both), and it should also accept a reference to a session token as a parameter. Hitting the end point should migrate the anonymously created lists to the authentication values in the request headers.

GET /user/token {session-token: "sg32ohsgdo3o"}

**Comment by julie-sullivan** [comment]
See #1646

**Comment by julie-sullivan** [comment]
Also, creating a new user should do the same thing. Copy over lists to the new profile.

**Comment by julie-sullivan** [comment]
@josh the UI will need to make it clear that the lists created are ephemeral, unless you log in. The current lists page says:

```
You are not logged in. Log in to save lists permanently and to mark items as favourites 
```

**Comment by julie-sullivan** [comment]
Merge is done here:

https://github.com/intermine/intermine/blob/dev/intermine/web/main/src/org/intermine/web/logic/profile/LoginHandler.java#L86

**Comment by justinccdev** [comment]
Design doc at https://github.com/justinccdev/intermine/wiki/retain-anonymous-lists-on-ac-creation-or-login-via-ws

**Comment by justinccdev** [comment]
Josh, the initial implementation of this now exists in my branch [1].  This is not final since there is some refactoring I will want to do.  The description is at [2].

You should be able to reach http://goose:8080/flymine/service to test.

[1] https://github.com/justinccdev/intermine/tree/merge-anon-session-into-user-account
[2] https://github.com/justinccdev/intermine/wiki/retain-anonymous-lists-on-ac-creation-or-login-via-ws

**Comment by julie-sullivan** [comment]
@justinccdev Can I close this ticket?

**Comment by justinccdev** [comment]
The initial work was done but Josh never took it further.  If it's not longer required then close it, but I would ask @yochannah first.

**Comment by yochannah** [comment]
I'm sure it's still relevant. To test I'll need to deploy a mine locally from this branch? I can put it in my calendar but not until after BOSC (i.e. early July)

**Comment by justinccdev** [comment]
Yes, you would need to do a local deploy.

**Comment by julie-sullivan** [comment]
@justinccdev Can you make a pull request as well? Thanks!

**Comment by julie-sullivan** [comment]
Putting this on the next release until we get a pull request.

**Comment by julie-sullivan** [comment]
@yochannah Can I close this ticket?

**Comment by yochannah** [comment]
@julie-sullivan no, we almost certainly still need this, but I haven't had the chance to test it. It's likely to get more important as we begin to implement mymine in bluegenes.

**Comment by julie-sullivan** [comment]
Can you maybe follow up with Justin to do the pull request?

**Comment by yochannah** [comment]
Yikes, I was going to manually create a PR from his branch, but it's probably non-trivial to update:
![image](https://user-images.githubusercontent.com/9271438/47162000-166a1a80-d2eb-11e8-9123-4251490ebfbd.png)

@justinccdev notsure if you're following updates - any chance you are able to look at this? I'll try pinging by email in a day or three if it looks like you are swamped by github notifications :)

**Comment by danielabutano** [comment]
A new /service/login endpoint has been added in my bluegenes branch.
The new endpoint implements the method POST, and receives in input username and password.
To call the new service you have to pass the session token (using the Authorization header, BlueGenes already uses it) so the anonymously saved lists can be added the authenticated user. 
The service returns a new token which has to be used for the further requests.

**Comment by danielabutano** [comment]
@uosl I was reviewing the code and I have decided to remove the renamedTemplates attribute returned before . An anonymous user can not save (even temporary) templates, only lists. So renamedTemplates is unneccessary
