### ISSUE TITLE
Simple data service GET /data/:type - what does it do?

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1651]
I've tried to run the "Simple data service" `GET /data/:type` service on iodocs on a couple of mines, and it just seems to say "pending" and never responds to anything?

---

edit - trying it directly in the browser works.... I tried it on Gene `GET /data/Gene` on beta flymine and got a 135 mb query response which is why it seemed to not come back on iodocs :laughing: 

In theory I think you're supposed to be able to filter it down somehow, but I don't know how. See screenshot:

![image](https://user-images.githubusercontent.com/9271438/29072435-85335480-7c3f-11e7-8e16-8d04e9e63eb3.png)

putting "adh" into the query param returns a 302 error.

This might actually be a useful web service if we can figure out how to use it? It's described as 

>This service allows simple access to queries against a single type. This is meant to allow for simple linking and resource-based access to InterMine data.

**Comment by julie-sullivan** [comment]
Used by JBrowse (I think) so I've relabelled this on iodocs.
