### ISSUE TITLE
Backup cron job - move scripts and save to different machine

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1654]
1. Backup script has moved. Update cron job

https://github.com/intermine/intermine-scripts/blob/master/bio/userprofile_backup.py
https://github.com/intermine/intermine-scripts/blob/master/bio/humanmine/userprofile_backup.py

2. Save to another machine. The whole point of the backup system is to save a copy, it doesn't make sense to save on the same machine. If that machine dies we are in trouble.

**Comment by julie-sullivan** [comment]
* use compressed postgres format instead of plain text
* how many do we need? only the most recent.

**Comment by julie-sullivan** [comment]
I don't see why flymine and humanmine need to use different scripts either.

**Comment by sergiocontrino** [comment]
updated crontab job to use new script for both mines and to dump in new directory
/micklem/dumps/userprofile
in humanmine and flymine subdirectories.

the script saves a dump a day for now, all gzipped except the last.
it also accommodate non standard naming for humanmine.
