### ISSUE TITLE
UI issues - buttons inaccessible on a small screen

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#1658]
This was noticed before, but, I am not sure if I reported.  It has come up again..

**curator experience**

 I was trying to demo the "manage columns" feature after preforming a query. I never noticed this problem before because I was always connected to a Thunderbolt monitor but you cannot access the "Cancel" and "Apply Changes" buttons with the default monitor settings while on a laptop. The buttons are too low on the manage columns window. I think there are a couple of solutions. One would be to change the size of the window so its smaller and include a scroll bar on the right side of the window, or two, make the window moveable so you could reorient the window on the screen using your cursor to change its position, or three, move the position of the buttons.

For comparison, if I select the "Manage Filters" option after running a query I am able to alter the filters and can easily see the "Cancel" and "define a New Filter" buttons on the bottom right of the window since the window is smaller.

**Comment by julie-sullivan** [comment]
@kkarra I don't suppose you have a screenshot of what you mean? 

@yochannah @joshkh or is it clear what's going on?

**Comment by kkarra** [comment]
using laptop size screen, upon 'manage columns' the buttons at the bottom to apply changes are unreachable..

[cancel_apply_changes_buttons_unreachable.pdf](https://github.com/intermine/intermine/files/1301092/cancel_apply_changes_buttons_unreachable.pdf)

**Comment by kkarra** [comment]
will this be fixed?

**Comment by yochannah** [comment]
@kkarra I've had a little play. I think the following css should fix it:

```css
.imtables .modal-dialog {
max-height:90vh;
margin:3vh auto;
}

.imtables .modal-header, .imtables .modal-body, .imtables .modal-footer {padding:1vh 15px}

.imtables .modal-body {
max-height: 70vh;
overflow:auto
}
```

This is what it looked like on a rather shrunken screen:

![image](https://user-images.githubusercontent.com/9271438/44394245-a7608780-a52e-11e8-9a63-30ae9d7d0d7a.png)

Could you test it out for me and tell if it helps? If it's good I'll add it to im-tables and do another point release. It should be fine to add to a css file (perhaps theme.css? https://yeastmine.yeastgenome.org/yeastmine/themes/yeastmine/theme.css ) at the end of the file. All of the style tweaks are prefixed `.imtables`, so it shouldn't affect anything except imtables.

**Comment by kkarra** [comment]
Thanks, Yo!!  Yes, that fixed the issue with the entire window displaying on a smaller screen. Tested locally, will add that bit to prod YM.
