### ISSUE TITLE
Generated Python Code for Query - show comments hides first line

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#1659]
The pop-up box that contains Generated Python code has  checkbox - 'Show comments' which is un-checked by default.  It assumes this line 1 to be a comments as well..
#!/usr/bin/env python

A user wrote asking for help to run the saved python query and it turns out he was missing that line, probably he copy pasted the code displayed without that key first line.

If easy fix, probably worth fixing...?

**Comment by yochannah** [comment]
That'll be.... this code block. 

https://github.com/intermine/im-tables/blob/09b426cd10edd95f6420965098d3c8382662ed17/src/views/code-gen-dialogue.coffee#L104-L108

**Comment by asherpasha** [comment]
I have submitted a pull request in im-tables repository.

**Comment by yochannah** [comment]
the PR for im-tables is merged - thanks @asherpasha! The github issue on this repo should probably stay open until we've updated and deployed the changed in intermine, not just im-tables.

**Comment by danielabutano** [comment]
Fixed
