### ISSUE TITLE
Add list id to the result of query/tolist service

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1669]
Requested by @joshkh.
Implemented on querytolist-addid branch on my repo. Travis fails client side. Have a look here:https://travis-ci.org/danielabutano/intermine/builds/267237204?utm_source=email&utm_medium=notification

**Comment by julie-sullivan** [comment]
https://github.com/intermine/intermine/issues/1327

Please note I am changing that end point in my branch too. There will be conflicts! Whoever merges into dev 2nd will have to fix. :D

**Comment by joshkh** [comment]
I missed a few other list related end points where the list ID needs to be returned:

* lists/union
* lists/subtract
* lists/intersect
* lists/diff
* lists/rename
* lists/append

This is pretty important for MyMine. Thank you!!

**Comment by julie-sullivan** [comment]
I am working on fixing the tests. Josh is going to remove the selenium tests too.

**Comment by julie-sullivan** [comment]
@danielabutano The tests are fixed now!! I honestly have no idea why they broke. :( Anyway, can you merge the dev branch into your branch and see if that fixes matters? thanks!

**Comment by joshkh** [comment]
# Tests #

### Test Lists ###
* 4genes `(eve, thor, zen, mad)`
* 1eve `(eve)`
* 1thor `(thor)`

The following end points now return a `listId` property:

### Union ###

```
http://beta.flymine.org/beta/service/lists/union

Params:

lists: 1eve
lists: 1thor
name: union
format: json

Response:

{"listId":181000009,"listName":"union","type":"Gene","listSize":2,"executionTime":"2017.09.27 15:55::06","wasSuccessful":true,"error":null,"statusCode":200}
```
### Intersect ###
```
http://beta.flymine.org/beta/service/lists/intersect

Params:

lists: 4genes
lists: 1thor
name: intersected
format: json

Response:

{"listId":181000012,"listName":"intersected","type":"Gene","listSize":1,"executionTime":"2017.09.27 15:59::54","wasSuccessful":true,"error":null,"statusCode":200}
```
### Difference ###
```
http://beta.flymine.org/beta/service/lists/diff

Params:

lists: 4genes
lists: 1thor
name: differenced
format: json

Response:

{"listId":181000011,"listName":"differenced","type":"Gene","listSize":3,"executionTime":"2017.09.27 15:58::20","wasSuccessful":true,"error":null,"statusCode":200}
```
### Subtraction ###
```
http://beta.flymine.org/beta/service/lists/subtract

Params:

references: 4genes
subtract: 1eve
name: newlist
format: json

Response

{"listId":181000008,"listName":"newlist","type":"Gene","listSize":3,"executionTime":"2017.09.27 15:51::45","wasSuccessful":true,"error":null,"statusCode":200}
```
### Rename ###
```
http://beta.flymine.org/beta/service/lists/rename

Params:

oldname: intersected
newname: intersected-renamed
format: json

Response:

{"listId":181000012,"listName":"intersected-renamed","listSize":1,"executionTime":"2017.09.27 16:06::58","wasSuccessful":true,"error":null,"statusCode":200}
```
### Append ###
```
http://beta.flymine.org/beta/service/lists/append

Params:

name: intersected-renamed
body: "even skipped" zen, bib hairless

Response:

{"listId":181000012,"listName":"intersected-renamed","listSize":3,"unmatchedIdentifiers":[
"hairless","even skipped"],"executionTime":"2017.09.27 16:30::46","wasSuccessful":true,"error":null,"statusCode":200}
```

**Comment by joshkh** [comment]
Oops, I missed an endpoint!

We also need to send back the list ID when a `DELETE` is sent to `/lists`
http://iodocs.apps.intermine.org/flymine/docs#/ws-available-lists/DELETE/lists
