### ISSUE TITLE
Load locations of protein domains

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#169]
We load protein domains from UniProt. Can we load them from InterPro instead? Then we can load locations too.

We had issues last time because the domains come from so many different sources, there were multiple locations etc. Hopefully that's solved now.

**Comment by julie-sullivan** [comment]
@sergiocontrino @rachellyne @vivekkrish @kkarra @chenyian-nibio 

Okay I've made the change to the data model to add protein domain regions, and I am certain that it will make absolutely no one happy. Good job, me!

My model:

***No changes***. None!

Proteins have protein domains, and protein domains have proteins.

That's it. But that was already in the model with the InterPro and UniProt data sources.

1. Protein domains already have a locations collection, so I used that for the regions. (Maybe not obvious enough?)
2. Protein domains already have a xrefs collection. I put the original domain identifier and database there.

So I didn't add or remove anything from the current model.

You could update your model to match this, or we could come up with a common solution everyone likes (YeastMine and TargetMine/Thalemine are still different).

If I don't hear anything, I am going to leave this source as is. Or I can rename it so I don't have merging issues with @chenyian-nibio .

**Comment by julie-sullivan** [comment]
Okay the above won't work because there needs to be a relationship between location and cross reference.

**Comment by rachellyne** [comment]
What do you mean?  We are changing the model to be like yeastmine so we can remove the cross-references?

**Comment by julie-sullivan** [comment]
Here is the model we are going with:

```
<class name="InterProDomain" is-interface="true">
<attribute name="name" type="java.lang.String"/>
<attribute name="description" type="java.lang.String"/>
</class>
<class name="ProteinDomain" is-interface="true">
<attribute name="method" type="java.lang.String"/>
<attribute name="start" type="java.lang.Integer"/>
<attribute name="end" type="java.lang.Integer"/>
<attribute name="shortName" type="java.lang.String"/>
<attribute name="type" type="java.lang.String"/>
<attribute name="name" type="java.lang.String"/>
<attribute name="description" type="java.lang.String"/>
<reference name="interpro" referenced-type="InterProDomain"/>
<collection name="parentFeatures" referenced-type="ProteinDomain"/>
<collection name="childFeatures" referenced-type="ProteinDomain"/>
<collection name="contains" referenced-type="ProteinDomain"/>
<collection name="foundIn" referenced-type="ProteinDomain"/>
<collection name="proteins" referenced-type="Protein" reverse-reference="proteinDomains"/>
<collection name="goAnnotation" referenced-type="GOAnnotation"/>
</class>

<class name="Protein" extends="BioEntity" is-interface="true">
<collection name="proteinDomains" referenced-type="ProteinDomain" reverse-reference="proteins"/>
</class>
```

**Comment by julie-sullivan** [comment]
This isn't in our download scripts: `match_complete`

**Comment by julie-sullivan** [comment]
Here's the model we are going with:

```
<classes>
  <class name="Protein" is-interface="true">
    <collection name="proteinDomainRegions" referenced-type="ProteinDomainRegion" reverse-reference="protein" />
  </class>
  <class name="ProteinDomainRegion" is-interface="true">
    <attribute name="start" type="java.lang.String"/>
    <attribute name="end" type="java.lang.String"/>
    <reference name="proteinDomain" referenced-type="ProteinDomain"/>
    <reference name="protein" referenced-type="Protein" reverse-reference="proteinDomainRegions"/>
    <collection name="database" referenced-type="CrossReference" reverse-reference="proteinDomains" />
  </class>
  <class name="ProteinDomain" extends="BioEntity" is-interface="true">
    <attribute name="identifier" type="java.lang.String"/>
    <collection name="proteinDomainRegions" referenced-type="ProteinDomainRegion" reverse-reference="proteinDomain" />
  </class>
</classes>
```

**Comment by julie-sullivan** [comment]
We may need to remove the interpro data from the uniprot data source. If we don't, we are going to have a protein, a protein domain, and a protein domain region that is empty.

**Comment by julie-sullivan** [comment]
@rachellyne Also, PDB has a protein domain reference in protein structure. I don't remember why. I am removing it though.

**Comment by rachellyne** [comment]
Would this affect mapping of domains onto the structure in a 3d viewer?  This is a good things to do, but I am not sure if we would have to have this modelled in a specific way to get it work.

**Comment by julie-sullivan** [comment]
@rachellyne I took the enrichment widget out. How is adding region going to impact the math on these?

```
      <enrichmentwidgetdisplayer id="prot_dom_enrichment_for_protein"
                                 title="Protein Domain Enrichment"
                                 description="Protein Domains enriched for items in this list."
                                 label="Protein Domain"
                                 startClass="Protein"
                                 startClassDisplay="primaryIdentifier"
                                 enrich="proteinDomains.name"
                                 enrichIdentifier="proteinDomains.primaryIdentifier"
                                 constraints="organism.name=[list]"
                                 typeClass="Protein"
                                 views="primaryIdentifier,organism.name,proteinDomains.primaryIdentifier,
                                       proteinDomains.name"
                                 externalLink="http://www.ebi.ac.uk/interpro/entry/"/>
```

**Comment by rachellyne** [comment]
We must use the interpro data for this.  We should carry on just using the interpro data.

**Comment by julie-sullivan** [comment]
it's not hte data I am worried about, it's the math. We've changed the frequencies that the domains turn up.

**Comment by rachellyne** [comment]
But not the interpro - there should be a many to one between each of the individual domains and the interpro.

**Comment by julie-sullivan** [comment]
But the relationship we are counting in the widget is:

Protein > region > protein domain.

Before it was the simpler:

Protein > protein domain.

We've changed the math.

**Comment by julie-sullivan** [comment]
before:

Protein > Protein Domain

Domain X annotates Protein A -- count = 1

After Protein > region > protein domain

Domain X annotates Protein A -- count = 20

**Comment by rachellyne** [comment]
But if you just count the interpro ids, you get the same number of domains.  If we can only count what's in the regions class, we'll have to put an interpro id in there too?

**Comment by julie-sullivan** [comment]
it's counting protein > region > protein domain.

Maybe you could compare the outcomes and make sure it's sensible?

**Comment by rachellyne** [comment]
I looked at two lists between beta and live. They give very similar p-values and the domains enrich in the same order so I think this is ok for now.  But I don't think it is the correct way to do it and could potentially make some results wrong.  Can we change the code so that it doesn't have to count everything?
