### ISSUE TITLE
Intermine Registry: please set Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1723]
I'd like to access the registry from within the browser, but I'm getting Access-Control-Allow-Origin errors. Could you please set this (preferably to '*')? Thanks!

**Comment by JoelRichardson** [comment]
Hi @julie-sullivan or @danielabutano , Any chance of getting this done soon-ish? Thanks!

**Comment by yochannah** [comment]
@JoelRichardson I think it should be [fixed](https://github.com/intermine/intermine-registry/pull/71) now - can you confirm? :)

**Comment by JoelRichardson** [comment]
@yochannah Yup, that did it. Thanks!
