### ISSUE TITLE
Some fields, e.g. taxon, are treated as integers in the results tables. Can we fix this in the model or in the results table?

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#1736]
Some numeric fields in InterMine represent unique identifiers such as `Organism.taxonId`. When passed to the `query/results` end point as the summayPath parameter, the results are calculated as numerical statistics such as the average and standard deviation, when it really should be treated as a string, such as `Gene.primaryIdentifier`.

I suspect that the summaryPath results are dispatched according to the field type, and `Organism.taxonId` is of type java.lang.Integer, so it's technically working as expected. Can this be solved by updating the data model so that the field is of type java.lang.String? Could this negatively impact other parts of InterMine?

![image](https://user-images.githubusercontent.com/4752532/34487626-14823cc2-efcd-11e7-961f-e1767894a2f4.png)

@JoelRichardson

**Comment by julie-sullivan** [comment]
@sammyjava Didn't you have a use case in which the data type had to be integer in the database, but you wanted it treated like a string in the results tables. Or was that someone else?

Otherwise, I don't think taxon ID should have been an integer in the first place.

**Comment by sammyjava** [comment]
Ummm, the only thing is that I use the taxonId_variety hack in my project.xml for identifying the variety of the particular taxon. So it must be a string. For example, 
```
    <!-- chado genomics -->
    <source name="lis-genomics" type="legfed-chado-db" dump="true">
      <property name="source.db.name" value="lis-chado"/>
      <property name="organisms" value="3847_Williams82"/>
      <property name="dataSetTitle" value="LIS Glycine max (3847_Williams82) data"/>
      <property name="dataSourceName" value="LIS chado database"/>
      <property name="processors" value="org.intermine.bio.dataconversion.SequenceProcessor"/>
    </source>
```
Identifies the variety of 3847 _Phaseolus vulgaris_ (common bean) as Williams82, the one that's been sequenced and assembled. That's the only unusual usage of taxonId that I know of. I strip it in the source and store it as an integer, storing Organism.variety from the portion after the underscore.

**Comment by julie-sullivan** [comment]
`Publication.year` is another integer field that should be treated like a string.

**Comment by JoelRichardson** [comment]
I agree. Math on year values makes sense, eg. searching for everything in the last 5 years or whatever, which is not the case for taxonids.

**Comment by julie-sullivan** [comment]
We talked about this on a call and I am trying to remember what was said. It was suggested that taxon ID be made a string to solve this display issue in the results table. Someone said that would not be a perfect solution because there is a use case for having an integer in the data model but the column to be treated like a string in the results tables.

I can't remember what that use case was though. 

Maybe Strings need to be strings and integers need to be integers?

I'm going to close this ticket until we can come up with a true case where the data model doesn't match the display in the results tables.

**Comment by JoelRichardson** [comment]
@julie-sullivan  I guess I don't understand. Taxonid should be a string not an integer. 
I don't know what other use case you're referring to.
