### ISSUE TITLE
HumanMine: External Links broken

### ISSUE THREAD

**Issue by hendrikweisser** [intermine/intermine#1761]
In gene pages on HumanMine, there are "External Links" in a list on the right side. Several of these are broken:

- Links to HuGe currently lead to a page on "libido enhancement products". Maybe the EBI's GWAS Catalog (http://www.ebi.ac.uk/gwas/) would be a replacement?
- Links to EBI's Expression Atlas (called "ArrayExpress Atlas" in the link list) lead to a 404 page. I believe they use the wrong format: `http://www.ebi.ac.uk/gxa/gene/[RefSeq gene no.]`
Based on manually searching in Expression Atlas, what would works is: `https://www.ebi.ac.uk/gxa/genes/[Ensembl gene ID]`
- Links to Ensembl sometimes lead to the wrong gene; e.g. ACTN2 (http://www.humanmine.org/humanmine/report.do?id=1252181) works, but PPARG (http://www.humanmine.org/humanmine/report.do?id=1118800) links to ASAH1. Again, linking via the Ensembl ID instead of RefSeq no. may work better.
- The BioGPS and HapMap links that I tried only gave me "Unable to connect".

(Entrez and BioGRID seem to work.)

**Comment by julie-sullivan** [comment]
@rachellyne Can you help me with this one too: #1660

**Comment by julie-sullivan** [comment]
Fixed by https://github.com/intermine/humanmine/commit/00f5f0b6af57122a8bbf233337dc4c7b0c39cc27

@rachellyne We should probably go through all the links (on FlyMine too). We are missing a few too, e.g. GTEx maybe? https://www.gtexportal.org/home/gene/PPARG

**Comment by rachellyne** [comment]
GWAS Huge:  use GWAs catalog for now: https://www.ebi.ac.uk/gwas/search?query=pparg
KEGG:   link maybe not so useful
Human protein atlas: https://www.proteinatlas.org/search/pparg
Array express atlas - not sure that we can link to this from Gene as it's specific to two different studies.
Intact - url didn't look obvious so not sure how to link.
BioGrid:  https://thebiogrid.org/111464/summary/homo-sapiens/pparg.html
GTex: https://www.gtexportal.org/home/gene/PPARG
clinvar:  https://www.ncbi.nlm.nih.gov/clinvar/?term=pparg%5Bgene%5D

**Comment by rachellyne** [comment]
Remove the bioGPS and hapmap links.

**Comment by rachellyne** [comment]
FlyMine:

Remove unigene link - keep the ncbi entrez link.  (Let's call the link the same thing in humanmine and flymine "NCBI entrez".

Update BDGP link:  http://insitu.fruitfly.org/cgi-bin/ex/report.pl?ftype=1&ftext=FBgn0004053
(seems to work with FBgn)

Remove Homologene link

**Comment by rachellyne** [comment]
FlyMine;

Remove SGD and ratmine links from pathway report pages.  Leave KEGG and add reactome.

**Comment by rachellyne** [comment]
We should have external links from all the dataset report pages as well.

**Comment by julie-sullivan** [comment]
All done. I've commited the changes and redeployed betas.

https://github.com/intermine/humanmine/commit/514d7b71653e140f065af5176721b03a4d558409
https://github.com/intermine/flymine/commit/efe15a4873f3a24e820d32a94fd65ad06aaa8e1f
