### ISSUE TITLE
Default query config should be in json

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1770]
![image](https://user-images.githubusercontent.com/9271438/36795235-62a1bf0a-1c9a-11e8-900d-05ee9cbb0633.png)
the default query returned by the web-properties endpoint is in xml. It would be _much_ easier to parse in bluegenes if it was json, instead.

**Comment by yochannah** [comment]
it is keyed under web-properties / services / defaults / query

**Comment by julie-sullivan** [comment]
What is the JSON for that query? I can update FlyMine and HumanMine. 

Unfortunately, this is located in the mine's `web.properties` file so I don't have any control over the other mines. However, looking at other mines, e.g. [yeastmine](https://github.com/yeastgenome/intermine/blob/master/yeastmine/webapp/resources/web.properties) and [mousemine](https://github.com/mgijax/mousemine/blob/master/webapp/resources/web.properties), I think this parameter was added and not used for anything. 

I don't see it here:

https://intermine.readthedocs.io/en/latest/webapp/properties/web-properties/

**Comment by julie-sullivan** [comment]
Oh, the docs are here: https://intermine.readthedocs.io/en/latest/webapp/blue-genes/

But no one has read those (yet!).

**Comment by yochannah** [comment]
re-opening - since we think people mmostly *haven't* deployed XML to prod it should be safe to switch to json, hopefully.

**Comment by yochannah** [comment]
Flymine;s query, converted to json:

```
{
  "from": "Gene",
  "select": [
    "secondaryIdentifier",
    "symbol",
    "primaryIdentifier",
    "organism.name"
  ],
  "orderBy": [
    {
      "path": "secondaryIdentifier",
      "direction": "ASC"
    }
  ],
  "where": [
    {
      "path": "organism.name",
      "op": "=",
      "value": "Drosophila melanogaster",
      "code": "A"
    }
  ]
}
```

**Comment by yochannah** [comment]
HumanMine:
```json
{
  "from": "Gene",
  "select": [
    "secondaryIdentifier",
    "symbol",
    "primaryIdentifier",
    "organism.name"
  ],
  "orderBy": [
    {
      "path": "secondaryIdentifier",
      "direction": "ASC"
    }
  ],
  "where": [
    {
      "path": "organism.name",
      "op": "=",
      "value": "Homo sapiens",
      "code": "A"
    }
  ]
}
```

**Comment by yochannah** [comment]
quick note to add - [no one has implemented this except flymine and humanmine](http://intermine.org/bluegenes-mine-config-checker/), so transitioning to JSON should definitely be safe.

**Comment by julie-sullivan** [comment]
Humanmine https://github.com/intermine/humanmine/commit/569eb69e592836457b4e8eb40e4930f3d92a01b7

FlyMine https://github.com/intermine/flymine/commit/12a9fb5df3e820a1933461bc05fabf8006611fcd

Will be updated next time I redeploy.
