### ISSUE TITLE
InterMine app: list of data from all InterMines

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1771]
A list of of all datasets (and their associated data sources) from all InterMines. Maybe something we can put on intermine.org? 

* Get list of mines from registry.intermine.org
* Query each one for list of data sets and associated data sources (see query below)
* display in a nice report - sort, search etc.
* once a day, check for updates
* be able to click through to the InterMine to actually view the data loaded by that dataset.
* A lot of descriptions are going to be empty, because they aren't used for anything right now. Help to prompt InterMine devs to update!

```
<query name="" model="genomic" view="DataSet.name DataSet.url DataSet.description DataSet.dataSource.description DataSet.dataSource.name DataSet.dataSource.url" longDescription="" sortOrder="DataSet.name asc">
</query>
```

**Comment by arunans23** [comment]
I would like to work on this issue. How to check for updates on a daily basis? Do we need to write cron jobs for that?

**Comment by arunans23** [comment]
Yes, that makes perfect sense. Thank you for the clarification. 

So, if we are going put this new feature on intermine.org where should I begin? Thanks in advance.

**Comment by yochannah** [comment]
@arunans23 

InterMine.org's github project is here: https://github.com/intermine/intermine-homepage-2017 - it's built in [hugo](https://gohugo.io/), which allows posts in markdown or HTML. 

Since you can include any HTML that you want, it's probably easier / faster to develop the project standalone with a mind for embedding it on a new page on intermine.org at some point later in the future? (@julie-sullivan will tell me if I'm wrong here :D, but it should be safe your you to make a start @arunans23 )

**Comment by arunans23** [comment]
@yochannah thanks for sharing the homepage repo. As you said, for now i'll develop a standalone repo that can be later included in the homepage.

**Comment by arunans23** [comment]
@yochannah @julie-sullivan I am having some troubles running the queries in individual mines. While some are returning results with status 200, some are responding with 400 bad request. 

The method I tried was, I retrieved the mine Url from registry and ran a loop over them by appending the query to them.

Working query : 
http://www.flymine.org/flymine/service/query/results?query=%3Cquery%20name%20%3D%20%22%22%20model%3D%22genomic%22%20view%3D%22DataSet.name%20DataSet.url%20DataSet.description%20DataSet.dataSource.description%20DataSet.dataSource.name%20DataSet.dataSource.url%22%20longDescription%3D%22%22%20sortOrder%3D%22DataSet.name%20asc%22%3E%0A%3C%2Fquery%3E

Not working query : 
http://adenine.bradley.edu/tetramine/service/query/results?query=%3Cquery%20name%20%3D%20%22%22%20model%3D%22genomic%22%20view%3D%22DataSet.name%20DataSet.url%20DataSet.description%20DataSet.dataSource.description%20DataSet.dataSource.name%20DataSet.dataSource.url%22%20longDescription%3D%22%22%20sortOrder%3D%22DataSet.name%20asc%22%3E%0A%3C%2Fquery%3E%27

There are 11 such mines that return status 400 bad request. I checked some mine Url like "https://yeastmine.yeastgenome.org/yeastmine" and they don't seem to be working. Your suggestions would be much appreciated.

**Comment by arunans23** [comment]
@julie-sullivan @yochannah 

I came up with something like [this](https://calm-earth-98875.herokuapp.com/). I got the UI design from Intermine registry. 

As per your requirement this will check for updates once a day, and the data is presented in a manner that is sorted and it can be searched.

**Comment by yochannah** [comment]
@arunans23 Oh my goodness, nice job!! Is there a repo for this that we can fork into the InterMine org? :heart_eyes:

**Comment by arunans23** [comment]
@yochannah  Yes I created a repo for the above application. [https://github.com/arunans23/intermine-dataset-registry](https://github.com/arunans23/intermine-dataset-registry). 

Please contact me if any changes needed to be done. :-)

**Comment by yochannah** [comment]
Closing - @arunans23 fixed this for us!! :heart:
