### ISSUE TITLE
Gradle: when installing bio project, intermine-bio-test.properties SHOULD NOT be mandatory

### ISSUE THREAD

**Issue by intermineorg** [intermine/intermine#1773]
I have tried to install the bio multi gradle project whitout having intermine-bio-test.properties stored in .intermine directory.
The copyMineProperties task in bio/model project is called and throws an exception. During installation phase, this task should not called, I think

**Comment by julie-sullivan** [comment]
Fixed by https://github.com/julie-sullivan/intermine/commit/304f4a40c3a3fe6936c742187c8cb6be957aa2d2 and https://github.com/julie-sullivan/intermine/commit/7d3166d89771a32d1a61f3835203408dfa30383c

**Comment by danielabutano** [comment]
I think that the problem still exists

**Comment by julie-sullivan** [comment]
@danielabutano So what is the solution? Remove this line?

```
inputs.sourceFiles.stopExecutionIfEmpty()
```
