### ISSUE TITLE
Ambiguous entries in the service instance of registry API

### ISSUE THREAD

**Issue by himanshukumar660** [intermine/intermine#1781]
In the service instance of registry API (`https://registry.intermine.org/service/instances`), we have certain ambiguous entries. For example,
1. We can find that in the entries for mines namely `ThaleMine`, `WormMine`, `YeastMine` and `ZebrafishMine`,  we have twitter key field values start with '@' while in all other mines, the twitter key field start without '@'.
2. We can also find the ambiguities in the neighborhood lists. In `MaizeMine`, the neighborhood list contains Plants but starts with space, while all other entries start without space. 
There could possibly be other ambiguities, but till now I found just these two.

**Comment by vivekkrish** [comment]
Hi @himanshukumar660, could you please move this issue to the appropriate repo: https://github.com/intermine/intermine-registry? Thank you!

**Comment by himanshukumar660** [comment]
Yes Sure.
