### ISSUE TITLE
GFF3: add header to record

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1786]
The header often has important metadata, such as the genome build,
date of annotation, etc. but is discarded.

https://github.com/intermine/intermine/blob/dev/bio/core/main/src/org/intermine/bio/io/gff3/GFF3Parser.java#L43

Instead, gather up all the header in a variable, and make it available to each GFF3Record object.

Tell @JoelRichardson

**Comment by JoelRichardson** [comment]
Thnaks @julie-sullivan. Can it be available to the constructor as well?
