### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [intermine/intermine#1787]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by redmusic27** [comment]
I have created a modern concept logo for you.
If you like it, I'll send you files and pr.

Concept : 
I made with the new style & modern. And i think it looks much better and more luxurious compared with the original.

- House form to symbolize the meaning of the warehouse
- Initials of InterMine " i & m "

![intermine](https://user-images.githubusercontent.com/37577374/38599905-71c0423c-3d8c-11e8-8d1d-4bf6c015a739.jpg)

Horizontal
![intermine-horizozntal](https://user-images.githubusercontent.com/37577374/38599588-4f55bebc-3d8b-11e8-9a2e-5e637f7a7575.jpg)
Vertical
![intermine-vertical](https://user-images.githubusercontent.com/37577374/38599592-534d1a56-3d8b-11e8-99f6-ce6e9be253f7.jpg)

what do you think?

**Comment by yochannah** [comment]
Hey @redmusic27 ! I think we're pretty happy with our logo at the moment, but thank you so much for putting effort and thought into this. 

It looks like there are some others who are specifically looking for logo help on GitHub though: https://github.com/search?utf8=%E2%9C%93&q=logo+label%3Ahelp-wanted&type=Issues&ref=advsearch&l=&l= - maybe give them a try! :)
