### ISSUE TITLE
Gradle: need a replacement for bio/test-all/dbmodel

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1799]
We used to use `bio/test-all/dbmodel` to run tests against, but that is gone. We need a replacement.

`bio-core` contains the generic `gff` data loader. When running a build, this code executes and uses the data model provided by the mine. The data loader does not reference objects directly instead does things like `createItem(featureType)`, where `featureType` is an `Intron` object, for example. 

We don't have any issues compiling the code because the data types are not required at compile time. The database would have been built using the mine's data model. If `Intron` was not in the data model, an error would be thrown at runtime. 

However, `bio-core-test` _does_ operate on objects, e.g. `Intron.getGene()` to test the converter worked correctly. The tests rely on data objects NOT present in bio-model. In our old system, we hand-configured the ant `build.xml` file to compile all the additions files from the listed data sources and use that to build the test database. We need a replacement for that.

Options:

1. rewrite tests to not operate on objects. Instead just query the database to see if the data is correct.
2. Use bio/sources all merged together to create the model for bio-core-test
3. Use a FlyMine source as a proxy for bio/test-all/dmodel.

I've done option 3. See #1794

**Comment by danielabutano** [comment]
@julie-sullivan do you remember how many tests were involved? Maybe option 1 were not so bad, we can add a ticket and eventually do it later...

**Comment by julie-sullivan** [comment]
This was fixed. We have the tests depend on a FlyMine JAR, `flymine-static` which has the mine's full data model.
