### ISSUE TITLE
CDS sequences and lengths not set properly

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1803]
In loading GFF3 files, I noticed that the length and sequence for the CDSs appear to be from just one of the constituent parts. For example, in this sample for a single gene:
[sample.txt](https://github.com/intermine/intermine/files/2000087/sample.txt)

In the mine, the CDS feature for 'MGP_AJ_P0018705' correctly has 3 locations, but the length and sequence appear to be just for the final segment. I would expect them to be the sum/concatenation of the parts.

**Comment by julie-sullivan** [comment]
@JoelRichardson Can you try this out? I've only used the unit test to test that it's working, maybe you can try with real data.

What I did was make a separate method to:

1. For each chromosome, query for CDSs without sequences
2. Loop through the CDSs
3. For each CDS.location, get the sequence from the chromosome for those coordinates and save in a temp variable.
4. When we see a new CDS, we process what we have for the previous CDS. This allows for multiple locations. We concatenate the sequences into one big one and save that new sequence with the CDS. Recalculating the length too.

**Comment by julie-sullivan** [comment]
@JoelRichardson has tested, works!
