### ISSUE TITLE
FASTA web service: support flank argument

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1809]
It would be awesome if the current trio of FASTA web services (starting with query/results/fasta) would support an optional "flank" argument specifying the amount of additional flanking sequence to include for each returned object. (And it would be super-duper awesome if the user could specify different upstream and downstream flanks...)

**Comment by sergiocontrino** [comment]
query/results/fasta already support this, and calls it extension. unfortunately it does not distinguish the 2 ends.
call it with service/query/results/fasta?=&query=QUERY&extension=10
unfortunately (again..) the upgrade to biojava #1772  broke it!

**Comment by JoelRichardson** [comment]
Thanks @sergiocontrino 
Wonder why extension doesn't show up here: http://iodocs.apps.intermine.org/mgi/docs#/ws-fasta-query/POST/query/results/fasta

**Comment by sergiocontrino** [comment]
yes, the omission is true for all mines, i realised it was there only when checking the code. trying to fix the biojava upgrade first, and then look into this.

**Comment by JoelRichardson** [comment]
Thank you! (I love it when upgrades break everything...)
