### ISSUE TITLE
FASTA web service: expose retrieve-by-region(s) functionality

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1810]
The current trio of FASTA web services can only return sequences of objects already in the database. It would be nice to have a web service for retrieving arbitrary slices of a genome. It looks like this functionality already exists (at least at FlyMine!) because when you do a region search you are given a button for retrieving the specified region as FASTA.

**Comment by julie-sullivan** [comment]
API end point will accept coordinates, like [regions/sequence](http://iodocs.apps.intermine.org/flymine/docs#/ws-genomic-region-to-fasta/GET/regions/sequence) does

What should the name be? `regions/fasta`. Does that even make sense.

@sergiocontrino Can you take a look?

**Comment by julie-sullivan** [comment]
Refs #1137

**Comment by JoelRichardson** [comment]
Also refs #1809

**Comment by julie-sullivan** [comment]
@JoelRichardson Doesn't the `/sequence` end point do this?

**Comment by JoelRichardson** [comment]
@julie-sullivan It does indeed! This one can be canceled. Thanks!
