### ISSUE TITLE
webservice xml queries failing with greater and less than operators

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine#1811]
there are cases where xml (valid and generated by our code generation) queries fail. seems to be related to the '<'  (&lt;) and '>' (&gt;)  signs in the constraint. the server responds with

> 400 Bad request. There was a problem with your request parameters:
> Query does not pass XML validation. XML document structures must start and end within the same entity.

**Comment by sergiocontrino** [comment]
some examples of failing queries:

1. 

`<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.chromosome.primaryIdentifier Gene.chromosomeLocation.start" sortOrder="Gene.primaryIdentifier ASC" constraintLogic="B and A and D" >
  <constraint path="Gene.symbol" op="!=" value="zen" code="B" />
  <constraint path="Gene.chromosomeLocation.start" op="&gt;" value="6745000" code="A" />
  <constraint path="Gene.chromosomeLocation.end" op="&lt;" value="6754194" code="D" />
</query>`

2. 

`<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.chromosome.primaryIdentifier Gene.chromosomeLocation.start" sortOrder="Gene.primaryIdentifier ASC" constraintLogic="B and A and C" >
  <constraint path="Gene.symbol" op="!=" value="zen" code="B" />
  <constraint path="Gene.chromosomeLocation.start" op="&gt;" value="6745000" code="A" />
  <constraint path="Gene.chromosome.organism.shortName" op="=" value="D. melanogaster" code="C" />
</query>`

but this is fine (using ">" instead of "&gt;").
`<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.chromosome.primaryIdentifier Gene.chromosomeLocation.start" sortOrder="Gene.primaryIdentifier ASC" constraintLogic="B and A and C" >
  <constraint path="Gene.symbol" op="!=" value="zen" code="B" />
  <constraint path="Gene.chromosomeLocation.start" op=">" value="6745000" code="A" />
  <constraint path="Gene.chromosome.organism.shortName" op="=" value="D. melanogaster" code="C" />
</query>`

**Comment by julie-sullivan** [comment]
Fixed by  #1670
