### ISSUE TITLE
Galaxy plugin - InterMine

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1819]
We have a FlyMine tool right now:

https://github.com/galaxyproject/galaxy/blob/dev/tools/data_source/flymine.xml

We have one for each mine. Looking at that file, it seems like we can replace with info from the registry.

Can we have a generic InterMine tool that will work for any mine in the registry?

Tell @danielabutano @yochannah

**Comment by julie-sullivan** [comment]
@danielabutano @yochannah Do we have / need docs for this? Can I close this issue?

**Comment by danielabutano** [comment]
galaxy has released yet the full integration with intermine. I would leave open this issue

**Comment by yochannah** [comment]
We should also add some guidance to the Galaxy Training network for this
before we close it.

**Comment by danielabutano** [comment]
**Export data from Intermine to Galaxy**
There are 2 options:
1- If you are in a mine instance, for instance flymine, you can run a query, select the option Export -> Send to Galaxy and the data will be exported in the galaxy instance specified in the Galaxy Location field (current implementation).
2- If you are in Galaxy, use the NEW intermine tool to be redirected to the registry, select the InterMine instance you want to use to export the data, run  the query,  select the option Export -> Send to Galaxy and the data will be exported in the Galaxy instance you started from.
At this purpose, a new endpoint has been implemented in the registry; it receives in input the GALAXY_URL parameter which will be used for the callback
http://registry.intermine.org/im-to-galaxy?GALAXY_URL=https%3A//usegalaxy.org/tool_runner%3Ftool_id%3Dintermine


**Export data from from Galaxy to InterMine**
You are in Galaxy, you can export data selecting InterMine, then you will be redirected to the registry, where you can select the specific mine where you want  to send your Galaxy data.
You will be redirected to the portal page of the mine selected.
At this purpose a new endpoint has been implemented in the registry:
http://registry.intermine.org/galaxy-to-im?URL={url provided by Galaxy to download the file containing type of identifier + identifier}
