### ISSUE TITLE
webapp: custom classes not appearing in browser data model

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1822]
This one may be difficult to debug. I've got a full data model in `dbmodel/build/resources/main/genomic_model.xml` and the classes are all present in `WEB-INF/lib/dbmodel.jar` in the war file. BUT, the webapp doesn't show any non-core classes. So now we've gone from the webapp expecting all core classes (which you just fixed this morning) to ignoring non-core classes in the model.
![screenshot-2018-6-12 soymine model tree browser page](https://user-images.githubusercontent.com/5657219/41306552-bc6fb6a0-6e33-11e8-80f6-fa826d151737.png)

**Comment by sammyjava** [comment]
I did re-run the following before rebuilding the webapp, just in case. No luck.
```
./gradlew postprocess -Pprocess=create-location-overlap-index
./gradlew postprocess -Pprocess=create-overlap-view 
./gradlew postprocess -Pprocess=create-attribute-indexes
./gradlew postprocess -Pprocess=summarise-objectstore
./gradlew postprocess -Pprocess=create-autocomplete-index
./gradlew postprocess -Pprocess=create-search-index
```

**Comment by julie-sullivan** [comment]
It looks like the issue is the model in `bio-core` is overriding your mine's model. Daniela is refactoring the model to ONLY live in `bio-model` instead which should fix this issue.

**Comment by sammyjava** [comment]
Is there a hack I can do in webapp/build.gradle in the meantime, or is this something Dani will be doing pretty soon? I'm doing some template building stuff and would like to have the webapp up on dev. No biggy, just wondering. @danielabutano

**Comment by julie-sullivan** [comment]
I think you can delete genomic_model.xml from `bio-core.jar`, or replace it with your own generated genomic_model.xml as a temporary hack to keep going. (@danielabutano is that right?)

This is all I am working on but not very close to a solution yet!

**Comment by sammyjava** [comment]
This must have been fixed ages ago. :1st_place_medal:
