### ISSUE TITLE
Problem merging items from different sources

### ISSUE THREAD

**Issue by nuin** [intermine/intermine#1826]
Hi

We are having trouble merging items coming from a couple of sources, more specifically GFF3 and FASTA. We are trying to load FASTA sequences for CDS items and we are ending up with duplicated entries that are not merging on what I assume is due to conflicting lengths. 

```sql
 secondaryidentifier | symbol  | primaryidentifier | lastupdated | length |   id    | name | scoretype | score | geneid | chromosomeid | chromosomelocationid | organismid | sequenceid | proteinid | sequenceontologytermid |            class
---------------------+---------+-------------------+-------------+--------+---------+------+-----------+-------+--------+--------------+----------------------+------------+------------+-----------+------------------------+-----------------------------
                     |         | CDS:2L52.1a       |             |   1284 | 1000005 |      |           |       |        |              |                      |    1000000 |    1000003 |           |                        | org.intermine.model.bio.CDS
                     | 2L52.1a | CDS:2L52.1a       |             |     45 | 2144854 |      |           |       |        |      2144831 |              2144853 |    1000000 |            |           |                2000025 | org.intermine.model.bio.CDS
(2 rows)
```
(top item comes from FASTA and bottom from GFF3)

Our GFF3 loader is generic, and as it long known, InterMine doesn't handle CDS length entries correctly from GFF3 (i.e. https://github.com/intermine/intermine/issues/1803), something that we noticed about a year and a half ago on WormMine, with no solution until recently.

It was suggested that we tried to setup a priorities (http://intermine.readthedocs.io/en/latest/database/database-building/priority-config/) and we tried all possible combinations with `celegans-cds-fasta` and `celegans-gff3` with no success.

```
CDS.length = \
        celegans-cds-fasta
```

Any help is appreciated. I decided to post the issue here rather than on Discord as it seems solutions are faster here.

Thanks in advance

**Comment by julie-sullivan** [comment]
What error message did you get originally? It should have been something like this:

```
Conflicting values for field Exon.chromosomeLocation between celegans-gff3-gene (value "Location [end=3354, feature=6360760, id=6360759, locat
edOn=6360749, start=3209, strand="-1"]" in database with ID 6360760) and celegans-gff3-mrna (value "Location [end=3354, feature=6360760, id=19
321726, locatedOn=6360749, start=3209, strand="-1"]" being stored). This field needs configuring in the genomic_priorities.properties file
```

Otherwise, setting priorities will not be useful. 

If your CDSs are not being merged it means you have not set their integration keys. These sources are not on github so I can't say for certain, but for example, this wormbase GFF source has no keys for any sequence features so nothing would be merged:

https://github.com/WormBase/intermine/blob/im-265/bio/sources/wormbase-gff/resources/wormbase-gff_keys.properties

**Comment by nuin** [comment]
There were no errors in merging, at least the CDS part. There were some errors on merging the mRNA FASTA file which were solved by adding the proper configuration to the priorities file

Here is a diff between what we had on WS264 (production) and our development on the priorities file

```
perties
51c51,52
<       celegans-gff3
---
>       celegans-gff3, \
>       celegans-transcript-fasta
94c95,99
<       wb-acedb-expr_cluster, *
---
>       wb-acedb-expr_cluster, \
>       wb-acedb-strain, \
>       wb-acedb-RNAi, \
>         panther
>
121a127,133
>
> MRNA.length = \
>       celegans-transcript-fasta, \
>       celegans-gff3
>
> CDS.length = \
>       celegans-cds-fasta
```

The merging for mRNA sequence worked flawlessly and I don't see the same duplication in the database. We are also using a generic GFF loader (MalariaMine) as our previous loader had some issues with some elements. This loader has been working fine, with the exception of the drawback of assuming (or not calculating) CDS lengths properly.

It doesn't make sense that integration keys are the problem, as we also didn't set anything for mRNAs and it works perfectly. Why the error with CDS only?

I assume that by using MalariaMine GFF loader we are using this key file

https://github.com/WormBase/intermine/blob/im-265/bio/sources/example-sources/malaria-gff/resources/malaria-gff_keys.properties


Would just adding a 

`CDS.primaryidentifier = primaryidentifier`

do the trick?

Thanks

**Comment by nuin** [comment]
Adding

`CDS.primaryidentifier = primaryIdentifier`

did the trick. Closing.
