### ISSUE TITLE
export button on result table: ignoring the extension for fasta sequence in proteins

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine#1827]
the extension works with dna sequences, but not with protein ones.

**Comment by yochannah** [comment]
@sergiocontrino could we add this as a ticket on im-tables as well? https://github.com/intermine/im-tables

**Comment by sergiocontrino** [comment]
done @yochannah, it is nr 163.

**Comment by sergiocontrino** [comment]
i think it does not make sense to have the extension for proteins, and the options should just not apply to protein export. could you confirm @rachellyne?

**Comment by sergiocontrino** [comment]
@rachellyne confirms.... so it is just a matter of removing the option for protein sequences (im-tables issue 163)
