### ISSUE TITLE
GO annotation - new evidence code HDA

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1831]
The build failed because there is a new evidence code I don't know how to process:

```
UniProtKB       A0AV96  RBM47           GO:0003723      PMID:22658674   HDA             F       RNA-binding protein 47  RBM47_HUMAN|RBM47       protein taxon:9606      20140203        UniProt         
UniProtKB       A0AV96  RBM47           GO:0003723      PMID:22681889   HDA             F       RNA-binding protein 47  RBM47_HUMAN|RBM47       protein taxon:9606      20140203        UniProt   
```

Here is the list of codes we are using: [go-evidence-codes](https://github.com/julie-sullivan/intermine/blob/gradle-merge/bio/sources/go-annotation/src/main/resources/go-evidence-codes)

Should I add it to the list? Or discard?

**Comment by rachellyne** [comment]
Is that new?  Add it to the list. don't discard it.

**Comment by julie-sullivan** [comment]
What's the name and URL?

**Comment by julie-sullivan** [comment]
http://geneontology.org/page/guide-go-evidence-codes
Oh, i see. Should I add the rest?

**Comment by rachellyne** [comment]
Yes, we should have them all.
