### ISSUE TITLE
Website footer: Add a link to github repo

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1832]
We should add some github links to our footer. Which github?

* intermine
* bluegenes
* the mine's github

**Comment by julie-sullivan** [comment]
Tell @yochannah

**Comment by julie-sullivan** [comment]
From Gos.

**Comment by yochannah** [comment]
configure in mine.properties, default to intermine + add link to bluegenes
in the intermine readme?

**Comment by sammyjava** [comment]
FWIW I think most folks roll their own footer.jsp. :)

**Comment by julie-sullivan** [comment]
This is referring to the bluegenes footer.

I don't know that we've done much with dev configuration for bluegenes yet.

**Comment by yochannah** [comment]
could we add it to the branding or defaults endpoint? Is that appropriate? We already read from those.

**Comment by julie-sullivan** [comment]
Yes! That's the best place for it.

**Comment by julie-sullivan** [comment]
this ticket belongs in bluegenes repo
