### ISSUE TITLE
Update version of Postgres JDBC driver?

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1838]
I'm running Pg 10 now and it's throwing some warnings which are fixed by running a newer JDBC driver in my mine's build.gradle. Here's what I'm using:
```
// https://mvnrepository.com/artifact/org.postgresql/postgresql
compile group: 'org.postgresql', name: 'postgresql', version: '42.2.2'
```
I don't think there's any reason not to use a recent JDBC driver even on an older (9.4) database. They're usually quite back-compatible.

**Comment by sammyjava** [comment]
For the record, here's what currently appears in `intermine/objectstore/build.gradle`
```
compile group: 'org.postgresql', name: 'postgresql', version: '9.4.1212'
```

**Comment by julie-sullivan** [comment]
Done! See 311bf05045eb61736647aa471f2b22e850c010ff
