### ISSUE TITLE
FlyMine: we have 117,000 chromosomes

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1843]
@rachellyne FlyMine has 117,000 chromosomes for the Drosophilas.

These have associated data so we just can't not load them (or can we?!). 

What should we do?

1. not load them. only load the "good" chromosomes. Where do I find those? We load from chado, there doesn't seem to be a way to tell them apart.
2. load but call them a different type. (Like what? And how do I distinguish?)
3. leave as is

**Comment by julie-sullivan** [comment]
The reason I am asking is that we do a postprocess with sequences and chromosomes, and it takes 24 hours. It used to take an hour.

I think this might be due to #1842 though.

**Comment by rachellyne** [comment]
They seem to have a different type already (SO ontology term).  The good ones are chromosome and chromosome arm while all the scaffolds are golden_path_region.

**Comment by julie-sullivan** [comment]
See #1052. We added this:

https://github.com/intermine/intermine/blob/dev/bio/sources/chado-db/main/src/org/intermine/bio/dataconversion/FlyBaseProcessor.java#L782

If it's a golden path, we set it to be a chromosome. 

I think the data has changed since that ticket.

**Comment by rachellyne** [comment]
Oh, maybe we can just take that line out then.  Can't think why we would have added that.

**Comment by julie-sullivan** [comment]
@rachellyne This didn't get the hoped for result. FlyBase has some chromosomes classified as chromosome arms and some as golden paths.

If you search for 2L on beta flymine you see that we now have duplicates:

![goldenpath](https://user-images.githubusercontent.com/1663057/42875173-f6ecddf4-8a7a-11e8-8630-a5d3d66429d6.png)

If I revert our change and treat golden paths as chromosome, this solves that problem but we are back with 117,000 chromosomes. Is there a way to filter out the "bad" chromosomes?

**Comment by julie-sullivan** [comment]
Here's a query that gets all types for features called `2L`. Organism 1 is `melanogaster`. It's classified as a chromosome arm and golden path. In InterMine, we consider this a chromosome.

```
FB2018_03=> select f.uniquename, f.organism_id, c.name from feature f, cvterm c where f.type_id = c.cvterm_id and f.uniquename = '2L';
 uniquename | organism_id |        name        
------------+-------------+--------------------
 2L         |          82 | golden_path_region
 2L         |           1 | chromosome_arm
 2L         |           7 | chromosome_arm
 2L         |           1 | golden_path_region
 2L         |         176 | golden_path_region
(5 rows)
```

**Comment by julie-sullivan** [comment]
@rachellyne If you search for chromosomes on the live flymine you will see lots of garbage chromosomes with no entities or additional information attached. How to get rid of these? They have long identifiers. Can I base it on that? 

Not sure how to tell the good from the bad!

**Comment by julie-sullivan** [comment]
Chado is very generic, e.g. a feature table instead of a gene table, so the parser is very complex. At the point where we change the type from golden path to chromosome, we don't know anything about located features. 

All I know is this:

* Integer featureId
* String chadoFeatureType
* String interMineType,
* String name
* String uniqueName
* int seqlen
* int taxonId

OPTIONS

1. "guess" based on identifier, e.g. only change the type of 2L, X.
2. do another query to get golden paths with located features. the better option but a lot more complicated.

**Comment by rachellyne** [comment]
If we do 1, we lose 18 genes (assuming we just take the main chromosomes and rDNA).  Maybe we could add this as a note to the data sources page explaining that we only load the main chromosomes?

Or - we can load all by hardcoding all identifiers based on last build?

**Comment by julie-sullivan** [comment]
I can hardcode. Bad idea in general but these won't change. Can you give me the list of good ones?

**Comment by rachellyne** [comment]
211000022278279
211000022278436
211000022278449
211000022278760
211000022279165
211000022279188
211000022279264
211000022279392
211000022279681
211000022280328
211000022280341
211000022280347
211000022280481
211000022280494
211000022280703
2L
2R
3L
3R
4
Unmapped_Scaffold_8_D1580_D1567
X
Y
rDNA

**Comment by rachellyne** [comment]
That's all that have at least one gene annotated to them.  The 211xxxxxx ones only have one gene each.
