### ISSUE TITLE
FASTA query web service: times out when extensions are used

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1844]
Tell @JoelRichardson 

The problem is with this end point: `/query/results/fasta`

1. arbitrary query returns a set of sequence features
2. returns the sequence of those features in FASTA format

This works fine except when the `extension` parameter is used.

[SequenceExporter.java](https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java#L266) gets the sequence from the feature. However, if `extension` is used, it gets the sequence from the Chromosome. Something like this:

```
feature.getChromosome().getSequence().getResidues().toString()
```
This times out. I don't know why.

There is no error message in the log files and we can't reproduce this error in FlyMine.

**Comment by julie-sullivan** [comment]
It's just a [toString()](https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java#L266).

**Comment by julie-sullivan** [comment]
You looked in `catalina.out`, is there anything in the other tomcat log files? e.g. localhost<DATE>.log.

**Comment by JoelRichardson** [comment]
@julie-sullivan The last log snippet I sent you ended with an out of memory error. 
As I said, it's issuing TONS of queries which by the looks of things is loading the whole clob (or many clobs - I'm not sure) 20 pages at a time.

**Comment by julie-sullivan** [comment]
That's from the catalina out log file. Is there anything in the other log files? Hoping for an actual error message.

**Comment by JoelRichardson** [comment]
One question: all of the chromosome 1's have a primary identifier == "1" (etc for the others). Most of them also have Mus musculus as the organism (three have other species). Is there any way it could be getting confused and instead of loading one chromosome "1", it's loading all of them?

**Comment by julie-sullivan** [comment]
It doesn't use the primary identifier. To get the chromsome, it uses the [Gene.chromosome reference](https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java#L256). So it would be using the intermine id "under the hood".

**Comment by JoelRichardson** [comment]
What I sent you was from intermine.log

**Comment by julie-sullivan** [comment]
Can you check `$TOMCAT/catalina.out` (right after making a request)? And the localhost log files. I am hoping for a useful error message.

**Comment by julie-sullivan** [comment]
I get a 500 error, I would expect a 504 error if it was a timeout -- and I would think it would take longer and not be instant. But that could be our web service returning the wrong error. that has been known to happen!

**Comment by JoelRichardson** [comment]
As I said, the error is "out of memory" - see below. Both intermin.log and catalina.out have the same message:

04/07/18,08:52:04 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
extension: 10
view: Gene.primaryIdentifier
query: 
<query name="" model="genomic" view="Gene.specific.id">
    <constraint path="Gene.primaryIdentifier" op="=" value="MGI:2142601"/> 
</query>

java.lang.OutOfMemoryError: Java heap space

**Comment by JoelRichardson** [comment]
As before, both logs also show a Loooooooooong series of queries requesting 20-page clob segments from the same clobid (a chromosome I assume). So...out of memory.

**Comment by julie-sullivan** [comment]
How much memory do you give the webapp? Can you experiment with giving more?

I see that it puts the chromosome sequences in a map. I don't see a clever way around this, because if you don't use the map you'd need a database query for each feature. Which might be more expensive?

https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java#L268

**Comment by JoelRichardson** [comment]
So wait a minute. If I'm understanding correctly, then the way extension is handled is by reading the entire chromosome sequence into memory and then taking string slices?! 

If that's the case, then the current implementation is not viable. 

I guess maybe I was under the misguided assumption that the sequence clob was random access (ie addressable). In fact, I have always thought that feature sequences were not actually materialized, but simply represented as offsets into the chromosome sequence. Is that not the case? (I'm certain Alex said this at one point.)

**Comment by JoelRichardson** [comment]
Even so, you can easily load an entire genome just to extract a few kb. Also, the current approach is actually issuing hundreds of queries (maybe thousands I dont know) in order to load the sequences because it's only requesting 20 clob pages per request.

Unfortunately, memory is not cheap where we are. We have to go through Jax IT for every request and they refuse to give any vm more than 32 GB (but you have to beg). Usually it's 16.

**Comment by julie-sullivan** [comment]
Is 32 GB what you have now? Because that feels like it should be enough.

You are right about the waste, but you can easily have several thousand+ results in a query and that would mean a database query for each row.

We can come up with a more scalable solution. Maybe sort by chromosome so you only have one in memory at a time? Process all features for the chromosome then discard when done. No map needed!

**Comment by JoelRichardson** [comment]
Not on beta. Its always been a wimpy server. Might even have 8.

So you can only retrieve a single "chunk" in one query? (I'm not familiar with the clob interface) There's no way to ask for multiple regions at once?

**Comment by julie-sullivan** [comment]
From @JoelRichardson 

```
Good question. I don¹t really know, but I guess I was thinking more along
the lines of somehow specifying the ranges via query rather than
explicitly writing them into the SQL. Something along these lines (playing
very fast and loose with syntax):

create temp table Ranges as
select f.primaryIdentifier as feature, f.chromosome, f.location.start,
f.location.end
from SequenceFeature f
where (whatever constraints we like)

select r.feature, c.sequence.residues.slice(r.start - extension, r.end +
extension)
from Chromosome c, Ranges r
where c.chromosome = r.chromosome


The hoped-for magic is the residues.slice() call or something equivalent.
No idea if anything like that call exists...
```

**Comment by julie-sullivan** [comment]
This seems like it would work! Not trivial though, might need to benchmark. 

Also I would need you to test as I can't replicate this issue! :)

**Comment by julie-sullivan** [comment]
> with the same number of queries?

We only have one query now, because the chromosome sequence is put in a map for use later as the features are processed. 

Do you think we could have a single query to get all sequences?

**Comment by JoelRichardson** [comment]
Right now if you specify an extension, it reads each chromosome with one query. OK. But.

That one query is being turned into a VERY long series of queries to read each chromosomes 20 clob pages at a time. Right now, the clob page is set at 7000 characters. Mouse chromosome 2 is a little over 180 MB. That's 25714 pages. AT 20 pages per query, that's 1285 queries to read one chromosome. Since I'm reading 19 chromosome 2s, that's 24,428 queries, transferring a total of 3.4 GB of data from disk, in order to extract a little over 500 kB of sequence.

When I said "the same number of queries" I meant the same as when no extension is specified. Right now, if no extension is specified, the coordinate range for each feature's sequence (ie the encoded value in the residues column) is converted into short list of queries to load the exact clob pages we need. Cool. Efficient. Why can't the extension amount simply be added into the calculation at the time of clob access?

**Comment by julie-sullivan** [comment]
Why is mousemine so different to flymine and humanmine? What it's doing now for mousemine doesn't seem correct.

Anyway, yes, what you say makes sense! I'll investigate.

**Comment by JoelRichardson** [comment]
What is mousemine doing that's different? How does it work in flymine if you add an extension? It doesn't load whole chromosomes?

**Comment by julie-sullivan** [comment]
That's a good question! Not sure!

For FlyMine, when you add the extension, it only returns the chromosomes for the features selected in the query. No timeout, or weird queries.

**Comment by julie-sullivan** [comment]
Correct. I do not see that.

**Comment by JoelRichardson** [comment]
What queries do you see?

**Comment by julie-sullivan** [comment]
Our network is now offline (we are moving back to the genetics dept)! I'll check when it's back up. 

Can you paste your queries in this ticket again? Maybe that will help.

Maybe something, e.g. a batch size, is configured suboptimally?

**Comment by JoelRichardson** [comment]
Reading entire chromosomes is suboptimal and I suspect, unnecessary.

**Comment by JoelRichardson** [comment]
From intermine.log...

When I retrieve Pax6 sequences from each strain with no extension I see clob queries like the following. Each strain's chromosome 2 is hit by a few clob accesses. Looking at the code I think the first two queries for each chromosome are to determine its total length (not sure why it's done that way). Then the 3d query actually gets the pages containing Pax6 from that chromosome.
```
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 0 AND clobpage < 20 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 24480 AND clobpage < 24500 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 14160 AND clobpage < 14180 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 3000035 AND clobpage >= 0 AND clobpage < 20 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 3000035 AND clobpage >= 26940 AND clobpage < 26960 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 3000035 AND clobpage >= 15400 AND clobpage < 15420 ORDER BY clobpage
```

When I add an extension of 1000, the here's what I get. Again, the first 2 queries determine the size of the sequence, and then from query 3 onward, it's just loading the whole thing 20 pages at a time.
```
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 0 AND clobpage < 20 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 24480 AND clobpage < 24500 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 20 AND clobpage < 40 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 40 AND clobpage < 60 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 60 AND clobpage < 80 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 80 AND clobpage < 100 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 100 AND clobpage < 120 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 120 AND clobpage < 140 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 140 AND clobpage < 160 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 160 AND clobpage < 180 ORDER BY clobpage
generated sql: SELECT value AS a1_ FROM clob WHERE clobid = 2000037 AND clobpage >= 180 AND clobpage < 200 ORDER BY clobpage

(etc for all the clob pages for this chromsome, then on to the next...)
```

**Comment by JoelRichardson** [comment]
Hi @julie-sullivan The more I look at the code, the more I think this issue can be easily solved. Here's the outline of what I'm thinking:

In BioSequenceFactory.java:
Add an extension parameter here: https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/biojava/BioSequenceFactory.java#L62
(Maybe also here? I'm not sure. Extension would only apply for DNA sequences.) https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/biojava/BioSequenceFactory.java#L103)
Add code that adjusts the residues string based on the extension amount here (this is the heart of the whole thing): https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/biojava/BioSequenceFactory.java#L67-L68

In SequenceExporter.java:
Pass the extension parameter here: https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java#L240
Delete all this: https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java#L247-L301
Don't need this test: https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java#L164
Just this: https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java#L164

**Comment by JoelRichardson** [comment]
If this makes sense to you, I'm going to try it here and let you know how it goes.

**Comment by JoelRichardson** [comment]
Never mind. I was misinterpreting the code. Back to the drawing board.

**Comment by JoelRichardson** [comment]
Actually, never mind the never mind. It works!!! I was able to get all Pax6 sequences with a 1kb flank just as fast as without any flank. I had to refine what I had proposed a bit, but the basic idea was right. Right now the code is sitting on a branch off our local fork, so I'll need to put together a proper pull request. In the meantime, here's the heart of the change. In ClobAccess, added a method to return a new ClobAccess with an added flank.

https://github.com/mgijax/intermine/blob/5a81bd4fbfc77db8d291180be2323497b858aa26/intermine/objectstore/main/src/org/intermine/objectstore/query/ClobAccess.java#L173-L207

Then in the sequence factory, tweaked the make() method to pass the extension:
https://github.com/mgijax/intermine/blob/5a81bd4fbfc77db8d291180be2323497b858aa26/bio/webapp/src/org/intermine/bio/web/biojava/BioSequenceFactory.java#L65-L85

The other change is in SequenceExporter, the createSequence method is simplified, and the createSequenceFeatureWithExtension method is gone.

https://github.com/mgijax/intermine/blob/366bfdaf5783b4c7eef1053123c0c0efbaaa3644/bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java#L224-L235
