### ISSUE TITLE
Solr: autocomplete issue

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1849]
In the current system if the user edits "dystrophy cone" in the Ontology term-> name, in the constraint popup window, the auto complete function shows all the names containing the 2 words independently from the order (e.g.code-rod dystrophy).
In solr, if the user edits

1. hydrolase active -> "2,5-dioxopiperazine hydrolase activity" doesn't show up
2. 11 hydrolase -> "11-cis-retinyl-palmitate hydrolase activity" doesn't show up

**Comment by arunans23** [comment]
@danielabutano I resolved issue. Please have a look when you try it next time. :-)

**Comment by danielabutano** [comment]
Fixed it! thanks
