### ISSUE TITLE
Solr: facets organism shows 3 organisms instead of one

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1852]
Quick search e.g.ABRA, 3 facets are shown under Organism: 3d7, falciparum and p but we have only one organism "P. falciparum 3D7"

**Comment by arunans23** [comment]
@danielabutano I have changed the code to use a keywordtokenizer instead of a standardtokenizer.

**Comment by danielabutano** [comment]
@arunans23 it still doesn't work

**Comment by arunans23** [comment]
@danielabutano did you use a fresh solr instance? It might be that old schemas are still used?

**Comment by danielabutano** [comment]
i deleted the 2 cores intremine-search and autocomplete. Isn't it enough?

**Comment by arunans23** [comment]
I think running this commands should be sufficient.
`bin/solr delete -c collection_name'`
`bin/solr restart`

If the error is still there, maybe deleting the solr folder and extracting it again would help.

**Comment by danielabutano** [comment]
Thanks @arunans23. restarting solr (after deleting the core) fixed the problem
