### ISSUE TITLE
Solr: autocomplete code review

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1855]
- [x] CreateAutocompleteIndexProcess: no need to load the properties objectstoresummary.config.properties (propertiesmanager java classes is used instead)

- [x] CreateAutocompleteIndexProcess: Indentation

- [x] AutoCompleter: getList; not sure if it’s still used, if not, please delete it

- [x] SolrClientHandler.java: solrUrl is hardcoded

- [x] SolrClientHandler.java: remove solrUrl variable never used

- [x] SolrIndex: code similar to Autocompleter.buildIndex(). Do we need it?

**Comment by arunans23** [comment]
@danielabutano the getList method in AutoCompleter is commented out [here](https://github.com/intermine/intermine/blob/gradle/intermine/webapp/src/main/java/org/intermine/dwr/AjaxServices.java#L1345). 

According to the issue #451 getList() is not used anymore. I think it is okay to delete. Please confirm.

**Comment by danielabutano** [comment]
yes, @arunans23  please go ahead deleting the getList method

**Comment by arunans23** [comment]
@danielabutano I have deleted the getList method
