### ISSUE TITLE
Webapp can't find org.intermine.webservice.server.jbrowse.Config

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1857]
I hadn't debugged this until I put SoyMine on production because we've got issues with JBrowse on dev mines, anyway. But it appears we have another gradle/classpath issue with intermine-jbrowse-endpoint. The webapp is throwing this exception on the JBrowse displayer.
```
12-Jul-2018 10:58:02.071 SEVERE [ajp-apr-8029-exec-26] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet ws-jbrowse-config
 java.lang.ClassNotFoundException: org.intermine.webservice.server.jbrowse.Config
```

**Comment by julie-sullivan** [comment]
Thanks! Fixed
