### ISSUE TITLE
/service/jbrowse/NNNN/stats/global throws 500

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1859]
The JBrowse displayer requests this URL for each track; it is throwing a 500 now in v2. That displays a nice red box on the track.
![screenshot_2018-07-12 soymine gene glyma 18g280900 g max](https://user-images.githubusercontent.com/5657219/42652406-8dceb7e8-85cf-11e8-845e-420b2ea73b21.png)

**Comment by julie-sullivan** [comment]
My JBrowse is fine. 

http://www.humanmine.org/humanmine/portal.do?class=Gene&externalids=5468

Does your tomcat log give you any more information? That error message is completely unhelpful.

**Comment by julie-sullivan** [comment]
In my log file:

```
]100512 [ajp-nio-8009-exec-93] ERROR org.intermine.webservice.server.WebService  - Service failed by internal error. Request parameters: 
java.lang.IllegalArgumentException: Invalid constraint: QueryField(org.intermine.model.bio.Organism, taxonId) (a java.lang.String) = java.lang.Integer: "9606" (a java.lang.Integer)

  at org.intermine.objectstore.query.SimpleConstraint.<init>(SimpleConstraint.java:68)
  at org.intermine.webservice.server.jbrowse.genomic.Engine.constrainToOrganism(Engine.jav
```

**Comment by julie-sullivan** [comment]
That fixed it for me, can you test? Thanks!

**Comment by sammyjava** [comment]
Yup fixed.
