### ISSUE TITLE
Solr: small refactoring in the SolrIndexHandler java class

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1868]
- [x] We could rename:
commitBatchData -> addSolrDocuments
commitSolrClient -> commit

- [x] call optimize in a separate method (take it out from commitSolrClient)

- [x] add flag to disable solr optimize call. default behaviour executes optimize 

- [x] add log info to display optimize execution time

**Comment by danielabutano** [comment]
@arunans23 I can't close it yet.enableOptimize flag has to be set with the value of the property index.solroptimize in the keyword search property file (if it exists)

**Comment by arunans23** [comment]
sorry about that. didnt fully understand the requirement..
