### ISSUE TITLE
Gradle: undeploying after cleaning causes an error

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1872]
I am trying to undeploy from a different place than I deployed:

```
./gradlew cargoUnDeployRemote -Dorg.gradle.project.release=beta --stacktrace
```

And I get this error:

```
Caused by: java.lang.IllegalArgumentException: File '/SAN_synbiomine/code/flymine/flymine/webapp/build/libs/webapp.war' does not exist
```

**Comment by sammyjava** [comment]
This is an issue? Seems like expected and appropriate behavior to me. Can't delete a war from a place that you didn't put it.

**Comment by julie-sullivan** [comment]
you are right as always @sammyjava
