### ISSUE TITLE
Regions bug: trying to leave extended region field blank results in error message that takes over the page

### ISSUE THREAD

**Issue by nuin** [intermine/intermine#1881]
Here's a screen recording:

https://www.dropbox.com/s/mhlsvj8422dhszq/Regions_bug_Aug_20_2018.mov?dl=0

The issue is that if you accidentally erase the entry for field 4 (the "Extend your regions at both sides" field) and try to move away from the field, there is the error message:

![44365191-17233380-a497-11e8-87cf-e1dd9055b7c3](https://user-images.githubusercontent.com/6273/44613591-75c41680-a7e3-11e8-9be5-051373b2d3eb.png)

which will not go away once clicking on "OK" and will not allow entering a number in field 4, or any field for that matter. You basically need to close the window and start over because nothing is allowed while that error message is showing, and you can't get rid of it.

**Comment by julie-sullivan** [comment]
Here's the code: https://github.com/intermine/intermine/blob/release-candidate/bio/webapp/src/main/webapp/model/genomicRegionSearchOptionsExtentionNonLinearSlider.jsp#L111

**Comment by julie-sullivan** [comment]
@nuin @chris-grove Here is the fix: 96570cabf62d7ff330599e89a9b1b0520f8c6dee

The fix will be in the next InterMine release. Alternatively, you can just cherry-pick that update as it's just the one line.
