### ISSUE TITLE
ServiceFactory, Page, etc. have gone missing in v2

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1882]
Some webapp code of mine is now throwing runtime errors because it cannot find ServiceFactory, Page, etc. Sure enough it's missing in the v2 RC branch:
```
[shokin@shokin-mines intermine-sammyjava-rc]$ find -name ServiceFactory.java
[shokin@shokin-mines intermine-sammyjava-rc]$ 
```
Here's where it was in v1:
```
[shokin@shokin-mines intermine-v1]$ find -name ServiceFactory.java
./intermine/webservice/client/main/src/org/intermine/webservice/client/core/ServiceFactory.java
[shokin@shokin-mines intermine-v1]$ 
```
May we have it back, please? I use it here: https://github.com/LegumeFederation/legfed-webapp-model/blob/c88a2e7724f9efdfd352b740ccd403921173f846/genotypeJSON.jsp

@adf-ncgr

**Comment by sammyjava** [comment]
@julie-sullivan HELP? This prevents me from updating my mines.

**Comment by julie-sullivan** [comment]
Yes, I moved the Java client to its own repo [here](https://github.com/intermine/intermine-ws-java/blob/master/main/src/org/intermine/webservice/client/core/ServiceFactory.java)

As for putting `ServiceFactory.java` back, I am not sure it makes sense to have in the codebase anymore.

Just looking at your code, it's not clear -- why don't you just query the database directly? Instead of using the web services?

**Comment by sammyjava** [comment]
I wondered that myself. It's called dynamically via Ajax as you page through a DataTable to get more data. I'm not sure why I wrote it that way. I'll muck with it now that I know where stuff is.

**Comment by sammyjava** [comment]
When you say "just query the database directly" do you mean with a SQL command? Or "directly" via the data model? This is a standalone JSP that returns a JSON to the requester (which happens to be another JSP) based on the POST values. So I'm just writing a standalone JSP to query the mine. It doesn't get anything passed in from the system like a controller does.

**Comment by sammyjava** [comment]
Erm, given that the Java generated by the Query Builder also uses these classes and methods, I think I'll just figure out how to make them available to the webapp. For example
```
package soymine;

import java.io.IOException;
import java.io.PrintStream;
import java.util.Iterator;
import java.util.List;

import org.intermine.metadata.Model;
import org.intermine.pathquery.Constraints;
import org.intermine.pathquery.OrderDirection;
import org.intermine.pathquery.PathQuery;
import org.intermine.webservice.client.core.ServiceFactory;
import org.intermine.webservice.client.services.QueryService;

public class QueryClient
{
    private static final String ROOT = "http://shokin-webapps:50030/soymine/service";

    public static void main(String[] args) throws IOException {
        ServiceFactory factory = new ServiceFactory(ROOT);
        Model model = factory.getModel();
        PathQuery query = new PathQuery(model);

        // Select the output columns:
        query.addViews("GenotypingLine.primaryIdentifier",
                "GenotypingLine.mappingPopulation.primaryIdentifier");

        // Add orderby
        query.addOrderBy("GenotypingLine.primaryIdentifier", OrderDirection.ASC);

        // Filter the results with the following constraints:
        query.addConstraint(Constraints.eq("GenotypingLine.mappingPopulation.primaryIdentifier", "BARC_1059007"));

        QueryService service = factory.getQueryService();
        PrintStream out = System.out;
        String format = "%-47.47s | %-47.47s\n";
        out.printf(format, query.getView().toArray());
        Iterator<List<Object>> rows = service.getRowListIterator(query);
        while (rows.hasNext()) {
            out.printf(format, rows.next().toArray());
        }
        out.printf("%d rows\n", service.getCount(query));
    }

}
```

**Comment by julie-sullivan** [comment]
Would it be possible to add to the struts config so it does have a controller? Would that solve your problem?

**Comment by sammyjava** [comment]
I just copied the classes I need over to org.ncgr.intermine. :) I moved all my overriding classes to org.ncgr.intermine as well because I discovered that my local org.intermine classes under my mine were not overriding the core classes like they did in v1. (I only update them in the core if they're of general use, but I've got some LIS-specific hacks that are now in org.ncgr.intermine as they probably should be; but interesting that overriding the core classes under a mine no longer works.)
