### ISSUE TITLE
Incorrect message "No orthologues were found" (sometimes)

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#189]
Passing some sets of genes from FlyMine to metabolicMine through orthologues sometimes gives a message 'No orthologues were found' but then displays a table of genes which are valid orthologues.  It doesn't always do this though.  Here is an example list of genes for which this happened:

FBgn0012034
FBgn0030522
FBgn0030915
FBgn0039909
FBgn0039911
FBgn0039920
FBgn0261244

**Comment by julie-sullivan** [comment]
Works as expected with humanmine.
