### ISSUE TITLE
Gradle: need /themes directory to merge correctly

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1902]
@nauer had an issue with his CHOmine. On the new gradle branch, the `/themes` directory for his mine wasn't being merged into the main intermine one.

- [intermine/webapp/src/main/webapp/themes](https://github.com/intermine/intermine/tree/release-candidate/intermine/webapp/src/main/webapp/themes)

- [flymine/webapp/src/main/webapp](https://github.com/intermine/flymine/tree/master/webapp/src/main/webapp)

I _think_ @nauer's `/themes` directory in CHOmine was in the `/model` directory (so `chomine/webapp/src/main/webapp/model/themes`). When I tried this placement in FlyMine, it did fail to see CSS. When I moved `/themes` to in flymine to be next to `/model` (so `flymine/webapp/src/main/webapp/themes`), it worked fine.

How do I fix this for future people? I couldn't find any other mine with a `/themes` directory. Maybe it's as simple as updating the migration script to move `model/themes` to `themes`?

**Comment by yochannah** [comment]
Here's an example: wormmine: 

Config tells us it's using the wormmine theme: https://github.com/WormBase/intermine/blob/im-266/wormmine/webapp/resources/web.properties#L40

The theme itself: https://github.com/WormBase/intermine/tree/im-266/intermine/webapp/main/resources/webapp/themes/wormmine

Thalemine also

config: https://github.com/Arabidopsis-Information-Portal/intermine/blob/stable/thalemine/webapp/resources/web.properties#L173
theme: https://github.com/Arabidopsis-Information-Portal/intermine/tree/stable/intermine/webapp/main/resources/webapp/themes/araport

I think that at least one of the URGI mines (RepetDB) also uses the structure - it resembles thalemine and wormmine when I inspect the code in the browser - but I can't find the source code in github. 

so copying over the whole folder of themes, OR just the theme specified in properties, ought to be enough I think?

**Comment by julie-sullivan** [comment]
@sergiocontrino When you migrated thalemine, did you have issues with the custom theme?

**Comment by julie-sullivan** [comment]
@sergiocontrino Can you also verify the updated docs are correct: https://intermine.readthedocs.io/en/latest/webapp/layout/

Thank you!!

**Comment by nauer** [comment]
Found out that only the path in the docs is wrong. Change `webapp/src/main/webapp/model` to `webapp/src/main/webapp/themes` in https://intermine.readthedocs.io/en/latest/webapp/layout/

**Comment by julie-sullivan** [comment]
Thanks @nauer ! I've updated the docs.

I am going to close this ticket but @sergiocontrino if you could confirm this is correct that would be great.

**Comment by sergiocontrino** [comment]
@nuin tested this for wormbase.
