### ISSUE TITLE
WikiPathways data loader

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#191]
Create a data source to load data from wikipathways.

http://www.wikipathways.org/index.php/Download_Pathways

**Comment by julie-sullivan** [comment]
There does not seem to be any demand for this.

**Comment by julie-sullivan** [comment]
@rachellyne says they collaborate with Reactome so no need for a separate converter. http://nar.oxfordjournals.org/content/44/D1/D488.full

**Comment by rachellyne** [comment]
I think it might be that we will need to get pathway data from wikipathways instead - so we get all relevant reactome and all wikipathways.  They have many formats, but maybe GPML format is the best one to use?  Or the API?
