### ISSUE TITLE
Gradle:bio-sources examples not available in any public repo

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1913]
The bio source malaria-gff used by biotestmine, and the other 2 bio-sources under bio/sources/example-sources are not available in any public repo (only snapshots).
This wil not allow to buidlDB in biotestmine for instance.
To install locally I had to modify https://github.com/intermine/intermine/blob/dev/bio/sources/settings.gradle#L88 to uncomment out.
Also the file https://github.com/intermine/intermine/blob/dev/bio/sources/example-sources/malaria-gff/build.gradle needs some updates. We have to update the dependencies section with:
`bioModel group: 'org.intermine', name: 'bio-model', version: bioVersion, transitive: false //to read genomic_keyDefs.properties
compile group: 'org.intermine', name: 'intermine-integrate', version: imVersion
`
Not sure about the others 2, I haven't installed them locally

**Comment by julie-sullivan** [comment]
I didn't have any problem building locally. Maven downloaded the correct JAR.

```
The bio source malaria-gff used by biotestmine, and the other 2 bio-sources under 
bio/sources/example-sources are not available in any public repo (only snapshots).
```

This is fine because the [InterMine version](https://github.com/intermine/biotestmine/blob/master/gradle.properties) is set to be `2.0.+`. This is correct, and would download the correct JAR. Did you change your version?

**Comment by danielabutano** [comment]
Yes, you were right! I had 2.1.+ set in biotestmine. With 2.0.+ it works.
I have updated #1922 th eexample bio sources so they can be installed loaclly
