### ISSUE TITLE
SOLR: error when searching for test

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1920]
@arunans23 @danielabutano The search looks great!

However, if I search for "test", I get a NULL pointer exception. You can see yourself now on beta.flymine.org

```
java.lang.NullPointerException: object must not be null.at 
org.intermine.api.searchengine.KeywordSearchResultContainer.<init>
(KeywordSearchResultContainer.java:54)
at org.intermine.api.searchengine.solr.SolrKeywordSearchHandler.getSearchHits(
SolrKeywordSearchHandler.java:183) 
at org.intermine.api.searchengine.solr.SolrKeywordSearchHandler.doKeywordSearch(SolrKeywordSearchHandler.java:82)
at org.intermine.web.struts.KeywordSearchResultsController.execute(KeywordSearchResultsController.java:128)
```

It looks like that happens in the constructor. Is "test" hardcoded? I can't get anything else to fail! 

Are there other cases where the object might be null? Maybe we could handle that better, return an error but no results?

**Comment by julie-sullivan** [comment]
I am rebuilding the search index that beta uses. I am thinking this might be a user error, and I was using the wrong database.

**Comment by arunans23** [comment]
AFAIK, there is nothing hardcoded as "test" and I did not encounter this before. I am trying to test this with biotestmine, but my current builds are outdated, so they are throwing various errors. I'll try to run a working biotestmine instance and test this.

**Comment by julie-sullivan** [comment]
user error!!! everything is working fine. Apologies.

I was looking at the wrong database.
