### ISSUE TITLE
web-properties endpoint for FlyMine returns 500

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1927]
GET www.flymine.org/query/service/web-properties 500

returns

```
{"web-properties":
null,"executionTime":"2018.10.19 15:18::27","wasSuccessful":false,"error":"Service failed. Please contact support.","statusCode":500}
```

If I recall, last time this happened, a property was missing or not configured - probably [one of these](https://intermine.readthedocs.io/en/latest/webapp/blue-genes/). Since it's happened a few times before, would it make sense to implement defaults or some sort of graceful failure?

**Comment by julie-sullivan** [comment]
I fixed this on beta flymine, I haven't redeployed live flymine yet. let me know the priority because I hadn't planned to redeploy flymine.

Duplicate of #1878

**Comment by yochannah** [comment]
Whoops, I thought the fix had been deployed already and this was a regression. My mistake! It's definitely not urgent.

**Comment by yochannah** [comment]
Whoops, I thought this was a regression from a fix that had already been deployed - sorry, my mistake! It's definitely not urgent.

**Comment by yochannah** [comment]
Julie fixed this like magic :100: :1st_place_medal:
