### ISSUE TITLE
Store data licences for integrated sources

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1939]
- [ ] Add a new attribute in the model in order to store the licence supplied by the data source providers
```
<class name="DataSet" is-interface="true">
  <attribute name="license" type="java.lang.String" term="http://purl.org/dc/terms/license"/>
  ...
</class>
```

- [ ] the attribute licence should store the URI of the licence. Here some examples https://www.w3.org/TR/void/#license

- [ ] Update the bio-source parsers to set the licence value retrieving it from the data (if it is provided) or project.xml

**Comment by julie-sullivan** [comment]
Should we use an ontology for the licences? I guess not because there can be ad hoc licences?

**Comment by julie-sullivan** [comment]
The first URL I tried is broken - http://www.ebi.ac.uk/swo/license/SWO_1000080

**Comment by julie-sullivan** [comment]
- [ ] Add template to list all the datasets and licences on report page. Right now it's just showing the default view of data sets, and we don't want to add licence to the default data set.

**Comment by julie-sullivan** [comment]
The licence will need to come from the data parser. If there is no data parser, e.g. GFF etc, then the licence can come from the project XML file.

**Comment by julie-sullivan** [comment]
This is going to be a branch of the `fair-obo` branch to use the new `term` feature.

**Comment by julie-sullivan** [comment]
Is there a case where the data loaded by InterMine for a single data set has different licences? Need to investigate.

**Comment by danielabutano** [comment]
> Should we use an ontology for the licences? I guess not because there can be ad hoc licences?

We use the term licence defined in the dublin core ontology as shown in ticet description 
we might think to use VOID ontology to describe other properties of InterMine datasets, but this is another discussion

**Comment by julie-sullivan** [comment]
@rachellyne @danielabutano Ontologies don't have a datasets collection. Should I add?

Actually, what would be best if I updated "Annotatable" class to have a dataset collection. That would make more sense. I could actually do this in the 3.1.0 release with the other model changes. Thoughts?

**Comment by julie-sullivan** [comment]
http://www.obofoundry.org/ Ontologies do have licences. But what would be the use of having an ontology with a restrictive licence? Is this interesting information? Maybe it's only the annotations we are interested in?

**Comment by julie-sullivan** [comment]
These are my findings so far. Each data set has one of the following:

1. a licence, e.g. Apache 2.0, e.g. https://opensource.org/licenses/MIT
2. a "fair use" page describing how data can be used, e.g. [https://www.ncbi.nlm.nih.gov/home/about/policies](https://www.ncbi.nlm.nih.gov/home/about/policies/)
3. "fair use" described somewhere on the website, e.g. http://www.ebi.ac.uk/interpro/user_manual.html#faqs_11
4. Data set has no licence information.

For options 2 and 3, there is the danger of the URL changing.

**Comment by julie-sullivan** [comment]
```
 description |               licence               |   id    | url |             name             | version | datasourceid | publicationid |              class              
-------------+-------------------------------------+---------+-----+------------------------------+---------+--------------+---------------+---------------------------------
             | https://opensource.org/licenses/MIT | 1000003 |     | BioGRID interaction data set |         |      1000002 |               | org.intermine.model.bio.DataSet
(1 row)

```
