### ISSUE TITLE
Add way to define my very favourite bag type for a mine

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1958]
Referencing the protein issue in this comment: https://github.com/intermine/bluegenes/pull/278#issuecomment-441027803 

In order to get preferred types for lists etc. (think like the two top emboldened classes in the querybuilder) we have to search the json model for a preferredbagtype tag. Given that json objects have no defined order, there's no way to assert which of these should be first in the list. 

I've worked around the issue in BlueGenes by sorting alphabetically, which brings gene to the top - but this is a hack that works by happenstance. If Allele was a preferredbagtype it would come first in the list.

**Comment by julie-sullivan** [comment]
>  If Allele was a preferredbagtype it would come first in the list.

That's correct behaviour.

**Comment by yochannah** [comment]
it might be _nice_ to allow admins to define a preferred default though, no?

**Comment by julie-sullivan** [comment]
They do specify their preferred defaults. I don't see the utility is having a preferred-preferred default.

What would you suggest? This is currently done by tags so we'd have to come up with a new mechanism I think.

**Comment by yochannah** [comment]
we have a web properties endpoint - it'd just need another single key/value property. defaultObjectType or something.

**Comment by julie-sullivan** [comment]
So get rid of the current mechanism? (Which is using tags.) Mixing tags and params is a Bad Idea. 

* In general, no one has asked for this feature so it feels like we are making work for ourselves. 
* The list of preferred types is very short so the human eye can read all of them at once.
* The rest of the list is in alpha order, to change this is confusing.

**Comment by julie-sullivan** [comment]
> we have a web properties endpoint it'd just need another single key/value property. defaultObjectType or something.


preferredBags is set by tags not web properties.

It might not make sense to people to tag classes as favourite, then go add classes to the web properties for favourite favourite. Do you agree? That's how bugs happen.

So let's hold off on this, and have a conversation about why some things are done by tags and some by properties. Maybe we can refactor to be more consistent!

**Comment by yochannah** [comment]
absolutely. 

The consistency might be nice - having to iterate through the entire model to get 1-2 preferred bag types is a bit of a pain, and many other properties come through the web properties instead. If we ended up putting the preferredbagtype into web properties, we could even have it stored in an ordered collection (i.e. an array in json).
