### ISSUE TITLE
Add Protein Atlas RNA Gene data

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1964]
The data is very simple:

/micklem/data/metabolic/protein-atlas/RNA-seq/version_18.1

Ensembl Gene ID

Gene symbol

Tissue

Value

Type = TPM

(although I can't unzip it on met1 and the unzipped one I copied across has the wrong permissions!  I can't log into Weasel as rcl30, I think Ian has re-named my computer.  I will try and sort out these issues).

The data will fit straight into the RNA-seq model in humanMine.

Dataset =  Protein Atlas RNA Gene data

(btw - we have an expression type as TMP.  This should be TPM).

**Comment by julie-sullivan** [comment]
1. I've fixed the permissions on that file
2. `(btw - we have an expression type as TMP. This should be TPM).` - Can you be more specific?
3. How do these data map to our model?

I see gene and tissue, where do put value and type? [
    Gene    Protein tissue Localisation](http://www.humanmine.org/humanmine/template.do?name=Gene_proteinAtlasExpression2&scope=all) I only see reliability and level.

**Comment by rachellyne** [comment]
2. btw - we have an expression type as TMP. This should be TPM).` - Can you be more specific? - the RNA_seq data we have loaded in humanMine currently comes from GTex.  The type should be TPM but it says TMP.  Even better TPM (transcripts per million).

3. This is RNA-seq data not protein localisation data - it should fit straight into the RNA-seq data model.  We currently have GTEx RNA-seq loaded too.

**Comment by julie-sullivan** [comment]
```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.rnaSeqResults.tissue Gene.rnaSeqResults.expressionType Gene.rnaSeqResults.expressionScore" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.rnaSeqResults.dataSets.name" op="=" value="Protein Atlas RNA Gene data"/>
</query>

```

Data is present, and looks correct (I only checked one gene)

**Comment by julie-sullivan** [comment]
@rachellyne please reopen if there are data issues!
