### ISSUE TITLE
Not releasing connections during data loading

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1973]
The integrate gradle task does not close the hikari connection properly!!
If we run:
 `./gradlew integrate`
every time we load a new source, we open ~20 new connections without releasing/close the others.
At some point there is the error:
Failed to create a Non-Pooling DataSource from PostgreSQL JDBC Driver 42.2.2 for postgres at jdbc:postgresql://localhost/items-biotestmine?loginTimeout=30: org.postgresql.util.PSQLException: FATAL: sorry, too many clients already

See also https://github.com/intermine/intermine/issues/1894

**Comment by danielabutano** [comment]
Thank @JoeCarlson to raise the issue and for the fix proposed

**Comment by JoeCarlson** [comment]
Here is a list of tasks that I've seen (so far) that need to have the HikariDataSource closed:
intermine/integrate/src/main/java/org/intermine/dataloader/ObjectStoreDataLoaderTask.java
intermine/integrate/src/main/java/org/intermine/task/DirectDataLoaderTask.java
intermine/integrate/src/main/java/org/intermine/task/DirectoryConverterTask.java
intermine/objectstore/src/main/java/org/intermine/task/AnalyseDbTask.java
intermine/objectstore/src/main/java/org/intermine/task/BuildDbTask.java
intermine/objectstore/src/main/java/org/intermine/task/CreateIndexesTask.java

AnalyseDbTask, BuildDbTask and CreateIndexesTask just need a database.shutdown() added. DirectDataLoaderTask and DirectoryConverterTask need a ((ObjectStoreInterMineImpl)(<writer>.getObjectStore())).getDatabase().shutdown().

I don't know how to deal with ObjectStoreDataLoaderTask. It has connections to both the items and production db. The connection to the production db can be closed with the cast to ObjectStoreInterMineImpl and then getDatabase().shutdown(). But I don't know how to shut the items database. I get a "can't do that" exception when I try to cast the Translating ObjectStore into a ObjectStoreInterMineImpl. Anyone know how to get the database for the source?

I suspect there may be other tasks that need to be touched.
