### ISSUE TITLE
Template ranks returned as string, not int

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1976]
Template ranks are returned as strings, which makes it harder to sort them than if they were true ints. We noticed this when we tried to sort them in BlueGenes: 

https://github.com/intermine/bluegenes/pull/310 

There are "unranked" templates which might be why it's returning strings. Returning those as nulls or 0 should be fine. null makes a little bit more sense of the two options.

This is massively non-urgent.

**Comment by julie-sullivan** [comment]
Which end point are you using? I can't see in the original ticket.

**Comment by julie-sullivan** [comment]
not sure it's possible. See [ApiTemplate.java](https://github.com/intermine/intermine/blob/dev/intermine/api/src/main/java/org/intermine/api/template/ApiTemplate.java#L199)

```
            if (templateRank == null) {
                // null value for new templates. PathQuery.formatKVPair() doesn't accept anything
                // but strings. Yo and Josh say to do this.
                return "unranked";
            }
```

**Comment by yochannah** [comment]
This endpoint: http://beta.flymine.org/beta/service/templates?format=json

**Comment by julie-sullivan** [comment]
so i don't think it's possible to do this. See this:

```
            if (templateRank == null) {
                // null value for new templates. PathQuery.formatKVPair() doesn't accept anything
                // but strings. Yo and Josh say to do this.
                return "unranked";
            }
```

We have it set up to only handle strings for some reason.
