### ISSUE TITLE
publication with null title in humanmine - possibly due to a dot in the title? 

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1977]
In HumanMine, the publication with [pubmed id 24501781](http://www.humanmine.org/humanmine/portal.do?class=Publication&externalids=24501781) has no title in InterMine, but it [does have a title on PubMed](https://www.ncbi.nlm.nih.gov/pubmed/24501781?dopt=Abstract). Given that the title is `Leukodystrophy Overview.` I'm assuming the dot in the title made things angry, perhaps? 

It looks particularly odd in this list: http://www.humanmine.org/humanmine/bagDetails.do?scope=all&bagName=PL_GenomicsEngland_GenePanel%3AAdult_solid_tumours_for_rare_disease as the top enriched publication is called "null". I originally thought the enrichment might be faulty, enriching on a null item, and a naive user still might think this is the case.

**Comment by julie-sullivan** [comment]
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?tool=flymine&db=pubmed&rettype=abstract&retmode=xml&id=24501781

Maybe because it's a `BookDocument`?

**Comment by julie-sullivan** [comment]
The summary is fine: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?tool=flymine&db=pubmed&id=24501781

**Comment by julie-sullivan** [comment]
@rachellyne Can you take a look at this. How should we handle?

* has lots of abstracts
* title of book is `GeneReviews`
* has two author list. one for editors and one for authors.

Just take first abstract? That would be the quick but wrong way.

**Comment by rachellyne** [comment]
Looks like there is one abstract but subdivided - we should add all sections if possible.  Title should be title of the section "Leukodystrophy Overview" not the book title (unless put "Leukodystrophy overview in GeneReviews".  Author list should be the authors not the editors.  We could think about adding some extra fields for editors and book title if we have a few of these.

**Comment by julie-sullivan** [comment]
Fixed. I'll double check in the next full build too.
