### ISSUE TITLE
Check if lists created overlap with other public lists (and user's lists)

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1978]
Jaccard Index is defined as the size of the intersection divided by the size of the union of two sets. 

https://commons.apache.org/proper/commons-text/apidocs/org/apache/commons/text/similarity/JaccardSimilarity.html

https://gist.github.com/tpeng/3496464 - A simple minhash implementation in Java.  

From Gos

```
>>
>> I've probably mentioned it, but we ought to be flagging up list overlaps (public with own,
>> own with public, own with own) to InterMine users:
>>
>>  - one is unexpected overlap in the sense that we have enrichment currently
>>  - another would be the Jaccard Index, which is easy to calculate:
>>        https://en.wikipedia.org/wiki/Jaccard_index
>
> And here is a super-cute sampling/hashing trick to estimate the Jaccard Index:
>       https://en.wikipedia.org/wiki/MinHash

The point about this is that once can sample each list extremely rapidly and only bother
to calculate overlap properly if the user subsequently clicks for more information.

```

From @AdrianBZG, some other algorithms to consider:

* TF-IDF + cosine distance
* levenstein similarity

**Comment by julie-sullivan** [comment]
Neo4j has a nice library

https://neo4j.com/docs/graph-algorithms/current/algorithms/similarity-jaccard/

```
7.1.2. Use-cases - when to use the Jaccard Similarity algorithm

We can use the Jaccard Similarity algorithm to work out the similarity between two things. We might then use the computed similarity as part of a recommendation query. For example, you can use the Jaccard Similarity algorithm to show the products that were purchased by similar customers, in terms of previous products purchased. 
```

**Comment by julie-sullivan** [comment]
@yochannah Can you tell me what you want the end point to look like? `/lists/jaccard-index` 

What would be the inputs? 

```
username
list name
```

And we compare that list with all the public lists, plus the lists the user owns.

Maybe a parameter to check against `public` only or `private` only. Is that even a use case?

**Comment by yochannah** [comment]
right so assuming this is a tool api-based tool: 

1. The user is logged in, OR has a temp session list. 
2. When the tool loads, it calls GET `lists/jaccard-index`
  - params: 
      - `token` (optional, could be anon user with temp list)
      - ONE OF: 
        - `list` The name of the list to investigate, optional unless identifiers is NULL.
        - `ids` Comma-separated list of InterMine object IDs, optional unless list name is NULL.
      - format: (`json` | `XML`) 
  - response something like: 
```json
{
  "input_ids": [123, 456, 789, 666, 489, 456, 423, 741, 852, 963, 753, 444, 555, 333, 369, 321], 
   // ^-- list name should be here instead if that was the input you received. 
  "results": [{
      "public_list_name": "some_gross_fly_science_word",
      "intersection_count": 12,
      "jaccard_index": 0.5
    },
    {
      "public_list_name": "less_gross_list",
      "intersection_count": 5,
      "jaccard_index": 0.25
    },
    {
      "public_list_name": "third_list",
      "intersection_count": 1,
      "jaccard_index": 0.01
    }
  ]
}
```

Some other points to ponder:

1) does this have a place on the list-of-lists page? (I think no, too much info to convey about the overlaps to fit in here). So only on a list analysis page.
2) maybe we don't want the "intersection_count" if that doesn't work with minhash. That's fine I guess. 
3) maybe we DO want to have a min_jaccard value to optionally not return items under a certain threshold?
4) I don't know why i used this_case and not camelCase. I think maybe it _should_ be camelcase?
5) is there a scenario where we want to pass two listnames and get the response just for those two lists? is there anything here that we wouldn't get from a simple intersection of those two lists?

**Comment by julie-sullivan** [comment]
Thanks! That helped! :)

```
    {
      "public_list_name": "third_list",
      "intersection_count": 1,
      "jaccard_index": 0.01
    }
```

1. That looks like you want a parameter name for `public_list_name` and then another one for `private_list_name`
2. No I don't have an intersection count. I suppose that might negate the speed I get from the minhash. What do you want to do? You sounded reluctant on your comment. We could have an extra parameter that would not use the minhash or not. (by default use it). Thoughts?

**Comment by yochannah** [comment]
1. re 1. where do you mean?
2. re intersections yeah, that was my thinking too - the neo4j examples shows overlap count as an item but I figured it might not be what we want with minhash. Param sounds like a better option. 
3. I realised I made a mistake - we might want to rename one of the params: 

```json
    {
      "overlapping_list_name": "third_list",
      "intersection_count": 1,
      "jaccard_index": 0.01
    }
```

that way we could detect overlaps with your own personal lists too and still have the param name be correct?

**Comment by julie-sullivan** [comment]
Accepts: `list` (string), `min` (float). Later I will add `ids` and `type`.

Here are the results

```
{
   "results": [
      {
         "list1": "0.2",
         "ribosomal protein": "1.0",
         "transferase": "1.0"
      }
   ],
   "executionTime": "2019.02.28 10:20::09",
   "wasSuccessful": true,
   "error": null,
   "statusCode": 200
}
```

Needs a code review. Does it ever!

**Comment by julie-sullivan** [comment]
This is where the math is btw:

https://github.com/intermine/intermine/blob/fair/intermine/webapp/src/main/java/org/intermine/webservice/server/lists/JaccardIndexService.java#L130
