### ISSUE TITLE
Need upgrade path for biojava

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1982]
@sergiocontrino We need docs as to how to upgrade to the newest BioJava library.

We did mousemine manually, but others have FASTA sources too:

https://github.com/ywchoi/medicmine-bio-sources/tree/upgrade-3.1/medicago-fasta/src/main/java/org/intermine/bio/dataconversion

Can you write up a doc for how to upgrade? And help @ywchoi upgrade?

**Comment by sergiocontrino** [comment]
i started a document [here](https://github.com/sergiocontrino/intermine/wiki/BioJava-Upgrade-notes.) 
i'll do some more checking and editing. 
@ywchoi please let me know if not useful/unclear/issues you are discovering and i'll try to help and to improve the doc. thanks!

**Comment by julie-sullivan** [comment]
Fixed now I think!
