### ISSUE TITLE
Set converter.class in the right place

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1984]
The converter.class property has to be set in the <bio-source-name>.properties file, e.g. chado-db.properties file and not in the project.xml, as it happens in https://github.com/intermine/flymine/blob/master/project.xml#L22

**Comment by julie-sullivan** [comment]
Fixed by https://github.com/intermine/flymine/commit/7aa08cb81f5047d52ea977632e5a2fdc8f2463fc#diff-c0a33b20a5bf94bd7bd5c012bf96f702
