### ISSUE TITLE
Panther - Entry only has protein accession and the taxon id in place of the gene identifier.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1995]
Adrian got a merging bug with biogrid and panther. no attributes except type = homologue?

**Comment by AdrianBZG** [comment]
Take a look at this line in panther data file:

HUMAN|HGNC=5834|UniProtKB=P06312	MOUSE|Gene=10090|UniProtKB=P01634	OEuarchontoglires	PTHR23267
