### ISSUE TITLE
Gretty plugin - remove from bio-webapp?

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2007]
GitHub changed their URL and caused the HumanMine build to fail. These seems fragile to me. See #2006 

Does it need to be in bio-webapp? I would prefer it be in the mine webapp file ONLY.

**Comment by sammyjava** [comment]
It's very fragile. Why are we using some dude's Github repo in our application? Should be on a CDN or something at least. Although this one was Github changing the URL for raw file downloads, nothing to do with the dude.
