### ISSUE TITLE
FASTA query result: CDS translation option

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#2015]
Would it be possible to add an option that does the protein translation on a CDS sequence?
My simple minded idea is to add a simple boolean parameter, translateCds (or something)
If true, and the view path's class is CDS, then the server would do the amino acid translation before returning the sequences.

Thanks!

**Comment by julie-sullivan** [comment]
That sounds straightforward. I bet our biojava library would do this for us. (haven't looked).

**Comment by sergiocontrino** [comment]
implemented without phase for the moment (can be added when we store it).
also: extension is not considered if translation is required.
