### ISSUE TITLE
Fasta query results: extra view parameters not showing up in header correctly

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#2016]
My question/issue is about adding multiple fields to the FASTA header lines.
I can add one field ok. But if I add another, only one of them makes it into the header.
Example: I want to add both the gene's symbol and name, but only name makes it in.

Here's my query, which returns the genomic sequence for Pax6 for strain A/J.
```
<query  model="genomic" view="Gene.id">
    <constraint path="Gene.canonical.primaryIdentifier" op="=" value="MGI:97490"/>
    <constraint path="Gene.strain.name" op="=" value="A/J"/>
</query>
```
I'm using the IOdocs interface. I leave Gene.length as a view column and then add Gene.canonical.symbol and Gene.canonical.name as additional view paths. The result only contains the name.

Thanks.

**Comment by julie-sullivan** [comment]
Yes, I can replicate! That's a bug. Hopefully easy to fix. (famous last words)

Are the pathquery views being updated correct? [FastaQueryService.java#L57](https://github.com/intermine/intermine/blob/dev/bio/webapp/src/main/java/org/intermine/bio/webservice/FastaQueryService.java#L57)

**Comment by danielabutano** [comment]
The issues has not completely fixed.
If I want to add an additional column in the view, I can modify the attribute view in the query and it works (it didn't before).
But the view parameter still does NOT work
