### ISSUE TITLE
add gradle task for automatically detect system proxy config

### ISSUE THREAD

**Issue by CodHeK** [intermine/intermine#2031]
@julie-sullivan  While setting up the `testmine` I faced a lot of problems making it work under a proxy ... I have solved this issue, I can send a PR if this seems like a significant contribution ! :D 

The PR would just a task in the `build.gradle` file in `testmine` folder that'll automatically fetch system proxy and configure for the build to work!

**Comment by julie-sullivan** [comment]
Yes please! :)

**Comment by julie-sullivan** [comment]
@CodHeK I am going to close this issue for now, as I am not sure what your issue is. 

But we'd be happy to see a pull request! If you had a problem it's likely others have too. :)
