### ISSUE TITLE
testmine server doesn't exit gracefully

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#2032]
Issue: 

In order to exit the testmine server I need to do the following things:

1. Press CTRL+C
2. type `./gradlew tomcatStop`

Normally I would expect one or the other to be required, but not both. If you just do 1) the process initially appears to exit but the server keeps on running, and if you only run 2) the terminal is never freed up for additional commands. 

Steps to reproduce:

1. clone intermine and make sure you have your testmodel.properties set up with the correct postgres user.
2. cd into /testmine and run ./setup.sh. This will set the hard-to-stop tomcat running if the build completes successfully.

**Comment by julie-sullivan** [comment]
@yochannah this worked for me, it's worked for me since we moved to gradle. maybe you can show me what's going on?

**Comment by julie-sullivan** [comment]
the script is working as expected. I think you had an instance of tomcat running already when you had your troubles.

Please re-open this ticket if that's not the case.

**Comment by yochannah** [comment]
This persists even after I have moved to a new user profile, and after a fresh reboot. Here's an example screenshot - I pressed CTRL+C and the script still doesn't exit: 

![image](https://user-images.githubusercontent.com/9271438/58268171-dab19a80-7d7c-11e9-9bb0-0a034dbee9b3.png)

**Comment by julie-sullivan** [comment]
@yochannah This was a design decision by us to do things this way.

option 1

send the console output to dev/null
only require single `./gradlew tomcatStop` command

option 2

CTRL + C (or use another console)
`./gradlew tomcatStop`

We chose option 2. If there is another option let me know but this was on purpose.

**Comment by yochannah** [comment]
lol - I wouldn't have re-opened the issue if I'd known that.
