### ISSUE TITLE
set preferredbagtype in web properties

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#2035]
Right now the only way to set preferred bag types is by annotating the model with tags. Rather than implementing a model annotater for this small feature, it might be nicer to simply use our config to return a preferredBagType ordered comma separated list, e.g.

```
preferredBagType=Protein,Gene
```

See https://github.com/intermine/intermine/issues/1958 for previous discussion.

**Comment by danielabutano** [comment]
current solution is fine
