### ISSUE TITLE
Can we remove flymine dependencies from core IM?

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#2040]
I'm working with FASTA and GFF files now, and it turns out that we should be able to associate a Strain with a Protein, which is a BioEntity, not a SequenceFeature. (I had explicitly created Protein.strain in my LegFed loaders, which should have been a hint). We have Strain as a BioEntity, which sounds normal but the extra fields in BioEntity are unlikely to be used by Strain, which is mostly a label.

So I updated the core model to have Strain as Annotatable and added the strain reference to BioEntity (and update corresponding reverse references) and removed it from SequenceFeature (since it's already in BioEntity).

But then when I rebuild IM, I find that a bunch of stuff still has Strain as a BioEntity! And it's inconsistent. (I'm working on the fasta loader, so this had to be figured out and fixed). I've now fixed the fasta source, but some remain. (And I had to force bioVersion=3.1.2 to get the new Strain, but that makes sense since I updated 3.1.2 locally and 3.1.+ was pulling an older version of the model.)
```
[shokin@shokin-mines bio]$ grep -R name=\"Strain\" | grep Annotatable
model/core.xml:  <class name="Strain" extends="Annotatable" is-interface="true">
postprocess/create-attribute-indexes/build/resources/main/genomic_model.xml:<class name="Strain" extends="Annotatable" is-interface="true">
postprocess/create-autocomplete-index/build/resources/main/genomic_model.xml:<class name="Strain" extends="Annotatable" is-interface="true">
... other postprocess ...
sources/biogrid/build/resources/main/genomic_model.xml:<class name="Strain" extends="Annotatable" is-interface="true">
sources/chado-db/build/resources/main/genomic_model.xml:<class name="Strain" extends="Annotatable" is-interface="true">
... other sources ...
```
```
[shokin@shokin-mines bio]$ grep -R name=\"Strain\" | grep BioEntity
postprocess/create-chromosome-locations/build/resources/main/genomic_model.xml:<class name="Strain" extends="BioEntity" is-interface="true">
postprocess/create-gene-flanking-features/build/resources/main/genomic_model.xml:<class name="Strain" extends="BioEntity" is-interface="true">
postprocess/create-intron-features/build/resources/main/genomic_model.xml:<class name="Strain" extends="BioEntity" is-interface="true">
postprocess/create-references/build/resources/main/genomic_model.xml:<class name="Strain" extends="BioEntity" is-interface="true">
postprocess/make-spanning-locations/build/resources/main/genomic_model.xml:<class name="Strain" extends="BioEntity" is-interface="true">
postprocess/transfer-sequences/build/resources/main/genomic_model.xml:<class name="Strain" extends="BioEntity" is-interface="true">
[shokin@shokin-mines bio]$ 
```
WTF? Well it turns out those post-processors (and, formerly, the fasta source) use the FLYMINE model, not the current IM model that you think you're specifying in gradle.properites:
```
[shokin@shokin-mines bio]$ cat postprocess/create-chromosome-locations/build.gradle 
...
dependencies {
    bioModel group: "org.intermine", name: "bio-source-flymine-static", version: System.getProperty("flymineVersion"), transitive: false
    compile group: 'org.intermine', name: 'intermine-integrate', version: imVersion
    compile group: "org.intermine", name: "bio-source-flymine-static", version: System.getProperty("flymineVersion"), transitive: false
}
...
```
You probably know about all this, but it's a Bad Thing in my opinion, especially now because we're tweaking the core data model and we shouldn't have to tweak it in flymine at the same time.

I'd like to submit a pull request on my Strain (and sources/fasta) update, which doesn't break any existing code since it simply puts the strain reference higher up the chain, but I'd like to see flymine dependencies removed beforehand in case further sources and postprocessors need to use the latest version of Strain.

**Comment by julie-sullivan** [comment]
Yes it is a bad thing!! It was a "temporary" hack (ha) until I could figure out how to get these classes in a bio model.

**Comment by julie-sullivan** [comment]
@sammyjava Can you test that works for you? Thanks!!!

**Comment by sammyjava** [comment]
You mean the changes I've made? I've also been tweaking the data model slightly (strains related) so it's not a standalone no-flymine situation any more on my branch. Although I could cook a branch which has only the flymine dependencies removed, I guess.

**Comment by julie-sullivan** [comment]
So removing the flymine dependencies is all you needed? I am glad my hack isn't a blocking issue for you! :)

I am working out how to get the tests to pass now (without the flymine dependency). I think I am going to have each postprocess be able to specify its own model -- just like bio/sources do. Not sure though!

**Comment by sammyjava** [comment]
Yeah, I just replaced all the flymine-static stuff with the normal name: 'bio-model', version: bioVersion in the build.gradles. I just committed my current state so you can see.
https://github.com/sammyjava/intermine/commit/571a78cf5c48679d50abcaa33ca673d2bf20e413
