### ISSUE TITLE
DataSet URLs do not appear in tables; do show in report heading

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#2045]
This may be related to #2018 but I think it's separate. See attached screenshots from FlyMine. DataSet URLs show as blanks (as opposed to "NO VALUE") in tables, while the URL does exist and appears in the heading of a DataSet report page. I've looked into it a bit and I'm baffled.

![Screenshot_2019-05-24 FlyMine Query results page](https://user-images.githubusercontent.com/5657219/58343193-9c18f000-7e0f-11e9-972e-f5736dc07147.png)

![Screenshot_2019-05-24 FlyMine DataSet Affymetrix array GeneChip Drosophila Genome 2 0 Array](https://user-images.githubusercontent.com/5657219/58343233-b783fb00-7e0f-11e9-9f51-79a2359404b4.png)

**Comment by julie-sullivan** [comment]
Here's the ticket: https://github.com/intermine/im-tables/issues/170

It had been fixed but then popped up again!
