### ISSUE TITLE
Error with region search

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#2048]
Paulo from wormMine pointed out the following problem with the region search:

https://www.dropbox.com/s/mhlsvj8422dhszq/Regions_bug_Aug_20_2018.mov?dl=0
<https://www.dropbox.com/s/mhlsvj8422dhszq/Regions_bug_Aug_20_2018.mov?dl=0>

I couldn't reproduce this with HumanMine or FlyMine - instead the error box disappears and the value is reset to 0, but then you get an error when you try to run the search.

**Comment by rachellyne** [comment]
Also - I got different behaviour using Chrome and Firefox. With firefox the error box had a checkbox that allowed the error to be dismissed.

**Comment by yochannah** [comment]
We actually fixed this last year - https://github.com/intermine/intermine/issues/1881 

What is the new error?

**Comment by yochannah** [comment]
Okay, so as mentioned earlier, #1881 fixes the original error.

To reproduce Rachel's new error: 

1. Delete the value from the textbox beside the range slider
2. Dismiss the alert box that comes up.
3. Click "search" _without_ modifying the text box or clicking on it in any way.

I can't test the fix right now, but I suspect that adding this line:

```javascript
jQuery("#${sliderIdentifier} input[type='text']").focus();
```

or maybe this line instead

```javascript
jQuery("#${sliderIdentifier} input[type='text']").focus();
```

right after this line: https://github.com/intermine/intermine/commit/96570cabf62d7ff330599e89a9b1b0520f8c6dee#diff-afad1a7a1e854a32b17fdd4f21bc1f97R112

would fix it.

**Comment by yochannah** [comment]
Tell @nuin about this.

**Comment by danielabutano** [comment]
Not relevant to the new interface
