### ISSUE TITLE
LOOP query in webapp does not work!

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine#2053]
a user send this via email to support:

For example, I tried the following query in FlyMine:

```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.interactions.participant2.primaryIdentifier Gene.interactions.participant2.symbol Gene.interactions.participant2.interactions.participant2.primaryIdentifier Gene.interactions.participant2.interactions.participant2.symbol" longDescription="For a specified gene, show physical and genetic interaction partners.  Optionally constrain to show just physical or genetic interactions or interactions determined by a specific method." sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and B">
  <constraint path="Gene" code="A" op="LOOKUP" value="notch" extraValue="D. melanogaster"/>
  <constraint path="Gene" code="B" op="!=" loopPath="Gene.interactions.participant2.interactions.participant2"/>
</query>
```

And I got the following error message:
XML is not well formatted. Got 
`<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.interactions.participant2.primaryIdentifier Gene.interactions.participant2.symbol Gene.interactions.participant2.interactions.participant2.primaryIdentifier Gene.interactions.participant2.interactions.participant2.symbol" sortOrder="Gene.primaryIdentifier ASC" constraintLogic="A and B" ><constraint path="Gene" op="LOOKUP" value="notch" extraValue="D. melanogaster" code="A" /><constraint path="Gene" op="!=" code="B" /></query>.
`

I guess the loop constraint was not processed correctly and it was truncated.

**Comment by sergiocontrino** [comment]
the loop constraint is not passed to the server, but is created in the query builder.

with what i think is the query of our docs:
query in webapp error message:

```
<query model="genomic" 
view="Gene.symbol Gene.primaryIdentifier Gene.organism.name Gene.homologues.homologue.symbol Gene.homologues.homologue.primaryIdentifier Gene.pathways.genes.symbol Gene.pathways.genes.primaryIdentifier" sortOrder="Gene.symbol ASC">
<constraint path="Gene.homologues.homologue" op="=" code="A" /></query>.

```
but query builder export

```
<query name="" model="genomic" 
view="Gene.symbol Gene.primaryIdentifier Gene.organism.name Gene.homologues.homologue.symbol Gene.homologues.homologue.primaryIdentifier Gene.pathways.genes.symbol Gene.pathways.genes.primaryIdentifier" sortOrder="Gene.symbol asc">
<constraint path="Gene.homologues.homologue" op="=" loopPath="Gene.pathways.genes"/>
</query>

```

**Comment by julie-sullivan** [comment]
When I try to import that query with a loop constraint, I get:

```
Import of query(ies) failed. Invalid format of query: "null"
```

**Comment by julie-sullivan** [comment]
When someone (doesn't matter who) added JSON queries, they updated the syntax of the loop queries, i think this is where the problem started:
https://github.com/intermine/intermine/commit/f93bda9a8731290878efed637fada7f47e5149e7#diff-0d762552042f052bfb56ff88bb9bf069

**Comment by julie-sullivan** [comment]
Looking at the code in `ExportQueryAction.java` that works:

```
    private String getQueryXML(String name, PathQuery query) {
        String modelName = query.getModel().getName();
        return PathQueryBinding.marshal(query, (name != null ? name : ""), modelName,
                PathQuery.USERPROFILE_VERSION);
    }
```
This exports the query with `loopPath` intact. Used in export in myMine, template form and query builder.

This is the code that fails to populate `loopPath`:

```
# in PathQuery.toXML()
PathQueryBinding.marshal(this, "query", model.getName(), writer, version);
```

`PathQuery.toXML()` is used when queries are imported or executed (in the case of saved queries)

**Comment by julie-sullivan** [comment]
Anyway, both the export and import look like they use the same xml binding code, so why are they acting different?

**Comment by julie-sullivan** [comment]
```
<query name="" model="genomic" view="Gene.symbol Gene.homologues.homologue.symbol" longDescription="" sortOrder="Gene.symbol asc">
  <constraint path="Gene" op="=" loopPath="Gene.homologues.homologue"/>
</query>
```

**Comment by julie-sullivan** [comment]
Running that query in iodocs works, running that query in the webapp does not.

**Comment by julie-sullivan** [comment]
This looks like a problem with `imjs`, not with the query code. @yochannah can you comment?

**Comment by yochannah** [comment]
I'm about 80% confident it's imjs, and it's on the roadmap to be done reasonably soon! :)
