### ISSUE TITLE
Put galaxy URL in global properties

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2055]
We have this in humanmine and flymine:

`galaxy.baseurl.default = https://usegalaxy.org`

Is there a reason NOT to put this in global.web.properties?

**Comment by julie-sullivan** [comment]
Galaxy has a disabled option:

```
## set to "false" to disable galaxy
galaxy.display = true
```

So this change seems safe.

**Comment by julie-sullivan** [comment]
```
galaxy.url.value = /tool_runner?tool_id=flymine
```
Each of the mines need to configure their own tool, so maybe let's wait on this change. No point. I don't think the URL is going to change again anyway!

**Comment by danielabutano** [comment]
@julie-sullivan we have the update the new tool_id with intermine
`galaxy.url.value = /tool_runner?tool_id=intermine`
