### ISSUE TITLE
GO enrichment widget - accessed via webservice

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#206]
Would it possible to retrieve the gene names that correspond to the number in the last column "Matches" when the widget is accessed via webservices?

**Comment by julie-sullivan** [comment]
@kkarra Is this still something you need?

Here's what the results look like now:

```
{"p-value":5.456186947436579E-4,"matches":10,"description":"Wnt signaling pathway","identifier":"GO:0016055"},
{"p-value":6.705601105154937E-4,"matches":13,"description":"cell adhesion","identifier":"GO:0007155"},
```

You are saying that in addition to "matches" you'd like the identifiers of the actual genes that matched. That makes sense.

**Comment by kkarra** [comment]
Yes, that was the original request. To return the gene names of the 'matches'. We don't need it now, SGD code handles the enrichment.
