### ISSUE TITLE
Migrate BovineMine

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2081]
https://github.com/theWizardsBaker/BovinemineMigrationTest

**Comment by julie-sullivan** [comment]
[Upgrade instructions](https://intermine.readthedocs.io/en/latest/intermine/upgrade/)
[Blog post](https://intermineorg.wordpress.com/2018/08/08/intermine-2-0/) -- with a video on how to upgrade

# BovineMine

1. copy bovinemine into its own repo
2. run migrate script 

```
~/git/intermine-scripts/gradle-migration/mine $ ./migrateMine.sh ~/git/bovinemine
```

3. pushed to github - https://github.com/julie-sullivan/bovinemine

# BovineMine Data Parsers

1. put bovinemine sources into their own repo - https://github.com/julie-sullivan/bovinemine-bio-sources
2. [remove intermine bio-sources](https://github.com/julie-sullivan/bovinemine-bio-sources/commit/94f7c39821aa72cd66100d3cc2dc7544db26d291)
3. migrate to gradle 

```
~/git/scripts/gradle-migration/data-sources $ ./migrateBioSources.sh ~/git/bovine-bio-sources/
```

# Building BovineMine

So we have our new data sources, but they aren't JARs on the classpath yet. To do that, run this command:

```
./gradlew install
```

Unlike the other commands in this ticket, you will use this one all the time. You will rebuild your JAR every time you make a change.

**Comment by julie-sullivan** [comment]
# Notes

1. Please read the upgrade instructions. You need to set `GRADLE_OPTS` for example.
2. InterMine 3.0 introduced Solr for the keyword search. I would leave this until you have the rest working. It's very easy to configure however.
3. We updated to the latest [BioJava](https://biojava.org/) library. The syntax for the FASTA files is different. I updated this in your `bovine-fasta` source but it's likely NOT correct. Please test!! @sergiocontrino can help you here.
4. I took your data model and put it in global_additions.xml. This model will be included in each data source JAR. It just makes the JARs easier to build.

# Next steps

I would take my repos and try:

```
# can you create the tables?
./gradlew builddb

# try a source
./gradlew integrate -Psource=psi-mi-ontology

# try a bovinemine specific source
./gradlew integrate -Psource=brenda-tissue-ontology

# deploy your webapp
./gradlew cargoDeployRemote
```
[Common gradle commands](https://intermine.readthedocs.io/en/latest/system-requirements/software/gradle/)

Then you can try a full database build!

**Comment by theWizardsBaker** [comment]
While following these directions for our other mine, I'm not able to buildDB. 

The IntermineTasks are not listed:

`
[letourneaujj@intermineTest hymenoptera]$ /db/intermine/intermine/intermine-scripts/gradle-migration/mine/migrateMine.sh ./
Converting . to gradle
Deleting eclipse configurations files
Deleting project properties files
Converting dbmodel project to gradle
cd dbmodel
Converting webapp project to gradle
cd webapp
Deleting log4j.properties file
Creating settings and build gradle files
Deleting default.intermine.*.properties
Migration completed

[letourneaujj@intermineTest hymenoptera]$ ./gradlew tasks --stacktrace

> Task :tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'hymenoptera'.
components - Displays the components produced by root project 'hymenoptera'. [incubating]
dependencies - Displays all dependencies declared in root project 'hymenoptera'.
dependencyInsight - Displays the insight into a specific dependency in root project 'hymenoptera'.
dependentComponents - Displays the dependent components of components in root project 'hymenoptera'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project 'hymenoptera'. [incubating]
projects - Displays the sub-projects of root project 'hymenoptera'.
properties - Displays the properties of root project 'hymenoptera'.
tasks - Displays the tasks runnable from root project 'hymenoptera'.

To see all tasks and more detail, run gradlew tasks --all

To see more detail about a task, run gradlew help --task <task>


BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed`

Any idea why this would be?

**Comment by danielabutano** [comment]
I can see hymenoptera using a version > 4.0.0
