### ISSUE TITLE
Lists endpoint always return empty tag array with lists

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2085]
If you open http://www.flymine.org/flymine/bag.do?subtab=view, check *Show tags* under options, and look at the *PL FlyTF_REDfly_TFs* list, it will have the tags `Expression Term:ubiquitous  another tag  foo  im:favourite  im:public  zop`.

Now if you use the web service endpoint, (eg. `curl http://www.flymine.org/flymine/service/lists\?format\=json`) it will return an empty array for the tags key for all the lists.

It doesn't seem like the web service includes tags at all. Can we get support for this, so Bluegenes can also make use of tags? (Like for implementing https://github.com/intermine/bluegenes/issues/377.)

**Comment by yochannah** [comment]
interesting - we've had this problem before - https://github.com/intermine/intermine/issues/1222

**Comment by danielabutano** [comment]
@uosl do we still need it?

**Comment by uosl** [comment]
Yes. I think it's important that we return tags set on public lists to unauthorized users, as otherwise anonymous users wouldn't be able to navigate folders which the super user has created for their public lists.

**Comment by uosl** [comment]
I'll close this as the lists endpoint **does** return tags, although only the ones created by the authorized user.

There exists a different issue for the remaining work: https://github.com/intermine/intermine/issues/2177
