### ISSUE TITLE
Specify row range for list creation

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#209]
I just had the situation where I wanted to create a list of the 100 most highly expressed genes - i.e I just wanted to select the first 100 rows of genes.  Would it possible to add this option to the list creation (as it is in the download tool)?   It could potentially be done through filtering the values but this would be much easier.

**Comment by julie-sullivan** [comment]
This isn't really possible as a row in the table != a row in the output. e.g. you might have outer joins, or a gene might be repeated in the table but not in the export.
