### ISSUE TITLE
VCF data parser to load data into Intermine. 

### ISSUE THREAD

**Issue by ratmine** [intermine/intermine#210]
Do we have a VCF file parser out there that can load data into Intermine?
Since a lot of the variant data comes in VCF format now, I was wondering if there was a dedicated parser just like the Gff3 parser..

**Comment by julie-sullivan** [comment]
@rnsmith This source works fine but I can't get the unit test to run the source properly.

Here is the project xml file:

```
<source name="vcf" type="vcf">
  <property name="src.data.dir" location="~/git/intermine/bio/sources/vcf/test/resources" />
  <property name="vcf.includes" value="*.vcf" />
  <property name="vcf.vcfTaxonId" value="9606" />
  <property name="vcf.vcfDataSetTitle" value="Ensembl SNP data set" />
  <property name="vcf.vcfDataSourceName" value="Ensembl" />
</source>

```
