### ISSUE TITLE
Remove "upload to GenomeSpace" export

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2107]
http://www.genomespace.org/news/the-genomespace-project-is-ending
`The GenomeSpace project ends on November 15, 2019`

Since the project is ending, we should remove our "Upload to GenomeSpace" text and functionality.

![genomespace](https://user-images.githubusercontent.com/1663057/65489669-842ba880-dea3-11e9-8953-31101e35947d.png)

**Comment by yochannah** [comment]
InterMine will need to bump an imjs version  it I think the implementation will need to be in imjs - I'll link an imjs ticket in.
