### ISSUE TITLE
Add gradle task to stop bluegenes

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2121]
We have a blueGenesStart gralde task but not blueGenesStop

**Comment by uosl** [comment]
Bluegenes has a `stop_web_server_BANG_` function to stop the web server. We could also make the main method take an argument to stop the server.

But I don't think it will be necessary to use these, as killing the process should be enough. I don't know how to do this with gradle/gretty though.

**Comment by danielabutano** [comment]
When we start bluegenes (from gradle) we call the java main class bluegenes.core; similarly to stop bluegenes we need a java main class. 
I have tried
`
task blueGenesStop(type: JavaExec) {
    group = 'BlueGenes'
    classpath = configurations.onlyRunTime
    main = 'bluegenes.core$stop_web_server_BANG_'
}
` 
but it doesn't work.
Decompiling the code, it seems that the java class bluegenes.core$stop_web_server_BANG_ is not a java main class.
