### ISSUE TITLE
ThaleMine: Gradle 4.9 / Java 11 migration.

### ISSUE THREAD

**Issue by asherpasha** [intermine/intermine#2128]
Hi,
I am upgrading ThaleMine to Gradle 4.9 and Java 11. I am using InterMine 4.1.0. I am getting an error. (Not all sources output this error. Most like only the ones in which we have additions to the model.)

Github (Note: Working Gradle 4.1/Java 8 version here):
[https://github.com/asherpasha/thalemine](https://github.com/asherpasha/thalemine)
[https://github.com/asherpasha/thalemine-bio-sources](https://github.com/asherpasha/thalemine-bio-sources)

ThaleMine builds without errors on Gradle 4.1, Java 8 and InterMine 4.1.0. It could be possible that the bug is in thalemine-bio-sources. I am not sure.

Attached Files:
[error_1.txt](https://github.com/intermine/intermine/files/3730950/error_1.txt)
[error_2.txt](https://github.com/intermine/intermine/files/3730951/error_2.txt)
[error_3.txt](https://github.com/intermine/intermine/files/3730952/error_3.txt)

Thanks.

**Comment by danielabutano** [comment]
@asherpasha You are right! I have same issues when I try to build biotestmine using Gradle Wrapper 4.9.
We have built all the InterMine artifacts using 4.9 but tested in biotestmine with the 4.1.
Also flymine has been released using gradle 4.1. 
For now, please build your thalemine using 4.1

**Comment by danielabutano** [comment]
Anyway, I have rebuilt biotestmine with gradle 4.1 + java11 and seems working. So I think the issues is related to the gradle.
