### ISSUE TITLE
The /query path for webservices doesn't work anymore

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2133]
Both https://flymine.org/query/version and https://flymine.org/flymine/query/version do not work. @sergiocontrino suggested it might be an issue related to the the proxy

**Comment by sergiocontrino** [comment]
fixed by Ian on the proxy setting 
(was 
`/query -[301 moved]-> /flymine`
instead of
`/query - [proxy]-> http://met0:8080/flymine/`
)
