### ISSUE TITLE
Add PUT method to the /lists webservice to update the description

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2148]
Added the PUT http method to the existing /lists web service. It receives in input 2 string parameters passed in the URL: name (name of the list belonging to the user) and newDescription
Return status code 400 for missing parameters or wrong list name

**Comment by uosl** [comment]
I just noticed that if `newDescription` is set to an empty string, the backend will return *"Missing parameter: 'newDescription'"*. We should be able to remove the description by setting it to an empty string.

**Comment by danielabutano** [comment]
@uosl try again.It should be fixed now

**Comment by uosl** [comment]
@danielabutano Would it be possible to allow users whom are not logged in to add a description to their list? Right now it will respond with success, but the description for the list will still be null.
