### ISSUE TITLE
Support specifying description when creating list

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2157]
Doesn't look like the `POST /lists` endpoint supports this currently, so you have to first create the list, and then update the description.

**Comment by danielabutano** [comment]
NOTE: the POST /lists service create a new list by uploading a set of identifiers.
The service receives in input the description. @uosl  I have also fixed the webservice which (before my fix :) ) created empty list.
`curl -X POST "http://localhost:8080/biotestmine/service/lists?name=dani5&description=mydescription&type=Gene" -H "Authorization:Token {token}" -H "Content-Type:text/plain" -d "MAL3P3.6, MAL3P2.9"
`

**Comment by uosl** [comment]
Looks like I wanted this on `POST /query/tolist` instead of `POST /lists`, and the former already supports specifying a description. But thanks for fixing that bug anyways [=
