### ISSUE TITLE
Error on flymine website

### ISSUE THREAD

**Issue by mbasil09** [intermine/intermine#2171]
Whenever we try to generate a python template, we get an error if we usse "ONE OF" or "NONE OF" constraints.

![image](https://user-images.githubusercontent.com/55938020/71525229-bca1af00-28f6-11ea-9d72-19e0840fe19e.png)

I believe this is an issue generated when we solved #1981

**Comment by yochannah** [comment]
@mbasil09 thanks for reporting this! 1981's fix hasn't been deployed to flymine yet, so it's probably something else.

what is the error - could you copy/paste it here? :)

**Comment by mbasil09** [comment]
@yochannah 
![image](https://user-images.githubusercontent.com/55938020/71525753-2ae77100-28f9-11ea-9d1d-06c1f6191b86.png)
when we try to generate a python template for this, we get a generic error.
![image](https://user-images.githubusercontent.com/55938020/71525772-4488b880-28f9-11ea-997f-ae5b4161ccc9.png)

This only happens when we use "ONE OF" or "NONE OF" constraints, and this happens in all templates not only this one.

**Comment by yochannah** [comment]
@mbasil09 ah, that makes sense! If you click on Drosophila Melanogaster in the screenshot above before proceeding, does the error still occur? I think the bug here _might_ be that it allows you to proceed to the next screen without selecting all the constraints fully.

**Comment by mbasil09** [comment]
@yochannah 
Oh that's right. Once I choose at least one constraint, there is no error.
I'll see if I can make it work, so that there is always some default selection.

**Comment by uosl** [comment]
This is harder to do in the new interface as changing to ONE OF/NONE OF will leave D. Melanogaster still selected, so you have to remove it first and then run the query. The im-tables will also show you a better error, making it clear that the query is invalid.
