### ISSUE TITLE
Include bgpath: prefixed tags in responses to lists webservice

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2177]
Note: This issue is related to the response in https://github.com/intermine/intermine/issues/2085#issuecomment-547996172. The findings below were tested with the `showTags=true` attribute.

Currently, tags are only included in the response to `GET /lists` if the user owns the list themselves, otherwise it will just be an empty array.

In Bluegenes (https://github.com/intermine/bluegenes/pull/444) we want users and the superuser to be able to organize their lists into folders. For this, we use a tag prefixed with `bgpath:` (only superusers are allowed to create tags prefixed with `im:`, so that wouldn't be viable when users need to set it as well).

Since `bgpath:` tags are only visible to the user/superuser who owns the list, this means that if a superuser organizes a bunch of lists into folders, no other user (authorized or not) will be able to see that folder structure.

We want the folder structure created by the superuser for public lists to be visible to all users, both authorized or not. For this, we need to include `bgpath:` tags in responses to `GET /lists` (only including them when a parameter like `showTags=true` is present is fine).

**Comment by danielabutano** [comment]
for the public list, the /lists webservice return all folder tags (tags starting with the bgpath: prefix)

**Comment by uosl** [comment]
This is still a bit weird. If I'm not logged in, I will get the bgpath tag for public lists, but if I'm logged in as a different user (not admin, and not the user who created the tag), I won't get the bgpath tag.

I tested against alpha flymine.

**Comment by uosl** [comment]
What do you think about also including regular tags on public lists? This way mine admins can add tags to their lists and users can filter by them. It also fits better with #2325.
