### ISSUE TITLE
Rename imtables package to im-tables in JavaScript generator

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2191]
When using *Generated JavaScript Code for Query* from im-tables running in InterMine, it produces a snippet that mentions the `imtables` npm package. We don't have access to this package, and are using `im-tables` instead (see https://www.npmjs.com/package/im-tables).

Please change
`/* Install from npm: npm install imtables` to `/* Install from npm: npm install im-tables`
 and `var imtables = require('imtables');` to `var imtables = require('im-tables');`. 
Note that only the usage of *imtables* in comments or strings is changed; we still wish to use it without a dash as a variable name since JS doesn't allow dashes there.

**Comment by danielabutano** [comment]
It's not generated in InterMine server. move ticket to im-table
