### ISSUE TITLE
In Flymine, some genes have no secondaryIdentifier

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2194]
All the genes with organism Rattus_norvegicus (10116) or Mus_musculus (10090) have no secondaryIdentifier (I might be useful for creating external simpler links)

**Comment by rachellyne** [comment]
What do you want to link to?  We currently link to ensembl but could also link to MGI, RGD - although we get these through the Mine links.  The identifiers currently come from a mix of sources (orthologues, uniprot, mgi etc) and maybe don't merge well.
