### ISSUE TITLE
Include creation/last modified date in saved queries webservice

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2201]
The `/user/queries` endpoints (http://iodocs.apps.intermine.org/flymine/docs#/ws-saved-queries/GET/user/queries) don't keep track of creation and last modified times.

This would be useful to have so we can sort saved queries by most recently used in Bluegenes.

**Comment by danielabutano** [comment]
Not urgent. It's not trivial. We need to change the model

**Comment by uosl** [comment]
I tested this and it returns `created: "2021-02-11"` which isn't really specific enough as it doesn't include the timestamp.

Does the Intermine backend know in which order the queries were created? If so, it could return `queries` as an array of objects, instead of an object, to ensure the newest-to-oldest ordering is kept. Although this would break backwards compatibility.
