### ISSUE TITLE
BovineMine Icon not showing on Intermine.org website

### ISSUE THREAD

**Issue by vvijayalakshmi21** [intermine/intermine#2222]
On clicking 'Which InterMine for my organism?' from Intermine.org homepage, a summary of available InterMines are displayed. The BovineMine icon is not displayed.

![image](https://user-images.githubusercontent.com/34595292/76187247-dd15a180-61a2-11ea-97cf-c13cd6c4ea99.png)

On inspecting the element, I found that the image png specified in the html is not available. 
src="**_http://bovinegenome.org/bovinemine/model/images/logo.png_**"

**Comment by vvijayalakshmi21** [comment]
HI, @danielabutano 
Kindly let me know which image has to be included in place of the one in the current code.

**Comment by CadencePrestissimo** [comment]
Hey,
I checked the code for this, this shows the images are extracted from intermine-registry ,
I updated the code in intermine-registry, could you please look into it.

**Comment by danielabutano** [comment]
fixed in the registry
