### ISSUE TITLE
Representations of the biology entity in XML and JSON format

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2226]
Add the JSON/XML summary data representation given the permaneent url.

The permanent urls are the links used in the _Share_ link displayed in the report page.
![image](https://user-images.githubusercontent.com/1678179/76324024-5fa27c00-62dd-11ea-9d55-249261ef522b.png)

The summary rapresentation should include all the fields dispayed in the top section of report page. See here an example
![image](https://user-images.githubusercontent.com/1678179/76323983-51ecf680-62dd-11ea-81fd-f6c21fa195ca.png)

The data representation can be specified by:
-  URI extensions. For example:
 `http://localhost:8080/biotestmine/protein:Q8I5D2.json`
`http://localhost:8080/biotestmine/protein:Q8I5D2.xml`
In this case we need to adapt the existing [PermanentURLFilter](https://github.com/intermine/intermine/blob/dev/intermine/webapp/src/main/java/org/intermine/web/filters/PermanentURLFilter.java) to first check of any prefix (json, xml case insensitive)

- HTTP content negotiation
To explain by example, if you use the following curl command: 
`curl -L -H “Accept: text/html” http://localhost:8080/biotestmine/protein:Q8I5D2`
it returns the HTML document wich describes the protein Q8I5D2.
We want to add the functionality which allows, given the following curl command:
`curl -L -H “Accept: application/json” http://localhost:8080/biotestmine/protein:Q8I5D2`
to return the json summary rapresentation for the protein Q8I5D2.

**Comment by vvijayalakshmi21** [comment]
Hi, I am an Outreachy applicant and a first time contributor. I would like to try this issue
Could you please assign this to me?

**Comment by danielabutano** [comment]
Hi @vvijayalakshmi21. I will not assign the tickets because other students might work on it.

**Comment by miracle-E** [comment]
Hi, I am an outreachy applicant and a first time contributor and would like to try this issue. Could it be assigned to me?

**Comment by akiljames83** [comment]
Hello @danielabutano, I am interested in taking on this project, could you give me some code pointers as to where web requests are handled and how the fields in the summary representation are populated? Thanks!
