### ISSUE TITLE
UI: change X color on JSP Queries

### ISSUE THREAD

**Issue by fequerver** [intermine/intermine#2245]
Link: https://www.flymine.org/flymine/customQuery.do

When you select a data type, a small description appears, this description close icon is a red X. It gives users the impression that an error occurred.

**Comment by fequerver** [comment]
The referred icon can be found in other pages, I've not checked if it's used with the same goal everywhere.
List:
https://github.com/intermine/intermine/search?q=%22cross.gif%22&unscoped_q=%22cross.gif%22

**Comment by CadencePrestissimo** [comment]
Is this issue still open , can I work on it ?

**Comment by danielabutano** [comment]
Not relevant anymore, we use a new interface
