### ISSUE TITLE
Add licence to the OboConverter

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2264]
Add in the OboConverter bio source (do, eco, go, mammalian-phenotype-ontology, psi-mi-ontology, so, uberon) the licences. Add in the {bio-source-name}.properties file a new property obo.ontology.licence and use it to set the dataset.licence linked to the ontology. In this way we have more chance to have dataset as Sequence Ontology with a licence.
It's always possible to override the licence value via project.xml adding 
`<property name="licence" value="my own licence"/>`
All the licences have been retrieved from http://www.obofoundry.org/

**Comment by sammyjava** [comment]
Good move, I've been writing lots of OBO sources for the various plant trait and crop ontologies.
