### ISSUE TITLE
Add externalLink/otherMines webservice

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2269]
Implement 2 web services to return External land Other Mines links to be used by bluegenes report page.

**Comment by danielabutano** [comment]
@uosl for the externalLinks WS the output might be something like: 
`{"externalLinks":
{"ensembl":"https://identifiers.org/ensembl:FBgn0004053",
"GenomeRNAi":"http://genomernai.org/ExternalLink/flybase/FBgn0004053",
"FlyExpress":http://www.flyexpress.net/search.php?type=image&search=FBgn0004053}}
`

**Comment by uosl** [comment]
You sure you don't want to provide it as an array of objects? The downside of key-value pairs is that you can't guarantee ordering, nor can you add more fields. It could be useful to have more fields like `description` (which could be displayed in an on-hover tooltip) in the future.

**Comment by danielabutano** [comment]
See the AttributeLinkController class

**Comment by sergiocontrino** [comment]
the attributelink property has various attributes:

- url  *
- text *
- imageName
- dataset
- delimiter
- usePost
- enctype
- useCheckbox

the last 4 are used for lists, * = compulsory

**Comment by sergiocontrino** [comment]
the service should return all the links (objects with text, url, and eventually other attributes) for a given class (Gene, Protein, etc) and a given organism (9606, 7227, or any if we have a *).

**Comment by sergiocontrino** [comment]
@uosl  would an output like that be ok? there are some redundant fields maybe, but should be ready for the lists link-out.

{
{"ensembl":{"valid":true,"linkId":"ensembl","imageName":"ensembl_logo_link.gif","attributeValue":"FBgn0000606","attributeName":"primaryIdentifier","text":"ensembl","title":"ensembl","url":"https://identifiers.org/ensembl:FBgn0000606"},"flyexpress":{"valid":true,"linkId":"flyexpress","imageName":"flyexpress_logo_link.png","attributeValue":"FBgn0000606","attributeName":"primaryIdentifier","text":"FlyExpress","title":"FlyExpress","url":"http://www.flyexpress.net/search.php?type=image&search=FBgn0000606"},"genomeRNAi2":{"valid":true,"linkId":"genomeRNAi2","attributeValue":"FBgn0000606","attributeName":"primaryIdentifier","text":"GenomeRNAi","title":"GenomeRNAi","url":"http://genomernai.org/ExternalLink/flybase/FBgn0000606"},"flyatlas":{"valid":true,"linkId":"flyatlas","imageName":"flyatlas_logo_link.png","attributeValue":"FBgn0000606","attributeName":"primaryIdentifier","text":"FlyAtlas","title":"FlyAtlas","url":"http://flyatlas.org/atlas.cgi?name=FBgn0000606"},"bdgp_in_situ":{"valid":true,"linkId":"bdgp_in_situ","imageName":"BDGP_logo_small.png","attributeValue":"CG2328","attributeName":"secondaryIdentifier","text":"BDGP in situ","title":"BDGP in situ","url":"http://insitu.fruitfly.org/cgi-bin/ex/report.pl?ftype=1&ftext=CG2328"},"ArrayExpressAtlas":{"valid":true,"linkId":"ArrayExpressAtlas","imageName":"arrayExpressAtlas_logo.png","attributeValue":"FBgn0000606","attributeName":"primaryIdentifier","text":"ArrayExpress Atlas","title":"ArrayExpress Atlas","url":"https://identifiers.org/gxa.gene:FBgn0000606"},"flybase1":{"valid":true,"linkId":"flybase1","imageName":"flybase_logo_link.png","attributeValue":"FBgn0000606","attributeName":"primaryIdentifier","text":"FlyBase","title":"FlyBase","url":"https://identifiers.org/fb:FBgn0000606"},"homologene":{"valid":true,"linkId":"homologene","imageName":"homologene_logo_link.png","attributeValue":"eve","attributeName":"symbol","text":"Homologene","title":"Homologene","url":"https://www.ncbi.nlm.nih.gov/sites/entrez?Db=homologene&cmd=detailssearch&term=txid7227[orgn]+eve[Gene]"}}
,"executionTime":"2021.02.17 10:58::26","wasSuccessful":true,"error":null,"statusCode":200}

**Comment by sergiocontrino** [comment]
also @uosl : is returning an empty string fine if no results/wrong id?

**Comment by uosl** [comment]
@sergiocontrino The JSON looks invalid as there needs to be a key for the first value. So something like
```
{"links":
{"ensembl":
...
```
should fix it. Otherwise it looks fine!

When there are no results, an empty object like `{"links": {}` would be better. If the ID is invalid, an error would be nice.

**Comment by sergiocontrino** [comment]
@uosl for the error (i.e. no object with the request id), please check if the output below  would be fine, or if you had something else in mind. thanks!

{
"-1"
,"executionTime":"2021.02.18 16:05::24","wasSuccessful":true,"error":null,"statusCode":200}

**Comment by uosl** [comment]
@sergiocontrino That's also invalid JSON.

I was thinking something like
```
{"links":{},"executionTime":"2021.02.18 16:21::16","wasSuccessful":false,"error":"No object with ID 10073945","statusCode":400}
```

**Comment by sergiocontrino** [comment]
i implemented something like this for no object:
{"links":"","executionTime":"2021.02.18 16:21::16","wasSuccessful":false,"error":"No object with ID 10073945","statusCode":400}

for the other mines links, i followed what is done in the jsp and return the json below: not sure if it is bg that checks orthologues or if the service should do it.
<pre>
{
	"otherMines": {
		"RatMine": {
			"fgCol": "#000",
			"default": "R. norvegicus",
			"logo": "ratmine_logo.png",
			"url": "http://ratmine.mcw.edu/ratmine",
			"bgCol": "#ABC2DA"
		},
		"ZebrafishMine": {
			"fgCol": "#FFF",
			"default": "D. rerio",
			"logo": "zfinlogo.png",
			"url": "http://zebrafishmine.org",
			"bgCol": "#006666"
		},
		"HumanMine": {
			"fgCol": "#000",
			"default": "H. sapiens",
			"logo": "humanmine_logo.png",
			"url": "https://www.humanmine.org/humanmine",
			"bgCol": "#C3C3C3"
		},
		"MouseMine": {
			"fgCol": "#FFF",
			"default": "M. musculus",
			"logo": "mousemine_small_logo.png",
			"url": "http://www.mousemine.org/mousemine",
			"bgCol": "#192F39"
		},
		"FlyMine": {
			"fgCol": "#FFF",
			"default": "D. melanogaster",
			"logo": "flymine_logo_link.gif",
			"url": "https://www.flymine.org/query",
			"bgCol": "#5C0075"
		},
		"YeastMine": {
			"fgCol": "#FFF",
			"default": "S. cerevisiae",
			"logo": "SGD_logo_small.png",
			"url": "https://yeastmine.yeastgenome.org/yeastmine",
			"bgCol": "#A7995E"
		}
	},
	"localMine": "iFly",
	"mayHaveLinks": true,
	"executionTime": "2021.02.19 14:29::36",
	"wasSuccessful": true,
	"error": null,
	"statusCode": 200
}
</pre>
