### ISSUE TITLE
Webservice for sending feedback

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2280]
Bluegenes' new frontpage has a feedback form.
 
![2020-07-13-110712_861x433_scrot](https://user-images.githubusercontent.com/3865590/87292684-136c8000-c4f9-11ea-802d-ba1413ed7cce.png)

We can reuse the email service currently used for sending registration emails, to also send feedback from users if we expose it through a new webservice (actually the JSP webapp already has a feedback form, so maybe we could reuse that as well).

Edit: Might be useful to work on this together with https://github.com/intermine/intermine/issues/2173, as they're both related to the emails service.

**Comment by danielabutano** [comment]
Added service /service/feedback, http method POST, input:

- email (not mandatory)

- feedback (mandatory)
