### ISSUE TITLE
200 OK response when deleting unauthorized list

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2288]
If I delete an unauthorized list (e.g. a public list that I don't own) I will get a 200 OK response with `wasSuccessful: true`. Thankfully the list won't actually get deleted, but I think it would be better to respond with a failure code and include a suitable message in `error` in the JSON response.

**Comment by danielabutano** [comment]
Update the webservice to return
"wasSuccessful":false,"error":"test1 not found","statusCode":400
