### ISSUE TITLE
Add appropriate error message when renaming a list to something existing

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2290]
When you use the `POST /lists/rename` endpoint passing a `newname` that is already taken by a different list, it will return the following response with the error `Service failed. Please contact support.`:
```
{"executionTime":"2020.08.05 11:38::44","wasSuccessful":false,"error":"Service failed. Please contact support.","statusCode":500}
```
It would be a big improvement to the Bluegenes interface if we supplied a proper message like `A list with the same name already exists`. I do not want to override the error message in the response in case something else went wrong.

This could also be fixed along with it: https://github.com/intermine/intermine/issues/1835

**Comment by danielabutano** [comment]
Fixed it. Nice user message + Status code returned 400
