### ISSUE TITLE
Webservice as key-value store for Bluegenes properties

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2295]
`/bluegenes-properties`
        - POST to add new key with value, or update value of existing key
        - PUT [does the same thing as POST]
        - GET to acquire value of key, or all key-values if not specified
        - DELETE to remove existing key
        - Admin required: POST, PUT, DELETE

**Comment by danielabutano** [comment]
POST to ADD new key with value (400 if you use an existing key)
PUT to UPDATE an existing resource (404 if the key doesn't exist)
DELETE to remove existing key (404 if the resource doesn't exist)
