### ISSUE TITLE
Update google auth and userinfo endopoints

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2296]
Thanks @sammyjava to find the issue!
Frm @sammyjava emial

> If I use the default API URI, which is coded in intermine/webapp/src/main/webapp/WEB-INF/global.web.properties:

oauth2.GOOGLE.identity-resource = https://www.googleapis.com/plus/v1/people/me/openIdConnect

Google returns

message    "Legacy People API has not been used in project 1234567 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=1234567 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
status    "PERMISSION_DENIED"

**Comment by sammyjava** [comment]
I can handle this one if you like. I think I need to change the Google response handling as well, as it appears to be something new, maybe not even JSON. I'm happy to take care of it and post a PR.

**Comment by sammyjava** [comment]
Ah, sorry, hadn't read your reply to the dev email list, I see you're on top of it! Carry on! Ciao!
