### ISSUE TITLE
Regression in POST lists webservice

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2303]
This only applies to the branch: https://github.com/danielabutano/intermine/tree/google-auth

Using a biotestmine built off that branch, when I do POST /lists?name=list824&type=Gene with body "ABRA", it will return 400 error: "list824_temp not found". This error will happen regardless if it matches any identifiers or not.

On current Flymine, this works fine (with body "zen" instead).

**Comment by danielabutano** [comment]
Thanks @uosl 
I have introduced the bug when I have fixed #2288.
