### ISSUE TITLE
Remove dependency from EBI maven nexus repo

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2324]
Download the libraries which we depend on and store in github
(http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/org/intermine/intermine-webapp/maven-metadata.xml.)

**Comment by sergiocontrino** [comment]
these are affected libraries (could be a partial list):

> Could not download jami-ols.jar (psidev.psi.mi.jami.bridges:jami-ols:1.1.0)

> Could not download jami-interactionviewer-json.jar (psidev.psi.mi.jami:jami-interactionviewer-json:2.0.4)

> Could not download bridges-core.jar (psidev.psi.mi.jami.bridges:bridges-core:1.1.4)

> Could not download jami-core.jar (psidev.psi.mi.jami:jami-core:1.2.5)

> Could not download ols-client.jar (uk.ac.ebi.ols:ols-client:1.18)

**Comment by danielabutano** [comment]
We might move to a more stable EBI maven repo: https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/ where there are differents versions. We need to test it carefully
