### ISSUE TITLE
BioGrid data change causing loader to throw Exception

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#2335]
We just stumbled over the following issue. We are running 1.8.5, but it looks like the issue still exists in 4.x.

The issue: the biogrid source loader contains a hard-coded translation table (PSI_TERMS), that maps interaction types (PSI-MI ids) to either "genetic" or "physical". As of our most recent download of the mouse subset from BioGrid (1 Mar 2021), the data include 11 additional genetic interaction types, which causes the loader to throw an exception ("Bad interaction type").
Adding these to the table fixes the immediate problem, although a more robust solution would be welcome.

**Comment by JoelRichardson** [comment]
PS: the 11 terms are MI:2368 through MI:2378

**Comment by danielabutano** [comment]
Thanks @JoelRichardson we will have a look soon

**Comment by rachellyne** [comment]
I'm also wondering if we should have an additional category - association - as we have proteins pulled down together that do not necessarily directly interact as "Physical". e.g MI: 0915: Interaction between molecules within the same physical complex. Often identified under conditions which suggest that the molecules are in close proximity but not necessarily in direct contact with each other.  Also: MI:0403: Coincident occurrence of molecules in a given subcellular fraction observed with a low resolution methodology from which a physical interaction among those molecules cannot be inferred.

**Comment by sergiocontrino** [comment]
thank you @JoelRichardson and @rachellyne. we can easily add the term @rachellyne suggested. the issue that @JoelRichardson highlighted is that these terms are hardcoded in the loader, and they appear to change (new entries) with time. do you know where/how we should source them @rachellyne, so we can avoid the hardcoding?
