### ISSUE TITLE
Support passing project.credits in web-properties ws

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2337]
Bluegenes will read `project.credits` (https://github.com/intermine/bluegenes/issues/557) for the mine-specific credits section at the bottom of the home page.

This should be an array of objects containing either `text, image, url` or `image, url` keys (it will be displayed differently depending on which set of keys are used). All values are strings.

Here is an example of the array:
```js
[
  {
    "text": "InterMine has been developed principally through support of the [Wellcome Trust](https://wellcome.ac.uk/). Complementary projects have been funded by the [NIH/NHGRI](https://www.nih.gov/) and the [BBSRC](https://bbsrc.ukri.org/).",
    "image": "https://www.humanmine.org/humanmine/images/icons/intermine-footer-logo.png",
    "url": "http://intermine.org/"
  },
  {
    "image": "https://www.humanmine.org/humanmine/images/wellcome-logo-black.png",
    "url": "https://wellcome.ac.uk/"
  },
  {
    "image": "https://www.humanmine.org/humanmine/images/logo_nhgri.png",
    "url": "https://www.nih.gov/"
  },
  {
    "image": "https://www.humanmine.org/humanmine/images/bbsrc-logo.gif",
    "url": "https://bbsrc.ukri.org/"
  }
]
```

By default, the array will be empty. We'll need to make sure to add documentation for this property so mine admins will know how to use it.

**Comment by danielabutano** [comment]
Just added the properrties to humanmine and flymine
