### ISSUE TITLE
Template description not updating on templates page

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#246]
When I update the template, the description updates correctly on the template form but not on the list of templates.

**Comment by sergiocontrino** [comment]
see MINE-744 for aip.

**Comment by julie-sullivan** [comment]
@sergiocontrino Putting this on the next milestone but should be a point release.

**Comment by sergiocontrino** [comment]
a new record id added in savedtemplatequery in the userprofile when a template is updated.
messages and variables (isNewTemplate) are correct though, so maybe this is intended.
the description is correctly updated in the mymine section (not in the templates page).

**Comment by julie-sullivan** [comment]
@sergiocontrino Can we update it so that the templates page is also updated?

**Comment by julie-sullivan** [comment]
You can update the description by redeploying the webapp.
