### ISSUE TITLE
Support semantic tooling

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#265]
All the cool kids do semantic web - you want to be cool, right?

In order of implementation:
- rdf description of what a model is
- rdf serialisation of model(s)
- rdf serialisation of data
- [linked data api](https://code.google.com/p/linked-data-api/wiki/API_Deployment_Example)

**Comment by julie-sullivan** [comment]
I am going to close this ticket for now. If we do decide to go in this direction, we'll make specific tickets for each task.
