### ISSUE TITLE
Ability to run the application under the default context

### ISSUE THREAD

**Issue by cmpich** [intermine/intermine#316]
At the moment I have to choose a non-default context to build and run the application as webapp.path parameter. However, ZFIN likes to run the mine under
http://zebrafishmine.org
without a context.

**Comment by julie-sullivan** [comment]
@cmpich Let me know if you are able to push the changes. I think it would be helpful for other interminers! :)

**Comment by cmpich** [comment]
With our zfinmine last checkin into github you should have access to the code changes to support the default context.

**Comment by julie-sullivan** [comment]
Thanks @cmpich!! Do you have the commit hash? Because I don't see it https://github.com/ZFIN/intermine/commits/dev

**Comment by julie-sullivan** [comment]
Going to close this for now as you were able to get it working yourselves.
