### ISSUE TITLE
Result table download modifications

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#374]
I was just using the download from the results tables and thought a few things were not clear.  These are some suggestions for better usability.

1. I found out by accident that you can now remove columns by clicking on the circle - this is a really important feature but I don't think this is obvious -  a box with a cross would work better.

2. I wanted to download some sequence data so was looking for FASTA format.  I couldn't find it at first as it was surrounded by so many words: 'NCBI compatible FASTA sequence'.  Just 'FASTA' would be better here.  This format is so widely used I wouldn't call it 'NCBI compatible' in particular.

3. Another reason it was hard to find the format is that the column on the left said  'tsv format' as default.  I would change this to just say 'Format' so it is obvious this is where all the different formats are found.

4. When you get to the download page it is dominated by 'Results URI' and 'Query xml'.  This is advanced usage so I wouldn't make it the main feature of the page.

**Comment by julie-sullivan** [comment]
@rachellyne Can we close this ticket?

**Comment by rachellyne** [comment]
I still don't think remove column is particularly obvious.  Can we have a cross?  This would be consistent with the results tables and clear to everyone.

**Comment by julie-sullivan** [comment]
@rachellyne beta.flymine has been updated. Take a look at the query results and close this ticket if you are happy?

I looked and think all your points have been nicely addressed.

**Comment by julie-sullivan** [comment]
@rachellyne I am taking your silence to mean you love all the changes and this ticket can be closed.
