### ISSUE TITLE
spin out the java webservice client from the server code

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#397]
And in so doing ensure:
- That the javadocs are available on github pages
- The the code is installable as a single uberjar

**Comment by julie-sullivan** [comment]
@danielabutano @justinccdev is this something we can do when we move to gradle?

**Comment by justinccdev** [comment]
I should think so.

**Comment by julie-sullivan** [comment]
Lives in https://github.com/intermine/intermine-ws-java now.
