### ISSUE TITLE
Recommendations - what is like my gene(s)?  what is the same about my gene(s)/lists?

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#4]
If I have a gene (or a list of genes) I would like to see genes that are similar to my gene - eg. have a similar expression pattern, go annotation, pathways, etc.

Also, given multiple lists, show me where they intersect through a given element eg. Pathways. This is similar, in principle, to the InterMod tool which does this across species. Here the lists may come from one (or more) species.

**Comment by julie-sullivan** [comment]
All of these requirements have moved to the GSoC project.

Can I close this ticket safely @joshkh?

**Comment by joshkh** [comment]
Yes, closing. Thanks.
