### ISSUE TITLE
Query - constrain on "NOT IN" collection

### ISSUE THREAD

**Issue by zfinintermine** [intermine/intermine#419]
Actual use case at zebrafishmine.org:

In the phenotype object, when "superterm2"  is present, make sure "phenotype term name" is in the "relational quality slim" (phenotypeTerm.subsets contains 'relational_slim').

We had to use two lists to accomplish this.  We could also see this being a "pipeline" @ steps.intermine.org and would love to test this functionality.

**Comment by julie-sullivan** [comment]
This works as described, in 1.4
