### ISSUE TITLE
Results table forgetting toggle state

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#421]
Reported by a MouseMine user. Verified at FlyMine.

If I have toggled a column off, I would prefer that it not reappear if I filter on a different column.

Example: in "Publication => Functions (GO terms)", if I toggle off the
"Publications - Title" column, and then filter on the "Ontology Annotations -
Name" column, the "Publications - Title" column is now back on after filtering.

**Comment by julie-sullivan** [comment]
Works as expected now.
