### ISSUE TITLE
Query results - add link to query builder

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#436]
@JoelRichardson 

>   * Always have a direct link to the Query Builder for the current
>     query. It's a pain without it when you really want it. (1.
>     Get-code->XML. 2. Copy 3. Go to QB tab 4. Click Import XML 5. Paste.
>     6. Click OK.)

**Comment by julie-sullivan** [comment]
This is working correctly in beta.

**Comment by JoelRichardson** [comment]
Yup this is great. Thanks!
