### ISSUE TITLE
Sharing lists -- need better message when owner hasn't upgraded lists

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#439]
@JoelRichardson 

> - User reported frequent inability to "access the site". Turned out to
>   be an issue involving shared lists, combined with an inaccurate (and
>   dire-sounding) error message: "Ooops…service unavailable." or
>   something like that. The real issue: he was accessing lists shared
>   by another user, and that user needed to upgrade the lists.

**Comment by julie-sullivan** [comment]
This is what happens now when you get invited to a bad list page:

![bad-list](https://cloud.githubusercontent.com/assets/1663057/26354376/3e73632e-3fbc-11e7-9639-5b13a7ddbf76.png)

Better, but should do what happens if the owner goes to that page, it just says the list doesn't exist. Why is the behaviour different?

**Comment by danielabutano** [comment]
@julie-sullivan I've reviewed the code and it's fine. Not able to test it locally!! The upgrading process is to fast and it ends before I can click on any of my lists. Any suggestions?

**Comment by julie-sullivan** [comment]
@danielabutano To test, I updated the status of the list directly in the database! :x

**Comment by danielabutano** [comment]
@julie-sullivan ok tested locally via URL http://localhost:8080/flymine/bagDetails.do?scope=all&bagName=Allele (A list not upgraded is never shown on the list page)

**Comment by julie-sullivan** [comment]
@danielabutano Do you want me to deploy beta flymine on this branch, so we can test Rachel's wonky list?

**Comment by danielabutano** [comment]
@julie-sullivan yes, good idea.Thnaks
