### ISSUE TITLE
Get rid of torque

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#484]
Torque is vendor agnostic ORM and code generator. We use it but should get rid of it because:
- We are not vendor agnostic, but wedded to psql
- We have our own ORM
- We generate our own code

The only thing we use Torque for is generating create table statements. This is profoundly round-the-houses as it means our schema descriptions go from model.xml -> torque.xml -> sql, when the middle step is completely unnecessary, and prevents the use of psql features such as UUID columns

**Comment by julie-sullivan** [comment]
we use torque for something useful. If we did remove it we'd have to rewrite ALL the OS queries and so easier just to leave it in.
