### ISSUE TITLE
Add field display name to Facets in web service results.

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#546]
#### Background:

Using quicksearch via web services returns keys using field names such as "primaryIdentifier" or "organism.name":

``` json
    "results": [
        {
            "id": 1007330,
            "relevance": 3.1994696,
            "type": "Gene",
            "fields": {
                "organism.name": "Drosophila melanogaster",
                "primaryIdentifier": "FBgn0004053",
                "symbol": "zen",
                "secondaryIdentifier": "CG1046"
            }
        },
```
#### Problem:

Most fields follow a naming convention that provides a good guess as to the display name, however some fields have a custom configuration. Example:

MouseMine:
"mgiJnum" displays as "Mgi Jnum" (what one would expect)
"MPTerm" displays as "MP Term" (where one would expect "M P Term")

If an application using quicksearch lives outside of an InterMine instance then there is no access to the configuration files that govern custom labels:
http://intermine.readthedocs.org/en/latest/data-model/data-labels/?highlight=labels
#### Fix:

Add "labels" to the Facets key of a quicksearch result:

``` json
    "facets": {
        "Category": {
            "Gene": 3,
            "RNAiResult": 1,
            "Publication": 4,
            "Author": 2,
            "Protein": 1
        },
        "pathways.name": {},
        "labels": {
            "organism.name": "Organism > Name",
            "mgiJnum": "Mgi Jnum",
            "MPTerm": "MP Term"
        },
        "organism.shortName": {
            "D. melanogaster": 1,
            "D. pseudoobscura": 2,
            "D. virilis": 1
        }
```

**Comment by julie-sullivan** [comment]
See #375
