### ISSUE TITLE
Show distribution in context of (unfiltered) distribution.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#553]
From Gos

> Ran query --> table
> Column summary (numeric data) for Column A
> Grabbed slider to look at top of the distribution --> sets filters
> Clicked filter icon: removed a filter
>     then had to click filter icon again to remove the other filter
>         * would be nice to be able to remove multiple and then close
> Filtered on Column B (categorical) via the column summary
> Looked at Column A summary
>     now see very much zoomed in distribution (which is correct) but I can't 
>     get a sense of how it relates to the unfiltered distribution.
>         * would be nice if it showed the new distribution in the context of
>           the unfiltered distribution (I was trying to see whether a
>           particular category in Column B corresponded to the high values in
>           Column A)
>
>           No doubt the suggestion above would be annoying sometimes when one
>           *wants* to see the resulting filtered distribution with as much
>           resolution as possible. 
>
>           So:
>               * maybe allow a toggle to "scale to fit the filtered data".  It
>           would still be useful to show the unfiltered distribution as a
>           fainted colour...
>

**Comment by alexkalderimis** [comment]
needs discussion - especially regarding the effects of constraints.
