### ISSUE TITLE
Selecting sequence download disables row selection,

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#559]
If you wish to download sequence (fasta, gff, bed), the row selector on the download becomes disabled so the only option is to download all sequences.  Also, the downloaded file starts from the last sequence rather than the first.

**Comment by julie-sullivan** [comment]
@rachellyne We can't do this because a row in intermine doesn't equal a row in the output file. Does that make sense?

**Comment by rachellyne** [comment]
Not really.  The rows should refer to the results table regardless of the output format?
