### ISSUE TITLE
Precompute fails with outer joins

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#568]
Per @kkarra

> 13/03/14,18:16:44 ERROR org.intermine.objectstore.intermine.ObjectStoreInterMineImpl     - Error
> java.lang.IllegalArgumentException: [82, SELECT], [36, intermine_default], [97, .], [36, subjectId], [93, AS], [35, "bagId"], [84, ,], [36, intermine_default], [97, .], [36, id], [93, AS], [36, intermine_defaultid], [85, FROM], [36, CrossReference], [93, AS], [36, intermine_default], [84, ,], [36, DataSource], [93, AS], [36, a1_], [86, WHERE], [36, intermine_default], [97, .], [36, sourceId], [77, =], [36, a1_], [97, .], [36, id], [106, AND], [57, LOWER], [95, (], [36, a1_], [97, .], [36, name], [96, )], [76, LIKE], [37, 'mim'], [106, AND], [90, ORDER], [88, BY], [36, intermine_default], [97, .], [36, subjectId], [84, ,], [36, intermine_default], [97, .], [36, id]
>     at org.intermine.sql.query.Query.<init>(Query.java:182)
>     at org.intermine.sql.query.Query.<init>(Query.java:127)
>     at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.precomputeWithConnection(ObjectStoreInterMineImpl.java:1885)
>     at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.precomputeWithConnection(ObjectStoreInterMineImpl.java:1995)
>     at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.precompute(ObjectStoreInterMineImpl.java:1844)
>     at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.precompute(ObjectStoreInterMineImpl.java:1824)
>     at org.intermine.api.query.WebResultsExecutor.precomputeTemplate(WebResultsExecutor.java:183)
>     at org.intermine.dwr.AjaxServices.preCompute(AjaxServices.java:176)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>     at java.lang.reflect.Method.invoke(Method.java:597)
>     at org.directwebremoting.impl.ExecuteAjaxFilter.doFilter(ExecuteAjaxFilter.java:34)
>     at org.directwebremoting.impl.DefaultRemoter$1.doFilter(DefaultRemoter.java:428)
>     at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:431)
>     at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:283)
>     at org.directwebremoting.servlet.PlainCallHandler.handle(PlainCallHandler.java:52)
>     at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:101)
>     at org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:146)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
>     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
>     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
>     at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:270)
>     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
>     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
>     at org.intermine.web.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:139)
>     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
>     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
>     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
>     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
>     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
>     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
>     at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
>     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
>     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
>     at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
>     at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
>     at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
>     at java.lang.Thread.run(Thread.java:662)
> Caused by: line 1:194: unexpected token: AND
>     at org.intermine.sql.query.SqlParser.select_command(SqlParser.java:346)
>     at org.intermine.sql.query.SqlParser.sql_statement(SqlParser.java:166)
>     at org.intermine.sql.query.SqlParser.sql(SqlParser.java:121)
>     at org.intermine.sql.query.SqlParser.start_rule(SqlParser.java:73)
>     at org.intermine.sql.query.Query.<init>(Query.java:147)
>     ... 41 more

**Comment by kkarra** [comment]
Will re-open if I see any errors. It looks good for now.
