### ISSUE TITLE
InterMine https

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#569]
Need to make it easier to use https

**Comment by julie-sullivan** [comment]
@sergiocontrino So this issue is fixed?

**Comment by sergiocontrino** [comment]
yes, was fixed with https://github.com/intermine/intermine/pull/634

**Comment by sergiocontrino** [comment]
i mean, the thalemine issue, don't know about the general issue raised in the ticket.

**Comment by julie-sullivan** [comment]
Yes, I think I created this ticket because of the issues AIP were having.
