### ISSUE TITLE
Implement or Delete GAF Export

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#582]
We either need to actually implement this, or delete code we don't intend on using.

References: 
- http://www.geneontology.org/GO.format.gaf-2_0.shtml#
- /bio-webapp/src/org/intermine/bio/webservice/GAFQueryService.java
- /bio-webapp/src/org/intermine/bio/webservice/GAFQueryServlet.java
- /bio-webapp/src/org/intermine/bio/web/export/GAFExporter.java

**Comment by julie-sullivan** [comment]
@kkarra is this still on your wishlist?

**Comment by kkarra** [comment]
If no one else cares, guess not.
