### ISSUE TITLE
cdn.intermine.org in generated JavaScript

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#593]
Generated JavaScript code (from a results table) accesses cdn.intermine.org, even if you have a local cdn configured. Could that be fixed?

**Comment by joshkh** [comment]
Truthing window.intermine.options is no longer a valid test for setting the CDN option on IM-Tables.

**Comment by joshkh** [comment]
@julie-sullivan Can you please test this?

Test case:
1. Change your head.cdn.location in web.properties to http://www.mousemine.org/cdn  (no trailing slash)
2. Redeploy webapp
3. Run any query
4. Generate JavaScript code
5. Tick the "As HTML Page" box
6. Confirm that the <script> tags in the output have mousemine's CDN as their source

**Comment by joshkh** [comment]
@JoelRichardson Could you try this pull request and let us know if it fixes the problem? Thanks! https://github.com/intermine/intermine/pull/1400

**Comment by sneuhaus** [comment]
Tested and working on MouseMine. Thanks!
