### ISSUE TITLE
Enrichment widgets - fail gracefully

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#608]
When you change a background population you get an ugly error:

```
Invalid JSON Response for Gene Ontology Enrichment
error is false; was expecting Null but got Service failed. Please contact support.
statusCode is false; was expecting HTTP code 200 but got 500 
```

I _think_ this only happens when I use a list that isn't a super-set of the list I am currently viewing. Instead, we should have a friendly error. We used to.

**Comment by JoelRichardson** [comment]
Hi @julie-sullivan, a MouseMine user just ran into this one. Any chance it will be fixed soon? Thanks!

**Comment by julie-sullivan** [comment]
@joshkh Can you take a look? Seems like it would be an easy fix!

**Comment by yochannah** [comment]
This was actually fixed here: https://github.com/intermine/intermine/issues/1164
