### ISSUE TITLE
Store unqualified class names in database

### ISSUE THREAD

**Issue by rnsmith** [intermine/intermine#675]
We need to store the classname of objects in each row of the database:

     intermine_start | intermine_end | strand |    id    | featureid | locatedonid |              class               
    -----------------+---------------+--------+----------+-----------+-------------+----------------------------------
            75765069 |      75765069 | 1      | 11487187 |  11487186 |     8512385 | org.intermine.model.bio.Location
            75765136 |      75765136 | 1      | 11487189 |  11487188 |     8512385 | org.intermine.model.bio.Location
            75765156 |      75765156 | 1      | 11487191 |  11487190 |     8512385 | org.intermine.model.bio.Location

We only ever have one package name in the model so there's no need to store the fully qualified classname, i.e. store `Location` instead of `org.intermine.model.bio.Location`. This reduces typical table sizes by around 20-25% and overall database size by 5-10%.

**Comment by julie-sullivan** [comment]
Need to clean up OS first. See wiki ObjectStoreSimplification
