### ISSUE TITLE
Python build script

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#684]
The build script is small and doesn't need to do a whole lot but has too many dependencies. If we simplify the script, InterMine will be easier to install and use. Even better, can we rewrite the script in Python? This was done for the template_comparison script and saved us so much time.

Here is the doc for the build script:

http://intermine.readthedocs.io/en/latest/database/database-building/build-script/

1. Has several flags, e.g. to drop the database or not
2. runs a series of ant commands (to run data sources listed in XML config file)
3. based on flag in XML (dump=true) makes a copy of the database
4. can restart build using the snapshots taken
5. can run a single data source, or all of the ones listed in XML config file

So a fairly simple script that can run a few commands. But hugely important because it will make builds so much easier!

**Comment by julie-sullivan** [comment]
take a look at the `corporate-jbrowse` branch in testmodel/dbmodel/extra. Python used to parse XML.

**Comment by joshkh** [comment]
The following command fixed this issue for me. Thanks, @julie-sullivan.

```
sudo apt-get install libxml-writer-perl libxml-sax-base-perl libxml-perl libxml-filter-saxt-perl libtext-glob-perl
```

**Comment by julie-sullivan** [comment]
---

An excerpt from today's excitement:

Can't run build because I don't have a Perl module:

> julie ~/git/intermine/flymine $ ../bio/scripts/project_build -b -v localhost /tmp/flymine-build.tmp
> Can't locate XML/Parser/PerlSAX.pm in @INC (you may need to install the XML::Parser::PerlSAX module) (@INC contains: /local-homes/julie/perl5 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at ../bio/scripts/project_build line 15.
> BEGIN failed--compilation aborted at ../bio/scripts/project_build line 15.
> julie ~/git/intermine/flymine $ sudo apt-cache search  XML::Parser::PerlSAX
> libxml-filter-saxt-perl - Perl module for replicating events to several event handlers

Which Perl module do I need?

> julie ~/git/intermine/flymine $ sudo apt-cache search  XML::Parser::PerlSAX
> libxml-filter-saxt-perl - Perl module for replicating events to several event handlers

I already have that installed according to Ubuntu.

> julie ~/git/intermine/flymine $ sudo apt-get install libxml-filter-saxt-perl
> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> libxml-filter-saxt-perl is already the newest version.
> 0 to upgrade, 0 to newly install, 0 to remove and 6 not to upgrade.

---

I tried perlbrew too.

> julie /usr/lib/perl $ perlbrew mirror
> Fetching mirror list
> Page not retrieved; HTTP error code 400 or above. at /usr/share/perl5/App/perlbrew.pm line 190.
> julie /usr/lib/perl $ perlbrew mirror
> Fetching mirror list
> Server issued an error response. at /usr/share/perl5/App/perlbrew.pm line 196.

(snipped from description. We don't need to scare people.)

**Comment by julie-sullivan** [comment]
@danielabutano @justinccdev If we are re-writing the build script for Gradle, we should use Python.
