### ISSUE TITLE
Portal - add optional organism constraint

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#686]
From @kkarra

> We have a button on our of SGD pages that create a List in YeastMine, we 
> use form and post method to send the ids to make a list. With the 
> addition of genes from different Organisms, the list no longer is just 
> yeast genes. I was wondering what the name and values params should be 
> to restrict it to "Organism.shortName = S. cerevisiae” ?

**Comment by kkarra** [comment]
This works fine in 1.4
