### ISSUE TITLE
keyword search:  hyphen

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine#688]
by @bdrosen:
the hyphen should be ignored when indexing words:
at the moment 
sucros-proton return results (in thalemine, https://apps.araport.org/thalemine)
but 
sucrosproton 
sucros
do not

**Comment by julie-sullivan** [comment]
@sergiocontrino Can we close this ticket?

**Comment by sergiocontrino** [comment]
yes @julie-sullivan , let's close
