### ISSUE TITLE
Add "Show Tags" option to Lists page

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#702]
> We are planning on using tags as a "list of lists" label to allow us to keep together  lists of disparate types.  We use InterMine as the persistent storage for our Phytozome shopping carts, and a typical cart has heterogenous data types in it (e.g., genes, families, SNPs, etc.).
> 
> The "Lists->View" interface allows one to filter by, among other things, tags, and it has an option to "Show descriptions".  Would it be possible to include the option "show tags", so the lists are displayed with tags?  This is necessary because, if an actual tag name is showing in the "--filter by a tag--"  pulldown, one  can't tell from the display whether one is seeing all lists with that particular tag, or all lists independent of tag because the user clicked the "RESET" button next to the tag name pulldown..  Including the tag with Name display would alleviate this ambiguity (and would be much more useful than the alternative solution of resetting the pulldown to show "--filter by a tag--" after RESET is clicked).

**Comment by julie-sullivan** [comment]
@joshkh Can you investigate?

**Comment by julie-sullivan** [comment]
The checkbox works so there is a toggle, need to add tags to the websearchable object so those are available to output to JSP.

**Comment by JoeCarlson** [comment]
@julie-sullivan, we're about to deploy a new build next week. I'll check it then.
