### ISSUE TITLE
Transfer sequences shouldn't query for SNPs

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#706]
The transfer-sequences postprocess is updating SNPs, but it's using the coordinates on the reference chromosome not the variation. So this is wrong really.

transfer-sequence should ignore all sequence-alterations for this reason

**Comment by julie-sullivan** [comment]
@rachellyne Do you agree?

**Comment by rachellyne** [comment]
That sounds wrong to me.  We have the reference and altered sequences anyway.

**Comment by julie-sullivan** [comment]
But the SNPs sequence will be the reference sequence. That's not right is it?

**Comment by rachellyne** [comment]
That's not right, but we load the reference and altered sequence directly don't we?
