### ISSUE TITLE
Panther, Homologene converters assuming all Homologues are genes

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#709]
From @JoelRichardson

> We have just discovered an issue with our Homologene and Panther loads.
> There are about 500 instances where an MGI marker is in a panther or homologene cluster (legitimately), but that marker is not a Gene or subtype. Mostly they are Pseudogenes or Gene Segments. They end up not merging, and so we get 500 spurious new Gene objects with a duplicated MGI id and no other data.
> 
> Example: do a keyword search for MGI:1277199. You will see the 'real' feature — D13Ertd608e, a 'DNA Segment' — along with the extra Gene object. To see all the spurious instances, query for mouse genes with null symbols.
> 
> The question is: what to do? In the short term, we could try preprocessing the Panther/Homologene files to remove non-gene MGI ids. (Seems kind of distasteful..) A longer term solution would be for the loaders not to assume that everything is a Gene.

**Comment by julie-sullivan** [comment]
@JoelRichardson Is this still a problem? Your first example works now. 

Without a "type" column, we are going to have to assume a gene. We could change to create a sequence feature instead I suppose?

**Comment by JoelRichardson** [comment]
Hi @julie-sullivan ,

Sorry, I'm not sure what you're referring to as the first example. I have not looked in detail at this issue in a long time, but as I said at the dev workshop, we have implemented scrubbers to remove any non-genes from the incoming data. We do this for homologene, panther, biogrid, and intact. I don't know how much data is currently being removed this way, but I could find out.

**Comment by julie-sullivan** [comment]
1. The issue is that the Panther people told us that they only analyse protein coding genes.

http://www.pantherdb.org/news/news20140124.jsp
"PANTHER 9.0 is built from the 2013 release of the Reference Proteome set that contains one representative protein sequence for each protein-coding gene in each of 85 genomes."

2. In their data file are `DNA Segment` objects, and other non-genes. (Per your comment above).

But since they promised all entries would be protein coding genes, that is what the data source is creating.

3. Ideally they would have a "type" column. BUT they say that all types are protein coding genes!

Solutions?

1. correct data file to only include protein coding genes. (maybe they have fixed)?
2. change data model to have homologues reference sequence features. update all homologue data sources to create sequence features not genes. Update homologue mappings (e.g. friendly mine viewers) to handle sequence features not genes. 
3. Use the ID resolvers to filter out non-genes.

I'd like to close this ticket!

**Comment by JoelRichardson** [comment]
But it's not just Panther - it's Homologene, BioGrid, IntAct, and probably others. 
Oh well. I think it's fine to close the ticket because it's still not clear what the right answer is.
