### ISSUE TITLE
Enrichment widget API docs - errors with default example list

### ISSUE THREAD

**Issue by mlyne** [intermine/intermine#724]
Default examples for Enrichment Widgets on IO docs provide the wrong list types. 

For example - FlyMine:
http://iodocs.labs.intermine.org/flymine/docs#/ws-widgets/GET/list/enrichment

Generates:
The uniprot_keywords enrichment query only accepts lists of Protein, but you provided a list of Gene

Similar errors are found for the enrichment examples under MGI and FlyMine beta.

**Comment by julie-sullivan** [comment]
works as expected now.
