### ISSUE TITLE
We should revisit the standalone mode

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#749]
Embedded Tomcat is great these days, and it is standard practice these days to run an application with an embedded server (Jetty is the most popular, but Tomcat does the same thing). If we restored the ability to run InterMine as a standalone application we could:
- Remove a system dependency (Tomcat)
- Allow InterMine to be deployed in container environments (eg. Heroku, Dokku).
- Make testing it out very easy - we could supply a runnable jar.

**Comment by julie-sullivan** [comment]
See #464
