### ISSUE TITLE
Query results - onhover the cell embiggens

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#753]
When you hover over a cell, a popup appears with summary information. However the cell then becomes as large as the popup window. This is new, recent behaviour.

![query-results](https://cloud.githubusercontent.com/assets/1663057/4164828/4a94bdc0-34fb-11e4-923e-4a5d07ab38bb.png)

**Comment by hkmoon** [comment]
In my firefox, when I use "head.js.results.RESULT_TABLES = CDN/js/intermine/im-tables/1.7.x/imtables-mini-bundle.js" in global.web.properties, it shows the weird box.
However, using CDN/js/intermine/im-tables/1.6.x/imtables-mini-bundle.min.js does not have that problem.

**Comment by julie-sullivan** [comment]
@sneuhaus says this is still an issue:

> Mousing over an identifier sometimes causes the table cell to dramatically change size (this seems to happen in firefox but not in chrome).

**Comment by julie-sullivan** [comment]
This is fixed in beta
