### ISSUE TITLE
cytoscape diagram not right in yeastmine

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#763]
I am wondering why I don't see blue and red double headed arrows and the toggle between physical and genetic interaction working correctly in YeastMine? e.g. [ura5](http://yeastmine.yeastgenome.org/yeastmine/portal.do?class=ORF&externalids=S000004574)

**Comment by julie-sullivan** [comment]
@kkarra This is fixed with InterMine 1.6. If you get a dev version up, can you test and let us know what you think? The tool will update automatically.

**Comment by julie-sullivan** [comment]
See  #1051

**Comment by kkarra** [comment]
Looks good. Am sure improvements will come with time!
