### ISSUE TITLE
cytoscape display export: error #3769

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine#764]
attempts to export results in an 'error #3769' message.
true for chrome 37.0.2062.120 and firefox 30.0
it seems relatad to a bug in flash
http://stackoverflow.com/questions/23703920/flash-sandbox-security-error-just-started-popping-up-in-the-last-day-dead-in-wa
a possible solution is mentioned here
https://groups.google.com/forum/#!topic/cytoscapeweb-discuss/548wkpC3iE8

**Comment by julie-sullivan** [comment]
@sergiocontrino Can we close this ticket? I think this was fixed with InterMine 1.6

**Comment by julie-sullivan** [comment]
See  #1051
