### ISSUE TITLE
Objects need stable, persistent cross-mine identifiers

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#776]
*Requirements*: We need to persist references to objects (e.g. in steps) in such as way that the reference is valid weeks, months or years later. We also need a way to integrate data sets from different providers (federation).

*Current situation*: we can InterMineObject.id, or identifiers built from the class keys.

*Problems with the current situation*: object ids are unstable and not suitable for persistence. Class keys identifiers are potentially unstable  (may be updated) and each mine is allowed to have its own class key scheme on a per class basis. There is a portal mechanism, but this is not exposed and cannot be integrated into queries (requiring at least N+1 queries). 

*Proposed solution*: All referenceable objects (`InterMineObject`s) should have a collection of `URI`s. Each `URI` is lexically unique and refers to only one object. On database rebuilds, if the object is replaced by a new one the URI points at that new object. Old `URI`s are never removed from the database, unless their object is. New `URI`s may be added to the collection, with the same semantics - all `URI`s are functionally the same (although one may be treated as `preferred` or `canonical`). All MODs that wish to interoperate store a common set of identifiers. `URI`s are generally constructed of a namespace part and an identifier section.

*Use case*: A gene is stored with an Ensembl ID and an NCBI ID. Two URIs are created and added to the collection for this Gene (eg: `http://www.ensembl.org/ENSGN001` and `http://www.ncbi.org/1234`). Either one of these can be used as a persistent reference to the object. If two data sets need to be integrated, they are merged on the URIs of their objects (e.g. search results).

Actions:
  * Modify model (possibly as an InterMOD only extension - but core model preferred)
  * InterMOD should decide which identifier schemes to support on a per data-source/class basis.
  * Curators must populate these fields - resolving collisions where necessary.

notify: @julie-sullivan @mlyne @rachellyne

**Comment by julie-sullivan** [comment]
Not needed for blue genes.
