### ISSUE TITLE
Manage Columns needs to allow addition of multiple columns 

### ISSUE THREAD

**Issue by dmgood11** [intermine/intermine#778]
Currently, adding columns to an analysis report provides a bit too much Zen practice:  one needs to open the interface, navigate through the data model hierarchy to the desired column, and select it, at which point the interface resets, the hierarchy collapses, and the process must be repeated from scratch for the next column one wishes to add.  This is especially frustrating in two cases:  adding columns from deep in the model hierarchy (so drilling down takes awhile, and it's easy to get lost), and when adding columns that will almost always  be added together, e.g., GO id/namespace/description.

Would it be possible to use a checkbox or multirow-highlight approach to select several columns for addition at a time?

thanks,
-David Goodstein
 JGI

**Comment by dmgood11** [comment]
Hi, was wondering if this made it's way into the 1.4 beta?

**Comment by julie-sullivan** [comment]
Not yet. If this change doesn't make it into 1.4 it'll be in the next release, 1.4.1 which will only be changes related to the query results. Should be ready for testing in a few weeks.

**Comment by julie-sullivan** [comment]
@dmgood11 This is working now in beta, and will be part of the InterMine 1.5 release.

**Comment by dmgood11** [comment]
Thanks!

-David M. Goodstein
  Joint Genome Institute
