### ISSUE TITLE
Export correct strand on FASTA output with extension

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#779]
In the Download Results window, choose Format = FASTA sequence, then click on Output, and it includes an ‘Extension’ option which will append extra residues on each end of the specified size.
bug is that it's only pulling +strand sequence, even when the ORF is on the Crick strand.

**Comment by kkarra** [comment]
Julie, is the fix in 1.4?  I was wondering what to change if I wanted to push the fix to yeastmine before I switch to 1.4.
thanks,
-Kalpana

**Comment by julie-sullivan** [comment]
This ticket going to be part of the 1.4.1 milestone which should be ready for testing in a few weeks. We didn't have time to put any of the results tables fixes in 1.4 so they are getting their own release.

Here's the announcement email: http://mail.intermine.org/pipermail/dev/2015-January/003176.html

**Comment by julie-sullivan** [comment]
This is working in beta. Will want @kkarra to test too.

@kkarra This fix will be in 1.5 which should be out shortly after InterMOD.

**Comment by sergiocontrino** [comment]
for example, using the template
"Chromosomal location --&gt; All genes."  with default values:

FBgn0031208, strand = 1 export is correct (i find the sequence has been extended by the amount required)
FBgn0002121, strand = -1 export has the right length, but i don't recognise the sequence
e.g. 
no extension:
gcacactagacccaccgatcgcgactttgtgtgtgttaaaatgacgcgcatatcgttttg....
with 20 bp extension:
aaatattgtaaagccagtttgttaaataaaatacatgttttattaataatcctaagctaa...

**Comment by sergiocontrino** [comment]
the new version does what i was expecting (i.e. adding the right amount of bases both ways). closing.

**Comment by julie-sullivan** [comment]
Fixed by 759e0bbc0b35aa48477517b834d330f38aa65d04
