### ISSUE TITLE
Add Protein.interactions collection

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#788]
Tell @rachellyne

**Comment by julie-sullivan** [comment]
@rachellyne Can you have a look at this? I'd like to do this for the next release.

**Comment by rachellyne** [comment]
Yes.  Maybe discuss tomorrow?

**Comment by julie-sullivan** [comment]
@rachellyne To clarify (again!): I updated the intact converter to process proteins and create the interactions collection. Do we now want to copy these to genes.interactions? including the interaction detail, roles, etc.

**Comment by rachellyne** [comment]
yes, I think we do.

**Comment by julie-sullivan** [comment]
Okay just for now, for intact I am going to load the interactions only on the proteins. 

We'll modify the interactions tools to use these data for genes by going through proteins. If it becomes too difficult to get to the interaction data, we'll just copy it over. Let's try this way first. 

We do this for gene ontology annotation, query for all the genes and proteins and copy over the annotations to the other side.

If we do copy over the information, we will skip the interacting regions. But keep everything else, i think?

**Comment by julie-sullivan** [comment]
Working on BioGRID now. Question. Here is a sample entry for a protein interaction:

```
      <interactor id="4">
        <names>
          <shortLabel>phr</shortLabel>
          <alias type="systematic name">Dmel_CG11205</alias>
          <alias type="synonym">C2PHR</alias>
          <alias type="synonym">CG11205</alias>
          <alias type="synonym">CG11205-PA</alias>
          <alias type="synonym">Dm CPD</alias>
          <alias type="synonym">DmelCG11205</alias>
          <alias type="synonym">Phl</alias>
          <alias type="synonym">anon-OV1</alias>
          <alias type="synonym">anonOV1</alias>
        </names>
        <xref>
          <primaryRef db="entrez gene/locuslink" dbAc="MI:0477" id="35735" />
          <secondaryRef db="ensembl" dbAc="MI:0476" id="FBGN0003082" />
          <secondaryRef db="refseq" dbAc="MI:0481" id="NM_078929" />
          <secondaryRef db="refseq" dbAc="MI:0481" id="NM_165564" />
          <secondaryRef db="refseq" dbAc="MI:0481" id="NP_724613" refType="identity" refTypeAc="MI:0356" />
          <secondaryRef db="refseq" dbAc="MI:0481" id="NP_523653" refType="identity" refTypeAc="MI:0356" />
          <secondaryRef db="uniprot/trembl" dbAc="MI:1099" id="A1Z757" />
          <secondaryRef db="uniprot/trembl" dbAc="MI:1099" id="Q7JY97" />
          <secondaryRef db="flybase" dbAc="MI:0478" id="FBGN0003082" />
          <secondaryRef db="ensembl" dbAc="MI:0476" id="FBPP0087915" />
          <secondaryRef db="ensembl" dbAc="MI:0476" id="FBPP0087914" />
          <secondaryRef db="biogrid" dbAc="MI:0463" id="61601" />
        </xref>
```

In FlyMine the gene `phr` has four proteins. Two of which are listed above. 

What should I do? I looked at the biogrid site, but they only list genes. What would be the best way to represent these data?

**Comment by julie-sullivan** [comment]
Just FYI, maybe we don't need to do this anymore?
```
                if (prey.equalsIgnoreCase(role1)
                        && prey.equalsIgnoreCase(role2)) {
                    // spoke!  not storing prey - prey, only bait - prey
                    continue;
                }
```

**Comment by julie-sullivan** [comment]
@rachellyne Can a gene / protein interact with itself? I have logic that skips these.

**Comment by rachellyne** [comment]
Yes, we decided to leave self interactions out.  An exception of course would be in complexes.

**Comment by julie-sullivan** [comment]
@rachellyne Can you take a look at the worm biogrid file? Checkout the interactor `F17E9.5`. I believe this is true for all worms.

```
      <interactor id="276">
        <names>
          <shortLabel>F17E9.5</shortLabel>
          <alias type="systematic name">F17E9.5</alias>
          <alias type="synonym">CELE_F17E9.5</alias>
        </names>
        <xref>
          <primaryRef db="refseq" dbAc="MI:0481" id="NP_501412" refType="identity" refTypeAc="MI:0356" />
          <secondaryRef db="entrez gene/locuslink" dbAc="MI:0477" id="177629" />
          <secondaryRef db="refseq" dbAc="MI:0481" id="NM_069011" />
          <secondaryRef db="wormbase" dbAc="MI:0487" id="WBGENE00017542" />
          <secondaryRef db="biogrid" dbAc="MI:0463" id="42742" />
        </xref>
        <interactorType>
          <names>
            <shortLabel>protein</shortLabel>
            <fullName>protein</fullName>
          </names>
```

No UniProt accession. What can we do about this?

**Comment by julie-sullivan** [comment]
Whoops, just found one for FlyBase too:

```
      <interactor id="1020">
        <names>
          <shortLabel>CR17025</shortLabel>
          <alias type="systematic name">Dmel_CR17025</alias>
          <alias type="synonym">CG17025</alias>
          <alias type="synonym">DmelCR17025</alias>
        </names>
        <xref>
          <primaryRef db="entrez gene/locuslink" dbAc="MI:0477" id="12797896" />
          <secondaryRef db="flybase" dbAc="MI:0478" id="FBGN0040554" />
          <secondaryRef db="ensembl" dbAc="MI:0476" id="FBGN0040554" />
          <secondaryRef db="biogrid" dbAc="MI:0463" id="2592302" />
        </xref>
        <interactorType>
          <names>
            <shortLabel>protein</shortLabel>
            <fullName>protein</fullName>
          </names>
```

**Comment by julie-sullivan** [comment]
Options:

ONE

* Assign protein interactions to proteins, genetic interactions to genes
* If no UniProt accession, discard

TWO

* Assign protein interactions to proteins, genetic interactions to genes
* If no UniProt accession, assign to gene

THREE
* Assign all interactions to gene
* Postprocess to copy all gene.interactions to protein.interactions 
   * only protein interactions?
   * IntAct too?

Three is the best option; it will make the code simpler and easier to maintain and BioGRID obviously are gene-centric.

Note that all IntAct interactions had a UniProt accession.

**Comment by julie-sullivan** [comment]
@rachellyne Here's what I am going to do:

1. keep interactions on gene, as we are. Genes are what most people are looking at anyway.
2. postprocess, copy over all the interaction data to the protein. 
    * copy over all physical interactions from gene to protein. including IntAct and BioGRID 
    * interaction.participant1 will be protein instead of gene.
    * interactions will be "duplicated"
    * all data (experiment, regions etc) will be copied too
    *

**Comment by julie-sullivan** [comment]
@rachellyne Should we ask BioGRID why their interactors are identified as proteins? When they have gene identifiers?

**Comment by rachellyne** [comment]
We could do - although many experiments will be designed around the genes even though it's the proteins they are interested in, so I guess that's why it's like that.  I don't like there inconsistency though.

**Comment by julie-sullivan** [comment]
We are going to do this as a postprocess instead of in the data source (like GO does it). This will require devs to have to add this postprocess if they want to copy these data over. This is a good thing. As copying over interactions from gene to protein is new and different, it's a good thing this doesn't happen "automatically". 

That's the thinking.

**Comment by julie-sullivan** [comment]
@rachellyne That won't work. We can't do a postprocess for software reasons. We also can't do it as a postprocess for each data source. I'll write up the reasons but as of right now I can't find a good solution. It looks like we are going to stick with interactions on gene for now.

**Comment by julie-sullivan** [comment]
<h3>ONE</h3>

Assign protein interactions to proteins, genetic interactions to genes
If no UniProt accession, discard (BioGRID only)

<h3>TWO</h3>

Assign protein interactions to proteins, genetic interactions to genes
If no UniProt accession, assign to gene (bad idea)

<h3>THREE</h3>

Assign all interactions to gene
Postprocess to copy all gene.interactions to protein.interactions

This won't work for several reasons. I may need to think about coming up with a solution.

* Do a postprocess. Query for Genes.interactions and copy to proteins. 
  * Won't work because: the postprocess system doesn't "know" about interactions. It's not in the core data model. Some mines don't have interactions. In this case, they would get a compilation error. 

* Do a postprocess, but within the data source. No model issues
  * Will work if we just do IntAct. If we do BioGRID too we will have issues.

Scenario:

1. Load IntAct data. 
2. Run IntAct postprocess. 
    a. Query for all interactions where type = "physical". 
    b. copy from genes to proteins
3. Load BioGRID data
4. Run BioGRID postprocess. 
    a. Query for all interactions where type = "physical". 
    b. copy from genes to proteins

4a will contain some IntAct interactions. Also, the Interactions reference BioEntity, not gene or protein. 

<h3>FOUR</h3>

Assign all interactions to gene, as we are now. No change

**Comment by julie-sullivan** [comment]
Other options:

1. Put IntAct on protein, BioGRID on gene

**Comment by julie-sullivan** [comment]
@rachellyne For the gene in the physical interaction, it came from `Giot L (2003)`, that big experiment. Which seems really dodgy.

**Comment by julie-sullivan** [comment]
@rachellyne And FBGN0040554 doesn't have any associated proteins. (hence our problem)

**Comment by julie-sullivan** [comment]
We've decided to leave as is. For now. Maybe biogrid will update their data file.
