### ISSUE TITLE
services.json should contain mine appropriate defaults

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#789]
Currently the service documentation contains several hardcoded defaults - it should contain placeholders: (eg: `{foo.bar}`), which get interpreted as `webProperties.getProperty("services.defaults." + "foo.bar")`.

**Comment by alexkalderimis** [comment]
The purpose of this is to make the iodocs interactive API docs nicer by providing appropriate defaults. A good example is the query service - we cannot provide a default query because it depends on the model. But if the services endpoint can read default from the web-properties then the maintainers of a site can simply define an appropriate default query.

**Comment by julie-sullivan** [comment]
@vivekkrish Can you test this fix?

**Comment by vivekkrish** [comment]
cc @eriksf

Hi @julie-sullivan , sure we can test it out with ThaleMine.

However it seems that the version of web.xml in your branch (https://github.com/alexkalderimis/intermine/blob/44f3a1b2768bfbdf022bd24cb35983df1bcabc5e/intermine/webapp/main/resources/webapp/WEB-INF/web.xml) is slightly offset, in terms of lines, when compared with the web.xml in our stable branch (https://github.com/Arabidopsis-Information-Portal/intermine/blob/stable/intermine/webapp/main/resources/webapp/WEB-INF/web.xml).

Maybe we can just cherry pick just this commit instead of doing a complete merge.

@sergiocontrino , how does this impact the work that you are doing w.r.t merging InterMine 1.5.1 into AIP/intermine/stable?

Thank you!

**Comment by sergiocontrino** [comment]
hi @vivekkrish! 
not sure where we are on this. regarding web.xml the merge should be fine. there is only one addition in the araport file that will stay (a commit from svetlana, trying to remove session errors fbebac6), unless you want it out.
i have a pull request to merge 1.5.3 into stable and i was planning to do it now, please let me know if this is fine. i could then add this change into stable?
cc @eriksf

**Comment by vivekkrish** [comment]
Hi @sergiocontrino,

Given that we have already merged InterMine 1.5.5 into ThaleMine `stable`, and this issue has been added to the InterMine 1.6 milestone, should we wait until 1.6 to bring this one change into our stable?

Comparing this particular commit with our stable, https://github.com/Arabidopsis-Information-Portal/intermine/compare/stable...alexkalderimis:44f3a1b2768bfbdf022bd24cb35983df1bcabc5e, there doesn't seem to be any conflicts and should be a clean merge.

I'm ccing @agnespychan and @eriksf for their input on this.

Thank you.
Vivek

**Comment by sergiocontrino** [comment]
hi @vivekkrish , yes, i think we could wait for the merge with im 1.6 after release 1.7.

**Comment by julie-sullivan** [comment]
@sergiocontrino I am taking this off this release. It had a checkstyle error:

https://github.com/intermine/intermine/pull/1010

Let me know if this is a priority.

**Comment by julie-sullivan** [comment]
From @joecarlson
```

    I’m not sure if it’s beneficial to have the automatically generated API
    docs at iodocs.labs.intermine.org http://iodocs.labs.intermine.org for
    PhytoMine. Most of the data-specific example queries return no results
    (not surprising as they are not based on the data and data types in
    PhytoMine). That might be more frustrating than enlightening for users.

    Could PhytoMine be removed from the iodocs collection?
```

**Comment by JoeCarlson** [comment]
We're happy with phytomine being left out of the iodocs.labs.intermine.org. I don't see it there now. does that mean the testing is completed?

**Comment by julie-sullivan** [comment]
@JoeCarlson No, not tested yet but should be done for next milestone (July). I've removed your username so if you don't want to be bothered with ticket updates, just delete your comment. (I think that will work?)

**Comment by sergiocontrino** [comment]
see pr #1565, closing
