### ISSUE TITLE
GenomicRegionBedService has an undocumented parameter

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#790]
https://github.com/intermine/intermine/blob/f906ee114f65f9cc35588b57711e786c531d3b7d/bio/webapp/src/org/intermine/bio/webservice/GenomicRegionBedService.java#L33

That parameter should be in the web-bio.xml file. Also it should be less insane in the way it is parsed.

**Comment by julie-sullivan** [comment]
1. logic should be easier to understand

**Comment by julie-sullivan** [comment]
has to be backwards compatible but should accept true false too
