### ISSUE TITLE
Support one/none of operator

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#796]
In results table add filter dialog, allow use to select multiple values with a one/none of operator.
(medium priority)

**Comment by alexkalderimis** [comment]
this is complete. Needs testing upon integration.

**Comment by julie-sullivan** [comment]
@alexkalderimis This worked. However "Add value" didn't suggest an organism name for me so I had to remember how to spell *Caenorhabditis elegans*

**Comment by julie-sullivan** [comment]
Just realised that is what  #795 is about, so never mind.

**Comment by julie-sullivan** [comment]
Working on 1.5.1. branch
