### ISSUE TITLE
Add UI support for range queries.

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#797]
In both the query builder and in the add filter dialog, add support for defining range queries.
(high priority)

**Comment by julie-sullivan** [comment]
@alexkalderimis I still get this error when I try to use some constraints:


>Error: Illegal operator: OUTSIDE
>Unable to construct query: Error: Illegal operator: OUTSIDE

**Comment by julie-sullivan** [comment]
This is working as expected on the branch. Will ask Joel to test once it's on the beta branch.

**Comment by julie-sullivan** [comment]
@sergiocontrino Can you test? This looks like it's working as expected now.
