### ISSUE TITLE
Angle bracket issue in column summary dialog

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#800]
In a column summary dialog, angle brackets need to be escaped (unless changed by the escapeXml field config).
(high priority)

**Comment by julie-sullivan** [comment]
@alexkalderimis @JoelRichardson  Is there an example of an angle bracket in FlyMine? I can't think of one.

**Comment by julie-sullivan** [comment]
@alexkalderimis This isn't working as expected.

Run this template: http://humanmine.org/humanmine/template.do?name=GeneOrthAllele

Here is an allele:

```
Ctnnb1<tm1Mmt>/Ctnnb1<+>,Pparg<tm1.1(tTA)Jmgr>/Pparg<+>,Tg(tetO-cre)1Jaw/0
```

The summary looks like:

```
Ctnnb1/Ctnnb1<+>,Pparg<tm1.1(tTA)Jmgr>/Pparg<+>,Tg(tetO-cre)1Jaw/0
```

The `<tm1Mmt>` is missing

**Comment by julie-sullivan** [comment]
This is now working correctly. Will ask JoelRichardson to test once the fix is on the beta branch.
