### ISSUE TITLE
maintain 'List' input order

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#813]
We have had a couple of users write in asking about their input List items order being maintained. I think it might be nice feature if is possible or easy to do. I would assume the order has to be maintained for further actions as well as in piping it to a template etc.

"Hey SGD. I like your new YeastMine tool a lot. However, why is it that when I search a gene list from the YeastMine home page (http://yeastmine.yeastgenome.org/yeastmine/begin.do), the output table is in a different order than my original list. For example, if I search <RAD27, PMS1, MSH2, MLH1, RAD52, YMR166C>, the output table is ordered: <MSH2, MLH1, YMR166C, RAD52, RAD27, PMS1>. I don't see the rationale behind the re-ordering and it makes it difficult to combine YeastMine annotations with existing files. Thanks for your time and help!

**Comment by julie-sullivan** [comment]
@kkarra Outputting in the same order wouldn't help your user regardless. Identifiers don't map 1-to-1 to genes! An identifier can match 0, 1 or many genes.

What they really want is the "DOWNLOAD SUMMARY" blue button on the list upload summary page. That maps between what they entered and what's in the database.

**Comment by kkarra** [comment]
If the user sorts their original input in one way and then intermine results the same way it might be all they need. Not sure what this user had in mind regarding combining with existing annotations. I just brought it up to see if it had merit and if there was some easy solution like 'Match on case' ..may be 'Keep input order'. If it is not that straightforward, please feel free to close it.

**Comment by julie-sullivan** [comment]
But we can never "keep input order" because identifiers don't match objects in the database one-to-one. Does that make sense? So we are unable to keep order.

gene1 (synonym A, B, C)
gene2
gene3

What happens if I enter this in the list upload and click on [X] Keep in order:

1. A (will return gene1)
2. Monkey
3. gene2
4. B (gene1 again!)

So really we should return:

1. gene1
2. no results
3. gene2
4. gene1

But that doesn't make sense. You can't have duplicate objects in the list.

**Comment by julie-sullivan** [comment]
What they want is the download button on the list upload page here:

![download](https://cloud.githubusercontent.com/assets/1663057/5841071/e8ceb664-a191-11e4-964c-814986a3d1fd.png)

This *is* in order!!
