### ISSUE TITLE
Adding numerical constraint in results filter does not accept minus values

### ISSUE THREAD

**Issue by mlyne** [intermine/intermine#851]
Observed while constraining to a numerical value when applying a new filter in results tables. Although the field covers a range of - to + values, when entering a minus value the filter interprets the minus and resolves to 'NaN'. 

As a workaround, you can add the value first, then prefix with the minus.

Observed in Chrome under Ubuntu 14.04.

**Comment by julie-sullivan** [comment]
This is working on beta.
