### ISSUE TITLE
Panther - rat genes

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#866]
@rachellyne It looks like Rat genes are in the panther file three different ways:

1. Systematic name, e.g. CLEC6A
2. Ensembl, e.g. ENSRNOG00000046921
3. RGD, e.g. 1564571

Am I wrong? Do you think you might contact Panther and ask them for a unified way to refer to rat genes?

```
RAT|Gene=CLEC6A|UniProtKB=D3ZWT9	RAT|Ensembl=ENSRNOG00000046921|UniProtKB=M0R3U8	P	Amniota|Mammalia	PTHR22802
RAT|Gene=CLEC6A|UniProtKB=D3ZWT9	RAT|RGD=1564571|UniProtKB=F1M1A9	P	Amniota|Mammalia	PTHR22802
RAT|Gene=CLEC6A|UniProtKB=D3ZWT9	RAT|RGD=1582956|UniProtKB=F1LXR5	P	Amniota|Mammalia	PTHR22802
RAT|Gene=CLEC6A|UniProtKB=D3ZWT9	RAT|RGD=1561104|UniProtKB=D3ZXN3	P	Amniota|Mammalia	PTHR22802
RAT|Gene=CLEC6A|UniProtKB=D3ZWT9	RAT|RGD=2324825|UniProtKB=F1LYU9	P	Amniota|Mammalia	PTHR22802
RAT|Gene=CLEC6A|UniProtKB=D3ZWT9	RAT|RGD=1585258|UniProtKB=F1M698	P	Amniota|Mammalia	PTHR22802
RAT|Gene=CLEC6A|UniProtKB=D3ZWT9	DANRE|ZFIN=ZDB-GENE-061207-22|UniProtKB=F1QW96	O	Osteichthyes	PTHR22802
```

**Comment by julie-sullivan** [comment]
@rachellyne Did you ever get a response?

I'm going to close this ticket and we will use the ID resolver to handle rat genes in panther.

**Comment by rachellyne** [comment]
No I didn't. Panther are not good at responding to emails.  If we can use the ID resolver I won't hassle them again.
