### ISSUE TITLE
ERROR: function bioseg_create(integer, integer) does not exist

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#869]
@rnsmith I am getting a lot of these in my LOG files:

```
org.postgresql.util.PSQLException: ERROR: function bioseg_create(integer, integer) does not exist
org.postgresql.util.PSQLException: ERROR: function bioseg_create(integer, integer) does not exist
org.postgresql.util.PSQLException: ERROR: relation "organism__key_taxonid" already exists
org.postgresql.util.PSQLException: ERROR: function bioseg_create(integer, integer) does not exist
org.postgresql.util.PSQLException: ERROR: function bioseg_create(integer, integer) does not exist
org.postgresql.util.PSQLException: ERROR: function bioseg_create(integer, integer) does not exist
```

Since I am on 9.3 I didn't install Bioseg. Can we get rid of these?

**Comment by sammyjava** [comment]
I'm not so sure this should be closed. I'm running Postgresql 9.4.6 (Fedora 23 distro) and the InterMine dev version from March 7 (21fea0dae3fc3f98fcebb54eb409347c1e414947). And, I still get an error message in the Postgres log:

```
STATEMENT:  SELECT bioseg_create(1, 2)
ERROR:  function bioseg_create(integer, integer) does not exist at character 8
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
Now, I did not run create-location-range-index in post-process, but I also didn't run create-bioseg-location-index. I did run create-overlap-view, which is supposed to tell the app not to use bioseg.

So, I think something is slightly amiss. I don't see any front-end issues with this, but one shouldn't really be throwing this Postgres error on a 9.4.6 database, right?
