### ISSUE TITLE
Regions Tab export file columns

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#877]
Is it possible to add a column (e.g. feature type ) to the file tab, csv file(s) generated from the Regions tab Results page?

**Comment by julie-sullivan** [comment]
@kkarra Here are the docs: 

http://intermine.readthedocs.org/en/latest/webapp/region-search

I know that page is difficult to read but there is a parameter under `web.properties`:

```
## Query fields when export results as csv/tsv
genomicRegionSearch.query.Gene.views = {0}.primaryIdentifier,{0}.symbol,{0}.chromosomeLocation.locatedOn.primaryIdentifier,{0}.chromosomeLocation.start,{0}.chromosomeLocation.end,{0}.organism.shortName
```

That should be what you need!
