### ISSUE TITLE
reverse-reference system cannot capture some relationships

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#897]
In the testmodel there are Employees that have departments that have employees - so `Employee::department` is the reverse reference of `Department::employees`, naturally enough. However there are also Managers (a subtype of Employee) who also have departments which have managers, but `Manager::department` is not a reverse reference of `Department::manager`, even though they are in fact reverse-references.

The natural inclination is to add this fact to the model as follows:

```xml
<reference name="manager" referenced-type="Manager" reverse-reference="department"/>
```

However doing so causes the build to fail because the reverse reference cannot be found on the Manager class, and in any case reverse references must point to each other. This case makes it quite clear that it is easy to think of natural instances where more than one reverse-reference relationship can exist, and where they both make sense.

This is _far_ from urgent, but it would be interesting to know why this kind of relationship is illegal, and whether it would be possible to support these kinds of well-formed models.

**Comment by julie-sullivan** [comment]
If manager is a subclass of employee, it will inherit the department reference.

I don't understand what part of this is failing. The only way this wouldn't work if a Manager was not also an employee of the department they are managing, which isn't possible. 

I could be misunderstanding you though. I'm a little groggy still from all the Xmas chocolate.

**Comment by alexkalderimis** [comment]
The problem is that the scenario is logical, but the system forbids
it.

**Comment by julie-sullivan** [comment]
How is it failing? Manager *does* have a department, it inherits it from employee.

The only way this wouldn't work if a Manager was not also an employee of the department they are managing, which isn't possible. 

Where is the problem?

**Comment by alexkalderimis** [comment]
If you read the original message I am not trying to add a field to manager, which as you say inherits one from Employee, but to Department (well, to add the rev-ref attr to that field). The object-store system prohibits marking `Department::manager` as the reverse reference of `Manager::department`

This is not a high priority issue.

**Comment by julie-sullivan** [comment]
Manager *has* a department reference. 

Department *has* an employee collection. If you want only managers, you constrain the subclass to be Manager.

It's preventing you from duplicating a collection. The model is working how it's supposed to.

**Comment by alexkalderimis** [comment]
This isn't about adding another collection - just marking an existing reference as a reverse reference of another reference (of which is is a logical reverse reference).
