### ISSUE TITLE
OBO file contains different ontologies

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#901]
FlyBase anatomy file includes some GO terms. This is creating GO terms and calling them anatomy terms. 

I set the priorities to be:

```
OntologyTerm.ontology = *, fly-anatomy-ontology
OntologyTerm.namespace = *, fly-anatomy-ontology
```

But this ends up with an anatomy term that is also a SO term:

```

flymine-1.4-2014-12-19=# select * from anatomyterm where name ='gene';
 identifier | obsolete | namespace |    id     | name |                                                                                                    description                                                                                                     | ontologyid |                               class                                
------------+----------+-----------+-----------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+--------------------------------------------------------------------
 SO:0000704 | f        | sequence  | 113000002 | gene | A region (or regions) that includes all of the sequence elements necessary to encode a functional transcript. A gene may include regulatory regions, transcribed regions and/or other functional sequence regions. |  113000000 | org.intermine.model.bio.AnatomyTerm org.intermine.model.bio.SOTerm
(1 row)
```

Ontology terms merge on name+ontology or identifier.

How to fix? 

@rachellyne Is this illegal? 

http://oboformat.googlecode.com/svn/trunk/doc/GO.format.obo-1_2.html

```
data-version
    Gives the version of the current ontology. 
```

So that sort of assumes there is only one ontology present. Thoughts?

**Comment by julie-sullivan** [comment]
Causes #832

**Comment by julie-sullivan** [comment]
Apparently this is a thing now so we have to deal with it somehow.

1. GO creates a go-full file with lots of ontologies. It also has a go-basic file with just GO terms. Maybe ask Fly to do the same?
2. `namespace` is supposed to be unique, this is enforced by the consortium. However InterMine has no idea which are the legal namespaces for an ontology. There is a default one set at the beginning of the file but many ontologies have multiple namespaces.

An alternate take would be to uniqueify on prefix, e.g. GO, UBERON, etc. This would be preferable.

a. Can we contact GO and express our concerns?
b. I could make the ontology browser discard terms that don't have the correct prefix. How do I know what the correct prefix is? Take the first one?

**Comment by julie-sullivan** [comment]
The same anatomy file has some other troubling entries:

```
[Typedef]
id: regulates
name: regulates
namespace: gene_ontology
xref: RO:0002211

[Term]
id: FlyBase:FBgn0004652
name: fruitless
is_a: SO:0000704 ! gene

[Term]
id: FlyBase:FBgn0010433
name: atonal
is_a: SO:0000704 ! gene

[Term]
id: PATO:0000001
name: quality
namespace: quality
def: "A dependent entity that inheres in a bearer by virtue of how the bearer is related to other entities." [PATOC:GVG]
synonym: "trait" EXACT []

```

**Comment by rachellyne** [comment]
@julie-sullivan, do you know where we are getting this file from?  It looks wrong - it shouldn't have genes and biological processes in it, these are not anatomy.  I just had a quick look at the file online and it looked fine.  I'll download this manually and then take a look at the download script.

**Comment by julie-sullivan** [comment]
It looks like we are getting it from:

http://svn.code.sf.net/p/fbbtdv/code/fbbt/releases'

I don't know why I get it from there.

**Comment by rachellyne** [comment]
I have a feeling we had the same problem last build.  This file looks fine:

http://flybase.org/static_pages/downloads/FB2014_06/ontologies/fly_anatomy.obo.gz

**Comment by julie-sullivan** [comment]
Another possible solution, process the OWL file:

http://www.obofoundry.org/id-policy.shtml

It's got the full URI.

**Comment by julie-sullivan** [comment]
I am going to set a `prefix` parameter for each OBO source. If the ontology term does not match the set prefix, then it will be discarded. 

Tell @kkarra

**Comment by julie-sullivan** [comment]
A list of prefixes is available at obofoundry.org

**Comment by julie-sullivan** [comment]
**A summary**

The fashion now is to cross reference terms from other ontologies in a single OBO file. In this case, the Fly anatomy file contains GO terms. However the OBO file format does not specify that the ontology has to be defined. Meaning there is no ontology associated with each ontology term. 

Currently the OBO parser assumes a single ontology per OBO file. This means that all ontology terms in the Fly anatomy file are created as anatomy terms --  when in reality that file contains GO, PATO and SO terms too. This caused merging problems.

There is the namespace value which is unique per ontology. However GO has three legal namespaces but there is no way for me to know what they are. The OBO file specification says the default_namespace should be defined at the top. If a term has a different namespace, then it is defined in the ontology term stanza. But there is no list of legal namespaces for the InterMine processor to check.
