### ISSUE TITLE
Reactome - assigning too many pathways

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#927]
There may be a problem with the way we process the reactome data.  Taking example "metabolism of lipids and lipoproteins" we have about 450 more proteins than in reactome.  Do we maybe take proteins from parent pathways as well, as some I have checked are under other forms of metabolism.  These are the dodgy proteins for this pathway:

A5LHX3
O00217
O00221
O00231
O00232
O00233
O00445
O00468
O00483
O00487
O00555
O14503
O14521
O14548
O14561
O14732
O14795
O14810
O14818
O14920
O14949
O14950
O14957
O15055
O15111
O15239
O15534
O43181
O43242
O43306
O43314
O43318
O43570
O43674
O43676
O43677
O43678
O43819
O43837
O43920
O60266
O60503
O60504
O60825
O75038
O75056
O75145
O75182-1
O75251
O75306
O75334
O75335
O75352
O75380
O75390
O75438
O75487
O75489
O75787
O75832
O75880
O75947
O75964
O95139
O95153
O95167
O95168
O95169
O95178
O95182
O95237
O95298
O95299
O95398
O95622
O95644
O95989
O95999
O96000
P00156
P00395
P00403
P00414
P00734
P00740
P00742
P00797
P00846
P00915
P00918
P01111
P01112
P01116
P01185
P01308
P02545-1
P02545-2
P02730
P02753
P02766
P03886
P03891
P03897
P03901
P03905
P03915
P03923
P03928
P04035-1
P04035-2
P04070
P04150
P04899
P05121
P05129
P05141
P05496
P05771
P06493
P06576
P06753
P07225
P07339
P07451
P07900
P07919
P07951
P07954
P08311
P08473
P08574
P08709
P09455
P09493
P09622
P09669
P09958
P0CG47
P0CG48
P10176
P10606
P10644
P12074
P12235
P12236
P12821
P13073
P13497-3
P13804
P13861
P14635
P14649
P14854
P14927
P15086
P15088
P15144
P15336
P15954
P16118
P16220
P16298
P16885
P17252
P17568
P17980
P18084
P18206
P18859
P19174
P19404
P19838
P20336
P20618
P20674
P20700
P20718
P20936
P21579
P21912
P22307-1
P22695
P22748
P22891
P23677
P23946
P24311
P24539
P24844
P25098
P25705
P25786
P25787
P25788
P25789
P25874
P25963
P27815
P27987
P28062
P28065
P28066
P28070
P28072
P28074
P28331
P28482
P29218
P29373
P29474
P29536
P29762
P29972
P30049
P31040
P31321
P31323
P31431
P31749
P31930
P32019
P34741
P35052
P35218
P35749
P35998
P36542
P36956-1
P36956-3
P36957
P38117
P38435
P40145
P40306
P40926
P41181
P42167-1
P42704
P43166
P43490
P43686
P47985
P48047
P48201
P48454
P48556
P48730
P48735
P48995
P49023
P49441
P49674
P49720
P49721
P49821
P50120
P50213
P50402
P51178
P51553
P51654
P51665
P51828
P51970
P53597
P54284
P54750
P55036
P55058-1
P55058-2
P55087
P55851
P55916
P56134
P56181
P56199
P56381
P56385
P56556
P58753
P60660
P60880
P60900
P61289
P61764
P61764-1
P62158
P62191
P62195
P62333
P62491
P62736
P62979
P62987
P63027
P63096
P63098
P63208
P63267
P67936
P68871
P69905
P78333
P99999
Q00722
Q01064
Q01668
Q01970
Q02094
Q02156
Q02218
Q04206
Q04864
Q05513
Q05655
Q05682
Q06055
Q06323
Q06413
Q07075
Q07343
Q07954
Q08209
Q08289
Q08462
Q08493
Q08499
Q08828
Q09428
Q10586
Q12968
Q13136
Q13200
Q13423
Q13469
Q13572
Q13586
Q13616
Q13936
Q14114
Q14123
Q14393
Q14571
Q14573
Q14642
Q14643
Q14654
Q14814
Q14997
Q15008
Q15067-1
Q15067-2
Q15147
Q15526
Q15653
Q15746
Q15878
Q16134
Q16401
Q16526
Q16566
Q16572
Q16623
Q16718
Q16790
Q16795
Q16875
Q16877
Q2TAA5
Q3E731
Q3KNW5
Q49AN0
Q4KWH8
Q5BKT4
Q5I7T1
Q5RI15
Q5VZY2
Q6PFW1
Q7L804
Q7Z4F1
Q86SQ9
Q86UR5
Q86Y39
Q86YW0
Q8N158
Q8N1Q1
Q8N3E9
Q8N8Q8
Q8NC56
Q8NEB5
Q8NFM4
Q8NFP7
Q8NFU5
Q8TAA3
Q8WTV0-2
Q8WWR8-2
Q8WYA1
Q8WZA2
Q92482
Q92530
Q92551
Q92685
Q96AA3
Q96D31
Q96DU7
Q96F25
Q96G61
Q96I36
Q96I99
Q96IY4
Q96PC2
Q99436
Q99460
Q99643
Q99766
Q99798
Q9BQB6
Q9BSH4
Q9BT22
Q9BV10
Q9BVK2
Q9BX66
Q9BXL7
Q9BYF1
Q9C0J9
Q9H3H5
Q9H553
Q9H6U8
Q9H8X2
Q9NP71
Q9NP73
Q9NQ66
Q9NTG7
Q9NX14
Q9NY47
Q9NZJ9
Q9P0J0
Q9P0S2
Q9P212
Q9P2R7
Q9UBR2
Q9UDW1
Q9UDY8
Q9UHC9-2
Q9UHH9
Q9UI09
Q9UK39
Q9UKB1
Q9UKT7
Q9UL46
Q9ULV0
Q9ULX7
Q9UNM6
Q9UNW1
Q9UPQ8
Q9Y297
Q9Y2D0
Q9Y2U8
Q9Y490
Q9Y561
Q9Y5P4-2
Q9Y625
Q9Y672
Q9Y6K9
Q9Y6M9
Q9Y6N1

**Comment by julie-sullivan** [comment]
http://www.reactome.org/download/current/UniProt2Reactome.txt
@rachellyne doesn't contain the pathway "metabolism of lipids and lipoproteins"

I was thinking of processing the flat file because I can't read the OWL file.

**Comment by julie-sullivan** [comment]
@rachellyne I processed the flat file with UniProt proteins and I get a different number of pathways:

<table>
<tr>
<td>flat file</td>
<td>2,424</td>
</tr><tr>
<td>biopax</td>
<td>3,096</td>
</tr>
</table>

The pathway "metabolism of lipids and lipoproteins" isn't even there, which it should be. We have a few options. 

1. There is an ensembl to pathway file.
2. I could upgrade the library I use to parse the biopax data.

Oh wait, there is a file `UniProt2Reactome_All_Levels.txt`. brb, let me try that.

**Comment by julie-sullivan** [comment]
When I process that file, I get 3,171 total pathways, including `metabolism of lipids and lipoproteins`. Also, for protein A5LHX3 it has `Metabolism of amino acids and derivatives` instead of the lipids pathway.

`Metabolism of amino acids and derivatives` now has a total of 189 Proteins which matches the reactome site exactly.

So it seems like the biopax library is assigning too many pathways to too many proteins. Use this new data source instead?

**Comment by rachellyne** [comment]
Yes, let's try that.  I'll tell reactome that there data is wrong.

**Comment by julie-sullivan** [comment]
@rachellyne I think it's probably the biopax parsing library I am using that is the problem. I'll post a message to their dev list. I can't really tell of course because I can't grep the biopax to see if the data is correct!
