### ISSUE TITLE
Add HumanMine to list of mines in global properties.

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#938]
1. Add HumanMine to list of known mines.
```properties
intermines.humanmine.url=http://humanmine.org/humanmine
intermines.humanmine.name=HumanMine
intermines.humanmine.logo=humanmine_logo.png
intermines.humanmine.bgcolor=#C3C3C3
intermines.humanmine.frontcolor=#000
intermines.humanmine.defaultValues=H. sapiens
intermines.humanmine.description=Mine for Homo Sapien data.
```

2. Also, change ZFIN color to better match its theme.
```properties
intermines.zfinmine.bgcolor=#006666
intermines.zfinmine.frontcolor=#FFF
```

**Comment by julie-sullivan** [comment]
See #933

**Comment by julie-sullivan** [comment]
If we change the colours now, the colours will be different for the mines depending on which mine you are at. Is that going to be confusing? @sergiocontrino ? What do you think?

Also, only some mines (that update) will have humanmine, the rest will have metabolicmine.

We need a registry!

**Comment by joshkh** [comment]
I'm creating a separate issue for a mine registry.

Also, I'll push my changes into the human-debut branch rather than create another pull request.

**Comment by joshkh** [comment]
Done: See d339395ef65329b1e00a761d931d03271c7545c3

**Comment by julie-sullivan** [comment]
Let's merge this now but put up a proper registry for 2.0
