### ISSUE TITLE
Need public registry for friendly mines.

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#940]
Currently, each mine accesses its own local properties file to find information about other mines. These properties, by default, come from our code base. This is bad.
- We need to version InterMine every time a new mine is added or a property of an existing mine is changed.
- Changes do not propagate to existing mines unless they pull from us.
- Different versions of InterMine will have different properties which can create a disconnect when linking to other mines.

**Comment by joshkh** [comment]
At the very least, each mine will need a UID and a URL.

Up for debate is whether or not we store branding information. Thoughts:

I suggest that we optionally store each mine's branding information in our registry. Each mine should check our registry first, and if no branding information is found then it checks the mine directly (branding API). 

In the end, branding information would rarely exist in our registry, but we could override colors when necessary.

**Comment by julie-sullivan** [comment]
@Hendekagon I've assigned this to you, let's chat when you have some time. There is already a partially implemented registry that Alex made somewhere. I'll try to find it.

**Comment by Hendekagon** [comment]
@julie-sullivan did you find that partially-implemented registry btw ?

**Comment by julie-sullivan** [comment]
@Hendekagon No, I never did.

**Comment by julie-sullivan** [comment]
1. The registry should only return mines that are online now.
2. Can mines add themselves to the registry? it's low traffic so might not matter.

**Comment by julie-sullivan** [comment]
Needed for:

* intermineR
* android app
* others.

**Comment by julie-sullivan** [comment]
We have an intermod search tool in the works. Should we have a boolean, "MOD"? Or maybe in the tool, it can have the list of mines, and get the URLs from the registry?

**Comment by julie-sullivan** [comment]
Also, should display on home page.

**Comment by julie-sullivan** [comment]
Other info we might want to collect (and make optional):

* twitter 
* location (vague. for our map. Just city country?)

Tell @yochannah

**Comment by yochannah** [comment]
lat/long specifics would be easier, so we could do something like this: http://yochannah.github.io/mineminer/

**Comment by julie-sullivan** [comment]
Another suggestion from the workshop: people don't want to know URLs. e.g. bovinemine.org instead of bovinegenome.org. 

Use the registry to allow people to query all interesting mines. somehow. Maybe let them select "cow" and "human".

**Comment by julie-sullivan** [comment]
@danielabutano close this ticket maybe, because the requirements are elsewhere.

**Comment by danielabutano** [comment]
This ticket will be implemented by the InterMine Registry GSoC project
