### ISSUE TITLE
Allow superclass lists in template list constraints

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#942]
From @JoelRichardson:

> A while ago I brought up the question of allowing a supertype list to be plugged into a bag constraint that wants a subtype. I had experimented by editing a query's XML directly, e.g., I took the "Gene->Homologs" query, edited the XML to name SequenceFeature list, and ran it. It worked as one would hope: the Genes in the list participated in the results while all the non-genes dropped out. The only thing needed to make it "real" was to modify the code that decides which bags to include in the option list of the constraint. I finally found that place, and the code change is very minimal. I have done this on my own dev install, but have not checked anything in. I have tested it and it seems to work just fine. 
> 
> This change addresses a common use case that has come up several times. Just a couple days ago, another user wrote to ask why their list (of SequenceFeatures) was not available to input to a template (that wanted Genes). When I explained, they then wanted to know how they could convert their list of features into a list of genes. There's no easy way that I know of. The best I can come up with is to export the ID column and then upload them again to create a new list of genes. Rather awkward. But with the change, this kind of thing is a snap. I don't really see a downside.

Sounds good to me! Can you make a pull request?

**Comment by alexkalderimis** [comment]
That sounds completely sensible - the type check should be of the form "does the constraint path share a common type with the bag type".

**Comment by julie-sullivan** [comment]
This was fixed by eed44ff8bc5e7e12305eb43528d6227d6ed2db86
