### ISSUE TITLE
results table no longer supports removing a filter

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#943]
results table no longer supports removing a filter

**Comment by joshkh** [comment]
The remove filter button is still present on the DOM but it's being rendered as 0px by 6px. Clicking it programmatically removes the filter as expected, but obviously it can't be clicked with the mouse in its current state.

The <i> element is only the height of its own padding so I think it's safe to say that the FontAwesome character used for the close icon can't be located.

**Comment by julie-sullivan** [comment]
This is working correctly in beta flymine.
