### ISSUE TITLE
Remove hardcoded test from webapp

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#949]
We do not show tables for bags of type 'Submission'. This is hardcoded into the jsp. This is terrible. We should:
  * Move this particular blacklist to properties
  * Perform this test in a helper (wrapped in a tile even)
  * Have a test for this behaviour

**Comment by julie-sullivan** [comment]
@sergiocontrino Can we remove this line: https://github.com/intermine/intermine/blob/beta/intermine/webapp/main/resources/webapp/bagDetails.jsp#L150

**Comment by sergiocontrino** [comment]
yes, i will check in directly on beta, if ok.
