### ISSUE TITLE
Escape list description

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#950]
Attackers can gain control of the webapp by injecting malicious content into a list description, which is unescaped. As proof set your list description to `<script>alert('pwned');</script>`

**Comment by alexkalderimis** [comment]
I am changing this on the branch I am working on, btw.

**Comment by alexkalderimis** [comment]
Yup, fixed I believe, but feel free to XSS attack yourself as detailed above.

**Comment by julie-sullivan** [comment]
Fixed by c706928c10f0f8ae8dc770d0fe9e07329c5dd686
