### ISSUE TITLE
Homologues need to merge

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#957]
Treefam and panther need to merge homologues.

(maybe other sources)

e.g. FBgn0035076 and FBgn0012037 have two paralogue records one from each data set. There should only be one record.

**Comment by sergiocontrino** [comment]
thalemine appears to have a similar issue, with all its homologues counted twice. it loads only panther though.
the homologue table contains the duplicated records. for an example, follow the steps below (MINE-708)

created a list of two genes
Gene > AGI ID	Gene > Symbol	Gene > Name	Gene > Brief Description
AT2G27990	BLH8	BEL1-like homeodomain 8	BEL1-like homeodomain 8
AT5G02030	RPL	REPLUMLESS	POX (plant homeobox) family protein
On the list analysis page, for this list (of 2 genes), I check the box to view orthologues in Arabidopsis (widget at bottom of page)
There are 80 rows in the table, but each row is duplicated.
Thus there are really only 20 ortho/paralogues for each of these genes.

**Comment by julie-sullivan** [comment]
@rachellyne Panther says these 12 genes are homologues of themselves.

```
flymine=# select primaryidentifier from gene where id IN (select geneid from homologue group by geneid,homologueid having count(*) > 1);
 primaryidentifier 
-------------------
 At1g07960
 At2g16405
 At4g38600
 At1g08680
 At4g15200
 At1g55250
 At2g30600
 AtCg00065
 At5g42540
 At2g30520
 At4g00630
 At3g52640
(12 rows)
```

Here's an example line from the data file I found:

```
ARATH|TAIR=At2g16405|UniProtKB=Q0V845	ARATH|TAIR=At2g16405|UniProtKB=Q0V845	P	Eukaryota|Embryophyta	PTHR22847
```

**Comment by julie-sullivan** [comment]
There are only two fly genes:

```
flymine=# select primaryidentifier from gene where id IN (select geneid from homologue group by geneid,homologueid having count(*) > 1);
 primaryidentifier 
-------------------
 FBgn0031488
 FBgn0033529
(2 rows)
```
