### ISSUE TITLE
improve error message when creating list from set operation

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine#958]
when logged in, from the MyMine section:
at the moment when you want to create a list as, for example, intersection of 2 lists and you forget to name the list first you get a message like:

 Names for lists and queries may only contain A-Z, a-z, 0-9, underscores and dashes.

that tricks users into thinking that this refers to the original lists names.

note also that in the public  list page, you are explicitly asked to name the list. not here.  behaviour is not consistent.

**Comment by sergiocontrino** [comment]
fixed in araport with 970744138b910919404c82db6ff890c96ae92413

**Comment by julie-sullivan** [comment]
@sergiocontrino Can you do a pull request?

**Comment by julie-sullivan** [comment]
Fixed by 1204dd82f48a55e6ddbdabc5d8888223fa852649
