### ISSUE TITLE
Download link for Java client is broken

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#963]
It's still referring to the obsolete filedownload.do.

**Comment by julie-sullivan** [comment]
See http://human.intermine.org/humanmine/api.do?subtab=java

The (download) link.

**Comment by alexkalderimis** [comment]
The API tab is going away in the next release. Easy fix.

**Comment by julie-sullivan** [comment]
My favourite type of fix!

**Comment by julie-sullivan** [comment]
@alexkalderimis I think the API tab is going to stay for InterMine 1.6? Can we fix the link in the meantime?

**Comment by julie-sullivan** [comment]
Fixed by ca4ef3ef4838ee2ec569f156b664767e50f10ff7
