### ISSUE TITLE
Fewer ANALYSEs while data loading

### ISSUE THREAD

**Issue by rnsmith** [intermine/intermine#969]
`ANALYSE` is run during data loading to make sure object equivalence queries in the target database remain fast. For large databases the time take to analyse probably outweighs the benefir of analysing. The `ANALYSE` operations should be less frequent.

**Comment by rnsmith** [comment]
Make tables analyses less frequent: https://github.com/intermine/intermine/commit/5a653d3df98115b689a23b2c87c4ed021e792989

**Comment by julie-sullivan** [comment]
See #975
