### ISSUE TITLE
Orthologs: add pairwise relationships for lists

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine#970]
ThaleMine suggested to make available the gene to gene mapping of orthologues in a list context.

**Comment by julie-sullivan** [comment]
Can you be more specific? Do you mean for a list show the orthologues? Or when you create a list from orthologues, keep those with the list?

**Comment by sergiocontrino** [comment]
in a list of genes, map each gene to its own orthologue (i.e. not just return the list of gene othologues to the original list)

**Comment by julie-sullivan** [comment]
After which action? In which context? What's the workflow? 

Do you mean just on a list analysis page? Or is there a specific action after which this should be displayed?

**Comment by julie-sullivan** [comment]
@sergiocontrino Do you have more details? Or can I close this?

**Comment by sergiocontrino** [comment]
hi @julie-sullivan, in a gene analysis page the links to orthologues could become a (hidden by default) table mapping the orthologic (?!)  relationships amongst genes in the 2 organisms.
i don't think it is a priority, never heard of it again, so i would say this could be closed or added to wish list (maybe @rachellyne has an opinion).

**Comment by julie-sullivan** [comment]
This can be done via a template, so I am going to close this.
