### ISSUE TITLE
PSI Interactions - taxon ID is strain 

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#971]
The yeast taxon ID is the strain, should update to use the regular taxon ID.

Edit: Add option to config file to set the strain for a taxon ID, like we do for UniProt.

**Comment by kkarra** [comment]
which config file is this in?

**Comment by julie-sullivan** [comment]
There isn't a way to set the strain for a taxon for this data source yet.

If this is something you need, I can make it a priority.
