### ISSUE TITLE
Reduce ANALYSEs while dataloading

### ISSUE THREAD

**Issue by rnsmith** [intermine/intermine#975]
ANALYSE is run periodically (rules in `BatchWriterSimpleImpl.java`) in the target database during data loading to prevent lookup queries for equivalent objects becoming inefficient.  Currently these are run on all tables but could be restricted to only those tables with integration keys.

`BatchWriterSimpleImpl` doesn't know anything about primary keys but a list of analysable tables could be passed in.

**Comment by rnsmith** [comment]
I made this change here and it seems to work, with a little clean up and a full test build it should be done: https://github.com/intermine/intermine/commit/c007a6a6cafb7dc4678693152fa6cf7477921e28

**Comment by julie-sullivan** [comment]
See #969
