### ISSUE TITLE
Keyword Search: don't index Gene.length

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#979]
Searching for 5468 brings up a gene with that length instead of pparg. That's dumb.

**Comment by julie-sullivan** [comment]
@rachellyne Does it make sense at all to index integers?

**Comment by rachellyne** [comment]
Pubmed IDs and NCBI Ids.   I can't think of anything else that would require you to put in a number.  You could if course - but that would be a strange way of searching this type of data and not recommended..

**Comment by julie-sullivan** [comment]
@justinccdev Can we exclude certain fields from being indexed? Does it make sense to? Who would look up a gene by its length? Meh, who am I to judge.

**Comment by justinccdev** [comment]
Set 

index.ignore.fields = Gene.length 

in <mine>/dbmodel/resources/keyword_search.properties

See http://intermine.readthedocs.io/en/latest/webapp/keyword-search/

**Comment by justinccdev** [comment]
Possibly we might have some InterMine keyword_search.properties that could specify this for core model properties (like Gene.length).  Something to bear in mind when we look at updating search.
