### ISSUE TITLE
create-db does not clear tracker table

### ISSUE THREAD

**Issue by JoeCarlson** [intermine/intermine#989]
When reusing a database, the object tables are cleaned out nicely, but the tracker table has accumulated records from the previous load.

This may explain my tracker table bloat.

**Comment by rnsmith** [comment]
I don't see this happening. In `flymine/integrate` I did this:
```
> (cd ../dbmodel; ant clean build-db) && ant -Dsource=uniprot
>  psql flymine -c 'select count(*) from tracker;'
 count  
--------
 615444
(1 row)
> (cd ../dbmodel; ant clean build-db)
> psql flymine -c 'select count(*) from tracker;'
ERROR:  relation "tracker" does not exist
LINE 1: select count(*) from tracker;
```
Did you do something different to observe the problem?

**Comment by JoeCarlson** [comment]
Hi Richard,

meebee I did not do the 'clean' step. I'll have to redo it to be sure.

I did something very similar and the tracker table was there and 
populated. I guess I thought is was weird that the model object tables 
were there and clean, but the tracker table was still there.

Thanks,

Joe

**Comment by rnsmith** [comment]
I can't reproduce this even without a clean. `BuildDbTask` uses `con.getMetaData().getTables(null, null, "%", null)` to get all tables in the database and drops them all. I don't see how it can leave the tracker table behind.
