### ISSUE TITLE
/branding web service endpoint should provide more details

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#990]
The /branding web service should provide project details along with the existing branding properties.

Current values served by /branding (from global.web.properties):

``` properties
branding.images.main = http://intermine.github.io/intermine.org/img/logo.png
branding.images.small = http://intermine.readthedocs.org/en/latest/_static/img/logo.png
branding.colors.focus.bg = #829b02
branding.colors.focus.fg = #fff
branding.colors.main.bg = #fff
branding.colors.main.fg = #595455
```

Proposed additions (to global.web.properties):

``` properties
project.title
project.subTitle
```

Reasons why we can't source default values from elsewhere:
- I was hoping to construct a url that pointed to the webapp logo:
  [webapp.baseurl]/[webapp.path]/model/images/logo.png
  ... but these aren't always used, or worse, not the correct logo. For instance, Thalemine has a full screen image there and they source their actual logo from gravatar.
- Much of the look and feel comes from the CSS which we can't predict.

I'll update the docs to explain the branding properties in more detail.

**Comment by julie-sullivan** [comment]
@joshkh Are these going under the registry?

**Comment by danielabutano** [comment]
Title and description (as logo, header.main and header.text) are returned by the registry 
`curl -X GET "http://registry.intermine.org/service/instances/flymine"`
