### ISSUE TITLE
Inheritance in webconfig-model.xml is inconsistant

### ISSUE THREAD

**Issue by sneuhaus** [intermine/intermine#996]
Defining fields in sequencefeature results in child classes being similarly configured, but this doesn't work if fields are configured in bioentity.

This is because inheritance only takes place if the child class has no field configs defined.
Since sequencefeature already (on mousemine) had field configs, the configs in bioentity are not applied to child classes. So not a bug, just how it works.

Inline list configurations don't get inherited at all.

For inlineLists assuming the desired behavior is to inherit from the parent if the child has no inline lists defined (consistant with inheritance for fieldconfigs) we need a few lines of code:

```
WebConfig.setSubClassConfig(){
.....
// existing code
if (thisClassType.getTableDisplayer() == null) {
        thisClassType.setTableDisplayer(superClassType.getTableDisplayer());
    }
//new code for inline lists
if (thisClassType.getInlineListConfig() == null || thisClassType.getInlineListConfig().isEmpty()){
   for(InlineListConfig cfg: superClassType.getInlineListConfig()){
        thisClassType.addInlineList(cfg);
        }
 }
```

I'll create a pull request for this.

**Comment by sneuhaus** [comment]
Hi Julie,
 Do you want me to make a pull request for this. Its only those 4 lines of code?

**Comment by julie-sullivan** [comment]
@sneuhaus Yes, unless you want me to make it. We'll need some sort of pull request / branch to test. Even though it's just four lines we still have to test. Does that four lines fix all of your problems?

**Comment by sneuhaus** [comment]
As far as I can tell it does. I'll make a branch/pull request

**Comment by julie-sullivan** [comment]
Fixed by #998

Thanks @sneuhaus!

**Comment by julie-sullivan** [comment]
The report page on gene looks wrong now, I need to update the config

**Comment by sergiocontrino** [comment]
page seems fine, closing for now.
